otwcode/otwarchive

- app/controllers/users_controller.rb
Pulled out some helper functions and fixed a few cases of logic duplication.
> UsersController cleanup

- features/importing/work_import.feature
> The hex files is down

- app/views/home/donate.html.erb
- public/drive.html
https://code.google.com/p/otwarchive/issues/detail?id=4199
> Issue 4199 drive page changes.

- app/controllers/invitations_controller.rb
- app/controllers/user_invite_requests_controller.rb
- features/other_a/invite_request.feature
- features/step_definitions/user_steps.rb
- features/support/paths.rb
https://code.google.com/p/otwarchive/issues/detail?id=4210
> 4210 Don't let banned users access or request invitations

- app/models/collection.rb
- spec/models/collection_spec.rb
Resolves issue: https://code.google.com/p/otwarchive/issues/detail?id=4154
> Issue 4154: Moderated challenges should appear on Open Challenges page

- .hound.yml
- app/controllers/kudos_controller.rb
- config/.rubocop.yml
https://code.google.com/p/otwarchive/issues/detail?id=4214
Stop Hound from baying about line length and quotation marks... this time without my committing to master dumbassery.
> 4214 Train the new puppy

- config/deploy/production.rb
Nothing to test, nothing to see
I would prefer this get merged and deployed ASAP.
> add ao3-front02

- README.md
Just testing the deploy to test bit
> Minimal change to readme to test deploy

- config/deploy/production.rb
Reverts otwcode/otwarchive#1990
> Revert "add ao3-front02"

- config/deploy/production.rb
Reverts otwcode/otwarchive#1992
As it is not that which is causing the deploy issue.
> Put ao3-front02 back 

- README.md
Reverts otwcode/otwarchive#1991
> Revert "Minimal change to readme to test deploy"

- app/controllers/application_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=4207
> 4207 Tell banned/suspended users to contact Abuse

- app/controllers/application_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=4217
**Merge after #1986**
> 4217 Tell user when they are suspended until

- app/helpers/works_helper.rb
https://code.google.com/p/otwarchive/issues/detail?id=4230
> add date last updated to download urls

- app/models/pseud.rb
- app/models/work.rb
- features/step_definitions/user_steps.rb
- features/works/work_create.feature
- lib/pseudable.rb
Issue 4215: Banned users can't be coauthors
https://code.google.com/p/otwarchive/issues/detail?id=4215
> Issue 4215: Banned users can't be coauthors

- public/502.html
- public/503.html
- public/507.html
- public/509.html
https://code.google.com/p/otwarchive/issues/detail?id=4226
> Move the error pages around

- app/mailers/admin_mailer.rb
- app/models/spam_report.rb
- app/models/work.rb
- app/views/admin_mailer/send_spam_alert.html.erb
- app/views/admin_mailer/send_spam_alert.text.erb
- app/views/works/_meta.html.erb
- config/config.yml
- db/migrate/20150111203000_add_akismet_score_to_works.rb
- lib/tasks/spam_report.rake
https://code.google.com/p/otwarchive/issues/detail?id=4212 
Now using  Akismet to get an opinion.
> Issue 4212 email for possible spam

- app/views/admin_mailer/send_spam_alert.html.erb
- app/views/admin_mailer/send_spam_alert.text.erb
Fix broken on test
https://code.google.com/p/otwarchive/issues/detail?id=4212
> Variable mixed around in the changes

- app/controllers/admin/user_creations_controller.rb
- app/views/user_mailer/admin_hidden_work_notification.html.erb
- app/views/user_mailer/admin_hidden_work_notification.text.erb
- features/admins/admin_works.feature
Resolves BOT-DB: https://code.google.com/p/otwarchive/issues/detail?id=3747
> 3747: Rework mailers, only email on hide, not unhide

- app/views/home/index.html.erb
- app/views/invitations/_user_invitations_navigation.html.erb
- app/views/invitations/index.html.erb
- app/views/invitations/manage.html.erb
- app/views/invite_requests/index.html.erb
- app/views/invite_requests/show.html.erb
- app/views/user_invite_requests/new.html.erb
- app/views/user_sessions/_passwd_small.html.erb
- features/admins/admin_invitations.feature
- features/other_a/admin_tasks.feature
- features/other_a/admin_tasks.feature.save
- features/other_a/invite_queue.feature
- features/other_a/invite_request.feature
https://code.google.com/p/otwarchive/issues/detail?id=4204
https://code.google.com/p/otwarchive/issues/detail?id=4205
https://code.google.com/p/otwarchive/issues/detail?id=4206
> Stop using "invites" as a noun and use "invitations"

- public/help/rating-help.html
https://code.google.com/p/otwarchive/issues/detail?id=4221
> issue 4221 Inartfully phrased rating help text

- public/help/css-help.html
- public/help/skins-creating.html
https://code.google.com/p/otwarchive/issues/detail?id=3843
> 3834 Update the CSS help files with what CSS we allow

- app/controllers/abuse_reports_controller.rb
- app/controllers/feedbacks_controller.rb
- app/models/abuse_report.rb
- app/models/feedback.rb
- app/models/feedback_reporters/abuse_reporter.rb
- app/models/feedback_reporters/feedback_reporter.rb
- app/models/feedback_reporters/support_reporter.rb
- app/views/abuse_reports/new.html.erb
- app/views/abuse_reports/report.xml.erb
- app/views/feedbacks/new.html.erb
- app/views/feedbacks/report.xml.erb
- config/application.rb
Clean up abuse and support controllers and centralize 16bugs calls so they'll be easier to change
https://code.google.com/p/otwarchive/issues/detail?id=4225
> Clean up abuse and support controllers

- public/drive.html
https://code.google.com/p/otwarchive/issues/detail?id=4238
> Issue 4238: Remove premium message

- public/help/css-help.html
- public/help/skins-creating.html
https://code.google.com/p/otwarchive/issues/detail?id=3843
Fix a typo
> 3843 Layer, not ayer, this is not Spanish

- app/controllers/invitations_controller.rb
- app/views/invitations/index.html.erb
- app/views/invite_requests/manage.html.erb
- app/views/invite_requests/show.js.erb
- features/other_a/invite_request.feature
- features/step_definitions/invite_steps.rb
Some more instances of Invite/Invitation
https://code.google.com/p/otwarchive/issues/detail?id=4205
https://code.google.com/p/otwarchive/issues/detail?id=4204
> Issue 4204 4205 4206

- app/views/abuse_reports/report.xml.erb
- app/views/feedbacks/report.xml.erb
Issue 4225: Add html_safe to prevent unnecessary escaping and remove extra paragraph tags
https://code.google.com/p/otwarchive/issues/detail?id=4225
> Issue 4225: Add html_safe to prevent unnecessary escaping

- app/controllers/invitations_controller.rb
- app/controllers/user_invite_requests_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=4205
> issue 4205 Fixing BOT

- app/controllers/comments_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=4244
> 4244 Only let admins access comments index

- app/models/feedback_reporters/feedback_reporter.rb
Restore paragraph tag stripping to abuse and support reports
https://code.google.com/p/otwarchive/issues/detail?id=4225
> BOT Fix: Restore paragraph tag stripping to abuse and support reports

- app/views/abuse_reports/report.xml.erb
- app/views/feedbacks/report.xml.erb
Remove extra spaces from abuse/support requests
https://code.google.com/p/otwarchive/issues/detail?id=4225
> Remove extra spaces from abuse/support requests

- Gemfile
- Gemfile.lock
- config/application.rb
https://code.google.com/p/otwarchive/issues/detail?id=4247
> Reduce the amount of logging

- app/controllers/comments_controller.rb
- app/decorators/homepage.rb
* Favorite tags will now display in alphabetical order
* Replying to a comment from the homepage will send you back to the homepage
> 4209 Homepage behavior tweaks

- public/stylesheets/site/2.0/01-core.css
- public/stylesheets/site/2.0/03-region-header.css
https://code.google.com/p/otwarchive/issues/detail?id=4253
> 4253 Less spacing around Subscribe and Favorite Tag buttons

- app/views/users/_legal.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4246
> Issue 4246: Make signup page text clear that you can be 13

- app/views/works/_work_header_navigation.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4119
> issue 4119 Don't show download link on drafts display

- Gemfile
- Gemfile.lock
- app/controllers/downloads_controller.rb
- app/models/work.rb
https://code.google.com/p/otwarchive/issues/detail?id=4242
Just use the Gem
> issue 4242 remove deprecation messages. 

- app/controllers/downloads_controller.rb
- app/models/work.rb
https://groups.google.com/forum/#!topic/ruby-roo/Wxf7jEWxpow
I have checked this on staging by hotfixing it and it looks better there. Its a problem that i didn't see in dev so hard to diagnose.
> issue 4242 remove deprecation messages ( fix bot )

- Gemfile
- Gemfile.lock
https://code.google.com/p/otwarchive/issues/detail?id=4243
> issue 4243 : Follow suggestions

- Gemfile
- Gemfile.lock
- app/controllers/downloads_controller.rb
- app/models/work.rb
Reverts otwcode/otwarchive#2053
> Revert "issue 4242: Another way to remove the warning"

- Gemfile
- Gemfile.lock
- app/controllers/downloads_controller.rb
- app/helpers/works_helper.rb
- app/models/work.rb
https://code.google.com/p/otwarchive/issues/detail?id=4242
This has the advantage of "olá, mundo!" -> "ola, mundo!"
> issue 4242: With yet another method with transliteration

- app/views/works/_standard_form.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4220
> 4220 Add warning about not composing in the form.

- app/controllers/favorite_tags_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=4262
> 4262 Add homepage link to Favorite Tags success message

- config/environments/production.rb
- config/environments/staging.rb
https://code.google.com/p/otwarchive/issues/detail?id=4271
Allow multiple memcached instances and load balance over them.
> Issue 4271 more memcached.

- app/controllers/home_controller.rb
- config/config.yml
https://code.google.com/p/otwarchive/issues/detail?id=4219
This is hard to test in dev
> issue 4119 : Cache homepage numbers

- app/controllers/home_controller.rb
- config/config.yml
Reverts otwcode/otwarchive#2049
> Revert "issue 4119 : Cache homepage numbers"

- app/views/user_invite_requests/new.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4201
> issue 4201 change request for invite text

- app/views/invite_requests/_invite_request.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=3691
> 3691 Invitations: 400 people in the queue and I am number 600 of those 400

- app/controllers/kudos_controller.rb
- app/models/kudo.rb
- public/javascripts/application.js
https://code.google.com/p/otwarchive/issues/detail?id=4245
> issue: 4245 : A guest should not be able to add kudos to a restricted work

- app/views/user_invite_requests/new.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4201
> contact Support, not Contact Support

- public/stylesheets/site/2.0/25-role-handheld.css
https://code.google.com/p/otwarchive/issues/detail?id=3000
This makes it so the entire contents of the modal will be visible on small screens instead of making the contents scroll within the modal.
> 3000 Better mobile scrolling on help modals

- public/stylesheets/site/2.0/25-role-handheld.css
https://code.google.com/p/otwarchive/issues/detail?id=3000
It... appears to have already fixed itself on production at some point in the last week or so. o_0
> Revert 3000 Better mobile scrolling on help modals

- app/views/user_invite_requests/new.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4201
> issue 4201 invitations not invites

- app/models/story_parser.rb
- app/views/works/new_import.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4264
Sometimes its easier just to start again
> Issue 4264: Add Quotev to the warning on the Import form

- app/controllers/chapters_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=3704
> 3704 Update the reading history for any chapter

- app/controllers/home_controller.rb
- app/views/home/unicorn_test.html.erb
- config/routes.rb
https://code.google.com/p/otwarchive/issues/detail?id=4279
> A simple health check

- app/controllers/application_controller.rb
- config/config.yml
https://code.google.com/p/otwarchive/issues/detail?id=4280
> Move expiry out of yml file so it works

- app/views/users/change_email.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=3086
The changes mentioned on pull request #2092 -- sorry, james; we just wanted to get this in ASAP.
> 3086 Add current email to dl on change email page

- app/views/works/index.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4285
The "Filters" link wasn't there on http://test.ao3.org/collections/COLLECTIONNAME/works
> 4285 Make sure Filters link shows on collections

- public/drive.html
https://code.google.com/p/otwarchive/issues/detail?id=4287
> 4287 Drive page changes

- config/application.rb
https://code.google.com/p/otwarchive/issues/detail?id=4276
> 4276 Don't enforce locales

- app/mailers/kudo_mailer.rb
> issue 4106 This one slipped though

- app/views/preferences/index.html.erb
- features/other_a/preferences_edit.feature
https://code.google.com/p/otwarchive/issues/detail?id=4099
> issue 4099 consitency.

- app/controllers/api/v1/works_controller.rb
- config/initializers/gem-plugin_config/resque.rb
- spec/api/api_spec.rb
https://code.google.com/p/otwarchive/issues/detail?id=4307
This fixes some undesirable behaviour that is affecting the ongoing HASA import for Open Doors.
> 4307 - Search for an exact match when checking an imported URL

- app/views/home/_tos.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4302
> Issue 4302 Change TOS

- app/mailers/user_mailer.rb
- app/models/work_observer.rb
- app/views/user_mailer/edit_work_notification.html.erb
- app/views/user_mailer/edit_work_notification.text.erb
- config/locales/en.yml
Nothing to test 
https://code.google.com/p/otwarchive/issues/detail?id=4313
> Issue 4313 clean up remove edit work notification

- app/mailers/kudo_mailer.rb
- app/views/kudo_mailer/batch_kudo_notification.html.erb
- app/views/kudo_mailer/batch_kudo_notification.text.erb
- config/locales/en.yml
https://code.google.com/p/otwarchive/issues/detail?id=4321
> Issue 4321 fix formatting on kudos email

- Gemfile
- Gemfile.lock
- config/initializers/transaction_retry.rb
https://code.google.com/p/otwarchive/issues/detail?id=4299
> Issue 4299 reduce the number of deadlocks

- app/mailers/kudo_mailer.rb
- app/views/kudo_mailer/batch_kudo_notification.html.erb
- app/views/kudo_mailer/batch_kudo_notification.text.erb
This is to fix the problem in https://code.google.com/p/otwarchive/issues/detail?id=4327
> 4327 - Apply bold style to individual kudos givers, not the entire string

- public/stylesheets/site/2.0/10-types-groups.css
https://code.google.com/p/otwarchive/issues/detail?id=4260
> 4260 Fix disappearing tag link underline

- public/stylesheets/site/2.0/10-types-groups.css
Reverts otwcode/otwarchive#2052
> Revert "4260 Fix disappearing tag link underline"

- app/controllers/application_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=3727
> 3727 Return to the restricted work after login

- app/controllers/application_controller.rb
https://code.google.com/p/otwarchive/issues/detail?id=3727
Reverting so we can merge something else while Pull Request #2142 awaits review
> Revert "3727 Return to the restricted work after login"

- app/sweepers/kudos_sweeper.rb
- app/views/kudos/_kudos.html.erb
- public/javascripts/application.js
https://code.google.com/p/otwarchive/issues/detail?id=4308
> 4308 Clicking formerly collapsed names in kudos list doesn't open user page

- app/controllers/admin/admin_users_controller.rb
- app/views/admin/admin_users/show.html.erb
- features/admins/admin_manage_users.feature
https://code.google.com/p/otwarchive/issues/detail?id=4168
Also disables the browser autocomplete setting on these fields to avoid any accidents.
> 4168 Editing FNOK after entering invalid username

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20150725141326_install_audited.rb
Add auditing to user accounts to allow us to track troll accounts
> Add auditing to user accounts

- config/routes.rb
Issue 4175: Fix bug preventing FAQ reordering
https://code.google.com/p/otwarchive/issues/detail?id=4175
> Issue 4175: Fix bug preventing FAQ reordering

- app/helpers/prompt_restrictions_helper.rb
- app/views/challenge/gift_exchange/_gift_exchange_form.html.erb
- app/views/challenge/prompt_meme/_prompt_meme_form.html.erb
- app/views/prompt_restrictions/_prompt_restriction_form.html.erb
I'm sure that the changes that I've made to the prompt_restrictions_helper could be much better, but it took long enough just to get this functional. I welcome suggestions/advice. :)
Issue 2491: https://code.google.com/p/otwarchive/issues/detail?id=2491
> Issue 2491 editing pm settings

- app/views/user_mailer/feedback.html.erb
- app/views/user_mailer/feedback.text.erb
- features/other_b/support.feature
Fixes issue #2148 (also known as https://code.google.com/p/otwarchive/issues/detail?id=4333 and https://otwarchive.myjetbrains.com/youtrack/issue/TST-1 and OTW3-4316 on Jira)
Change automated support feedback email in line with a request from Support.
> AO3-4324 - GCode 4333 - Improve Support confirmation email

- README.md
Resolves issue: https://otwarchive.atlassian.net/browse/AO3-4334
Does what the title says.
> AO3-4334 Add link to JIRA to GitHub README

- config/environments/production.rb
- config/environments/staging.rb
https://otwarchive.atlassian.net/browse/AO3-4329
This needs approval as I can't easily test it on a dev, this is the best I can demonstate:
09:57 /vagrant/otwarchive (AO3-4329)$ bundle exec rails c
Loading development environment (Rails 3.2.21)
2.0.0-p645 :001 > YAML.load_file("#{Rails.root}/config/local.yml")['MEMCACHED_SERVERS']
=> "127.0.0.1,127.0.0.1" 
2.0.0-p645 :002 > YAML.load_file("#{Rails.root}/config/local.yml")['MEMCACHED_SERVERS'].split(",")
=> ["127.0.0.1", "127.0.0.1"] 
2.0.0-p645 :003 >
> AO3-4329 Split a string to find the memcached servers

- app/views/works/_work_series_links.html.erb
https://otwarchive.atlassian.net/browse/AO3-4322
Was https://code.google.com/p/otwarchive/issues/detail?id=4331
> AO3-4322 Fix HTML tag on work series heading

- app/models/search.rb
Resolves: https://otwarchive.atlassian.net/browse/AO3-4292
> AO3-4249 Advanced work search date field is case sensitive

- .coveralls.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- features/support/env.rb
- spec/spec_helper.rb
Resolves: https://otwarchive.atlassian.net/browse/AO3-4348
Wherein we get rid of Coveralls, and tango with tests another day!
> AO3-4348 Remove Coveralls for Archive repository

- config/deploy.rb
- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4351
Nothing to test, sorry
> Ao3 4351 Changes to deployment 

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4352
> Ao3 4352 remove ao3-front02 while it out of service

- app/controllers/bookmarks_controller.rb
- features/bookmarks/bookmark_create.feature
Resolves: https://otwarchive.atlassian.net/browse/AO3-4338
Add a check that 'collection' exists, then proceed from there. This includes a cucumber test.
> AO3-4338 Fail nicely when collection doesn't exist on bookmark edit with tests!

- config/deploy/production.rb
Current state of the machines, maybe this should be a systems thing rather than in the code base in future.
> current state

- app/views/home/diversity_statement.html.erb
https://otwarchive.atlassian.net/browse/AO3-4034
All instances of "the archive" have been changed to "the Archive". Instances of "this archive" have not been changed.
> AO3-4034 Capitalisation fix in Diversity Statement

- config/deploy.rb
- config/deploy/i18n.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- lib/tasks/skin_tasks.rake
I think these are the changes needed for a new deploy.
> Need to recache skins everywhere

- app/controllers/comments_controller.rb
- app/views/comment_mailer/_comment_notification_footer_for_other.html.erb
- app/views/comments/review.js.erb
- app/views/home/_inbox_module.html.erb
- app/views/inbox/_approve_button.html.erb
- app/views/inbox/show.html.erb
- features/comments_and_kudos/comment_moderation.feature
- public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-3543
The tweaks from https://otwarchive.atlassian.net/browse/AO3-3543?focusedCommentId=333506&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-333506
> AO3-3543 Comment moderation tweaks

- app/controllers/comments_controller.rb
- app/views/comment_mailer/_comment_notification_footer_for_other.html.erb
- app/views/comments/review.js.erb
- app/views/home/_inbox_module.html.erb
- app/views/inbox/_approve_button.html.erb
- app/views/inbox/show.html.erb
- features/comments_and_kudos/comment_moderation.feature
A few more tweaks and bugfixes as described in https://otwarchive.atlassian.net/browse/AO3-3543
> AO3-3543-A few more tweaks to comment moderation

- config/deploy.rb
- config/deploy/production.rb
One server is back in action
And a pull request so the site is less naked.
> Infrastructure changes

- app/models/work.rb
Hotfix: don't index comment moderation field for works
https://otwarchive.atlassian.net/browse/AO3-4373
> Hotfix: don't index comment moderation field for works

- app/views/admin/admin_users/show.html.erb
- features/admins/admin_manage_users.feature
> AO3-4330-made it possible to destroy works for already permabanned user

- app/controllers/gifts_controller.rb
- app/helpers/works_helper.rb
- app/models/creation_observer.rb
- app/models/gift.rb
- app/models/pseud.rb
- app/models/user.rb
- app/models/work.rb
- app/views/gifts/_gift_blurb.html.erb
- app/views/gifts/index.html.erb
- app/views/works/_meta.html.erb
- app/views/works/_standard_form.html.erb
- app/views/works/_work_header_navigation.html.erb
- app/views/works/_work_header_notes.html.erb
- app/views/works/_work_module.html.erb
- config/routes.rb
- db/migrate/20150829180100_add_rejected_to_gifts.rb
- features/gift_exchanges/challenge_giftexchange.feature
- features/other_a/gift.feature
- features/step_definitions/challege_gift_exchange_steps.rb
- features/step_definitions/gift_steps.rb
- features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-3145
* You should now be able to reject and unreject gifts
** User viewing their own gifts page should see two button-style links at the top: "Accepted Gifts" and "Refused Gifts"
** The heading on the accepted gifts page will be "Gifts for [user]," and gifts will have a "Refuse Gift" button
** The heading on the rejected gifts page will be "Refused Gifts for [user]", and gifts will have an "Accept Gift" button
** When they click the "Refuse Gift" button, they see "This work will no longer be listed among your gifts." and the gift story should no longer say "For [user]" and should move from the "Gifts for [user]" to the "Refused Gifts for [user]" page. The blurb should also update.
** They should also now see a button that says "Accept Gift" …
> AO3-3145 gift rejection

- db/schema.rb
We shouldn't need this but it makes it work
> Let migrations work

- app/views/owned_tag_sets/_show_tags_by_alpha.html.erb
Resolves: https://otwarchive.atlassian.net/browse/AO3-4382
Just fixes a small typo that caused a partial to not render.
> AO3-4382 Missing = caused Freeform listbox to not render on page

- .phraseapp.yml
Investigating phraseapp github integration.
> A minimal .phraseapp.yml with no access token

- config/locales/en-US.yml
This should pass test and be reviewed.
I have just copied en.yml on to the end of en-US.yml
> Migrate data from en.yml to en-US.yml

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/staging.rb
- config/initializers/active_record_log_subscriber.rb
https://otwarchive.atlassian.net/browse/AO3-4392
> AO3-4392 Introduce bullet.

- Gemfile
> AO3-4392 Add bullet to staging

- config/environments/staging.rb
> AO3-4392 Turn off footer on staging

- app/helpers/application_helper.rb
- app/models/creatorship.rb
- app/models/pseud.rb
- app/models/user.rb
Cache bylines to help sad servers
https://otwarchive.atlassian.net/browse/AO3-4362
> Cache bylines to help sad servers

- features/other_a/reading.feature
To add to James's code change, an extra test to be clearer and more thorough about it.
> AO3-4401 Test for readings

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-4409
> Lets try this then, moving the links around.

- app/controllers/works_controller.rb
Merge after https://github.com/otwcode/otwarchive/pull/2250
https://otwarchive.atlassian.net/browse/AO3-4393
Go to http://test.archiveofourown.org/works and there should not be any errors ( Apart from possibly skins if https://github.com/otwcode/otwarchive/pull/2227 has not been merged ).
I would test with caching disabled, and also with filters disabled.
> AO3 4393 reduce n+1 in /works

- features/step_definitions/user_steps.rb
- features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-3922
> Tests for AO3-3922 co-authoring

- features/users/user_rename.feature
Checking the key behaviour, making it clear and easy for someone to fix later.
https://otwarchive.atlassian.net/browse/AO3-3468
> Tests for AO3-3468

- app/controllers/tags_controller.rb
- app/models/tag.rb
- features/step_definitions/tag_steps.rb
- features/tags_and_wrangling/tag_comment.feature
- features/tags_and_wrangling/tag_search.feature
This will affect the tag show page (ao3/tag/Angst and similar). It's now telling me my loading is over-eager, but I figure that's better than N+1, unless anyone can spot a better way to solve both.
> AO3-4405 N+1 tags show

- app/controllers/bookmarks_controller.rb
Performance improvement using bullet on /bookmarks page.
> AO3-4404 N+1 bookmarks

- app/helpers/pseuds_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4396
A clean up of https://github.com/otwcode/otwarchive/pull/2253
> AO3 4396 Remove n+1 from print_pseud_list

- app/models/skin.rb
https://otwarchive.atlassian.net/browse/AO3-4291
> AO3-4291 Fix parsing of media from filename

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4424
I think this is a low risk gem and can be folded in with another issue.
> Ao3 4424 update newrelic

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4442
> AO3-4442 Update pickle

- features/works/work_delete.feature
https://otwarchive.atlassian.net/browse/AO3-4455
The automated test for deleting works has some old TODO comments. Fix the broken bits and finish it off.
> AO3-4455 Improving work deletion test, removing TODOs

- features/admins/admin_post_issues.feature
- features/admins/admin_post_news.feature
- features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-4464
The automated tests for admin news posts, known issues and marking comments as spam have TODOs or other comments in them that need updating, expanding or fixing.
> AO3-4464 Admin automated test TODOs

- features/admins/admin_tasks.feature
- features/importing/archivist.feature
- features/other_a/homepage.feature
- features/step_definitions/archivist_steps.rb
- features/support/paths.rb
- features/tags_and_wrangling/tag_wrangling_special.feature
- spec/models/abuse_report_spec.rb
- test/fixtures/roles.yml
https://otwarchive.atlassian.net/browse/AO3-4422
Covers testing the admin stats page, the Open Doors tools page, diversity statement, DMCA and donation pages. Also an attempt at testing updating works when accents change, though it doesn't yet do all the things we should test eventually.
> AO3-4422 Add some more automated tests

- lib/skin_cache_helper.rb
Be explicit that each skin has a different cache rather than expectin…g skin_cache_value to do that.
Add the skin id to the cache key.
> AO3-4370 fix bot

- lib/skin_cache_helper.rb
Reverts otwcode/otwarchive#2328
> Revert "AO3-4370 fix bot"

- public/stylesheets/site/2.0/16-zone-system.css
- public/stylesheets/site/2.0/26-media-narrow.css
Reverts otwcode/otwarchive#2305
> Revert "AO3-4350 Homepage off-center"

- app/controllers/admin/stats_controller.rb
- app/helpers/stats_helper.rb
- app/views/admin/stats/_invitation_stats.html.erb
- app/views/admin/stats/_tag_stats.html.erb
- app/views/admin/stats/_user_stats.html.erb
- app/views/admin/stats/_work_stats.html.erb
- app/views/admin/stats/index.html.erb
- config/routes.rb
Reverts otwcode/otwarchive#2325
> Revert "AO3-4463 Removing admin stats pages"

- public/stylesheets/site/2.0/16-zone-system.css
- public/stylesheets/site/2.0/26-media-narrow.css
Reverts otwcode/otwarchive#2336
> Revert "Revert "AO3-4350 Homepage off-center""

- app/models/skin.rb
- app/models/work_skin.rb
- app/views/layouts/_footer.html.erb
- config/environments/development.rb
- config/environments/test.rb
- features/other_b/skin.feature
- features/step_definitions/skin_steps.rb
- lib/skin_cache_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4378
This has the old recursive get_block, it is only in the  slow path so bah.
> AO3-4378 The return of the skin cache.

- features/bookmarks/bookmark_create.feature
https://otwarchive.atlassian.net/browse/AO3-4469
The automated test for bookmarks on restricted works has a TODO comment. Fix it.
> AO3-4469 Fixing bookmark test TODO

- features/importing/archivist.feature
- features/step_definitions/archivist_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4456
Automated test for importing works has some old TODO comments. Check them and either do them or remove them if no longer relevant.
> AO3-4456 Fixing TODOs in importing tests

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4433
I would look at ajaxy things for example comments unfolding and kudos giving.
> AO3-4433 Update jquery-rails

- public/javascripts/rails.js
https://otwarchive.atlassian.net/browse/AO3-4465
> AO3-4465 Upgrade rails.js

- features/comments_and_kudos/comments_redirect.feature
https://otwarchive.atlassian.net/browse/AO3-4487
The automated test for redirecting to chapter-by-chapter or entire work after making a comment has a WIP bit and some TODOs. Fix them.
> AO3-4487 Fix WIP test for comment redirecting

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-4409
> AO3-4409 Deployment skin issue

- app/controllers/application_controller.rb
Make sure that the site is happy with or with out a banner. ( I believe this is low risk )
https://otwarchive.atlassian.net/browse/AO3-4471
> AO3-4471 Cache the fact that there is not a site banner.

- config/deploy.rb
Reverts otwcode/otwarchive#2357
> Revert "AO3-4409 Deployment skin issue"

- app/helpers/works_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4397
Clean up of https://github.com/otwcode/otwarchive/pull/2254
> AO3 4397 Remove n+1 error in list of reciepients

- app/models/skin.rb
- app/views/skins/_form.html.erb
- app/views/skins/_wizard_form.html.erb
- spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4490
> AO3-4490 Require title for skins

- app/helpers/works_helper.rb
Reverts otwcode/otwarchive#2279
> Revert "AO3 4397 Remove n+1 error in list of reciepients"

- app/models/story_parser.rb
- features/importing/work_import_dw.feature
- features/step_definitions/preferences_steps.rb
- spec/models/story_parser_spec.rb
- spec/models/work_spec.rb
Reverts otwcode/otwarchive#2137
> Revert "AO3-3883 import date time not date"

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4445
> AO3-4445 update rack-dev-mark

- app/views/home/_tos.html.erb
- app/views/home/tos_faq.html.erb
https://otwarchive.atlassian.net/browse/AO3-4489
> AO#-4489 Fix BOT TOS changes.

- app/views/home/tos_faq.html.erb
> AO3-4489 Edits from Lady oscar

- app/models/chapter.rb
- app/models/work.rb
- lib/work_chapter_count_caching.rb
Cache the counts of the number of chapters a work has.
https://otwarchive.atlassian.net/browse/AO3-4496
> AO3-4496 Cache chapter counts

- app/controllers/feedbacks_controller.rb
- app/controllers/languages_controller.rb
- app/views/feedbacks/new.html.erb
- app/views/languages/_form.html.erb
- app/views/languages/edit.html.erb
- app/views/languages/index.html.erb
- app/views/languages/new.html.erb
- app/views/languages/show.html.erb
- config/config.yml
- db/migrate/20151018165632_add_support_available_to_languages.rb
- public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-4356
> AO3-4356 Make support languages editable by admins

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4444
> AO3-4444 update  rack-cache

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4431
> AO3-4431 update connection_pool gem

- app/controllers/collections_controller.rb
This is running on test and beta as a hot fix
https://otwarchive.atlassian.net/browse/AO3-4507
Release notes: Credit to de3sw2aq1
> AO3-4507 Validate collection type

- app/models/kudo.rb
- features/comments_and_kudos/kudos.feature
https://otwarchive.atlassian.net/browse/AO3-4508
> AO3-4508 validate kudos

- app/controllers/collections_controller.rb
(still one left for Gifts, but this gets most of them)
https://otwarchive.atlassian.net/browse/AO3-4406
> AO3-4406 N+1 on collection show page

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4425
https://github.com/swanandp/acts_as_list
This handles ordering of lists of things and is used by:
app/models/archive_faq.rb: acts_as_list
app/models/chapter.rb: # acts_as_list :scope => 'work_id = #
{work_id}
'
app/models/invite_request.rb: acts_as_list
app/models/question.rb: acts_as_list
app/models/serial_work.rb: acts_as_list :scope => :series
app/models/wrangling_guideline.rb: acts_as_list
> A03-4425 Update acts_as_list

- app/models/tag.rb
- app/models/work.rb
- app/views/works/_work_module.html.erb
https://otwarchive.atlassian.net/browse/AO3-4497
> Ao3 4497 Cache the list of tags associated with the work

- app/views/works/_work_header_navigation.html.erb
- features/step_definitions/work_steps.rb
> AO3-4504 - Remove Delete Work button from work view

- features/importing/work_import_errors.feature
https://otwarchive.atlassian.net/browse/AO3-4486
The work import test has a WIP bit for bogus URLs. Fix it into a proper test.
> AO3-4486 Fix work import test @wip

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4426
Testing: Import works from a remote url
> AO3-4426 Update addressable

- Gemfile
- Gemfile.lock
- script/check_syntax
- script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-4509
So we will either need to update a gem or add it to an exceptions list
> AO3-4509 Add gem security to tests

- app/models/story_parser.rb
- features/importing/work_import.feature
Follow-on to https://otwarchive.atlassian.net/browse/AO3-4499 whereby the change didn't seem to change very much.
> AO3-4499 Backdate the work to fix chapter dates on Chapter Index

- features/importing/archivist.feature
https://otwarchive.atlassian.net/browse/AO3-4484
The automated test for your works being imported and then you choose to orphan them was incomplete. Expand it.
> AO3-4484 Expanding importing test for orphaning

- lib/tasks/resque.rake
> AO3-4447 Update resque/redis/resque_scheduler

- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-4521
> AO3-4521 Migrate roles to test-app02

- lib/tasks/resque.rake
This looks good in dev.
https://otwarchive.atlassian.net/browse/AO3-4447
> AO3-4447 Fix BOT with scheduler failing to start

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- app/helpers/share_helper.rb
- app/models/work.rb
- app/views/works/_work_abbreviated_list.html.erb
- features/other_a/page_title.feature
- features/step_definitions/page_title_steps.rb
- features/support/hooks.rb
https://otwarchive.atlassian.net/browse/AO3-4512
I would look at the sharing links to make sure all is well.
> AO3-4512 More caching of tags

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- app/helpers/share_helper.rb
- app/models/work.rb
- app/views/works/_meta.html.erb
- app/views/works/_work_abbreviated_list.html.erb
- app/views/works/_work_module.html.erb
- features/other_a/page_title.feature
- features/step_definitions/page_title_steps.rb
- features/support/hooks.rb
- features/tags_and_wrangling/tag_wrangling_special.feature
- lib/tasks/memcached.rake
Merge this after https://github.com/otwcode/otwarchive/pull/2390
https://otwarchive.atlassian.net/browse/AO3-4230
This should hopefully fix the blurb caching issues.
> AO3-4230 work blurb caching fix

- app/views/comments/_single_comment.html.erb
The cache key on comments is too complex to work out, so just stick a maximum cache time of a week.
https://otwarchive.atlassian.net/browse/AO3-4510
> AO3-4510 Allow comments to fall out of the cache

- app/views/works/_meta.html.erb
https://otwarchive.atlassian.net/browse/AO3-4525
> AO3-4525 Remove unwanted "-" from top of works

- app/helpers/tags_helper.rb
- app/models/work.rb
New format, new version of cache key
https://otwarchive.atlassian.net/browse/AO3-4512
> AO3-4512 fix 500 on test

- .travis.yml
https://otwarchive.atlassian.net/browse/AO3-4527
> AO3-4527 Send Travis emails to otw-coders-extra

- public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-4538
> AO3-4538 Resize news post images to fix screen

- app/helpers/tags_helper.rb
- app/models/work.rb
Reverts otwcode/otwarchive#2407
> Revert "AO3-4512 fix 500 on test"

- app/views/works/_meta.html.erb
Reverts otwcode/otwarchive#2406
> Revert "AO3-4525 Remove unwanted "-" from top of works"

- app/models/work.rb
- app/views/works/_meta.html.erb
- app/views/works/_work_module.html.erb
- features/tags_and_wrangling/tag_wrangling_special.feature
- lib/tasks/memcached.rake
Reverts otwcode/otwarchive#2391
> Revert "AO3-4230 work blurb caching fix"

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- app/helpers/share_helper.rb
- app/models/work.rb
- app/views/works/_work_abbreviated_list.html.erb
- features/other_a/page_title.feature
- features/step_definitions/page_title_steps.rb
- features/support/hooks.rb
Reverts otwcode/otwarchive#2390
> Revert "AO3-4512 More caching of tags"

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- app/helpers/share_helper.rb
- app/models/work.rb
- app/views/works/_work_abbreviated_list.html.erb
- features/other_a/page_title.feature
- features/step_definitions/page_title_steps.rb
- features/support/hooks.rb
Reverts otwcode/otwarchive#2419
> Revert "Revert "AO3-4512 More caching of tags""

- app/models/work.rb
- app/views/works/_meta.html.erb
- app/views/works/_work_module.html.erb
- features/tags_and_wrangling/tag_wrangling_special.feature
- lib/tasks/memcached.rake
Reverts otwcode/otwarchive#2418
> Revert "Revert "AO3-4230 work blurb caching fix""

- app/views/works/_meta.html.erb
Reverts otwcode/otwarchive#2417
> Revert "Revert "AO3-4525 Remove unwanted "-" from top of works""

- app/helpers/tags_helper.rb
- app/models/work.rb
Reverts otwcode/otwarchive#2416
> Revert "Revert "AO3-4512 fix 500 on test""

- lib/tasks/resque.rake
Reverts otwcode/otwarchive#2403
> Revert "AO3-4447 Fix BOT with scheduler failing to start"

- lib/tasks/resque.rake
Reverts otwcode/otwarchive#2398
> Revert "AO3-4447 Update resque/redis/resque_scheduler"

- Gemfile
- Gemfile.lock
- config/initializers/gem-plugin_config/resque.rb
- script/gem_security.sh
Reverts otwcode/otwarchive#2380
> Revert "AO3-4447 Redis and resque gem updates"

- app/models/reading.rb
Check that readings still happen, this is going to be very hard to tell if it is in effect or not.
I can look at the logs and that is about it.
If it passes the automated tests around readings then i wouldn't expect more testing than that.
> AO3-4401 Batch readings rake task

- Gemfile
- Gemfile.lock
- script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-4460
This was reverted as it had been infected by the rufus scheduler update
> AO3-4460 update the rest-client

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-4545
> AO3-4545 skins on front end machines

- app/models/feedback_reporters/feedback_reporter.rb
Fixes BoT: https://otwarchive.atlassian.net/browse/AO3-4532
> AO3-4532 - Missing an attr_accessor in feedbacks reporter

- factories/feedback.rb
https://otwarchive.atlassian.net/browse/AO3-4532
A syntax error in the Support form tests was preventing the app from starting on webdev/local
> AO3-4532 Fix Support factory

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- app/helpers/application_helper.rb
- app/views/works/_work_module.html.erb
- app/views/works/show.html.erb
- features/step_definitions/work_steps.rb
- features/works/work_drafts.feature
Reverts otwcode/otwarchive#2365
> Revert "AO3-4494 Omit time when showing date on which drafts will be deleted."

- app/views/user_mailer/added_to_collection_notification.html.erb
- app/views/user_mailer/added_to_collection_notification.text.erb
Resolves BoT AO3-2665: https://otwarchive.atlassian.net/browse/AO3-2665
Fixed incorrect link in HTML and txt emails.
> AO3-2665 Fix link to user preferences from email

- app/views/user_mailer/added_to_collection_notification.html.erb
- app/views/user_mailer/added_to_collection_notification.text.erb
- app/views/user_mailer/invited_to_collection_notification.html.erb
- app/views/user_mailer/invited_to_collection_notification.text.erb
[Link to bug](https://otwarchive.atlassian.net/browse/AO3-2665)
> [AO3-2665] Preferences link in Add to Collection emails

- app/views/home/_dmca.html.erb
https://otwarchive.atlassian.net/browse/AO3-4561
> AO3-4561 Update counternotice generator & FAQ links

- app/controllers/admin/banners_controller.rb
- app/views/admin/banners/_banner_form.html.erb
- features/other_a/banner_general.feature
- features/step_definitions/banner_steps.rb
Reverts otwcode/otwarchive#2435
> Revert "AO3-4547 Allow banner updates WITHOUT turning banner back on"

- app/views/home/_dmca.html.erb
https://otwarchive.atlassian.net/browse/AO3-4561
> AO3-4561 Fix the link

- app/controllers/tag_wranglers_controller.rb
- app/controllers/tag_wranglings_controller.rb
- app/views/tag_wranglings/_wrangler_dashboard.html.erb
Cache the Unsorted Tags, don't particularly like this in the view
https://otwarchive.atlassian.net/browse/AO3-4581
> AO3-4581 cache wrangling counts. ( BOT )

- app/controllers/unsorted_tags_controller.rb
> AO3-4581 more caching the counts.

- app/controllers/potential_matches_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4577
> AO3-4577 fix for timeout of no-recipients page for large challenge

- app/views/works/_standard_form.html.erb
- app/views/works/_work_form_associations_language.html.erb
- app/views/works/edit_tags.html.erb
- features/admins/admin_works.feature
- features/works/work_edit_tags.feature
https://otwarchive.atlassian.net/browse/AO3-3597
Pull the language field out into partial and plop it down in the edit_tags page for admins
> AO3-3597 Let admins edit work languages

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4596
> AO3-4596 Take ao3-app09 and ao3-app10 out of service

- public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-4593
> AO3-4593 Indicate if HTML or Rich Text editor is in use

- app/views/tags/edit.html.erb
- features/tags_and_wrangling/tag_wrangling_characters.feature
- features/tags_and_wrangling/tag_wrangling_fandoms.feature
- features/tags_and_wrangling/tag_wrangling_freeforms.feature
- features/tags_and_wrangling/tag_wrangling_relationships.feature
https://otwarchive.atlassian.net/browse/AO3-4588
> AO3 4588 Make "Make tag non-canonical and unhook all associations" function admin only

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4598
> AO3-4598 Put ao3-app09 back in service

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4601
> AO3-4601 Add server back in to the mix

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4612
> AO3-4612 Reinstall an old server

- Gemfile
- Gemfile.lock
See https://github.com/otwcode/otwarchive/pull/2312
https://otwarchive.atlassian.net/browse/AO3-4446
> AO3-4446 Update Unicorn

- config/locales/en.yml
https://otwarchive.atlassian.net/browse/AO3-4420
> AO3-4420 Fix duplicate kudos sections

- app/controllers/users_controller.rb
Try and have a transaction to ensure that the user is found ( all to do with mysql clusters )
https://otwarchive.atlassian.net/browse/AO3-4585
> AO3-4585 wrap creating a user in a transaction 

- public/stylesheets/site/2.0/04-region-dashboard.css
- public/stylesheets/site/2.0/08-actions.css
- public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-4597
there was a tiny design quirk that always stood out to me on mobile...
this seems to fix it on both mobile and desktop
before: 
http://imgh.us/Screen_Shot_2016-07-09_at_10.33.38.png
after:
http://imgh.us/Screen_Shot_2016-07-09_at_10.32.37.png
it's my first time contributing to an open source project so i
apologise if i made any errors > <
> AO3-4597 actions spacing

- app/controllers/comments_controller.rb
- app/helpers/bookmarks_helper.rb
- app/views/bookmarks/new.html.erb
- app/views/comments/_comment_form.html.erb
- features/comments_and_kudos/add_comment.feature
- features/step_definitions/comment_steps.rb
- features/step_definitions/generic_steps.rb
- public/stylesheets/site/2.0/08-actions.css
Allow user to create a bookmark directly from commenting.
https://otwarchive.atlassian.net/browse/AO3-4544
> AO3-4544 comment bookmarks

- app/controllers/admin/banners_controller.rb
- app/views/admin/banners/_banner_form.html.erb
- features/other_a/banner_general.feature
- features/step_definitions/banner_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4547
Reverts otwcode/otwarchive#2470
> AO3-4547 Allow banner updates WITHOUT turning banner back on

- config/initializers/gem-plugin_config/sanitizer_config.rb
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4626
> AO3-4626 Remove from whitelist  two old sites

- config/initializers/gem-plugin_config/sanitizer_config.rb
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4627
> AO3-4627 Add  viddertube.com to whitelist

- config/initializers/gem-plugin_config/sanitizer_config.rb
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4335
> AO3-4335 Add archive.org to the Whitelist

- app/controllers/comments_controller.rb
- app/helpers/bookmarks_helper.rb
- app/views/bookmarks/new.html.erb
- app/views/comments/_comment_form.html.erb
- features/comments_and_kudos/add_comment.feature
- features/step_definitions/comment_steps.rb
- features/step_definitions/generic_steps.rb
- public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-4544
Reverts otwcode/otwarchive#2445 until we can fix the broken on test portion
> AO3-4544 Revert comment bookmarks

- app/controllers/collections_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4398
redoing https://github.com/otwcode/otwarchive/pull/2255 in a cleaner way ( i hope )
> AO3-4398 Remove n+1 from /collections

- features/step_definitions/challenge_promptmeme_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4640
> AO3-4640 Use yesterday and tomorrow for open/close dates in challenges

- app/models/indexing/index_subqueue.rb
https://otwarchive.atlassian.net/browse/AO3-4639
> AO3-4639 Update the list of valid options

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-4633
> AO3-4633 An ugly way to ensure that the machine is quiet during the upgrade

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4650
This removes warns from our test runs which makes it easier to understand
This only effects test runs and therefore there is not QA
> AO3-4650 Tidy up test warnings

- .travis.yml
https://otwarchive.atlassian.net/browse/AO3-4649
Speed up travis by having a cache for the bundler area
This only affects travis and does not need QA
> AO3-4649 Try travis caching of dependancies

- config/deploy.rb
Reverts otwcode/otwarchive#2528
> Revert "AO3-4633 An ugly way to ensure that the machine is quiet during the upgrade"

- features/gift_exchanges/potential_matches.feature
- features/step_definitions/potential_match_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4635
This pull request adds two extra tests to try to check whether the new matching code works with optional tags. (And it also fixes some mixed tabs-and-spaces indentations in the existing potential match test cases, since I just realized that it looked a bit wonky.)
The pull request only changes the automated test cases, so I don't think there's much to test (as long as the automated tests work).
> AO3-4635 Added extra tests for optional tags.

- Gemfile.lock
- app/controllers/bookmarks_controller.rb
- app/controllers/challenge_signups_controller.rb
- app/controllers/chapters_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/tag_set_nominations_controller.rb
- app/controllers/works_controller.rb
- features/bookmarks/bookmark_create.feature
- features/comments_and_kudos/add_comment.feature
- features/gift_exchanges/challenge_giftexchange.feature
- features/step_definitions/bookmark_steps.rb
- features/step_definitions/challege_gift_exchange_steps.rb
- features/step_definitions/comment_steps.rb
- features/step_definitions/search_steps.rb
- features/works/work_create.feature
- features/works/work_related.feature
- spec/controllers/chapters_controller_spec.rb
- spec/controllers/works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-**XXXX** (please fill in issue number and remove this comment)
(if you do not fill this in, we will use your GitHub account name and will use "they" to avoid making assumptions about your gender)
> AO3-4664 tidy up permissions

- spec/controllers/works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4664
> AO3-4664 Step over the test for a sec

- app/models/tag.rb
https://otwarchive.atlassian.net/browse/AO3-4653
Reduce the errors in the resque failed queue.
I would just make sure that a new work turns up in the tag listings.
> AO3-4653 Step over deleted tags

- app/models/indexing/index_subqueue.rb
https://otwarchive.atlassian.net/browse/AO3-4660
Clean up an error message and add a diagnostic so we can go looking for the real issue
I don't believe this needs testing ( Delete a work and ensure it is removed from feeds etc )
> AO3-4660 Issue with removing something from an index.

- features/other_b/skin.feature
- features/step_definitions/skin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4673
Adds a test to check that a logged in user can set a temporary skin
Nothing to test.
> AO3-4673 Add test for setting and unsetting skins

- Rakefile
https://otwarchive.atlassian.net/browse/AO3-4677
Rake is broken effectively on test.
> AO3-4677 Only think about coveralls in test

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4684
Upgrades our coverage gems to be more accurate ( we hope )
Nothing to be tested
> AO3-4684 Upgrade simplecov and coveralls and tins

- app/models/invitation.rb
- features/admins/admin_invitations.feature
- features/step_definitions/admin_steps.rb
- features/step_definitions/invite_steps.rb
- features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4679
This adds tests for the invite queue.
It also changes the definition of "out_of_invites" from having no unredeemed codes to having both no unredeemed codes and also no unsent codes which seemed obviously wrong
Make sure we are happy with the change of out_of_invites
> AO3-4679 Add tests for the invite queue.

- features/other_a/orphan_work.feature
- features/works/work_edit_multiple.feature
https://otwarchive.atlassian.net/browse/AO3-4671
This adds tests to check the functionality of deleting and orphaning multiple works
> AO3-4671 Add tests for delete and orphan multiple works

- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/bookmarks_controller.rb
- app/controllers/api/v1/works_controller.rb
- spec/api/api_authorization_spec.rb
- spec/api/api_base_controller_spec.rb
- spec/api/api_bookmarks_spec.rb
- spec/api/api_helper.rb
- spec/api/api_works_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4675
Adds Rspec tests to cover some areas left untested by the original tests. Also uncovered a couple of minor bugs (exception not caught, error message not returned).
Also standardises on double quotes throughout instead of a mix of single and double quotes.
> AO3-4675 API controller unit tests

- features/admins/admin_manage_users.feature
- features/admins/admin_works.feature
- features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4680
Increases coverage in Admin activities ( even if it is only two lines )
> AO3-4680 Add tests for admin activities

- README.md
https://otwarchive.atlassian.net/browse/AO3-4700
FIx the codeship badge and add a coveralls badge.
Look at the readme and see an image for codeship and a score for coveralls.
> AO3-4700 Fix codeship ?, Fix badges

- features/other_a/invite_request.feature
- features/step_definitions/invite_steps.rb
- features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4694
Extend tests in invitations_controller
> AO3-4694 Extend tests in invitations_controller

- features/other_b/errors.feature
- features/step_definitions/web_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4701
Adds coverage to error pages in various places.
> AO3-4701 Tests for misc error pages

- features/step_definitions/generic_steps.rb
- features/step_definitions/tag_steps.rb
- features/step_definitions/work_steps.rb
- features/support/paths.rb
- features/tags_and_wrangling/tag_wrangling_more.feature
https://otwarchive.atlassian.net/browse/AO3-4704
Extend tests for the tag_wranglings controller.
> AO3 4704 Extend tests for the tag_wranglings controller.

- app/controllers/challenges_controller.rb
- spec/controllers/challenges_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4715
This add some test coverage to the challenges_controller.rb file. 
Verify that code coverage has increased for the challenges_controller.rb file.
> AO3-4715 - Increase test coverage for challenges controller

- app/models/user.rb
- features/admins/admin_manage_users.feature
https://otwarchive.atlassian.net/browse/AO3-4669
Hopefully make the button do something useful...
At least the page should not 500
> AO3-4669 Fix the button that an admin can press on a user page

- spec/controllers/profile_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4725
Increases coverage to 100% for profile controller
> AO3-4725 Simple rspec test for profile controller

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4749
Remove ao3-app10 from server farm
No testing needed
> AO3-4749 ao3-app10 is unhappy

- features/other_a/invite_queue.feature
- features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-4762
> AO3-4762 added test for controllers/invite_requests_controller (admin deleting someone from queue)

- features/gift_exchanges/challenge_yuletide.feature
https://otwarchive.atlassian.net/browse/AO3-4770
Tidies up a few old TODOs
Cesy, she
> AO3-4770 Remove TODO comments in yuletide feature

- factories/api_key.rb
- spec/controllers/admin/api_controller_spec.rb
- spec/support/login_macros.rb
https://otwarchive.atlassian.net/browse/AO3-4761
Tests admin/api_controller
Run `bundle exec rspec spec/controllers/admin/api_controller_spec.rb`
potatoesque, she/her
> AO3-4761 Tests for admin/api_controller

- features/prompt_memes_a/challenge_promptmeme_setup.feature
- features/step_definitions/challenge_promptmeme_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4777
Bring us up to 100% coverage for the prompt meme model
> AO3-4777 Finish prompt meme model test

- app/controllers/abuse_reports_controller.rb
- app/models/abuse_report.rb
https://otwarchive.atlassian.net/browse/AO3-4752
> AO3-4752 – AbuseReportsController Strong Params

- app/controllers/admin/settings_controller.rb
- app/models/admin_setting.rb
https://otwarchive.atlassian.net/browse/AO3-4753
> AO3-4753 – AdminSettingController Strong Params

- app/controllers/languages_controller.rb
- app/models/language.rb
https://otwarchive.atlassian.net/browse/AO3-4756
> AO3-4756 – LanguagesController Strong Params

- features/admins/admin_post_issues.feature
- features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4773
add steps for deleting known issues in admin_steps.rb
add test for deleting known issues in admin_post_issues.feature
add a few lines just to cover "show" button as well
> AO3-4773 Extend tests for known_issues_controller

- spec/controllers/external_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4767
Make sure we're covering the external works controller's fetch action.
Refer to JIRA
> AO3-4767 Specs for the external works controller

- script/try_command.sh
https://otwarchive.atlassian.net/browse/AO3-4776
This pull resets the state of coverage data if a run in codeship needs to be retried.
> AO3-4776 Reset coverage on a failure

- app/controllers/admin_posts_controller.rb
- app/models/admin_post.rb
https://otwarchive.atlassian.net/browse/AO3-4758
> AO3-4758 – AdminPostsController Strong Params

- app/controllers/preferences_controller.rb
- app/models/preference.rb
https://otwarchive.atlassian.net/browse/AO3-4757
> AO3-4757 – Remove redundant fallback for new user preferences

- app/controllers/admin/banners_controller.rb
- app/models/admin_banner.rb
https://otwarchive.atlassian.net/browse/AO3-4755
> AO3-4755 – AdminBannersController Strong Params

- app/controllers/feedbacks_controller.rb
- app/models/feedback.rb
https://otwarchive.atlassian.net/browse/AO3-4759
> AO3-4759 – FeedbacksController Strong Params

- app/controllers/collections_controller.rb
- app/models/collection.rb
- features/collections/icon.feature
- features/step_definitions/icon_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4764
> AO3-4764 – CollectionsController Strong Params

- app/controllers/pseuds_controller.rb
- app/models/pseud.rb
https://otwarchive.atlassian.net/browse/AO3-4763
> AO3-4763 – PseudsController Strong Params

- app/controllers/challenge_assignments_controller.rb
- config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-4806
Clean up code in challenge_assignments_controller 
Given we can find no references to the use of this code, I would hope automated testing should be sufficient.
> AO3-4806 Remove unused methods

- app/controllers/subscriptions_controller.rb
- app/models/subscription.rb
https://otwarchive.atlassian.net/browse/AO3-4798
Adds strong parameters to subscriptions.
Refer to JIRA issue.
> AO3-4798 Strong params for subscription

- app/models/admin.rb
- app/models/admin_activity.rb
- app/models/fandom.rb
- app/models/media.rb
- app/models/people.rb
- app/models/related_work.rb
- app/models/unsorted_tag.rb
https://otwarchive.atlassian.net/browse/AO3-4791
The idea here is that both brakeman and ourselves do not think we are doing mass assignment in a number of controllers, It seem sensible to confirm this by turning on the use of strong parameters in the controllers. This way we will not get less surprises in the move to rails 4.
No manual testing
> AO3-4791  Add strong parameters to models where we don't think we are doing mass assignment 

- features/admins/admin_skins.feature
- features/other_b/skin.feature
- features/other_b/skin_public.feature
- features/other_b/skin_wizard.feature
- features/step_definitions/skin_steps.rb
- features/step_definitions/tag_steps.rb
- features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-4819
Extend tests for skins controller, plus do some minor refactoring and shuffling of the skin tests because daaaang, was that one long feature.
Should bring the skins_controller tests up to 93% and, as a bonus, the Work Skin model up to 100.
Refer to JIRA.
> AO3-4819 Tests for skins controller

- app/controllers/downloads_controller.rb
- app/models/admin_setting.rb
- app/views/admin/settings/index.html.erb
- app/views/works/_work_header_navigation.html.erb
- db/migrate/20151130183602_add_download_enabled_to_admin_settings.rb
Reverts otwcode/otwarchive#2192
> Revert "AO3-4357 Allow downloads to be disabled"

- app/controllers/tags_controller.rb
- factories/tags.rb
- features/other_b/subscriptions_fandoms.feature
- features/step_definitions/subscription_steps.rb
- spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4823
Increases coverage on tag controller.
> AO3-4823 expand tests on tag controller

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4766
Removes the references to windows gems.
No Manual testing required
> AO3-4766 Remove windows gems

- spec/controllers/collection_profile_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4837
Add test for collection_profile_controller
> AO3-4837 Add test for collection_profile_controller

- app/views/works/_meta.html.erb
https://otwarchive.atlassian.net/browse/AO3-4846
> AO3-4846 Update cache key for work meta so new series links will show

- factories/prompt_restriction.rb
- factories/tags.rb
- spec/controllers/owned_tag_sets_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4822
Tests for owned_tag_sets_controller
No functional changes
potatoesque, she/her
> AO3-4822 Adding rspec tests for owned_tag_sets_controller

- app/views/collections/_header.html.erb
- public/stylesheets/site/2.0/17-zone-home.css
https://otwarchive.atlassian.net/browse/AO3-4848
Fix a clear added in #2401 that led to excessive white space at the top of collection profiles.
> AO3-4848 Fix excessive whitespace on collection profile

- app/views/user_mailer/delete_work_notification.html.erb
- app/views/user_mailer/delete_work_notification.text.erb
- config/locales/en.yml
https://otwarchive.atlassian.net/browse/AO3-4305
Hopefully only the text version will have the quotes. 
Have a work deleted by a creator, look at the text version
> AO3-4305 proposed fix for "title"

- app/controllers/admin_sessions_controller.rb
- app/controllers/user_sessions_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4385
Use ssl for session operations.
This doesn't get run in development or in test. 
Check that you can log in as a user and as an admin.
Check that when you look at the source it has a https url.
> AO3-4385 Update session handling

- app/controllers/admin_sessions_controller.rb
- app/controllers/user_sessions_controller.rb
Reverts otwcode/otwarchive#2240
> Revert "AO3-4385 Update session handling"

- README.md
- app/models/admin.rb
https://otwarchive.atlassian.net/browse/AO3-4844
Have old passwords continue to work
Try and login with an old password
> AO3-4844 Validate old SHA512 admin passwords

- app/controllers/invite_requests_controller.rb
- app/models/invite_request.rb
https://otwarchive.atlassian.net/browse/AO3-4782
Implement strong parameters
`bundle exec cucumber -f progress -r features features/admins/admin_invitations.feature`
and follow the test instructions in the JIRA [Ticket](bundle exec cucumber -f progress -r features features/admins/admin_invitations.feature)
> AO3-4782 Add strong parameters to invite requests

- app/controllers/archive_faqs_controller.rb
- app/models/archive_faq.rb
https://otwarchive.atlassian.net/browse/AO3-4780
Implements strong parameters and ForbiddenAttributesProtection on ArchiveFAQ
2. Admin Posts > Archive FAQ > New FAQ Category
3. Fill out the form
4. Press "Post"
5. Follow "Edit"
6. Change information on form
7. Press "Post"
None
he/him
> AO3-4780 Implements strong params on AchiveFAQ

- factories/challenge_claims.rb
- factories/prompt.rb
- spec/controllers/challenge_claims_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4886
Improve coverage on ChallengeClaimsController
> AO3-4886 Improve coverage on ChallengeClaimsController

- app/controllers/tag_wranglings_controller.rb
- app/controllers/tags_controller.rb
- app/views/tag_wranglings/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4858
Fix http://test.archiveofourown.org/tag_wranglings?show=characters&sort_column=taggings_count&sort_direction=DESC
Which currently gives an error
> AO3-4858 We were using taggings_count in SQL queries which will not work

- spec/controllers/challenge_assignments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4887
Only tests two of the lines without coverage, so there's plenty more to do, but it's an improvement and it would be good to get confirmation that I'm on the right track. In parallel I'll keep working on the other lines without coverage.
> AO3-4887 Challenge Assignment controller test for no_challenge

- app/controllers/tag_wranglings_controller.rb
- app/controllers/tags_controller.rb
- app/views/tag_wranglings/index.html.erb
Reverts otwcode/otwarchive#2799
> Revert "AO3-4858 We were using taggings_count in SQL queries which will not work"

- spec/controllers/external_authors_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4916
Check invitation/external_author before/after complete_claim.
Other changes:
- Test claim instead of get_external_author_from_invitation, which is a before_filter having no view/response
- Test deleting imported works
- Test when the logged in user is the external author
Just automated tests.
When https://otwarchive.atlassian.net/browse/AO3-4879 (#2754) is completed, this controller will have 100% RSpec coverage.
> AO3-4916 Extend tests for external_authors_controller

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4443
https://github.com/pry/pry
Pry is a powerful alternative to the standard IRB shell for Ruby. It is written from scratch to provide a number of advanced features.
Should not effect production,staging or test
None required
> AO3-4443 update pry

- app/controllers/known_issues_controller.rb
- app/models/known_issue.rb
https://otwarchive.atlassian.net/browse/AO3-4781
Implements strong parameters and ForbiddenAttributesProtection for KnownIssue
2. Go to http://test.archiveofourown.org/known_issues/new to create a new one (I suspect the link to this page only shows up if you delete the existing known issue page, and I am not doing that to find out)
3. Fill out the form
4. Press "Post"
5. Follow "Edit"
6. Update the information in the form
7. Press "Post"
None
he/him
> AO3-4781 Implements strong params for KnownIssue

- app/controllers/user_sessions_controller.rb
- doc/app/UserSessionsController.html
- features/users/authenticate_users.feature
https://otwarchive.atlassian.net/browse/AO3-4617
the error message a user sees when they enter the wrong login information has been changed to include a link to the new password page
please make sure the old error message 
_The password or user name you entered doesn't match our records. Please try again or follow the 'Forgot password?' link below. If you still can't log in, please visit Problems When Logging In for help._ 
has been changed to
_The password or user name you entered doesn't match our records. Please try again or <a href="http://archiveofourown.org/passwords/new">reset your password</a>. If you still can't log in, please visit <a href="http://archiveofourown.org/admin_posts/1277">Problems When Logging In</a> for help._
> AO3-4617 Change login error message to include "reset password" link

- app/controllers/collection_participants_controller.rb
- app/models/collection_participant.rb
https://otwarchive.atlassian.net/browse/AO3-4812
Implements strong parameters and ForbiddenAttributesProtection for CollectionParticipant
1. Log in
2. Browse > Collections > New Collection
3. Fill in the required information on the form
4. Submit
5. Follow the "Membership" link near the top of the collection's page
6. Enter at least one valid user name in the unlabeled field near the top of the membership page
7. Submit
None
he/him
> AO3-4812 Implements strong params for CollectionParticipant

- app/controllers/admin/api_controller.rb
- app/models/api_key.rb
https://otwarchive.atlassian.net/browse/AO3-4774
Implements strong parameters and ForbiddenAttributesProtection on Admin::ApiKey
1. Log in as admin at http://test.ao3.org/admin/login
2. Manage API Tokens > New API Token
3. Fill out the form
4. Press "Create API Token"
5. Use the "Edit" button for the key you just generated to go to the edit page
6. Fill out the form
7. Press "Update API Token"
None
he/him
> AO3-4774 Admin Api strong params

- app/controllers/owned_tag_sets_controller.rb
- app/models/tagset_models/owned_tag_set.rb
https://otwarchive.atlassian.net/browse/AO3-4850
Implements strong parameters and ForbiddenAttributes on OwnedTagSet
1. Log in
2. Browse > Tags > Tag Sets > New Tag Set
3. Fill in required information, plus anything else you want
4. Submit
5. Edit
6. Change something
7. Update
No other references
he/him
> AO3-4850 Implements strong parameters to OwnedTagSet

- app/controllers/collection_items_controller.rb
- app/models/collection_item.rb
https://otwarchive.atlassian.net/browse/AO3-4892
Implements strong parameters and ForbiddenAttributesProtection for CollectionItem
1. Log in
2. Browse > Collections > New Collection
3. Enter a Collection name, Display title, and any other settings or information you want (e.g. make it moderated and unrevealed)
4. Submit
5. Now you'll want to fill your collection with items – that means post some works, invite some works, and add some bookmarks, preferably using a couple of different accounts (i.e. not just the collection owner's account)
6. Log back in as the collection owner
7. Browse > Collections > [Whatever you named your collection] > Manage Items
8. Where the collection items are will depend on your collection's settings (e.g. a moderated collection will have any works created by …
> AO3-4892 Collection Item strong params

- app/controllers/series_controller.rb
- app/models/series.rb
- spec/controllers/series_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4893
Implements strong parameters and ForbiddenAttributeProtection to Series
1. Log in
3. Fill in required information
4. Check "Add co-authors?"
5. Enter the name of a co-author
5. Select "This work is part of a series"
6. Fill in a name for your new series in "Or create and use a new one:"
7. Post Without Preview
8. Hi, username! > My Dashboard > Series
9. Choose "Edit" on the series you created (or another one – doesn't matter, as long as you have a series)
10. Change the Series Notes, Series Description, and/or completion status
11. Update
12. The series should update with a success message
13. Choose "Remove Me As Author"
14. Choose OK to confirm
15. The series should update with a success message (your name might still …
> AO3-4893 Series strong params

- app/controllers/challenge_claims_controller.rb
- app/models/challenge_claim.rb
- spec/controllers/challenge_claims_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4903
Implements strong parameters and ForbiddenAttributesProtection for ChallengeClaim
To test manually, you'll want to find or create a prompt meme challenge, and then find or create some prompts in that challenge. Then you'll want to follow the "Prompts (#)" link in the prompt meme's sidebar and use the "Claim" buttons to claim some prompts.
It would be a good idea to make sure you can also use the "Drop Claim" button to get rid of claims you don't want, and to use the "Fulfill" button to make sure your claim is marked fulfilled when you post a work for it.
None
he/him
> AO3-4903 Challenge Claims strong params

- app/controllers/tags_controller.rb
- app/models/tag.rb
- spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4907
This PR implements strong parameters and ForbiddenAttributesProtection for Tag
For the first item, you'll want to log in as a wrangler and check that you can do all the wrangling activities:
Change a tag's canonical status
Add/remove a Media for a Fandom tag
Add/remove a Fandom for a Character, Relationship, or Freeform tag
Add/remove Characters for a Relationship tag
Add/remove a Metatag
Add/remove a Subtag
Add/remove a Synonym
Fix taggings count
Change a tag's capitalization/diacritic marks
Change a tag's unwrangleable status
Assign a category to an unsorted tag (http://test.archiveofourown.org/unsorted_tags)
Change a Fandom tag's Name To Use For Alphabetical Sorting
You shouldn't need to check that the work indexes have been update when …
> AO3-4907 Tags strong params

- app/controllers/profile_controller.rb
- app/controllers/users_controller.rb
- app/models/profile.rb
https://otwarchive.atlassian.net/browse/AO3-4784
Implements strong parameters and ForbiddenAttributesProtection for Profile
This is a weird one – it's for the show action! Since we can't really reproduce the "existing user has a nil profile" situation, the best we can do is make sure you can access a user's profile, e.g. http://test.ao3.org/users/testy/profile
None
he/him
> AO3-4784 Profile strong params

- app/controllers/bookmarks_controller.rb
- app/models/bookmark.rb
https://otwarchive.atlassian.net/browse/AO3-4909
This PR implements strong parameters and ForbiddenAttributesProtection on Bookmark
Test creating and editing bookmarks for works, series, and external works – make sure all of your input is saved and there are no unexpected errors.
No external references
he/him
> AO3-4909 Bookmarks strong params

- app/controllers/admin/admin_invitations_controller.rb
- app/controllers/invitations_controller.rb
- app/models/invitation.rb
- app/views/admin/admin_invitations/find.html.erb
- app/views/admin/admin_invitations/index.html.erb
- app/views/invitations/index.html.erb
- features/admins/admin_invitations.feature
- features/other_a/invite_queue.feature
- features/other_a/invite_request.feature
* [ x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
https://otwarchive.atlassian.net/browse/AO3-4779
Implements strong parameters and Invitations.
1. Log in as testy
2. Hi, username! > My Dashboard > Invitations > Manage Invitations
3. Click on the token for an invitation that has a link in it's copy and use column to go to the invitation's page, e.g. http://test.archiveofourown.org/users/testy/invitations/355584
4. Edit the address in the "Enter an email address" field
5. Press "Update Invitation"
You should be able to change this without any unexpected error messages.
You should also do roughly the same thing as an admin:
2. Invitations > Invite New Users
3. Under "Track Invitations," enter …
> AO3-4779 Invitations strong params

- app/controllers/external_authors_controller.rb
- app/controllers/opendoors/external_authors_controller.rb
- app/models/external_author.rb
https://otwarchive.atlassian.net/browse/AO3-4859
This PR implements strong parameters and ForbiddenAttribute protection to OpenDoors::ExternalAuthor
1. Log in as a user with archivist privileges (e.g. testy)
2. Hi, username! > Open Doors
3. Under "Block Email Address," fill in "Email" with an email address
4. Press "Submit"
None
(he/him)
> AO3-4859 Implements strong parameters on OpenDoors::ExternalAuthor

- app/controllers/challenge_assignments_controller.rb
- app/models/challenge_assignment.rb
…ChallengeAssignment
https://otwarchive.atlassian.net/browse/AO3-4861
This PR applies strong parameters and ForbiddenAttributes protection to ChallengeAssignment. This implementation of strong parameters explicitly allows which parameters are allowable for use on this controller. The current implementation uses an approach from an old Railscast (198) which was created prior to the advent of strong parameters. Because the root level param `challenge_assignments` acts like a nested_attribute, we can protect it (and its nested params) by using the array syntax. This does not, however, give us the `require` protection of ensuring `challenge_assignments` exists without a refactor of the current implementation.
1. Log in
2. Browse > Collections > New Collection
3. Fill in required fields and …
> AO3 4861 challenge assignment strong params

- app/controllers/challenge_signups_controller.rb
- app/controllers/prompts_controller.rb
- app/models/challenge_signup.rb
- app/models/prompt.rb
This PR addresses both tickets [AO3-4904](https://otwarchive.atlassian.net/browse/AO3-4904) and [AO3-4902](https://otwarchive.atlassian.net/browse/AO3-4902), because the ChallengeSignupsController passes Prompt params through its create method.
Of note, the reason various `*_tagname` params show up twice is because lists of tagnames can show up in the parameters in different formats. When there are 0 or 1 tagnames, they show up as a string (allowed by `:tagnames`), and when there is more than one they show up as an array (allowed by `tagnames: []`), so both must be allowed by the controller to allow for full functionality.
https://otwarchive.atlassian.net/browse/AO3-4904 and https://otwarchive.atlassian.net/browse/AO3-4902
Adds strong_params to …
> AO3-4902 AO3-4904 ChallengeSignups and Prompts strong params

- spec/controllers/collection_items_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4878
Adding test coverage for the collection items controller.
> AO3-4878 adding collection item test

- app/controllers/chapters_controller.rb
- app/models/chapter.rb
- app/models/story_parser.rb
https://otwarchive.atlassian.net/browse/AO3-4911
This PR adds strong params to the Chapter model and ChaptersController, which protects the Chapter model there.
The StoryParser model is handed params from the API::V1::WorksController, which are white-listed with an options method, although strong-params aren't being used. While StoryParser uses mass assignment to create a new Chapter, it does so with this white-listed options method.
Test importing multiple URLs as chapters of a single work, paying particular attention to whether the chapter title, summary, and notes import correctly.
Are there any other relevant issues / …
> AO3-4911 story parser strong params

- spec/controllers/challenge_assignments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4921
Increases coverage a little, though there's still some way to go.
> AO3-4921 Expand challenge assignment spec test

- app/views/home/_dmca.html.erb
https://otwarchive.atlassian.net/browse/AO3-4938
The OTW moved causing the DMCA Agent address to change, this causes that to be reflected on the Archive's DMCA page (though arguably it should be in a config file to the extent that otwarchive is a code base for multiple uses).
Visit /dmca and verify that under "How to initiate a formal DMCA takedown request..." the OTW's address appears
`228 Park Ave S #18156`
`New York, New York 10003-1502`
Also verify that this is indeed the correct address as shown in JIRA, and by another source.
Dense Lancer
He/him
> AO3-4938 Update DMCA agent address

- app/mailers/user_mailer.rb
- app/views/user_mailer/invitation.html.erb
- app/views/user_mailer/invitation.text.erb
- config/locales/en-GB.yml
- config/locales/en.yml
- features/other_a/invite_queue.feature
- spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4884
i18n of the invitation mail
Test by checking you can still invite people and the mail they get looks okay in English.
See also #2286
> AO3-4884 i18n invite

- spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4685
More tests.
No pain, only tests. Check that coverage for the controller is now at 100%.
> AO3-4685 Extend tests for invite_requests_controller

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4957
Make it so that leaving a comment like
Hello<
world 
Does not cause the unicorn to die, giving the user a 50x error
Leave a comment like:
Hello<
world 
And ensure that it appears
> AO3-4957 Downgrade nokogumbo

- features/comments_and_kudos/add_comment.feature
https://otwarchive.atlassian.net/browse/AO3-4957
Attempts to add tests we were unable to add in #2866
> AO3-4957 Test for angle brackets at end of line

- app/controllers/archive_faqs_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4548
> AO3-4548 Fix bot for faq reordering

- app/views/user_mailer/invitation.html.erb
https://otwarchive.atlassian.net/browse/AO3-4884
This should sort the exposed HTML.
Test run is still in progress, so it may be worth waiting for that to finish before merging.
> AO3-4884 fixing exposed HTML

- .travis.yml
- config/database.travis.yml
- script/travis_configure.sh
https://otwarchive.atlassian.net/browse/AO3-4982
Moves our tests to a supported os on travis
> AO3-4982 Move travis to later os

- app/models/tag.rb
- spec/support/login_macros.rb
https://otwarchive.atlassian.net/browse/AO3-4978
Remove a duplicated method in rspec  and one method which appeared twice in the tags but was never used.
I don't believe this requires any testing...
> AO3-4978 Remove duplicated code

- features/collections/collection_create.feature
- features/other_a/invite_queue.feature
- features/prompt_memes_b/challenge_promptmeme_posting_fills.feature
- features/step_definitions/collection_steps.rb
- features/step_definitions/tag_set_steps.rb
- features/step_definitions/work_related_steps.rb
- features/step_definitions/work_steps.rb
- features/support/paths.rb
- features/tag_sets/tag_set.feature
- features/tag_sets/tag_set_nominations.feature
- features/works/chapter_edit.feature
- features/works/work_create.feature
- features/works/work_related.feature
https://otwarchive.atlassian.net/browse/AO3-4990
Adds Cucumber test coverage for various scenarios we weren't covering, per a quick glance at some models in Coveralls. See the issue or the code for a complete list.
Check the line coverage on Coveralls. See issue for lines.
> AO3-4990 Cucumber tests for miscellaneous uncovered scenarios 

- spec/controllers/works/miscellaneous_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5003
fix broken rspec
No manual tests required
> AO3-5003 fix broken rspec

- spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5004
More tests for the abuse report model. Test cases from https://otwarchive.atlassian.net/browse/AO3-4257.
Automated.
> AO3-5004 Add tests for work URL detection in abuse reports

- spec/controllers/serial_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4714
> AO3-4714 Expand serial works controller test

- app/views/downloads/_download_preface.html.erb
https://otwarchive.atlassian.net/browse/AO3-4943
Fix downloads for works in series.
> AO3-4943 fix series issue with downloads

- app/models/challenge_signup.rb
- app/models/skin.rb
- lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-4736
Skins are broken on test.
Try and change your skin and see if it works....
We might have broken skin paths in memcached. If so it still will not work and we will need to do a memcached flush. But on beta we shouldn't need to do that as it will have never got the broken paths in there.
> AO3-4736 Broken skins.

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5027
This is needed as we have added a "new" server"
None required
> AO3-5027 Add ao3-app12 to the deploy script

- spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5005
> AO3-5005 clarifying duplicate test in user_mailer

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/models/filter_tagging.rb
- app/models/work.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/initializers/secret_token.rb
- config/secrets.yml
https://otwarchive.atlassian.net/browse/AO3-5038
Clean up warnings
Should only make changes to test and dev
> AO3-5038 Reduce rails 4.2 warnings

- factories/collections.rb
- spec/controllers/collection_items_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4947
> AO3-4947 Expanding collection item test

- spec/controllers/challenge_assignments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4946
Expands the test coverage
> AO3-4946 Expand challenge assignment test

- app/models/chapter.rb
https://otwarchive.atlassian.net/browse/AO3-5033
Fixes issue on staging with posting new works. The fix_positions method is trying to update all chapters with a null work_id, which is both wrong and timing out.
Post a new work on staging. Also check chapter position updates as part of the larger regression test.
> AO3-5033: Fix posting issue with new works

- app/helpers/application_helper.rb
- config/initializers/gem-plugin_config/will_paginate_config.rb
https://otwarchive.atlassian.net/browse/AO3-5107
Makes it so we continue to use our custom HTML for pagination.
Refer to JIRA
https://github.com/mislav/will_paginate/wiki/Link-renderer
> AO3-5107 Rails BOT: Restore custom link redering for pagination

- app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5112
Fixes ability to log in as admin by updating our protect_from_forgery code
Should now be able to log in as an admin
> AO3-5112: Rails BOT Fix admin login issue

- .codeclimate.yml
https://otwarchive.atlassian.net/browse/AO3-5124
Adds a config file for codeclimate
Not testable
> AO3-5124: Add codeclimate config file

- app/controllers/user_sessions_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5129
Cleans up the fix for AO3-5129, since I figured out what the cause was and how to simplify the code
See issue
> AO3-5129: Remember me tweak

- app/controllers/home_controller.rb
- config/routes.rb
- public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-5153
Dynamically updates form authenticity tokens for logged out users, to get around page caching bugs.
You should be able to log in on staging.
> AO3-5153: New approach to fixing auth tokens dynamically

- config/environments/production.rb
- config/environments/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5157
Makes staging and production logs less chatty
N/A
> AO3-5157: Update log levels after Rails default change

- app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5158
Put the forced logout back
I think we need this although I am not sure.
> AO3-5158 Forced logout ??

- db/migrate/20170918172719_add_more_index_to_tag_nominations.rb
https://otwarchive.atlassian.net/browse/AO3-5175
Add indexes for tag nomination
None required.
> AO3-5175 Add indexes for tag nomination

- app/views/chapters/_hidden_fields.html.erb
- features/works/chapter_edit.feature
https://otwarchive.atlassian.net/browse/AO3-3300
Fixes total chapters being set to "?" when adding a new chapter using the "Post" button on the preview screen.
Testing notes in ticket.
Zorac, he/him
> AO3-3300 Fix chapter preview wiping total chapters

- app/models/abuse_report.rb
- config/config.yml
- lib/tasks/after_tasks.rake
- spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4729
Accept 5 abuse reports per profile per month, taking into account variations in the profile URL.
> AO3-4729 Accept 5 abuse reports per profile per month

- app/models/tagset_models/tag_set.rb
https://otwarchive.atlassian.net/browse/AO3-5178
Fixes slow tag set callback that causes timeouts for large tag sets
Behavior should remain unchanged and pages should load faster.
> AO3-5178: Fix slow tag set callback

- lib/autocomplete_source.rb
- lib/tasks/load_autocomplete_data.rake
https://otwarchive.atlassian.net/browse/AO3-4952
Hopefully fix the issues building the autocomplete database.
Look and see if the data is appearing.
> AO3-4952 REDIS AUTOCOMPLETE missing lib files

- app/controllers/chapters_controller.rb
- spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5065
Reverts otwcode/otwarchive#2961
> Revert "AO3-5065 Fix error where posting chapter would not post work"

- LICENSE
https://otwarchive.atlassian.net/browse/AO3-5055
Adds the GNU GPL version 2 license to the repository, per GitHub's guidelines
Make sure a file named license is present in the repo
> AO3-5055 Add GNU GPL version 2 license

- app/controllers/abuse_reports_controller.rb
- app/views/abuse_reports/new.html.erb
https://otwarchive.atlassian.net/browse/AO3-5093
Just a little code cleanup in the abuse reports aisle
No behavior should change. Abuse reports in other languages should still submit and save properly.
(if you do not fill this in, we will use your GitHub account name and will use "they" to avoid making assumptions about your gender)
> AO3-5093 Refactor some abuse report code

- app/models/indexing/index_subqueue.rb
https://otwarchive.atlassian.net/browse/AO3-5165
Removes failed indexing queues from Redis
Not really testable
> AO3-5165 Remove failed queues from Redis

- config/redis.codeship.example
- config/redis.example
https://otwarchive.atlassian.net/browse/AO3-5187
Updates our example Redis config files to include the new Redis instance
> AO3-5187 Add autocomplete Redis instance to Redis config examples

- features/importing/work_import_dw.feature
https://otwarchive.atlassian.net/browse/AO3-5184
Fixes the broken Dreamwidth community import test
Automated test fix.
> AO3-5184 Fix image url in DW community import test

- .codecov.yml
- .coveralls.yml
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- features/support/env.rb
- spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5195
Use Codecov for coverage. **Before this gets merged**, I need help from AD&T staff to:
- Log in https://codecov.io/ with the GitHub otwcode account and enable the otwarchive repository
- Remove the coveralls Rake task from the Codeship build
See issue.
> AO3-5195 Use Codecov for coverage

- public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-5216
This was the fix for [AO3-5153](https://otwarchive.atlassian.net/browse/AO3-5153) (#3039), which got lost in a merge.
Logging in on staging should work again.
> AO3-5216 Fix setting authenticity tokens when cached pages load

- app/models/search/bookmark_query.rb
- app/models/search/query.rb
- app/models/search/work_query.rb
- spec/models/query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5231
Fixes weird text in search header on advanced search pages. Also reduces duplication and makes tag search more predictable.
See issue.
> AO3 5231: Fix search headers

- spec/controllers/gift_exchange_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4855
Improves coverage for the gifts exchange controller
Run tests.
Tal Hayon
Please use he.
> AO3-4855 Add rspec tests for the gifts exchange controller

- app/controllers/pseuds_controller.rb
- app/views/home/site_map.html.erb
https://otwarchive.atlassian.net/browse/AO3-5151
Changes remaining instances of people_path to search_people_path
Refer to https://otwarchive.atlassian.net/browse/AO3-5151?focusedCommentId=353299&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-353299
> AO3-5151 Convert remaining people_path to search_people_path

- app/decorators/pseud_decorator.rb
- spec/models/pseud_decorator_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5276
If you search people by fandom(s), the results should now display as "50 works, 33 bookmarks | 14 works in Thor (Movies), 1 work in Twilight (Movies)"
Refer to JIRA
> AO3-5276 Add total number of works to results when searching for fandom

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5321
Updates the version of the paperclip gem
Check that you can create a new avatar and replace and delete an old one
> AO3-5321  Update paperclip

- public/help/tagset-about.html
- public/help/work-import.html
https://otwarchive.atlassian.net/browse/AO3-5237
Change a verb and an FAQ link's text in the work import help, and correct a paragraph in the tag set help.
> AO3-5237 Update work import and tag set help

- app/helpers/bookmarks_helper.rb
- app/views/bookmarks/_bookmark_blurb.html.erb
- app/views/bookmarks/_bookmarkable_blurb.html.erb
https://otwarchive.atlassian.net/browse/AO3-5365
* Adds some classes so we can fix Low Vision Default
* Removes a TODO we won't do
* Moves the logic for displaying the count to a helper so it isn't repeated in the bookmarkable and bookmark blurbs
Refer to JIRA
Rest of fixes for Low Vision Default will be in the JIRA issue
> AO3-5365 Update bookmarkable blurb

- public/robots.public.txt
https://otwarchive.atlassian.net/browse/AO3-5381
Hopefully allows archive.org to work with us once more.
> AO3-5381 Remove confusing robots.txt comments

- features/other_a/pseuds.feature
- features/prompt_memes_c/challenge_promptmeme_claims.feature
- features/step_definitions/web_steps.rb
- features/tags_and_wrangling/tag_wrangling_characters.feature
- features/tags_and_wrangling/tag_wrangling_fandoms.feature
- features/tags_and_wrangling/tag_wrangling_freeforms.feature
- features/tags_and_wrangling/tag_wrangling_relationships.feature
- features/users/user_rename.feature
- features/works/chapter_edit.feature
https://otwarchive.atlassian.net/browse/AO3-5380
Add assertions to checked checkbox steps.
> AO3-5380 Fix tests checking if checkboxes are checked

- app/models/user.rb
- spec/models/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3468
Works and series are indexed with the author's byline, which has the old username.
See issue.
> AO3-3468 Reindex user's works and series after username change

- app/models/chapter.rb
- app/models/serial_work.rb
- app/models/work.rb
- features/other_b/bookmark_indexing.feature
- features/step_definitions/bookmark_steps.rb
- features/step_definitions/work_steps.rb
https://otwarchive.atlassian.net/browse/AO3-3726
Updates the Date Updated for series bookmarks when a work in the series has chapters added or removed.
Refer to Jira
> AO3-3726 Update series date indexing when adding and removing chapters

- .travis.yml
- script/check_syntax
- script/travis_set_read_islolation.sh
https://otwarchive.atlassian.net/browse/AO3-5413 (please fill in issue number and remove this comment)
Change travis testing to use READ-COMITTED
Test only.
> AO3-5413 Make travis use READ-COMITTED

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5414
Updates the state of the servers
> AO3-5414 Update deploy script with changes to infrastructure

- app/controllers/users_controller.rb
- app/views/layouts/_tos_prompt.html.erb
- lib/skin_wizard.rb
- public/stylesheets/site/2.0/16-zone-system.css
https://otwarchive.atlassian.net/browse/AO3-5416
* Changes quotes in JavaScript
* Explicitly sets no_content as the response to ending the prompt while logged in
* Updates the skin wizard so the background, heading, and main text color on the TOS prompt will use the colors from your wizard skin
* Change color of disabled button 
* Make sure the text wraps if the button is too wide for the screen when logged in
> AO3-5416 Misc fixes for TOS prompt

- features/other_b/bookmark_indexing.feature
https://otwarchive.atlassian.net/browse/AO3-5374
We have a test failure that happened because we changed the capitalization on the search form button. This fixes it. 
Make sure Travis passes
> AO3-5374 Fix test broken by bookmark form changes

- lib/tasks/search.rake
https://otwarchive.atlassian.net/browse/AO3-5429
Add some task to catch up on broken indexes
Needs to be have a shell account
> AO3-5429 Add tasks for reindexing in new world

- Gemfile
- Gemfile.lock
- script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-5384 
https://otwarchive.atlassian.net/browse/AO3-5366
https://otwarchive.atlassian.net/browse/AO3-5385
Update gems
> AO3-5366 AO3-5384 AO3-5385 Update gems loofah, sanitize, rails-html-sanitizer

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5439
Update the sinatra gem
See JIRA
> AO3-5439 Update sinatra to 2.0.3

- app/controllers/bookmarks_controller.rb
- app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5449
This should remove the 500's that people are seeing on search pages.
> AO3-5449 Cache ES6 work/bookmark search results separately from old search results

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5451
Update sprockets.
```sh
bundle update sprockets --conservative
```
See issue.
> AO3-5451 Update sprockets to 3.7.2

- app/views/works/_filters.html.erb
- app/views/works/_search_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5468
What it says on the tin, and fix some quotation marks
Go to the pages and check the text
> AO3-5468 Change Status to Completion Status on work filter and search

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5466
Upgrade nokogiri to 1.8.3. Similar change for 1.8.2: #3242.
> AO3-5466 Upgrade nokogiri to 1.8.3

- public/help/work-search-text-help.html
https://otwarchive.atlassian.net/browse/AO3-5483
Updates help text to explain thrilling new unintuitive Elasticsearch behavior.
Look at the help text with your special eyes.
> AO3-5483 Explain new behavior of spaces in search help text

- db/migrate/20180731034724_index_comments_on_ip_address.rb
https://otwarchive.atlassian.net/browse/AO3-5495
Indexes comments on IP addresses, so the next time I have to look something up, I do not spend 15 seconds going, "God, could this be any slower?"
Run the migration on staging.
> AO3-5495 Index comments on IP address

- app/controllers/gifts_controller.rb
- spec/controllers/gifts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5445
Fixes "Refuse Gift" 500 error when you aren't logged as the recipient
Follow Bug description. Also enabled pending spec tests.
Tal.
Please use he.
> AO3-5445 Fix Refuse Gift 500 error

- app/models/chapter.rb
- app/models/redis_mail_queue.rb
- app/views/user_mailer/batch_subscription_notification.html.erb
- app/views/user_mailer/batch_subscription_notification.text.erb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
https://otwarchive.atlassian.net/browse/AO3-5503
Adds some caching to subscription email rendering.
The emails should still have correct information, and the html and text versions should still have correct formatting.
> AO3-5503: Add caching to subscription emails

- config/deploy/production.rb
- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5524
Move the hosts around.
No testing required.
(if you do not fill this in, we will use your GitHub account name and will use "they" to avoid making assumptions about your gender)
> New hosts to deploy

- app/views/admin/admin_users/show.html.erb
- features/other_a/invite_request.feature
- features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-4366
Added buttons as issue requested. 
Press the buttons. Also added feature tests.
Tal Hayon
Please use he.
> AO3-4366 Add manage and user invitations buttons to admin user page

- public/403.html
https://otwarchive.atlassian.net/browse/AO3-5330
Update the link to the contact us form on the blocked IP page.
Go to page. Click link. Observe.
> AO3-5330 Link to contact form with AO3 Support selected

- spec/miscellaneous/helpers/admin_post_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5548
Move a test file to somewhere it would actually run.
> AO3-5548 Move admin_post_helper_spec to the correct folder

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
None.
- Use https where possible
- Rename "Testing" to "Testing Instructions" to be clear
- Ask contributors to use the same name on JIRA
[skip ci]
Please proofread.
> Update contributing documentation

- features/importing/work_import_da.feature
https://otwarchive.atlassian.net/browse/AO3-5555
Fix a test failure in the importing tests
> AO3-5555 Look for new URL in DeviantArt test

- Gemfile
- Gemfile.lock
- script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-5543
https://otwarchive.atlassian.net/browse/AO3-5553
Update nokogiri to 1.8.5, loofah to 2.2.3.
See issues.
> AO3-5543 AO3-5553 Update gems nokogiri and loofah

- spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5560
Rearranged some comment tests.
None.
> AO3-5560 Use shared examples for hidden commentable tests

- app/controllers/users/sessions_controller.rb
- app/views/users/registrations/_passwd.html.erb
- features/users/authenticate_users.feature
- public/stylesheets/site/2.0/22-system-messages.css
Fixes several minor issues with the Devise PR:
* color of text in an error message
* wrong notice text when logging in
* JavaScript validation not working on account creation page
> AO3-2839 Devise front end fixes

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5588
We need to add a server back in to the fold.
None
> AO3-5588 ao3-app04 returning to the fold

- config/config.yml
- features/users/authenticate_users.feature
- lib/html_cleaner.rb
https://otwarchive.atlassian.net/browse/AO3-5589
Fixes logging in with certain passwords.
> AO3-5589 Fix certain passwords

- app/models/user.rb
[skip ci]
https://otwarchive.atlassian.net/browse/AO3-5590
> AO3-5590 Fix comment on login lookup

- app/controllers/works_controller.rb
- app/models/work.rb
- features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-1305
Fixes word count in work preview. Count was not updated using posted data.
Added some steps to work edit feature. Bug description contains steps.
Tal.
Please use he.
> AO3-1305 Fix word count in work preview

- app/models/download_writer.rb
- public/stylesheets/ebooks.css
- script/codeship_ebook_converters.sh
- script/travis_ebook_converters.sh
* Fix the font size on PDFs by preventing shrinking
* Stop logging to allow large PDFs to be generated
* Adjust margins on EPUB and MOBI chapter content
Look with your special eyes.
> AO3-3880 Work download tweaks

- app/controllers/downloads_controller.rb
- app/controllers/errors_controller.rb
- app/models/download.rb
- app/models/download_writer.rb
- config/config.yml
- config/initializers/mime_types.rb
- features/step_definitions/work_download_steps.rb
- features/works/work_download.feature
https://otwarchive.atlassian.net/browse/AO3-5614
Adds AZW3 downloads.
Download the files and make sure they work on devices and in apps that support AZW3. Check some works in RTL languages like Hebrew.
> AO3-5614 Add AZW3 downloads

- script/codeship_ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-5630
Codeship recently [upgraded the OS to Ubuntu Bionic](https://changelog.codeship.com/codeship-basic-builds-run-on-ubuntu-bionic-90622).
Codeship should pass.
> AO3-5630 Update wkhtmltopdf Codeship install

- features/gift_exchanges/challenge_giftexchange.feature
- features/importing/work_import_da.feature
https://otwarchive.atlassian.net/browse/AO3-5638
https://otwarchive.atlassian.net/browse/AO3-5289
Fix the DA import test... not for the last time.
Also freeze time in a gift exchange test to avoid time zone check (from #3209) failures during DST transitions.
None.
> AO3-5638 Fix image URL in DeviantArt import test

- app/views/works/_standard_form.html.erb
Corrected the grammar in the new post new work in app/views/works/_standard_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5592
> AO3-5592 Correct Grammar Mistake in the post new work 

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5641
Ensure we have god and unicorn at modern versions and documented in this repository. The systems ansible should now use this repository for systems gems.
Does the archive deploy, no obvious tests
> AO3-5641 Add system gems god and unicorn

- app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5457
Removed the unused function tag_list from works_controller
None needed.
Tal.
Please use he.
> AO3-5457 Remove tag_list from works_controller

- app/controllers/api/v2/works_controller.rb
- spec/controllers/api/api_helper.rb
- spec/controllers/api/v2/api_works_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5650
Sets the imported work's language through the API.
See Jira
> AO3-5650 Set work language from API

- spec/controllers/wrangling_guidelines_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4681
Redirect checks become stricter after #3429.
Travis build should pass.
> AO3-4681 Fix spec for notice on deleting wrangling guidelines

- config/config.yml
- spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-2808
css can now use jpeg pictures.
Follow steps in bug description.
Tal.
Please use he.
> AO3-2808 Add jpeg to SUPPORTED_EXTERNAL_URLS

- lib/tasks/opendoors.rake
- spec/lib/tasks/opendoors.rake_spec.rb
- spec/miscellaneous/lib/tasks/opendoors.rake_spec.rb
- spec/spec_helper.rb
- spec/support/fixtures/opendoors_import_url_mapping.csv
https://otwarchive.atlassian.net/browse/AO3-5245
Fix a bug that caused the rake task to be unable to update the URL on imported works.
See ticket.
> AO3-5245 Update Open Doors rake task to use AO3 ids to find works

- config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-5664
Remove the routes I forgot to remove in the first PR
> AO3-5664 Remove API v1 routes

- Gemfile
- Gemfile.lock
- config/brakeman.ignore
https://otwarchive.atlassian.net/browse/AO3-5687
Ignore all current brakeman errors while we fix them, Having this will ensure we do not add more issues to our codebase.
Look in https://hakiri.io/ and note this allows 2 other warnings and 1 sql injection as not ignored. I have code which should be merged soon which actually refactors this code.
> AO3-5687 Install Brakeman Gem and ignore all current warnings

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5695
Update new relic gem
Login in to staging new relic instance.
> AO3-5695 Update newrelic_rpm, drop unused newrelic-redis gem

- app/controllers/api/v2/works_controller.rb
- spec/controllers/api/v2/api_bookmarks_spec.rb
- spec/controllers/api/v2/api_works_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5699
Fix a blocking bug in the mass import API
See Jira
> AO3-5699 Pass works instead of whole response to claim notification method

- features/importing/work_import_da.feature
None.
These tests are failing intermittently until [AO3-5716](https://otwarchive.atlassian.net/browse/AO3-5716) is fixed, so we'll ignore them for now.
Travis should pass.
> Skip DeviantArt importing tests

- app/models/collection_item.rb
https://otwarchive.atlassian.net/browse/AO3-5720
See the link on JIRA.
See the link on JIRA.
> AO3-5720 Modify the rules of CollectionItem#approve_automatically.

- app/helpers/series_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5334
Correct text in JavaScript confirmation prompt
> AO3-5334 Update confirmation prompt when removing self from series

- app/views/works/_standard_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5730
Sets focus on chapter title and number input fields when the user clicks on the fields' labels in the new work form.
Steps for testing are already described in JIRA ticket.
lethnie, she/her
> AO3-5730 Fix labels for chapter title and number in new work form

- app/views/home/_intro_module.html.erb
https://otwarchive.atlassian.net/browse/AO3-5673 
Adds delimiter (,) to numbers, grouped by thousands.
Display only, no functionality change. Standard library method number_with_delimiter.
dlhardin, she/her
> AO3-5673 fandoms | users | works numbers on homepage are hard to parse

- app/views/users/delete_preview.html.erb
https://otwarchive.atlassian.net/browse/AO3-5688 
Add link to orphaning FAQ in account deletion preview.
No new features.
dlhardin, she/her
> AO3-5688 link to orphaning faq in account deletion preview

- app/views/challenge_assignments/_assignment_blurb.html.erb
- features/gift_exchanges/challenge_giftexchange.feature
- features/step_definitions/challege_gift_exchange_steps.rb
Previously, we were assuming that the `@collection` variable being set meant the user currently looking at the page was a maintainer.
This assumption turned out to be erroneous, because `@collection` is also set when a non-maintainer user has multiple assignments in the same challenge.
The reason this happens for users with multiple assignments is that the challenge sidebar sends the user to a different path when that's the case:
```
<% elsif @challenge_assignments.size > 1 %>
<li><%= span_if_current ts("My Assignments"), user_assignments_path(current_user, :collection_id => @collection.name) %>
<% end %>
```
This goes to the `index` action of the `challenge_assignments_controller`, where this happens:
```
def index
if params[:user_id] && (@user = User.find_by(login: params[:user_id]))
if …
```
> AO3-5733 Check the current user is a maintainer before showing privileged info

- public/stylesheets/README.md
- public/stylesheets/README.txt
- public/stylesheets/masters/low_vision_default/README.md
- public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
- public/stylesheets/masters/reversi/README.md
- public/stylesheets/masters/reversi/reversi_site_screen_.css
- public/stylesheets/masters/snow/README.md
- public/stylesheets/masters/snow/snow_site_screen_.css
- public/stylesheets/masters/snow_blue/README.md
- public/stylesheets/masters/snow_blue/snow_blue_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-5787
* Copies the CSS for the public site skins we intend to continue supporting to the repository so we can better track and submit changes, although the changes will still need to be manually copied to production. 
* Updates README file to explain that and to use markdown instead of plain txt.
* Adds README files for the skins that need a bit more explanation; README files assume you have some knowledge of the skin form.
> AO3-5787 Add supported public site skins to repository for tracking purposes

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5795
Update the mysql gem to one we believe will support Debian 10
Just a smoke test I think....
> AO3-5795 Update mysql2 gem for Debian 10 support

- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5797
Runs staging on some new vm's running debian 10
A general smoke test.
> AO3-5797 Update server names in deploy script for staging

- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5800
Update the name of the staging front end.
Not applicable
> AO3-5800 New frontend server for staging

- config/config.yml
Adds a comment so we know what BLACKLISTED_MULTIMEDIA_SRCS is for and how it should be formatted, since we stumbled over that.
Nothing to test.
> AO3-5693 Add comment about media blacklist format

- app/models/search/bookmarkable_query.rb
- app/models/search/work_query.rb
- spec/models/search/bookmark_query_spec.rb
- spec/models/search/bookmark_search_form_spec.rb
- spec/models/search/work_query_spec.rb
- spec/models/search/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5790
When we changed the language search to use the language code instead of the numeric ID,
we didn't set the mapping for that field to `keyword`.
This has worked ok for languages with simple codes having the same capitalisation throughout, but has broken down for languages with mixed capitalisation in their codes, such as português brasileiro (`ptBR`) and português europeu (`ptPT`).
The most elegant solution would be to set the mapping and reindex, but we don't want to do another reindex so soon after we just did a big one, so what we are doing is change the filter.
Are there …
> AO3-5790 Fix work and bookmark searches for certain languages

- lib/work_stats.rb
- spec/controllers/chapters_controller_spec.rb
- spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5639
Previously, visiting a work that was part of an unrevealed collection was increasing the hit count, even though all a regular (non-admin) visitor could access was a message about the work being unrevealed, and not the work itself. This was upsetting or spooking out the creators, because "unrevealed" suggests no one can access the work other than its creator(s).
This PR adds a check that the work is not part of an unrevealed collection.
Previously, visiting a work that was hidden by an admin (which all admins can do) was increasing the hit count. This was upsetting to the creators, because "hidden" suggests no one can access the work other than its creator(s).
This PR adds a check that the work is not hidden by admin. …
> AO3-5639 Don't count hits on unrevealed and hidden works

- public/444.html
https://otwarchive.atlassian.net/browse/AO3-5832
Adds an Error 444 page we can give to users whose connection we drop to help with Elasticsearch load. [Error 444](https://httpstatuses.com/444) is an unofficial nginx error code.
Go to https://test.archiveofourown.org/444.html and see how it looks.
> AO3-5832 Add Error 444 page for Elasticsearch

- config/deploy/production.rb
- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5836
Change which servers we deploy to.
This will have to be deployed by hand as it goes to master and deploy and I will test the deploy to test by hand.
> AO3-5836 change deployment servers

- app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5832
Update a code comment following #3705.
None.
> AO3-5832 Update comment on status code for Elasticsearch errors

- Gemfile
- Gemfile.lock
- config/application.rb
- config/config.yml
- config/routes.rb
- config/secrets.yml
https://otwarchive.atlassian.net/browse/AO3-5759
Adds the [Lockup gem](https://lockupgem.com) for staging and allows us to set a password and password hint in config.yml. 
Refer to Jira.
> AO3-5759 Add Lockup to password protect staging

- config/initializers/rack_attack.rb
https://otwarchive.atlassian.net/browse/AO3-5841 
Whitelist the internal networks.
( We are hitting this right now )
> AO3-5841 Add internal network to Rack::Attack safe list

- Gemfile
- Gemfile.lock
- config/application.rb
- config/config.yml
- config/routes.rb
- config/secrets.yml
Reverts otwcode/otwarchive#3717
> AO3-5759  adding Lockup to remove password protection on staging

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5847
Updates the production deploy script because the servers have moved around.
None.
> AO3-5847 Update servers in production deploy script

- config/initializers/rack_attack.rb
https://otwarchive.atlassian.net/browse/AO3-5848
Shouldn't do anything, since [safelists are supposed to be applied first](https://github.com/kickstarter/rack-attack#how-it-works); but we'll definitely rule out ordering as a possible problem.
Not sure can be tested in staging.
> AO3-5848 Move Rack::Attack.safelist block to the top

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5849 
Make it less likely that new servers will be a pain when they are added in future.
This can't be tested.
> AO3-5849 Remove domains from server names in production deploy config

- lib/otw_sanitize/embed_sanitizer.rb
- spec/miscellaneous/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5853
replace later
replace later
sarken/her
> AO3-5853 placeholder

- lib/otw_sanitize/embed_sanitizer.rb
https://otwarchive.atlassian.net/browse/AO3-5853
replace later
replace later
Ariana/her
> AO3-5853 Rescue the 500 on strange schemes

- public/stylesheets/masters/reversi/reversi_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-4241
makes the search text readable when you focus on the header search box
set your site skin to reversi, click/tap on the header search box and type something, then check that the text is white
> AO3-4241 Reversi: Make text in focused header search box more readable

- app/controllers/kudos_controller.rb
- app/models/kudo.rb
- app/models/user.rb
- factories/users.rb
- spec/controllers/kudos_controller_spec.rb
- spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5850
Begin saving to the new user ID column on the kudos table.
See issue.
> AO3-5850 Update user IDs when logged in kudos are changed

- app/views/admin/admin_users/bulk_search.html.erb
https://otwarchive.atlassian.net/browse/AO3-5233
Fixes copy-pasted terminology
> AO3-5233 Remove URL terminology in bulk admin search

- script/get_user_data.rb
https://otwarchive.atlassian.net/browse/AO3-5676
Makes the get_user_data script spit all the information out in the Rails console to be copied and pasted.
Refer to Jira.
> AO3-5676 Make user data script print in console instead of to file

- lib/tasks/after_tasks.rake
- spec/controllers/invite_requests_controller_spec.rb
- spec/miscellaneous/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5851
What it says on the tin. 
Tests should pass, and a database admin should run this and make sure the output looks good and the kudos are indeed updated.
> AO3-5851 Add rake task to fill in user_id for existing kudos

- config/deploy/staging.rb
https://otwarchive.atlassian.net/browse/AO3-5874
The old staging servers have returned ( well I have reinstalled them all on new hardware ).
> AO3-5874 Old staging servers return

- Gemfile
- Gemfile.lock
- config/application.rb
- config/config.yml
- config/routes.rb
- config/secrets.yml
https://otwarchive.atlassian.net/browse/AO3-5875
Reverts #3721
This will remove lockup from staging. We have basic auth in place and lockup is not playing nicely with caching.
> AO3-5875 Remove Lockup gem

- db/migrate/20200221045607_drop_approved_from_feedbacks.rb
https://otwarchive.atlassian.net/browse/AO3-5807
Add `--ask-pass` option to both `pt-online-schema-change` commands.
See JIRA.
> AO3-5807 Add --ask-pass option to pt-online-schema-change command.

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5888
Rearrange the servers
> AO3-5888 Rearrange all the servers

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5899
Remove servers from the deploy 
No testing required.
> AO3-5899 Remove servers to be firewalls

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5902
We have turned ao3-app02 off don't deploy to it.
No testing required.
> AO3-5902 Decommission ao3-app02

- README.md
None.
We just [migrated to travis-ci.com from travis-ci.org](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/). Thanks @sarken!
None, [skip ci].
> Update README.md with new travis-ci.com badge

- script/codeship/setup.sh
- script/travis/elasticsearch_upgrade.sh
https://otwarchive.atlassian.net/browse/AO3-5911
Edit a number.
See issue.
> AO3-5911 Update Elasticsearch to 6.8.8 in CI

- app/controllers/chapters_controller.rb
- app/controllers/works_controller.rb
- spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5906
Reverts otwcode/otwarchive#3787
> AO3-5906 Revert: Set view adult response header for nginx to convert to cookie

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5914
We have powered down two servers
> AO3-5914 Remove decommissioned servers

- config/deploy/staging.rb
- features/support/hooks.rb
https://otwarchive.atlassian.net/browse/AO3-5916
Some of the work I want to do on caching needs multiple front ends so we need an additional staging front end server
No testing required
> AO3-5916 Add an additional front end staging server

- features/step_definitions/user_steps.rb
- features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-5921
See JIRA.
See JIRA.
> AO3-5921 Try to fix some intermittent test failures.

- db/migrate/20200415010506_remove_hits_from_preferences.rb
https://otwarchive.atlassian.net/browse/AO3-4622
Adds pt-online-schema-change command for the hit count preference migration.
> AO3-4622 Add pt-online-schema-change for hit count preference migration

- config/config.yml
- config/initializers/rack_attack.rb
https://otwarchive.atlassian.net/browse/AO3-5828
Allows us to white list specific ip address 
Have a ip address range of the tester added to the config and show that the rate limit does not apply.
> AO3-5828 Add IP whitelist for Rack Attack

- app/controllers/readings_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5882
Updates the Page Title for the Marked for Later page, from 'Saved for Later' to 'Marked for Later' as per the issue.
(If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions.)
Tyme
(If you have a Jira account, please …
> AO3-5882 Updated Marked for Later Page Title

- config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-5976
- Decommission an old machine 
- Add a new front end.
No testing required.
> AO3-5976 Decommission ao3-app11, put ao3-front04 back in service

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5957
Upgrades the version of rack and rack-dev-mark to a more secure version
If the testing site is working that is probably good enough
> AO3-5957 Bump rack and rack-dev-mark

- config/initializers/gem-plugin_config/sanitizer_config.rb
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5974
There is a security issue with sanitizer and this is the work around.
To test, we’ll probably want to try creating a work with embeds (iframe in particular) and our HTML regression test doc.
> AO3-5974 Update sanitizer configuration with workaround for CVE-2020-4054

- script/create_admin.rb
https://otwarchive.atlassian.net/browse/AO3-5980
https://otwarchive.atlassian.net/browse/AO3-5623
- Update admin creation script to prompt for roles
- Print the admin login HTTPS URL for the right environment
- Remove spaces in admin logins
- Output i18n role names in wiki output
Someone should run the script. I did:
<details>
Paste or enter admins, one per line, in the format
USERNAME, EMAIL, ROLE
or
USERNAME, EMAIL, ROLE, ROLE, ROLE
where USERNAME is their Org name without spaces and without the admin- prefix
and ROLE is one of:
communications
docs
open_doors
policy_and_abuse
superadmin
support
tag_wrangling
translation
then two line breaks to end:
Pandemonica,monika@example.com,support,tag_wrangling
Modeus,gummymaid@example.com,tag_wrangling …
> AO3-5980 AO3-5623 Update admin creation script to prompt for roles

- app/models/admin.rb
- app/policies/admin_post_policy.rb
- app/policies/comment_policy.rb
- config/locales/models/en.yml
https://otwarchive.atlassian.net/browse/AO3-5518
https://otwarchive.atlassian.net/browse/AO3-5519
https://otwarchive.atlassian.net/browse/AO3-5886
* Adds board role
* Lets admins with that role do admin post things, delete comments, and mark comments spam
Refer to Jira.
> AO3-5518 AO3-5519 AO3-5886 Add board admin role with admin post and comment moderation permissions

- app/policies/admin_setting_policy.rb
- features/admins/admin_invitations.feature
- features/other_a/invite_queue.feature
- spec/controllers/admin/settings_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5883
What it says on the tin.
Refer to Jira.
> AO3-5883 Let policy_and_abuse admins turn queue on/off and specify how many invites to send per day

- .travis.yml
- config/travis/database.yml
- docker-compose.yml
- script/check_syntax
- script/travis/mysql.sh
https://otwarchive.atlassian.net/browse/AO3-6012
Changes the database system to mariadb for test.
No testing required, test and dev changes only
> AO3-6012 Use MariaDB in Travis CI and Docker

- app/views/layouts/_proxy_notice.html.erb
- config/locales/views/en.yml
- config/locales/views/zh-CN.yml
- public/stylesheets/site/2.0/16-zone-system.css
https://otwarchive.atlassian.net/browse/AO3-5975
* Use English text that matches Chinese text
* Use proper HTML lists
Legal said we could do whatever we wanted with the formatting, so I have made the two languages match.
(`userstuff` is an unintuitive class name given it's not user stuff, but it's consistent with our use elsewhere, e.g. on the TOS.)
Refer to Jira.
> AO3-5975 Update proxy notice

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6033
Update to newer version, shouldn't make any difference to users, only to coders
Check the Archive homepage loads
> AO3-6033 Update codecov gem to 0.2.0

- app/controllers/works_controller.rb
- spec/controllers/works/default_rails_actions_spec.rb
✓ Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
✓ Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
✓ Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
✓ Have you added the [Jira](https://otwarchive.atlassian.net) issue number as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
✓ Do you have fewer than 5 pull requests already open? If not, please wait until they are reviewed and merged before creating new pull requests.
https://otwarchive.atlassian.net/browse/AO3-5861
Fixes 500 error when accessing URLs like …
> AO3-5861 Fix 500 on /users/{invalid}/works/collected

- app/views/layouts/_javascripts.html.erb
Pull Request Checklist
Note on tests: I checked and didn't find any feature tests for this, but let me know if it would be appropriate to add some and I'll take a crack at it.
https://otwarchive.atlassian.net/browse/AO3-6046
Currently, if you save a page from certain browsers and then reopen the file, the proxy warning notice appears. This prevents pages from showing the warning proxy notice if the page is a saved file on the user's local machine.
_How can the Archive's QA team verify that this is working as you intended?_
Handily outlined in the Jira card already, but reproduced here:
* Go to https://test.archiveofourown.org
* observed in …
> AO3-6046 Do not show proxy notification if viewing from a file

- app/models/bookmark.rb
- app/models/collection.rb
- app/models/concerns/taggable.rb
- app/models/filter_updater.rb
- app/models/tag.rb
- app/models/tagging.rb
- config/config.yml
- db/migrate/20201210140123_add_organizational_fields_to_collections.rb
- spec/models/concerns/filterable_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6086
Sets up code to prepare for the larger feature that migrates Collections search features to Elasticsearch
(If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions.)
(If you have a Jira account, please include the same name in the "Full name" …
> AO3-6086 Make collections taggable behind the scenes

- lib/otw_sanitize/embed_sanitizer.rb
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6096
Addressable considers " https" an invalid scheme.
...Rake it One More Time
> AO3-6096 Remove spaces around Dewplayer audio URLs

- lib/tasks/after_tasks.rake
- spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6096
Print count of chapters where embeds are really converted.
Oops!...Please Rake It Again
> AO3-6096 Fix output of task to replace Dewplayer embeds

- config/initializers/rack_attack.rb
- spec/requests/rack_attack_spec.rb
- spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6115
Fix Rack::Attack configurations (URLs and parameters to check).
Use cURL to POST to /users/login? idk.
> AO3-6115 Fix rate limiting on user login attempts

- app/models/role.rb
- app/models/roles_user.rb
- app/models/user.rb
- config/initializers/gem-plugin_config/permit_yo_config.rb
- factories/users.rb
- features/admins/users/admin_manage_users.feature
- features/step_definitions/tag_steps.rb
- features/step_definitions/user_steps.rb
- spec/controllers/admin/admin_users_controller_spec.rb
- spec/controllers/locales_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6137
Create a log item when an admin changes a user's roles.
Refer to Jira.
> AO3-6137 Log admin changes to user roles

- lib/tasks/defaults.rake
- spec/support/task_example_group.rb
https://otwarchive.atlassian.net/browse/AO3-5525
Fixes  the rake task 😬
> AO3-5525 Add environment dependency to defaults:create_roles task

- app/views/preferences/index.html.erb
- features/other_a/preferences_edit.feature
- features/other_a/reading.feature
- features/step_definitions/preferences_steps.rb
- public/help/misc-preferences.html
https://otwarchive.atlassian.net/browse/AO3-6155
Reword text relating to the History preference. 
Refer to Jira.
(If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.)
(If you do not fill in this section, we will use your GitHub account name and
they/them pronouns to avoid making assumptions about your gender.)
> AO3-6155 Changed wording for History preference

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
None.
Makes some tweaks to the pull request template and contributing guidelines. This is a draft.
Submit a pull request.
> Tweaks to pull request template and contributing guidelines

- app/models/tag.rb
https://otwarchive.atlassian.net/browse/AO3-5431
Remove the scopes `related_tags_for_all`, `related_tags`, and `filters_with_count`, and the methods `indirect_bookmarks` and `visible_taggables_count` from the `Tag` class.
> AO3-5431 Remove unused code from the Tag class.

- app/models/tagset_models/tag_set.rb
https://otwarchive.atlassian.net/browse/AO3-6179
Removes 9 unused methods/scopes from the TagSet class. Also adds/inserts a few newlines, just because I was in the area and the spacing was bothering me.
> AO3-6179 Clean up unused TagSet methods.

- features/step_definitions/generic_steps.rb
- features/works/work_create.feature
- public/javascripts/livevalidation_standalone.js
https://otwarchive.atlassian.net/browse/AO3-3585
Reverts otwcode/otwarchive#3982 until we deal with some accessibility issues.
> Revert "AO3-3585 Reenable submit buttons after live validation errors are addressed"

- app/models/prompt.rb
https://otwarchive.atlassian.net/browse/AO3-6186
Remove unused constants, scopes, and methods from the Prompt class.
> AO3-6186 Remove unused Prompt methods.

- lib/plugins/acts_as_commentable/comment_methods.rb
- spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6126
Don't check comment parents when we're in the middle of deleting the ultimate parent (e.g. works).
See issue.
> AO3-6126 Fix deleting works with deleted comment placeholder chains

- lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-5988
When we switch to .find_each, works are not eager loaded anymore, so calling works_using_tag.size doesn't give us the correct count.
See issue.
> AO3-5988 Fix output count for After:fix_teen_and_up_imported_rating

- app/models/challenge_signup.rb
https://otwarchive.atlassian.net/browse/AO3-6181
Refactor `ChallengeSignup#unique_tags` to reduce duplication and make it more readable.
It's still not as simple as Code Climate wants, but it's an improvement.
> AO3-6181 Refactor ChallengeSignup#unique_tags.

- app/views/kudos/_kudos.html.erb
We do not test for visual changes
https://otwarchive.atlassian.net/browse/AO3-6168
Wanted to fix the issue as it's a consequence of my old PR 😅 
Issue was set as Medium difficulty, but with the great suggestions in the description I can't find anything else that needs fixing. Might be wrong as usual 😄 
- all looks the same with javascript disabled
- heading doesn't directly have `id="kudos"`, but that's ok (I believe id is used now only when navigating directly to kudos section from work blurb and for rendering new kudo)
- I can't figure out how to apply other existing skins other than Default and Archive 2.0, but I believe they are not affected …
> AO3-6168 Introduce kudos heading

- README.md
Nada!
Adds some text about an API to the README.
Look at README with your special eyes. Or your special screen reader or Braille device, but that's not a meme from a commercial from like 15 years ago.
> Add API section to README

- app/models/admin_post.rb
- spec/controllers/admin_posts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6093
Attempt 3! 😄 
korrien, she/her
> AO3-6093 Do not create tags for translation of invalid post

- .github/workflows/automated-tests.yml
- Gemfile
- Gemfile.lock
- docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-6270
Bump elasticsearch to reflect server version
Just a smoke test.
> AO3-6270 Bump elasticsearch to 7.16.1

- app/controllers/invite_requests_controller.rb
- spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6242
Allows admins to search invitation requests by IP
Steps as mentioned on the JIRA issue:
- Log in as admin
- Invitations > Manage Queue
- Enter an IP address in the search field
What name and pronouns should we use to credit you in the [Archive of Our Own's Release …
> AO3-6242 Let admins search invitation requests by IP

- app/views/home/site_map.html.erb
- app/views/layouts/_footer.html.erb
- features/admins/admin_languages.feature
- features/other_a/abuse_report.feature
- features/other_b/support.feature
- public/403.html
- public/445.html
- public/500.html
- public/502.html
- public/503.html
- public/507.html
- public/nomaintenance.html
- public/status/index.html
https://otwarchive.atlassian.net/browse/AO3-5619
1. Change "Technical Support and Feedback" to "Technical Support & Feedback" in footer and static error pages.
2. Change "Support and Feedback" to "Technical Support & Feedback" in site map.
3. Change "Report Abuse" and "Technical Support and Feedback" to "Policy Questions & Abuse Reports" and "Technical Support & Feedback" in status page.
See Jira ticket. Additionally, test.archiveofourown.org/status should be checked as well.
> AO3-5619  Update link text to Support in footer and site map

- public/help/collection-preferences.html
https://otwarchive.atlassian.net/browse/AO3-6231
Update help text for "Turn off emails about collections" preference.
See Jira ticket.
[AO3-6231 Notify work creators when collection moderators change the work to anonymous or unrevealed
](https://otwarchive.atlassian.net/browse/AO3-5028)
> AO3-6231 Update help text for "Turn off emails about collections" preference

- app/views/admin/_header.html.erb
- app/views/menu/_menu_about.html.erb
- app/views/menu/_menu_browse.html.erb
- app/views/menu/_menu_fandoms.html.erb
- app/views/menu/_menu_search.html.erb
https://otwarchive.atlassian.net/browse/AO3-4530
Use `link_to` instead of `span_if_current` for main and admin dropdown menus. 
See Jira ticket.
https://otwarchive.atlassian.net/browse/AO3-3852
> AO3-4530 Use link_to in main navigation and admin header

- factories/chapters.rb
- features/step_definitions/work_steps.rb
- spec/controllers/bookmarks_controller_spec.rb
- spec/controllers/chapters_controller_spec.rb
- spec/controllers/tags_controller_spec.rb
- spec/lib/tasks/after_tasks.rake_spec.rb
- spec/lib/tasks/work_tasks.rake_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/chapter_spec.rb
- spec/models/search/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5968
Modifies the default chapter factory to make chapters posted by default, and adds a `:draft` trait for chapters.
> AO3-5968 Make the chapter factory create posted chapters by default.

- app/views/users/sessions/_greeting.html.erb
https://otwarchive.atlassian.net/browse/AO3-6305
Make greeting dropdowns have proper styling by not using `span_if_current`.
https://otwarchive.atlassian.net/browse/AO3-4530
> AO3-6305 Use link_to for greeting dropdowns

- app/models/search/bookmarked_work_indexer.rb
- lib/tasks/search.rake
https://otwarchive.atlassian.net/browse/AO3-6315
This should be faster than querying only works with bookmarks.
Fix typos in search.rake.
See issue.
> AO3-6315 Query all works when reindexing bookmarkables

- app/helpers/comments_helper.rb
- spec/helpers/comments_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6323
Follow up on AO3-6323, fixing an issue in the original pull request.
See JIRA.
> AO3-6323 Add user ID to comments

- app/helpers/mailer_helper.rb
- app/views/user_mailer/_work_info.text.erb
- app/views/user_mailer/recipient_notification.html.erb
- app/views/user_mailer/recipient_notification.text.erb
- config/locales/mailers/en.yml
- spec/helpers/mailer_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5348
* Add missing formatting to series metadata label in text email
* Finish i18n, except for "by creators," which we're going to deal with for subscriptions first
Give a gift that's a work in a series.
> AO3-5348 Gift notification i18n

- config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6146
Fixes copy associated with the warning about changing user names to be consistent with the copy elsewhere.
See associated Jira ticket
Follow-up to #4161
What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)? **Brian Austin (they/he)**
> AO3-6146 Fix copy for user name change info

- features/importing/archivist.feature
- features/importing/work_import.feature
- features/importing/work_import_dw.feature
- spec/models/story_parser_spec.rb
None.
Disable failing tests until we can fix them ([AO3-6353](https://otwarchive.atlassian.net/browse/AO3-6353)).
Also delete an old test with unclear checks.
None.
> Skip Dreamwidth importing tests

- app/models/collection_item.rb
https://otwarchive.atlassian.net/browse/AO3-6338
Remove unused methods from CollectionItem
N/A
N/A
Tara Rosenthal (she/her)
> AO3-6338 Remove unused CollectionItem methods

- .github/workflows/automated-tests.yml
- Gemfile
- Gemfile.lock
- docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-6332
This PR will:
* Update the gem version to 7.17.0
* Update the elasticsearch container image in development and CI to 7.17.1. 
According to the issue in Jira, it should be enough to make sure that when you post a work, it appears in a tag’s work listings and on your works page. I don't have permission to Jira yet.
warlockmel (Geraldine Jimenez) (she/her)
> AO3-6332 Upgrade Elasticsearch to 7.17.1

- app/controllers/comments_controller.rb
- app/helpers/comments_helper.rb
- app/views/comments/_single_comment.html.erb
- app/views/home/_inbox_module.html.erb
- app/views/inbox/show.html.erb
- features/comments_and_kudos/hidden_comments.feature
https://otwarchive.atlassian.net/browse/AO3-6127
It addresses the problems found by the QA team mentioned in the ticket.
> AO3-6127 Add notice banner to hidden comments

- app/controllers/comments_controller.rb
- features/comments_and_kudos/hidden_comments.feature
https://otwarchive.atlassian.net/browse/AO3-6127
Expose option for admins to hide comments. Revision No. 3
Follow instructions on JIRA.
EchoEkhi (He/Him/{/([A-Z][a-z]*)/g})
> AO3-6127 Log hiding and unhiding comments

- app/controllers/users_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6361
Record a log item when admins change a user's email.
See bug replication steps in Jira.
> AO3-6361 Record admin email change

- app/helpers/application_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6360
* It removes unused functions in the application helper
> AO3-6360 Remove unused methods from ApplicationHelper

- app/models/pseud.rb
https://otwarchive.atlassian.net/browse/AO3-6369
Remove unused Pseud scopes and methods
N/A
Bilka (he/him)
> AO3-6369 Remove unused Pseud scopes and methods

- factories/skins.rb
https://otwarchive.atlassian.net/browse/AO3-6343
I accidentally introduced a flaky test in AO3-6343. This PR should fix it. I ran `rspec spec/controllers` 36 times in this run, and it passed every time:
https://github.com/tickinginstant/otwarchive/actions/runs/3011254353
> AO3-6343 Fix flaky test introduced in AO3-6343

- app/controllers/admin/spam_controller.rb
- app/policies/moderated_work_policy.rb
- app/policies/spam_policy.rb
- app/views/admin/_header.html.erb
- features/admins/admin_spam.feature
- spec/controllers/admin/spam_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6381
Restrict admin access to spam
Description 
Log in as an admin with the policy_and_abuse or superadmin role
You should see Spam in the admin navigation and it should take you to https://test.archiveofourown.org/admin/spam
You should be able to perform the various marking/unmarking as spam activities on this page as well as the Confirmed Spam and Approved Works pages
Log in as an admin without the policy_and_abuse or superadmin role
You should not see Spam in the admin navigation and should not be able …
> AO3-6381 Restrict admin access to spam page

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-6412
Fixes the workers on staging
Log on to test-app15 and check that it has the database config and the workers are running.
> AO3-6412 Workers need their config 

- app/views/admin_posts/index.html.erb
- app/views/admin_posts/show.html.erb
- features/admins/admin_post_news.feature
https://otwarchive.atlassian.net/browse/AO3-4355
Show localized RSS feeds when clicking on the "RSS Feed" button for admin posts
See Jira ticket.
What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)? **Brian Austin (they/he)**
> AO3-4355 Set language for admin posts RSS

- script/create_admin.rb
https://otwarchive.atlassian.net/browse/AO3-6089 
Try running the script with capitalized role names 
Cesium-Ice, she/her
field on …
> AO3-6089 Make admin script creation roles not case sensitive

- app/controllers/collection_items_controller.rb
- config/routes.rb
- spec/controllers/collection_items_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6337
* It removes the unused  #destroy action in CollectionItemsController and its related functions/code.
Automated tests are enough
> AO3-6337 Remove unused CollectionItemsController#destroy action

- lib/html_cleaner.rb
https://otwarchive.atlassian.net/browse/AO3-6421
- Adds a stripped down version of the `sanitize_value` function that removes all of the code that changes formatting, leaving only the code that sanitizes, and call it in `sanitize_field` to add an extra sanitizing step right before display.
> AO3-6421 Temporarily add an extra sanitizing step.

- .github/workflows/automated-tests.yml
https://otwarchive.atlassian.net/browse/AO3-6426
Use Ubuntu 20.04 for the Automated Tests workflow.
> AO3-6426 Use Ubuntu 20.04 for Automated Tests workflow.

- app/views/works/new_import.html.erb
* [✅] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [✅] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [❌] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* No functionality changes
* [✅] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
* [✅] Do you have fewer than 5 pull requests already open? If not, please wait
https://otwarchive.atlassian.net/browse/AO3-6418
Adds Wattpad.com to the banner at the top of …
> AO3-6418 Add Wattpad to import warning

- README.md
None.
Follow instructions from https://github.com/badges/shields/issues/8671.
Preview the rich diff.
> Update README.md with new Shields.io badge URL

- config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6197
* Removes unused Defensio variables in the config.yml 
No testing required
> AO3-6197 Remove unused Defensio config variables

- config/initializers/gem-plugin_config/sanitizer_config.rb
- lib/paragraph_maker.rb
- public/help/html-help.html
- public/stylesheets/site/2.0/21-userstuff.css
- spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6466
Allow the [`<details>` element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element) and [`<summary>` element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element).
Interpretation:
1. Make sure both `<details>` and `<summary>` elements are accepted
2. Make sure neither gets wrapped in a `<p>`
3. Don't break the contents of `<summary>` up into paragraphs 
4. *Do* break the contents of `<details>` other than `<summary>` up into paragraph(s), as needed
6. Don't bother requiring a `<summary>` to be the child of a `<details>`
I modeled this heavily on "Allow figure and figcaption HTML tags" ([Jira](https://otwarchive.atlassian.net/browse/AO3-5934)/[Pull …
> AO3-6466 Allow <details> and <summary> HTML tags

- app/controllers/tags_controller.rb
- features/tags_and_wrangling/tag_wrangling_special.feature
- spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6387
Prevent accidentally uncanonizing an existing tag when creating a new one.
As per the JIRA walkthrough.
> AO3-6387 Prevent editing existing tags when creating new tags

- lib/css_cleaner.rb
- spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6319
It allows hsl and hsla colors in skins.
EchoEkhi (he/him)
> AO3-6319 Allow hsla colors in skins

- app/views/home/_dmca.html.erb
https://otwarchive.atlassian.net/browse/AO3-6481
Replace broken link on https://archiveofourown.org/dmca with [Chilling Effects Clearinghouse DMCA Notices FAQ](https://www.lumendatabase.org/topics/29#topic-faqs).
1. Go to DMCA page;
2. Check third link.
Isabel Nunes (she/her)
> AO3-6481 Fix broken link on DMCA Policy page

- lib/tasks/skin_tasks.rake
- spec/lib/tasks/skin_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6482
Rename the task to more accurately reflect what it does.
> AO3-6482 Rename task for caching skins

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-6482
What it says on the tin.
> AO3-6482 Update deploy.rb to use new skin task name

- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6449
Upgrades New Relic version to latest 8.16.0.
No
> AO3-6449 Update NewRelic to 8.16.0

- public/robots.public.txt
n/a ("We only accept pull requests for issues we have already added to Jira, with the exception of spelling corrections and documentation improvements") 
This appears to be mostly the same as a spelling correction.
Removes tabs from the `robots.txt` that _might_ mess up some directives, but is also just odd and pointless.
AO3: [colleicute](https://archiveofourown.org/users/colleicute) | GitHub: [thecutefinder](https://github.com/thecutefinder) | Pronouns: he/him or they/them
However, you don't need to attribute me. This is a minor change.
> Replace tabs with spaces in robots.txt

- app/views/downloads/_download_preface.html.erb
https://otwarchive.atlassian.net/browse/AO3-5770
> AO3-5770 Change phrasing of archive warnings in downloaded files

- config/locales/phrase-exports/bn.yml
- config/locales/phrase-exports/fi.yml
- config/locales/phrase-exports/he.yml
- config/locales/phrase-exports/hr.yml
- config/locales/phrase-exports/hu.yml
- config/locales/phrase-exports/ky.yml
- config/locales/phrase-exports/nb.yml
- config/locales/phrase-exports/ru.yml
- config/locales/phrase-exports/sv.yml
- config/locales/phrase-exports/tr.yml
Exported the most recent locale files from Phrase
> Updated translations from Phrase

- app/controllers/tag_wranglers_controller.rb
- config/config.yml
- spec/controllers/tag_wranglers_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6470
Add improvements to mitigate the problem uncovered with wranglers who last wrangled a lot of tags
See Jira
Follow up from #4502 
> AO3-6470 Wrangling report performance improvements

- config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6470
Decrease limit for tag wrangling report to 1,000
In Jira
> AO3-6470 Decrease wrangling report limit

- app/models/kudo.rb
- app/views/comments/_commentable.html.erb
- config/locales/models/en.yml
- config/locales/views/en.yml
- features/comments_and_kudos/kudos.feature
- spec/controllers/kudos_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6517
Prevent blocked users from leaving kudos on their blockers' works.
> AO3-6517 Prevent blocked users from leaving kudos on their blockers' works.

- public/stylesheets/site/2.0/03-region-header.css
- public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-4268
Make dropdown menus fit small screens.
See Jira ticket.
> AO3-4268 Implement full screen width dropdowns for small screen sizes

- config/config.yml
- lib/otw_sanitize/media_sanitizer.rb
- spec/lib/otw_sanitize/media_sanitizer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6199
Automated testing
> AO3-6199 Rename variable and method for banned media embed sources

- public/javascripts/application.js
Reverts otwcode/otwarchive#4272 -- something came up, so we're bumping it to the next release
> Revert "AO3-6158 Remove US$ before banner goal/progress values"

- app/models/admin_blacklisted_email.rb
- app/models/collection.rb
- app/models/comment.rb
- app/models/external_author.rb
- app/models/invitation.rb
- app/models/invite_request.rb
- app/models/user.rb
- app/validators/email_veracity_validator.rb
- config/locales/validators/en.yml
- features/other_a/profile_edit.feature
- features/users/user_create.feature
- spec/models/abuse_report_spec.rb
- spec/models/admin_blacklisted_email_spec.rb
- spec/models/feedback_spec.rb
- spec/models/invitation_spec.rb
- spec/models/invite_request_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
Reverts otwcode/otwarchive#4390 -- something came up, so we're bumping it to the next release
> Revert "AO3-3997 Replace email_veracity with email_format"

- config/config.yml
- lib/otw_sanitize/media_sanitizer.rb
- spec/lib/otw_sanitize/media_sanitizer_spec.rb
Reverts otwcode/otwarchive#4356 -- something came up, so we're bumping it to the next release
> Revert "AO3-6199 Rename variable and method for banned media embed sources"

- public/stylesheets/site/2.0/26-media-narrow.css
Reverts otwcode/otwarchive#4148 -- something came up, so we're bumping it to the next release
> Revert "AO3-4268 Implement full screen width dropdowns for small screen sizes"

- app/policies/user_policy.rb
- app/views/admin/admin_users/_user_form.html.erb
Reverts otwcode/otwarchive#4355 -- something came up, so we're bumping it to the next release
> Revert "AO3-6141 Disable user role checkboxes based on admin permissions"

- app/policies/user_policy.rb
- app/views/admin/admin_users/_user_form.html.erb
Reverts otwcode/otwarchive#4531
> Revert "Revert "AO3-6141 Disable user role checkboxes based on admin permissions""

- public/javascripts/application.js
Reverts otwcode/otwarchive#4536
> Revert "Revert "AO3-6158 Remove US$ before banner goal/progress values""

- app/helpers/works_helper.rb
- app/views/works/_work_module.html.erb
- features/search/works_stats.feature
Reverts otwcode/otwarchive#4537
> Revert "Revert "AO3-5777 Add thousands separators to long numbers in work blurbs""

- app/views/comments/_comment_form.html.erb
Reverts otwcode/otwarchive#4538
> Revert "Revert "AO3-6243 Remove condition for comment form to be 'remote' to avoid CSRF token missing error""

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6568
Removes webdrivers gem to get rid of a ChromeDriver deprecation. Per [GitHub discussion](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1642649978), this is the recommended course of action from the maintainer of webdrivers.
Automated testing only.
Sarken did this, I'm …
> AO3-6568 Remove webdrivers gem

- app/views/layouts/_header.html.erb
- config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6552
The containing paragraph has a `menu` role. This requires[1] its direct
children to have one of a few allowed roles, the most appropriate for
this case being `menuitem`.
[1] https://www.w3.org/TR/wai-aria-1.1/#menu
Separate commit so it can be easily removed if we don't want to i18n
partially. (I'd prefer not to i18n the entire file in this PR.)
Are there other relevant …
> AO3-6552 Login link needs ARIA role

- public/robots.public.txt
[https://otwarchive.atlassian.net/browse/AO3-6583](https://otwarchive.atlassian.net/browse/AO3-6583)
This improves the robots.txt to block chatGPT from scraping AO3. I have also gone through the googlebot wild cards and they appear to all still be valid to keep Googlebot from scanning those. 
This is a robots.txt file. We can use [https://www.websiteplanet.com/webtools/robots-txt/](https://www.websiteplanet.com/webtools/robots-txt/) to test the syntax. 
NA
Ivedonestranger (He/him)
> AO3-6583 Updated the robots.txt to block chatGPT.

- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/users/registrations/new.html.erb
- config/locales/views/en.yml
- public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-6546
Remove a [10+ year old JS function](https://github.com/otwcode/otwarchive/commit/75db584fb7bf2d44e69bb65ed28bf7f4a3d22ccc#diff-e84dc62276e8d65b4a8fe34f17c23a6688184e0899eeaf1e0a652008ad20c5ad) that disabled form submission in the Create Account page. It looks like the race conditions it was trying to avoid have been obviated since then.
I have also made the Cancel button a regular link, rather than submitting the form as I thought it was unnecessary. See additional testing instructions below.
I have also done some internationalization and fixed a minor bug in the validation message of the TOS and …
> AO3-6546 Fix account creation form becoming stuck

- app/controllers/admin/admin_invitations_controller.rb
- app/views/admin/admin_invitations/find.html.erb
- config/locales/controllers/en.yml
- config/locales/views/en.yml
- features/admins/admin_invitations.feature
- features/support/paths.rb
until they are reviewed and merged before creating new pull requests. **I am adopting stale PRs, so I hope this doesn't count to my own limit?**
https://otwarchive.atlassian.net/browse/AO3-5732
- Show error when searching invitations by email has 0 results. 
- Add a test. 
- Did some i18n to the view and made some changes to make the test work.
See Jira ticket .
[Stale PR ](https://github.com/otwcode/otwarchive/pull/3844) If this is merged, we should close it.
[First PR ](https://github.com/otwcode/otwarchive/pull/3844)Tyme (They/Them) 
> AO3-5732 Show error when searching invitations by email has 0 results

- app/controllers/admin/admin_invitations_controller.rb
- app/views/admin/admin_invitations/index.html.erb
- config/locales/views/en.yml
- features/admins/admin_invitations.feature
https://otwarchive.atlassian.net/browse/AO3-5732
Test a partial match that will yield multiple results — a `.com` search, for example.
https://github.com/otwcode/otwarchive/pull/4603/files
> AO3-5732 Fix partial email search not displaying all invitations

- public/robots.public.txt
https://otwarchive.atlassian.net/browse/AO3-6595
Disallow ChatGPT-User robot from crawling any pages on the Archive
> AO3-6595 Disallow ChatGPT-User robots

- db/migrate/20230717161221_add_fnok_user_id_to_log_items.rb
https://otwarchive.atlassian.net/browse/AO3-6467?focusedCommentId=360424
Use the new, simpler to run, syntax for migration pending on staging
https://github.com/otwcode/otwarchive/pull/4528
https://github.com/departurerb/departure
> AO3-6467 Update add_fnok_user_id_to_log_items migration to new syntax

- app/models/user.rb
- config/application.rb
- spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6483
> AO3-6483 Make old password changes deserializable

- app/views/home/donate.html.erb
- config/locales/views/en.yml
- features/other_a/homepage.feature
- features/step_definitions/generic_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6621
Lit. just updating a link + Moving a few sentences toward an i18n file
> AO3-6621 Update OTW Donation Link

- public/stylesheets/ebooks.css
https://otwarchive.atlassian.net/browse/AO3-5626
field on your Jira profile, so we can assign you the issues you're working on. …
> AO3-5626 Fix overlapping text when download has child related works

- app/views/layouts/barebones.html.erb
- public/stylesheets/ebooks.css
https://otwarchive.atlassian.net/browse/AO3-5626
Moves the CSS change to the correct file.
Refer to Jira.
> AO3-5626 Actually fix overlay text when download has child related works

- .erb-lint.yml
- app/views/chapters/_chapter.html.erb
> AO3-6636 Add speculation rules next-chapter prefetch (#4661)

- app/views/skins/_form.html.erb
- db/migrate/20230811004337_change_css_type.rb
- spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6551
Despite the intended limit being `CONTENT_MAX` (510,000 characters), attempting to create a skin with more than 65,535 characters of CSS would hit a 500 error as a result of the wrong SQL column type having been used. This adds a migration correcting it to `longtext`, placing it in line with other columns intended to have a limit of `CONTENT_MAX`.
Note that the JIRA ticket mentions having a JavaScript character counter for skins as a nice-to-have. ~~I am unsure how to implement this, and it seems separate from the actual issue.~~ This has been added as well.
Try creating a very long skin, such as …
> AO3-6551 Correct skin CSS column type

- app/controllers/collection_participants_controller.rb
- features/collections/collection_participants.feature
- spec/controllers/collection_participants_controller_spec.rb
[https://otwarchive.atlassian.net/browse/AO3-6528](https://otwarchive.atlassian.net/browse/AO3-6528)
This changes the wording of the response a user gets when they attempt to add someone to a challenge that has been banned. With this change, it is no longer possible to tell if the user selected had been banned. 
Ban or suspend a user
Log in as admin
Manage Users > Find Users 
In “Name,” enter the name of the user you want to ban or suspend
Find
Follow the “Details” link
Under “Warnings and suspensions,” choose the desired option to ban or suspend
Fill in “Notes”
Update
Log out
As the user who is not banned/suspended, create a collection and …
> AO3-6528 Collection participant error message reveals when users are suspended or banned

- app/helpers/mailer_helper.rb
- config/locales/mailers/en.yml
https://otwarchive.atlassian.net/browse/AO3-6548
Fix broken in test.
> AO3-6548 Fix spacing in guest names on comment notifications

- public/stylesheets/site/2.0/10-types-groups.css
- public/stylesheets/site/2.0/15-group-comments.css
https://otwarchive.atlassian.net/browse/AO3-6548
Fix the CSS for the kudos icon and user icons in comments.
> AO3-6548 Fix display of kudos image

- .github/labeler/contents.yml
https://otwarchive.atlassian.net/browse/AO3-6653
Fix the missing space in content.yml that was causing labeler to fail.
Merge and let 'er rip.
> AO3-6653 Fix missing space in actions/labeler config

- lib/otw_sanitize/media_sanitizer.rb
- spec/lib/otw_sanitize/media_sanitizer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6665
Some spring cleaning.
Refer to issue.
> AO3-6665 Check URL protocols of media src attributes

- lib/tasks/tag_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-6662
The rake task has been erroring and not deleting all the tags 
Follow instructions on jira
james_, he/him
> AO3-6662 Catch errors in rake tasks deleting zero use tags

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- config/initializers/cookies_serializer.rb
- config/initializers/session_store.rb
https://otwarchive.atlassian.net/browse/AO3-6629
This switches from encrypted to signed-only session cookies and changes the format to JSON for easy parsing. This enables session inspection by an intermediary proxy such as NGINX or Cloudflare.
Albert Pedersen (he/him)
> AO3-6629 Switch to signed JSON-formatted session cookies

- lib/tasks/search.rake
- spec/lib/tasks/search_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6624
Add a reminder for the person running the index_tags command to tell the wrangling team the task is being run.
Someone with database access can run the task on staging, or any dev can run it on their dev environment.
I dont think so.
What name and pronouns should we use to credit you in the [Archive of …
> AO3-6624 index tags command msg

- Gemfile
- Gemfile.lock
- features/admins/users/admin_manage_users.feature
- spec/controllers/chapters_controller_spec.rb
- spec/lib/tasks/admin_tasks.rake_spec.rb
- spec/lib/tasks/work_tasks.rake_spec.rb
- spec/lib/works_owner_spec.rb
- spec/models/redis_hit_counter_spec.rb
- spec/models/search/bookmark_search_form_spec.rb
- spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6134
Replaces Delorean gem with TimeHelpers
Automated
> AO3-6134: Remove gem Delorean from test dependencies

- features/comments_and_kudos/add_comment.feature
https://otwarchive.atlassian.net/browse/AO3-3463
Fix broken on test (test only)
Run tests
See ticket comments
EchoEkhi
> AO3-3463 Fix test to not use a DST timezone

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6647
> AO3 6647 added gems for modern ssh for install

- app/controllers/series_controller.rb
- app/helpers/users_helper.rb
- app/models/series.rb
- features/users/user_dashboard.feature
https://otwarchive.atlassian.net/browse/AO3-6592
Optimizes the database query used for `series_link` and `pseud_series_link`.
See Jira.
Bilka (he/him)
> AO3-6592 Optimize the database query for the series count in the user sidebar

- app/controllers/bookmarks_controller.rb
- app/models/bookmark.rb
- features/step_definitions/bookmark_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6336
Remove default_scope and update related queries.
> AO3-6336 Remove default_scope for bookmarks

- app/mailers/user_mailer.rb
- app/views/user_mailer/claim_notification.html.erb
- app/views/user_mailer/claim_notification.text.erb
- config/locales/mailers/en.yml
- spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4308
Check the email notification can be internationalized.
> AO3-4308 I18n claim_notification

- docker-compose.yml
- script/docker/init.cmd
- script/docker/init.sh
* [] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
https://otwarchive.atlassian.net/browse/AO3-6705
Cf ticket
Try executing the scripts locally and see if anything breaks.
As soon as merged, `docker compose` should also lose its hyphen [on the wiki](https://github.com/search?q=repo%3Aotwcode%2Fotwarchive+docker+compose&type=wikis).
> AO3-6705 New docker syntax

- app/controllers/autocomplete_controller.rb
https://otwarchive.atlassian.net/browse/AO3-6669
Makes it impossible to have duplicates in the autocomplete.
> AO3-6669 Incase elastic does get an exact match

- config/locales/views/en.yml
* [ x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x ] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x ] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
* [x ] Do you have fewer than 5 pull requests already open? If not, please wait
https://otwarchive.atlassian.net/browse/AO3-6608
Delete icon alt and comment text when deleting icon. I forgot to …
> AO3-6608 Update delete icon checkbox text

- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/_bookmark_blurb.html.erb
- app/views/bookmarks/_bookmarks.html.erb
- app/views/bookmarks/fetch_recent.js.erb
- app/views/bookmarks/hide_recent.js.erb
- config/routes.rb
- features/bookmarks/bookmark_create.feature
- public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
- public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-6725 
Remove functionality that is slow and causes issues.
Log in, bookmark some works.
Go to your psued page for example https://archiveofourown.org/users/zz9pzza/pseuds/zz9pzza ( https://archiveofourown.org/users/{{username}}/pseuds/{{pseud}} ) 
Scroll down to "Recent bookmarks", check that the bookmark does not have the "Show Most Recent Bookmarks"  button
If you have a Jira account, …
> AO3-6725 remove get recent bookmarks

- factories/users.rb
- test/mailers/previews/admin_mailer_preview.rb
- test/mailers/previews/comment_mailer_preview.rb
- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4815
> Revert "AO3-6017 Use unique names for users in mailer previews"

- app/views/user_mailer/feedback.html.erb
- app/views/user_mailer/feedback.text.erb
- config/locales/mailers/en.yml
- features/other_b/support.feature
- spec/mailers/user_mailer_spec.rb
- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4788
> Revert "AO3-5351 Make remaining text in feedback response i18n-able"

- config/initializers/gem-plugin_config/redis.rb
- config/initializers/gem-plugin_config/resque.rb
Reverts otwcode/otwarchive#4787
> Revert "AO3-6706 Support Sentinel config for Redis clients"

- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/_bookmark_blurb.html.erb
- app/views/bookmarks/_bookmarks.html.erb
- app/views/bookmarks/fetch_recent.js.erb
- app/views/bookmarks/hide_recent.js.erb
- config/routes.rb
- features/bookmarks/bookmark_create.feature
- public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
- public/stylesheets/site/2.0/13-group-blurb.css
Reverts otwcode/otwarchive#4808
> Revert "AO3-6725 remove get recent bookmarks"

- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4782
> Revert "AO3-6704 Use URL from current host in abuse report response mailer preview"

- app/controllers/readings_controller.rb
- app/controllers/works_controller.rb
- features/other_a/reading.feature
Reverts otwcode/otwarchive#4781
> Revert "AO3-5506 Don't include hidden works in Readings"

- lib/html_cleaner.rb
- spec/lib/html_cleaner_spec.rb
Reverts otwcode/otwarchive#4798
> Revert "AO3-6087 Stop removing non-printable Unicode characters"

- app/helpers/bookmarks_helper.rb
- app/views/external_works/_blurb.html.erb
- app/views/external_works/_work_module.html.erb
- app/views/series/_series_module.html.erb
- app/views/series/show.html.erb
- config/locales/models/en.yml
Reverts otwcode/otwarchive#4560
> Revert "AO3-5371 Add descriptive classes to external work and series blurbs"

- app/helpers/bookmarks_helper.rb
- app/views/external_works/_blurb.html.erb
- app/views/external_works/_work_module.html.erb
- app/views/series/_series_module.html.erb
- app/views/series/show.html.erb
- config/locales/models/en.yml
Reverts otwcode/otwarchive#4819
> Revert "Revert "AO3-5371 Add descriptive classes to external work and series blurbs""

- public/stylesheets/site/2.0/22-system-messages.css
Reverts otwcode/otwarchive#4818
> Revert "Revert "AO3-6570 Import Work error message overflows for long URLs""

- lib/html_cleaner.rb
- spec/lib/html_cleaner_spec.rb
Reverts otwcode/otwarchive#4820
> Revert "Revert "AO3-6087 Stop removing non-printable Unicode characters""

- app/controllers/readings_controller.rb
- app/controllers/works_controller.rb
- features/other_a/reading.feature
Reverts otwcode/otwarchive#4821
> Revert "Revert "AO3-5506 Don't include hidden works in Readings""

- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4826
> Revert "Revert "AO3-6704 Use URL from current host in abuse report response mailer preview""

- app/helpers/mailer_helper.rb
- app/views/admin_mailer/comment_notification.text.erb
- app/views/admin_mailer/edited_comment_notification.text.erb
- config/locales/mailers/en.yml
- spec/mailers/admin_mailer_spec.rb
- spec/mailers/comment_mailer_spec.rb
- test/mailers/previews/admin_mailer_preview.rb
- test/mailers/previews/comment_mailer_preview.rb
Reverts otwcode/otwarchive#4829
> Revert "Revert "AO3-6017 Add role of commenter to comment notification emails""

- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/_bookmark_blurb.html.erb
- app/views/bookmarks/_bookmarks.html.erb
- app/views/bookmarks/fetch_recent.js.erb
- app/views/bookmarks/hide_recent.js.erb
- config/routes.rb
- features/bookmarks/bookmark_create.feature
- public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
- public/stylesheets/site/2.0/13-group-blurb.css
Reverts otwcode/otwarchive#4825
> Revert "Revert "AO3-6725 remove get recent bookmarks""

- db/migrate/20240404183910_add_indices_to_owned_set_taggings.rb
Reverts otwcode/otwarchive#4823
> Revert "Revert "AO3-6708 Add indices to owned set taggings""

- config/initializers/gem-plugin_config/redis.rb
- config/initializers/gem-plugin_config/resque.rb
Reverts otwcode/otwarchive#4822
> Revert "Revert "AO3-6706 Support Sentinel config for Redis clients""

- app/views/user_mailer/feedback.html.erb
- app/views/user_mailer/feedback.text.erb
- config/locales/mailers/en.yml
- features/other_b/support.feature
- spec/mailers/user_mailer_spec.rb
- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4824
> Revert "Revert "AO3-5351 Make remaining text in feedback response i18n-able""

- factories/users.rb
- test/mailers/previews/admin_mailer_preview.rb
- test/mailers/previews/comment_mailer_preview.rb
- test/mailers/previews/user_mailer_preview.rb
Reverts otwcode/otwarchive#4827
> Revert "Revert "AO3-6017 Use unique names for users in mailer previews""

- .gitpod.yml
- config/environments/development.rb
- docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-6707
Add config for GitPod to support easier remote development.
I was kinda surprised how fast startup was, but with the `init` section, devs should be able to turn on pre-builds too for making things faster.
> AO3-6707 Add GitPod config

- app/models/search/bookmark_indexer.rb
- app/models/search/work_indexer.rb
- config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6744
james_
> AO3-6744 Change number of shards

- app/controllers/home_controller.rb
- app/views/home/about.html.erb
- app/views/home/donate.html.erb
- config/locales/views/en.yml
- features/other_a/homepage.feature
https://otwarchive.atlassian.net/browse/AO3-6724
I18n and update the text on the donate and about pages.
~~I resisted the urge to update all links to be https instead of http.~~ All links on the two pages have been updated to https.
See Jira.
Bilka (he/him)
> AO3-6724 Update volunteering/about information

- config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-6742
Fix deploy issue introduced in #4865
> AO3-6742 Remove more New Relic things

- app/jobs/report_attachment_job.rb
- app/models/abuse_report.rb
- app/models/feedback_reporters/feedback_reporter.rb
- config/config.yml
- lib/zoho_resource_client.rb
- spec/lib/zoho_resource_client_spec.rb
- spec/models/abuse_report_spec.rb
- spec/models/feedback_reporters/feedback_reporter_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6563
Add a send attachment async job whenever a work is reported.
I'm not familiar with async jobs  and how we generate downloads, so I might need to be pointed in the right direction.
> AO3-6563 Attach HTML download copies of works to abuse tickets

- app/views/admin_posts/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-6010
https://github.com/otwcode/otwarchive/pull/4907#discussion_r1739944045
> AO3-6010 Hide empty tag if no admin actions

- lib/tasks/after_tasks.rake
- spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6405
Adds task for removing multiple ratings on a work, which was [a bug fixed about a year ago](https://otwarchive.atlassian.net/browse/AO3-6533) (sorry for the wait). 
`docker compose run --rm test bundle exec rspec spec/lib/tasks/after_tasks.rake_spec.rb` passes. 
N/A
ellieyhcheng (she/her)
> AO3-6405 Task for removing multiple ratings on a work

- docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-6837
Use selenium/standalone-chromium image to accommodate most platforms including Apple Silicon (M1) machines.
See Jira
Amy Lee
> AO3-6837 Use selenium/standalone-chromium in docker-compose

- app/views/blocked/users/index.html.erb
- app/views/muted/users/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-6819
Extracting headline from the list and removing the list's role
Please refer to the testing instructions in the JIRA ticket
Dev21Maker (he/him)
field on your Jira profile, so we can …
> AO3-6819 Invalid HTML for Blocked Users and Muted Users pages

- app/views/home/site_map.html.erb
- config/locales/views/en.yml
[https://otwarchive.atlassian.net/browse/AO3-6840](https://otwarchive.atlassian.net/browse/AO3-6840) 
Adds entry for TOS FAQ to Site Map > About the Archive of Our Own
lydia-theda
> AO3-6840 Add TOS FAQ to site map

- app/helpers/application_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6843
Suppress the TOS popup on the homepage, the login page (including failed logins), the archive FAQ pages and the pages for failed feedback and abuse report submissions. 
Bilka (he/him)
> AO3-6843 Suppress the TOS popup on more pages

- app/views/home/_dmca.html.erb
https://otwarchive.atlassian.net/browse/AO3-6829
Updates as requested on https://github.com/otwcode/otwarchive/pull/4953
> AO3-6829 Make section references in DMCA consistent

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6858
Adds puma install, it does not start to use it 
This change does not have any functional changes. It allows us to migrate to puma 
james_
> AO3-6858 Add puma library

- config/application.rb
- config/initializers/disable_active_storage_analyzer.rb
https://otwarchive.atlassian.net/browse/AO3-6878
Keep the database happier by turning off this very noisy job (that we probably won't use anyway)
> AO3-6878 Disable ActiveStorage analyzers

- app/controllers/home_controller.rb
https://otwarchive.atlassian.net/browse/AO3-6874
Adds site name to browser page title in TOS related pages.
1. Navigate to the [Terms of Service](https://test.archiveofourown.org/tos), [Content Policy](https://test.archiveofourown.org/content), [Privacy Policy](https://test.archiveofourown.org/privacy) and [Terms of Service FAQ](https://test.archiveofourown.org/tos_faq) pages.
2. Confirm that on each of these pages, the site name in the browser tab are "Terms of Service | SITE NAME", "Content Policy | SITE NAME", "Privacy Policy | SITE NAME" and "Terms of Service FAQ | SITE NAME" respectively. On staging this should be "| \*\*\*TEST ARCHIVE***"
Indes (they/them)
> AO3-6874 Add browser page titles to TOS related pages

- config/locales/controllers/en.yml
https://otwarchive.atlassian.net/browse/AO3-6801
Updates error message text for users who are suspended, banned, or have disabled password resets
lydia-theda
> AO3-6801 Update error messages for banned, suspended, and no_resets users

- app/views/collections/_sidebar.html.erb
https://otwarchive.atlassian.net/browse/AO3-6238 
field on your Jira profile, so we can assign you the issues you're working on. …
> AO3-6238 Specify blank show_random params in sidebar for collection dashboard

- CONTRIBUTING.md
N/A
Just a typo. Commit will skip CI builds.
> Fix typo in contributing documentation

- app/helpers/collections_helper.rb
- app/helpers/skins_helper.rb
- app/helpers/users_helper.rb
- config/environments/production.rb
- config/environments/staging.rb
https://otwarchive.atlassian.net/browse/AO3-6898
Relates to https://github.com/rails/rails/issues/44242
> AO3-6898 Disable ActiveStorage proxying

- app/helpers/collections_helper.rb
- app/helpers/skins_helper.rb
- app/helpers/users_helper.rb
- config/environments/production.rb
- config/environments/staging.rb
Reverts otwcode/otwarchive#5049
> Revert "AO3-6898 Disable ActiveStorage proxying"

- config/locales/mailers/en.yml
- spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6863
Modifies the english locale and matching test to update the co-creator email subject lines.
Run the tests in `spec/mailers/user_mailer_spec.rb`
Jira Account: unsafe_deref, he/him
> AO3-6863 Update co-creator subject lines and tests

- test/fixtures/admins.yml
https://otwarchive.atlassian.net/browse/AO3-6904
add role superadmin and change login to admin-testadmin
> AO3-6904 Update admins.yml

- Gemfile.lock
- config/initializers/monkeypatches/deliver_after_commit.rb
https://otwarchive.atlassian.net/browse/AO3-6902
Updated after_commit_everywhere to 1.6.0 as described in the issue.
Stephen Lewis, he/him
> AO3-6902 Upgraded after_commit_everywhere to 1.6.0

- app/views/archive_faqs/_admin_index.html.erb
- app/views/archive_faqs/show.html.erb
- config/locales/views/en.yml
- features/admins/admin_post_faqs.feature
https://otwarchive.atlassian.net/browse/AO3-6313
Removes info about updated date from Archive FAQ and Show pages on admin
See Jira
N/A
Indes (they/he)
> AO3-6313 Removed updated at info from FAQ categories on admin

- config/config.yml
- config/initializers/rack_attack.rb
https://otwarchive.atlassian.net/browse/AO3-6926
Allow us to apply rate limits per logged in user. This is in addition to the per ip rate limits. 
I am not sure if this can be tested on staging as I am not sure the header will turn up on staging. I can probably tell later 
Are there other relevant issues/pull requests/mailing list discussions? If not, you can remove this section.
james_ hi/him
> AO3-6926 Allow rate limiting by user

- config/initializers/rack_attack.rb
https://otwarchive.atlassian.net/browse/AO3-6926
> AO3-6926 Fix rate limit header names

- app/controllers/admin/admin_users_controller.rb
- config/locales/controllers/en.yml
- config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6942
Updates the page title for `confirm_delete_user_creation` page in admin view to be more dynamic and consistent with other similar page titles
Laura (she/her)
> AO3-6942 Update page title in admin for spam ban deletion 

- app/controllers/collection_profile_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/fandoms_controller.rb
- app/controllers/people_controller.rb
- app/controllers/tags_controller.rb
- config/locales/controllers/en.yml
- spec/controllers/collection_profile_controller_spec.rb
- spec/controllers/collections_controller_spec.rb
- spec/controllers/fandoms_controller_spec.rb
- spec/controllers/people_controller_spec.rb
- spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6939
This PR adds browser page titles for the following collections related pages:
* `/collections/{collection_id}/profile`
- Page title: `{collection name} - Profile | ...`
* `/collections/{collection_id}/collections`
- Page title: `{collection name} - Subcollections | ...`
* `/collections/{collection_id}/fandoms`
- Page title: `{collection name} - Fandoms | ...`
* `/collections/{collection_id}/people`
- Page title: `{collection name} - People | ...`
* `/collections/{collection_id}/tags`
- Page title: `{collection name} - Tags | ...`
1. Browse -> Collections.
2. Click on any Collection.
3. Navigate to …
> AO3-6939 Add browser page titles for collection pages

- features/importing/work_import.feature
- features/step_definitions/work_import_steps.rb
- features/support/vcr.rb
https://otwarchive.atlassian.net/browse/AO3-6980
Fix the work importing tests that started failing because one of the sites went 404.
Automated tests should pass.
Bilka
> AO3-6980 Use mocks for unavailable site in work_import.feature

- app/models/user.rb
- factories/collections.rb
- features/bookmarks/bookmark_share.feature
- features/collections/collectible_open_collection.feature
- features/other_b/skin_wizard.feature
- features/search/filters.feature
- features/step_definitions/bookmark_steps.rb
- features/step_definitions/collection_steps.rb
- features/step_definitions/skin_steps.rb
- features/step_definitions/work_steps.rb
- features/works/work_share.feature
- spec/controllers/collection_items_controller_spec.rb
- spec/models/collection_item_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6982
No more flaky tests.
No manual QA required.
**search/filters.feature:**
Without the fix [40 test runs](https://github.com/Bilka2/otwarchive/actions/runs/14663051259) resulted in 6 failures.
With the fixes [120 test runs](https://github.com/Bilka2/otwarchive/actions/runs/14664324231) result in no failures.
**bookmarks:**
Without the fix [40 test runs](https://github.com/Bilka2/otwarchive/actions/runs/14665264729) resulted in 9 failures.
With the fixes [120 test runs](https://github.com/Bilka2/otwarchive/actions/runs/14665498093) result in no failures.
**other_b:**
Without the fix [40 test runs](https://github.com/Bilka2/otwarchive/actions/runs/14681505380) resulted in 5 failures.
With the fixes [120 test …
> AO3-6982 Fix flaky cucumber features using javascript

- app/controllers/media_controller.rb
- app/models/media.rb
- app/views/home/_fandoms.html.erb
- app/views/menu/_menu_fandoms.html.erb
- config/locales/controllers/en.yml
- features/step_definitions/tag_steps.rb
- features/tags_and_wrangling/tag_wrangling_media.feature
https://otwarchive.atlassian.net/browse/AO3-5513
Changes the fandoms page, the fandoms partial on the logged out homepage and the fandom menu in the header to only show canonical media.
Create canonical media, make sure it shows up in the 3 spots, decanonize it, make sure it now longer shows up. Create non-canonical media, make sure it doesn't show up in the 3 spots, canonize it, make sure it now shows up.
Bilka
> AO3-5513 Change fandom lists to only show canonical media

- app/controllers/stats_controller.rb
- features/other_b/stats.feature
https://otwarchive.atlassian.net/browse/AO3-5270
Updates the statistics page to calculate yearly word counts based on the chapters posted within the year.
marcus8448 (he/him)
> AO3-5270 Calculate statistics page word counts at the chapter level

- public/help/skins-creating.html
https://otwarchive.atlassian.net/browse/AO3-7000
Update the CSS tutorial link to use W3schools, since the old one now links to a crypto magazine :slightly_frowning_face:
> AO3-7000 Update CSS basics tutorial link

- config/locales/phrase-exports/el.yml
- config/locales/phrase-exports/hi.yml
- config/locales/phrase-exports/uk.yml
No issue.
Update the footer and greeting translations manually (bypassing Phrase which we can't use currently) so we can use them for manual testing.
Bilka
> Update footer translations in Greek, Hindi and Ukrainian

- Gemfile
- Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-7016
> AO3-7016 Update Departure to 6.8.0

- app/models/admin_post.rb
- factories/comments.rb
- features/admins/admin_post_news.feature
- features/comments_and_kudos/comments_adminposts.feature
- features/step_definitions/admin_steps.rb
- spec/controllers/comments/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7022
> AO3-7022 Default to only registered commentors on news post

- features/admins/users/admin_find_users.feature
- features/admins/users/admin_manage_users.feature
- features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6565
Fix tests: https://github.com/otwcode/otwarchive/actions/runs/16251756782/job/45882379574
Bilka
> AO3-6565 Fix test failures related to merge conflict

- public/stylesheets/site/2.0/08-actions.css
- not sure how to test, I don't know a lick of frontend, but I've attached screenshots from my iphone proving it works:
https://otwarchive.atlassian.net/browse/AO3-7005
Fix button bolding by adding `font-weight: 400`.
1. Start this branch's version of ao3 on your computer.
2. Connect your computer to your iphone hotspot (I wasn't able to get it working with my wifi, the router must be doing some ip isolation).
3. On your firewall, open the port 3000 both ways.
4. On your computer, run `hostname -I` or use the UI to check your ip address.
5. On your iphone, go into safari incognito mode (very important! Otherwise safari somehow caches the website …
> AO3-7005 Remove unwanted iOS button bolding
