app/controllers/works_controller.rb, app/views/works/_meta.html.erb, db/migrate/20150106211421_add_ip_address_to_works.rb, lib/tasks/spam_report.rake
This is lacking css, and I want to see if it passes our tests however I think it looks reasonable.
https://code.google.com/p/otwarchive/issues/detail?id=4211
=> issue_4211 Record ip addresses on new works

app/controllers/invite_requests_controller.rb, app/views/invite_requests/manage.html.erb
* The link to delete an invite request now keeps and sends the current page number to the controller
* The controller redirects to that page instead of defaulting to the first page.
* The tiniest bit of cleanup/refactoring (`each` instead of `for`, colon instead of rocket, etc.)
https://code.google.com/p/otwarchive/issues/detail?id=4224
=> Issue 4224: keep page number after deleting

app/controllers/admin/user_creations_controller.rb, app/mailers/user_mailer.rb
Resolves Bot-DB: https://code.google.com/p/otwarchive/issues/detail?id=3747
=> 3747: Pass in ID instead of User and Work Objects

app/views/admin_mailer/send_spam_alert.html.erb, app/views/admin_mailer/send_spam_alert.text.erb
The URL for the user is incorrect. In the emails, it's http://test.archiveofourown.org//users/sarken/works -- note the two / instead of one. However, it _does_ work, so it's not the end of the world.
The plain text version of the email could benefit from a blank line between "The following accounts have a suspicious level of traffic:" and "User sarken ( http://test.archiveofourown.org//users/sarken/works ) has a score of 2" but I'd need to see an email with multiple users and multiple works before I could tell you if that blank line needs to be before or after <% @spam.each_pair do |user_id, info| %> on line 4.
Also in the plain text email, there are spaces between the URL and the parentheses for the user, e.g. ( http://test.archiveofourown.org//users/sarken/works ), but not for the work, …
=> Issue 4212 akismet

app/models/filter_tagging.rb
Issue 4227: Fix for filters not being removed
The before filter was returning false and causing the destroy action to roll back. Added method for filter cleanup which we'll have to figure out how to do retroactively.
=> Issue 4227: Fix for filters not being removed

app/models/work.rb
Issue 4234: Fix for broken indexing. Spam fields were causing errors due to incorrect mapping.
https://code.google.com/p/otwarchive/issues/detail?id=4234
=> Issue 4234: Fix for broken indexing

app/views/external_works/show.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4229
There's already a `<li>` in external_works/_blurb.html.erb, so we need to get rid of the one here.
=> 4229 Extra li element on external works

app/views/works/_adult.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4228
Makes sure the `<li>` containing the blurb is inside an `<ol>`. (I chose `<ol>` because that's what we use on external_works/show.html.erb. Precedent, baby.)
=> 4228 Fix HTML on adult content warning page

public/503.html
https://code.google.com/p/otwarchive/issues/detail?id=4235
The page title that appears in the browser bar should correspond with the error message, which says the Archive was responding to slowly. Instead, the page title said, "Exceeded maximum allowed downloads per minute."
=> 4235 Fix 503 page title

public/javascripts/application.js
If you have the Testing tag favorited and open the tag's works page in two browser windows, when you use the Unfavorite Tag button in both windows, the second attempt would give an empty flash message rather than a sensible message because the form was being submitted to a URL that no longer exists. Now it will just say, "We're sorry! Something went wrong." The same should apply to trying to remove a subscription in two windows or trying to delete a history item in two windows.
=> 4209 Error message if you try to perform same AJAX action in two tabs

app/models/favorite_tag.rb, app/models/reading.rb
If you marked a work for later and then accessed it again (but didn't mark it as read), the list on the homepage would still regenerate when the reading rake task ran. This should only regenerate the list when you change a work's marked for later status.
This also fixes it so tags that are decanonized will be correctly removed from favorite tags lists.
=> 4209 Marked for Later updating, Favorite Tag decanonizing

app/controllers/inbox_controller.rb, app/decorators/homepage.rb, app/models/inbox_comment.rb, app/models/user.rb, app/views/inbox/show.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=3758
If you posted a work, had someone comment on that work, deleted that work, and attempted to go to the homepage, you'd (sometimes) get a 500 error. This is because it didn't have the `<% next if feedback_comment.nil? || feedback_comment.is_deleted? %>` logic the inbox has.
However, simply using that logic could result in either (a) only two of three unread items displaying on your homepage or (b) an empty inbox section on the homepage, much like it results in the inbox count being wrong when there are non-visible unread items from deleted works/chapters.
So I have instead created a method that check the status of items' `feedback_comment` and returns the ActiveRecord …
=> 4209 3758 Inbox comment count wrong

app/controllers/works_controller.rb
If an admin set "Turn off filtering on index pages," the works pages would error. This stops that.
=> 4209 Don't break work pages when filters are disabled

app/decorators/homepage.rb, lib/tasks/after_tasks.rake
https://code.google.com/p/otwarchive/issues/detail?id=4251
Will make it so favorite tags are alphabetized by sortable name, e.g. "The Fandom" will be under F. Includes rake task to add sortable_name to tags that are lacking.
=> 4251 Sortable name for favorite tags

lib/tasks/after_tasks.rake
https://code.google.com/p/otwarchive/issues/detail?id=4251
Improve the rake task a bit: including ratings (oops), use find_each, and only set sortable_name for canonical tags that have a blank sortable name.
=> 4251 Include ratings in sortable_name task

app/helpers/application_helper.rb, app/views/chapters/_chapter.html.erb, app/views/works/_work_header.html.erb, app/views/works/_work_module.html.erb, features/collections/collection_anonymity.feature
https://code.google.com/p/otwarchive/issues/detail?id=4252
You'll also see the creator's name if you yourself are the creator, since that's how the code was originally written.
Relevant changes are in https://github.com/sarken/otwarchive/commit/be06c47f6a832f3d7d7f238ce41cdd2b2eebcdb1 and https://github.com/sarken/otwarchive/commit/0aafb5a86c5bf7095641bfb64e09f97143284924 and the test in https://github.com/sarken/otwarchive/commit/f40471880920f33bbd16bbe7907952b2196d5d78 and https://github.com/sarken/otwarchive/commit/84293cef0381cc63f510b0ba0541c5f2aa90dfb4 -- the rest are whitespace and Houndy syntax things.
=> 4252 Allow easier access to creator's usernames in anonymous challenges

app/helpers/application_helper.rb
https://code.google.com/p/otwarchive/issues/detail?id=4258
The error was: 
```
Error message
ActionView::Template::Error: undefined method `+@' for "\n":ActiveSupport::SafeBuffer
Stack trace (show Rails)
…eases/20150301093335/app/helpers/
application_helper.rb: 401:in `checkbox_section_toggle'
…eases/20150301093335/app/helpers/
application_helper.rb: 493:in `checkbox_section'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
router.rb:  68:in `block in call'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `each'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `call'
```
=> 4258 Stop error on edit tag sets page

Gemfile, Gemfile.lock, app/controllers/downloads_controller.rb, app/models/work.rb
https://code.google.com/p/otwarchive/issues/detail?id=4242
=> issue 4242: Another way to remove the warning

app/models/story_parser.rb, features/importing/archivist.feature, features/step_definitions/archivist_steps.rb
When importing external works as an archivist, either through the mass importer or the form, if you set the external author's name to something invalid, the external author is quietly dropped. This strips out the invalid characters that prevent the external author name from being created and associated with the work.
https://code.google.com/p/otwarchive/issues/detail?id=4265
=> 4265 - Strip out invalid characters before attempting to create a new external author

app/controllers/api/v1/import_controller.rb
This adds the ability to send an email with either a claim notification or an invitation (for Archive users and external authors respectively).
https://code.google.com/p/otwarchive/issues/detail?id=4268
Due to a bit of feature creep, it also fixes a bug which prevented general settings like send_claim_emails and post_without_preview were correctly passed down the chain of command.
Note: sending emails is toggled on/off by the client side so merging this won't automatically start sending emails for each import.
=> 4268 mass import emails

app/controllers/api/v1/import_controller.rb, app/controllers/api/v1/works_controller.rb, config/routes.rb, spec/api/api_spec.rb
https://code.google.com/p/otwarchive/issues/detail?id=4270
This creates an end point which takes an array of external urls and for each one, returns either an error indicating it hasn't been found, or the work's URL and creation date on the Archive.
=> 4270 get the Archive URLs for imported works

app/models/tagging.rb, features/bookmarks/bookmark_create.feature
https://code.google.com/p/otwarchive/issues/detail?id=3471
(The test should fail in the first commit, showing the bookmark blurb not updating when the tags are edited. The test should pass in the second commit, showing the bookmark blurb updating in light of the code change.)
=> 3471 Editing bookmark tags should update the bookmark blurb

app/models/abuse_report.rb, config/config.yml, lib/tasks/after_tasks.rake
https://code.google.com/p/otwarchive/issues/detail?id=4266
What this does is clean up the URL a bit for reported works and then check and make sure the last month hasn't already seen 5 or more reports containing "/works/123/" (where "123" is the id of the work being reported). The cleanup of the URLs is to make sure that, even if "works/1234" has reached the maximum, "works/123" can still be reported.
=> 4266 Only allow a URL to be reported to Abuse 5 times per month

app/controllers/application_controller.rb, app/controllers/home_controller.rb, lib/tasks/tag_tasks.rake
Caching the admin settings. Cache expiration is handled in an after_save callback here: https://github.com/otwcode/otwarchive/blob/master/app/models/admin_setting.rb#L86
Resolves issue: https://code.google.com/p/otwarchive/issues/detail?id=3450
=> 3450: More caching of admin settings.

app/views/external_works/_work_module.html.erb, app/views/series/_series_module.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4263
The fandom tags didn't have the fandoms class, so the CSS was not being properly applied.
=> 4263 Series and external work fandom name slightly indented

features/importing/archivist.feature
https://code.google.com/p/otwarchive/issues/detail?id=4261
Fix the failure in cucumber features/importing/archivist.feature:100 # Scenario: Import a single work as an archivist specifying an external author with an invalid name that resulted from issue 4261
=> 4261 Fix importing test

app/views/bookmarks/index.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4288
https://code.google.com/p/otwarchive/issues/detail?id=4289
To make sure the Filters link always displays on a user's bookmark page, we shouldn't check if the bookmarks belong to the *current user* before getting into the navigation logic -- we just want to check if they belong to *a* user.
Also, to make sure the Filters and Bookmark External Work links appear correctly on collections' bookmark pages, we needed to check if the bookmarks are in a collection.
=> 4288 4289 Filters & other bookmark navigation missing

features/works/work_search.feature
https://code.google.com/p/otwarchive/issues/detail?id=4290
It was failing on features/works/work_search.feature:62 `Then I should see "5 Found"' when we searched for works revised at: > 2 years ago because the work last revised on April 29 2013 is now (correctly) included in the results, bringing the desired total of results from 5 to 6.
=> 4290 Fix work search test failure

features/other_a/reading.feature
https://code.google.com/p/otwarchive/issues/detail?id=4297
The number of times a work has been viewed on lines 145 and 154 goes back and forth between two values, so these tests have been failing extremely frequently. Our best bet is to comment those lines out for now.
=> 4297 Reading test fix

app/views/share/_share.html.erb
Apologies for the trivial pull request, but this prevents mixed-content warnings when site accessed over https.
=> 4298 Use a protocol-relative URL for tumblr share image

app/views/kudo_mailer/batch_kudo_notification.html.erb, app/views/kudo_mailer/batch_kudo_notification.text.erb, app/views/layouts/mailer.html.erb, app/views/layouts/mailer.text.erb, config/locales/en.yml, config/locales/pt-BR.yml
Issue 4100: https://code.google.com/p/otwarchive/issues/detail?id=4100
This PR fixes the subject line originally created in pull request #1868. The subject line now has 'AO3' correctly wrapped in brackets []
=> [AO3] issue 4100 

app/models/work.rb, features/cassette_library/cucumber_tags/work_external_language.yml, features/cassette_library/cucumber_tags/work_external_parent.yml, features/step_definitions/work_steps.rb, lib/url_helpers.rb
https://code.google.com/p/otwarchive/issues/detail?id=3060
For internal works, we just want to see if it's a work on the archiveofourown.org domain (APP_HOST) rather than checking if it's on http://archiveofourown.org (APP_URL).
For external works, we want to turn the https:// into http:// automatically
=> 3060 Don't error when given https URLs for parent & external works

app/views/external_works/_blurb.html.erb, app/views/prompts/_prompt_blurb.html.erb
https://code.google.com/p/otwarchive/issues/detail?id=4294
https://code.google.com/p/otwarchive/issues/detail?id=4295
The fandom tags were slightly indented because a class name was missing.
=> 4294 4295 Fandom tag indented on prompts, external works

app/views/tag_wranglings/_wrangler_dashboard.html.erb
Resolves issue: https://code.google.com/p/otwarchive/issues/detail?id=4304
The 'Unsorted Tags' link calls upon 'UnsortedTag.count' which needlessly queries the database on every Wrangling page, regardless of the count information being useful or not. 
Moving the 'Unsorted Tags' link down with the rest of the bin links ensures that the database is queried only when working on actual tags.
=> 4304: Move the Unsorted tags bin link down with rest of bin links

app/controllers/admin_posts_controller.rb, app/views/admin_posts/_filters.html.erb
Resolves issue: https://code.google.com/p/otwarchive/issues/detail?id=4286
Simply carried over the code changes in #1874 to also be used in the index listing of the Admin Posts.
=> 4286: Only display languages with associated locales in admin post dropdown

config/deploy.rb
https://code.google.com/p/otwarchive/issues/detail?id=4332
=> Restart more slowly

app/controllers/comments_controller.rb, app/views/comments/_comment_form.html.erb
Set IP address data for all comments and do it more securely in the controller instead of the view.
(No issue yet, will discuss.)
=> Set comment ip addresses more securely and universally

config/deploy/production.rb
resque workers ao3-app09 and ao3-app10. While it might mean we are
a bit heavy on the workers it will mean that the wrangulator will
fly. Additionally we don't record newrelic stats for resque workers
so we don't have to pay for resque workers, also we have a power budget
for the rack and we are under it so lets keep the machines for a bit
so we get some last work out of them for a year or so.
=> The old ao3-front01 and ao3-front02 have been repurposed to be

app/models/work.rb, lib/url_formatter.rb, spec/models/story_parser_spec.rb, spec/models/work_spec.rb
https://code.google.com/p/otwarchive/issues/detail?id=4325
Instead of doing a partial match as a last resort, the #find_by_url code now does exact matches based on various URL combinations. This should allow it to find URLs with insignificant query parameters (e.g. LiveJournal's ?style=mine), significant query parameters that we know about (e.g. eFiction's sid parameter) and URLs ending with consecutive numbers (like the temporary site I did for HASA before realising the bug existed).
Test cases have been added for all these scenarios.
=> AO3-4316 - Improve URL matching for imported works

features/collections/collection_anonymity.feature, features/comments_and_kudos/kudos.feature, features/importing/work_import_lj.feature, features/other_b/series.feature, features/prompt_memes_a/challenge_promptmeme.feature, features/works/chapter_edit.feature, features/works/work_dates_edit.feature, features/works/work_edit.feature, features/works/work_related.feature
Resolves: https://otwarchive.atlassian.net/browse/AO3-4339
Deferred Cucumber tests (or pieces of them) refer to Google Code issue numbers, which don't correspond directly to their new JIRA issue number. I've gone through the cucumbers and replaced all the old numbers with new numbers.
=> AO3-4339 Make deferred cucumbers point to new JIRA issues

lib/css_cleaner.rb
https://otwarchive.atlassian.net/browse/AO3-2439
Was https://code.google.com/p/otwarchive/issues/detail?id=2442
When a user attempted to use a CSS selector like `.listbox > .heading`, it would get converted to `.listbox &gt; .heading`, which didn't work. This makes it so the `&gt;` in the selector gets converted back to a `>`. This may or may not be a terrible idea.
=> AO3-2439 Stop converting > to &gt; in skins

app/helpers/application_helper.rb, app/views/errors/403.html.erb, app/views/errors/404.html.erb, app/views/errors/422.html.erb, app/views/errors/500.html.erb, public/500.html, public/502.html, public/503.html, public/507.html, public/nomaintenance.html, public/stylesheets/site/2.0/05-region-main.css
https://otwarchive.atlassian.net/browse/AO3-4345
A line of text on our 404 pages was the wrong color in the Reversi skin due to some wonky HTML on the page. This corrects the HTML on that page and all the other dynamic error pages, and it also makes the error page markup the same for both the dynamic and static pages.
=> AO3-4345 Error page markup and styling corrections

lib/css_cleaner.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4340
Basically, we allow the `clip` property in skins, but don't currently allow the only useful value for it: `rect(top, right, bottom, left)`. We also allow the `transform` property, and the `rotate()` transformation, but not `rotatex(angle)` or `rotatey(angle)`, despite allowing `scalex()` and `scaley()` for the same property. Twas all very odd.
Obviously, this is a Very Important pull request.
=> AO3-4340 Allow sensible values for transform and clip CSS properties

app/controllers/fandoms_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4347
On a collection's Fandoms page, "Uncategorized Fandoms" was included in the select menu for browsing y category. However, the page was always empty. This removes the option from the menu.
=> AO3-4347 Remove Uncategorized Fandoms from category list in collection

app/controllers/collection_participants_controller.rb, app/controllers/collections_controller.rb, app/models/pseud.rb, app/models/work.rb, features/works/work_create.feature
Resolves: https://otwarchive.atlassian.net/browse/AO3-4344
Banned and Suspended users can no longer:
1) Be added to Collections as Participants
2) Be added to Works as Co-authors (suspended users were able to be added)
I have changed the error message to say that "{name} is currently banned and ..." This, in my opinion, covers both perm-banned and suspended users. We don't need to make that distinction to the public, and it saves lines of code having to be written.
=> AO3-4344 Banned and Suspended users cannot participate in Collections

app/views/tag_wranglings/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4337?jql=issuetype%20%3D%20Improvement
Updates the Wrangling Tools page for wranglers to lin to the new JIRA issue tracker, instead of the old gCode one.
=> AO3-4337 Update gCode link to JIRA link for Wrangling Tools page

app/controllers/comments_controller.rb, app/helpers/comments_helper.rb, app/views/comment_mailer/_comment_notification_footer.erb, app/views/comment_mailer/_comment_notification_footer.text.erb, app/views/comments/_comment_form.html.erb, app/views/comments/unreviewed.html.erb, features/comments_and_kudos/comment_moderation.feature
https://otwarchive.atlassian.net/browse/AO3-3543
1. If comments are moderated and you are not the work creator, the comment form will now have a message: "This work's creator has chosen to moderate comments on the work. Your comment will not appear until it has been by approved by the creator."
2. The emails will now say "Comments on this work are moderated and will not appear until approved by the work creator." This might need some fiddling, appearance-wise, because I couldn't test it on dev.
3. If anyone other than the work creator or an admin attempts to access the unreviewed comment page, they will be redirected to the log in page (if not logged in) or to the homepage (if logged in) with a message: "Sorry, you don't have permission to see that."
4. If anyone other than the work …
=> AO3-3543 Moderated comments tweaks

app/controllers/works_controller.rb, app/views/works/_standard_form.html.erb, app/views/works/edit_multiple.html.erb, app/views/works/show_multiple.html.erb, features/comments_and_kudos/comment_moderation.feature, features/step_definitions/comment_steps.rb, features/step_definitions/work_steps.rb, features/support/paths.rb, features/works/work_edit_multiple.feature
https://otwarchive.atlassian.net/browse/AO3-3543
1. After some discussion with Docs and Support, change phrasing on standard work form commenting options to "Disable anonymous commenting" and "Enable comment moderation."
2. Make it possible to select from three radio options for anonymous and moderated comments when mass editing works: 
Anonymous Commenting: 
Keep current anonymous comment settings
Enable anonymous comments
Disable anonymous comments
Comment Moderation:  
Keep current comment moderation settings
Enable comment moderation
Disable comment moderation
=> AO3-3543 Mass edit comment settings

app/controllers/home_controller.rb
AO3-4360: Don't generate counts for logged-in users on the front-page
The partial which uses the counts gets called here: https://github.com/otwcode/otwarchive/blob/master/app/views/home/index.html.erb#L2
and is only used if the user is not logged_in?.
https://otwarchive.atlassian.net/browse/AO3-4360
=> AO3-4360: Don't generate counts for logged-in users

public/help/fandom-help.html, public/help/tagging-help.html
Resolves: https://otwarchive.atlassian.net/browse/AO3-4320
Added links to the Tag FAQs on both fandom-help.html and tagging-help.html
Removed the old (and now redundant) link to FAQs from fandom-help.html
(Basically just a text change, and both pages looked okay to me on my webdev.)
=> AO3-4320 Add Tag FAQs link to Tagging Help and Fandom Help text

app/views/pseuds/_pseuds_form.html.erb
Issue: https://otwarchive.atlassian.net/browse/AO3-4141
Took out the incorrect limited HTML info, added the regular "Plain text with limitd HTML" notice.
(Code was copied from the _standard_form.html.erb code.)
Looks correct on my WebDev, not sure if other (automated) tests should have been performed.
=> AO3-4141 Edit Pseud form displays incorrectly limited HTML tags available for use in description

config/.rubocop.yml
Turns off warnings for trailing whitespace and ambiguous regexp literals that actually make step definitions more readable
=> stop hound complaining unhelpfully

app/models/pseud.rb, app/sweepers/pseud_sweeper.rb, config/.rubocop.yml, features/other_a/autocomplete.feature, features/step_definitions/.rubocop.yml, features/step_definitions/autocomplete_steps.rb, features/step_definitions/pseud_steps.rb, features/step_definitions/user_steps.rb
A fix for AO3-3720 and also AO3-3621 which was caused by the same issue. 
The issue was (1) the removal/addition wasn't being triggered at all because the condition check was looking for :name instead of "name" etc, and (2) the removal wasn't using the correct stale values for pseud/username, and (3) for username changes, the correct current value had to be reloaded from the database before adding.
With shiny tests, yay. 
=> Fixes AO3-3720, pseuds not updating in autocomplete

app/models/inbox_comment.rb, app/models/user.rb
Use a single query to determine which inbox comments have comments attached to them rather than looping through the comments, which is non-performant for users with large inboxes.
https://otwarchive.atlassian.net/browse/AO3-4380
=> AO3-4380: Improve speed of inbox comment query

app/views/users/confirmation.html.erb, features/other_a/invite_request.feature, features/step_definitions/invite_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4374
After you create an account, the page that you see -- http://archiveofourown.org/users -- has a sentence that says: "If you don't hear from us within 24 hours, and you don't find our email in your spam filter, please drop us a line at Support (http://archiveofourown.org/support)."
That should be a hyperlink, not a typed out URL.
It also has a link that says: "Return to archive front page"
That should be "Archive."
BONUS ROUND: Instead of hard coding in the number of days after which an unactivated account will be purged, now we use the value in the admin settings (times 7 because that field is for weeks even though it's named days /o\) and, if that's blank, the config file. \o/
SUPER BONUS ROUND: Wrapped the page content in `<div …
=> AO3-4374 Spiffy up account creation confirmation page

features/gift_exchanges/challenge_giftexchange.feature, lib/challenge_core.rb
Resolves issue: https://otwarchive.atlassian.net/browse/AO3-4358
The 'Sign-up Form' and 'Prompt Form' links were missing in both Gift Exchanges and Prompt Memes (respectively) when a collection was moderated. This PR:
* Removed the check from the code that looked to see if a collection was moderated (and if it was, if that user was already a posting participant). 
* Added a new Cucumber test to catch regression on this functionality in the future
=> AO3-4358 Sign-up Form / Prompt Form link missing in modded collections

app/controllers/gifts_controller.rb, app/models/gift.rb
AO3-3145: Fix validation for gifts and make rejection errors easier to spot
The validation preventing gifting the same work multiple times to the same user should not have been comparing the gift to itself. Not sure how any updates were getting past that.
https://otwarchive.atlassian.net/browse/AO3-3145
=> AO3-3145: Fix validation for gifts and make rejection errors easier to spot

config/deploy.rb
Without the -f the web servers will still run on the old files
=> remove existing destination files

spec/mailers/user_mailer_spec.rb
Will make Travis a little quieter/happier. Currently it gives a warning: 
```
An error occurred in an `after(:context)` hook.
NoMethodError: undefined method `destroy' for nil:NilClass
occurred at /home/travis/build/otwcode/otwarchive/spec/mailers/user_mailer_spec.rb:89:in `block (3 levels) in <top (required)>'
```
which will stop happening after this change.
=> AO3-4402 Fixing one of the warnings in our specs for user_mailer database cleanup

.travis.yml
This will mean that individual coders can set up Travis on their own fork, so they can see the Travis build and test results without needing to run them locally (taking ages) or make a pull request (clutters up the PR queue with things that aren't ready).
=> AO3-4403 Travis for new repos

.gitignore
Will only affect coders using vagrant or other machines with settings that dump things in stdout under normal use.
=> AO3-4410 Making git on vagrant easier to use

config/environments/development.rb, config/environments/staging.rb
Resolves: https://otwarchive.atlassian.net/browse/AO3-4413
Changes the Bullet configuration so that notifications go to a browser's Console instead of being appended to the webpage's footer.
=> AO3-4413 Move Bullet notices to browser console instead of footer

app/views/layouts/_includes.html.erb, features/other_b/skin.feature, features/step_definitions/skin_steps.rb, public/stylesheets/site/2.0/25-media-midsize.css, public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-4291
* Adds a test to make sure users see the proper media queries and can use them in their own skins
* Adds a version number to the skin caching we do for the page head
* Increases the padding on the homepage in the midsize view so it doesn't look like hell (and then returns the narrow view's padding to the usual)
=> AO3-4291 Media query test, skin caching fix, splash padding

Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4428
I think this is low risk i believe it is used to colour the rake output
=> AO3-4428 update ansi

public/javascripts/application.js, public/stylesheets/site/2.0/25-media-midsize.css
https://otwarchive.atlassian.net/browse/AO3-4453
To make it so the list of pseuds can wrap across lines, we need to change how the list items display, and we need to adjust the JavaScript so instead of using jQuery's `toggle()` to apply a `style` attribute of `display: inline;` or `display: block;` directly to the pseud menu, it will use whatever display style is in the CSS for the window's current width.
=> AO3-4453 Let dashboard pseud menu wrap

public/stylesheets/site/2.0/16-zone-system.css, public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-4350
Please forgive the low-priority pull request; this issue was making it very hard to do the BOT-SPR for #2304 (which this is branched from)
* Makes it so all the modules on the logged-out homepage are centered on narrow screens
* Centers the tweets within the tweet area logged in and out on all the screen sizes, praise the lord
* Centers the title/date/comments on the logged-in homepage news items on narrow screens
=> AO3-4350 Homepage off-center

features/importing/archivist.feature, features/prompt_memes_a/challenge_promptmeme_setup.feature, features/prompt_memes_b/challenge_promptmeme_posting_fills.feature, features/prompt_memes_c/challenge_promptmeme_claims.feature, features/step_definitions/invite_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4441
Improve the automated tests for importing, which currently don't cover several key features. Adds tests for getting a claim email when someone imports your work, responding to that email to claim your work, responding to orphan, and responding to delete and ask not to be contacted again.
It appears that responding to claim is not working entirely smoothly, needs further investigation later. In rough testing on Staging, I managed to get an error 500 by clicking the claim link, then logging out. The test fails when you try to claim, with error 500 about login not existing.
Also rearrange the prompt meme tests that keep failing on Travis so they're of more equal size and logically arranged. Plenty more to optimise there, but keeping them …
=> AO3-4441 Automated tests for importing and rearranging prompt memes

features/bookmarks/bookmark_privacy.feature, features/step_definitions/bookmark_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4467
There are some TODOs in the automated test for private bookmarks. We didn't test that private bookmarks don't show up on a tag's bookmark listing, and now we do. We didn't check the bookmark's count of how many times that work has been bookmarked, and now we do.
=> AO3-4467 Fixing TODOs on private bookmark tests

features/admins/admin_post_news.feature
https://otwarchive.atlassian.net/browse/AO3-4468
The automated tests for admins posting news posts and commenting on them had a TODO - fix it by adding a clearer comment. The test for this is already expanded in a separate pull req.
=> AO3-4468 Fixing TODOs on admin news post tests

.travis.yml
https://otwarchive.atlassian.net/browse/AO3-4479
Add travis_retry feature. This will retry any test that fails 3 times before giving final failure. This means it'll take slightly longer to get notified in the event of a genuine failure, as well as taking longer to execute when a shutdown happens and it has to retry, but seems to work for eliminating the bogus failures due to shutdown. The perfect solution would be for Travis to reply to my comment on the issue about the shutdowns, but this will reduce our pain.
=> AO3-4479 Adding retries to Travis tests

public/stylesheets/site/2.0/04-region-dashboard.css, public/stylesheets/site/2.0/25-media-midsize.css
https://otwarchive.atlassian.net/browse/AO3-4478
Drafts/Bookmarks/Private Bookmarks/External Works/Taggings Count appeared on separate lines instead of side by side. (Once I fixed that, the options in `<span>` also needed the vertical alignment adjusted, since the `<a>` options had middle alignment and the `<span>` ones did not.)
=> AO3-4478 Fix alignment on wrangling dash in midsize and narrow layout

public/stylesheets/site/2.0/16-zone-system.css
https://otwarchive.atlassian.net/browse/AO3-4477
`overflow: hidden` is a relic of homepages gone by and is causing the reply form on the inbox to get cut off in some circumstances. It should go bye-bye.
=> AO3-4477 Fix homepage inbox reply form being cut off

features/importing/work_import_da.feature
https://otwarchive.atlassian.net/browse/AO3-4476
Our automated test for import from DeviantArt wasn't actually being run at all, because it was tagged @wip. Make it a complete work.
=> AO3-4476 Improving DeviantArt importing test

app/controllers/api/v1/import_controller.rb, app/models/story_parser.rb, spec/api/api_spec.rb, spec/models/story_parser_spec.rb
When you try to get it to import a plain text file with the wrong encoding, the API returns a spurious Rails routes error which breaks anything on the client side that tries to parse it as Json.
This needs to be tested through the API as that is the only thing affected by the issue this fixes.
=> AO3-4483 Mass importer can't import works with the wrong encoding

Gemfile.lock, app/controllers/challenge_signups_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4449
=> AO3-4449 update will paginate

app/views/pseuds/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4408
The Manage Pseuds page was missing some landmarks, which was making the New Pseud button unclickable
=> AO3-4408 New pseud button unclickable on Android

app/views/gifts/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4492
Our landmarks, which also act as clears (sob) were missing from the gifts page, which was causing display issues with the Accepted and Refused options on mobile
=> AO3-4492 Add missing landmarks to user gifts page

app/mailers/user_mailer.rb, app/views/user_mailer/abuse_report.html.erb, app/views/user_mailer/abuse_report.text.erb, config/locales/en-US.yml, config/locales/en.yml
The confirmation mail after you send an abuse report should look the same after this, but new strings should appear in PhraseApp.
https://otwarchive.atlassian.net/browse/AO3-4417
https://otwarchive.atlassian.net/browse/AO3-4439
=> AO3-4439: making abuse report in user mailer translatable i18n

features/comments_and_kudos/add_comment.feature, features/comments_and_kudos/comments_pagination.feature, features/step_definitions/comment_steps.rb, features/step_definitions/work_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4475
Our automated test for comment pagination, threading and editing has some TODOs. Fix them.
The last test here is a pretty slow one, given that it needs a lot of comments, so I've also done my best to speed it up.
=> AO3-4475 Fix TODOs in comment test

app/models/story_parser.rb, features/importing/work_import_dw.feature, features/importing/work_import_lj.feature, features/step_definitions/preferences_steps.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4499
Given two chapter with different dates in their content, the date of the last chapter to be imported should become the revision date of the entire work.
=> AO3-4499 - Set imported date to the date of the last chapter

app/controllers/challenge_signups_controller.rb, app/views/challenge/gift_exchange/_challenge_signups.html.erb, app/views/challenge/prompt_meme/_challenge_signups.html.erb, features/gift_exchanges/challenge_giftexchange.feature
RELEASE NOTES: Challenge moderators can now search the signups for their challenge by pseud instead of having to manually find them in the alphabetic list, which can be very long for a large challenge.
https://code.google.com/p/otwarchive/issues/detail?id=2867
https://otwarchive.atlassian.net/browse/AO3-2864
Signups for a large gift exchange should now be searchable by pseud. Has tests.
Also fixes a tiny unclosed ul tag on the prompt meme signup.
Signed-off-by: shalott <shalott@gmail.com>
=> AO3-2864 Challenge signup search

app/views/challenge/gift_exchange/_challenge_signups.html.erb
https://otwarchive.atlassian.net/browse/AO3-2864
- Fix the weirdness with the Download CSV button style
- Make search results say "Sign-ups" or "Sign-up" instead of "Signups" or "Signup"
- Update syntax
- Remove `role="menu"` because it shouldn't be used the way we were using it
- Add the HTML comments we use to remind us how the page is structured
=> AO3-2864 Fix Download CSV style on gift exchange signups page

app/views/admin_posts/_admin_post.html.erb, app/views/admin_posts/index.html.erb, app/views/admin_posts/show.html.erb, features/admins/admin_post_news.feature, features/step_definitions/admin_steps.rb, public/stylesheets/site/2.0/12-group-meta.css
https://otwarchive.atlassian.net/browse/AO3-4535
This rearranges the published, translation, and tag information on news posts into the proper dl.meta pattern at the top of the news post so we can have translation languages displayed as a compact comma-separated list rather than a ginormous vertical list of languages and titles. It also adds some styling so the dl.meta isn't a big box.
=> AO3-4535 Make admin post translation list shorter

app/views/admin_posts/_admin_post.html.erb
https://otwarchive.atlassian.net/browse/AO3-4123
Per a discussion with Translation chair Priscilla, this sorts the translations by the language's short name, so the order should match the order of languages in the "Language" filter menu at the top of the news post index
Longterm, Translation would prefer to be able to set a name for sorting, the same way Tag Wranglers do with fandoms
=> AO3-4123 Sort admin post translations by languages' short names

app/views/home/_news_module.html.erb
https://otwarchive.atlassian.net/browse/AO3-4522
This applies the concept on https://www.w3.org/TR/WCAG20-TECHS/ARIA7.html. Alas, we must hash rocket our ARIA roles.
=> AO3-4522 More accessible "Read more" links on homepage

app/controllers/admin/blacklisted_emails_controller.rb, app/models/admin_blacklisted_email.rb, app/models/comment.rb, app/validators/email_blacklist_validator.rb, app/validators/email_veracity_validator.rb, app/views/admin/_header.html.erb, app/views/admin/blacklisted_emails/index.html.erb, app/views/invite_requests/index.html.erb, config/locales/en-US.yml, config/locales/en.yml, config/routes.rb, db/migrate/20160331005706_create_admin_blacklisted_emails.rb, factories/admin_blacklisted_email.rb, features/admins/admin_email_blacklist.feature, features/step_definitions/admin_steps.rb, features/step_definitions/comment_steps.rb, features/step_definitions/work_steps.rb, features/support/factories.rb, features/support/paths.rb, public/stylesheets/site/2.0/07-interactions.css, spec/models/admin_blacklisted_email_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4536
Allows blacklisting of emails so they can't be used to post guest/anonymous comments.
See https://github.com/otwcode/otwarchive/pull/2410 for discussion and review comments
=> AO3-4536 guest email blacklist clean

app/views/feedbacks/report.xml.erb
Resolves a problem with: https://otwarchive.atlassian.net/browse/AO3-4532
Updating the subject line that is sent to the new Support tracker to include "[AO3] - Support" before the subject proper.
=> AO3-4532 Change subject line sent to Support Site

app/models/feedback_reporters/feedback_reporter.rb, app/views/feedbacks/report.xml.erb
Resolves problems with: https://otwarchive.atlassian.net/browse/AO3-4532
Encode the URL sent to the Support Ticket site so that it is percent-encoded.
*  https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters
=> AO3-4532 Allowing for the use of Diacritics and special characters in Support Form

app/helpers/works_helper.rb, app/models/bookmark.rb, app/models/work.rb, app/views/works/_work_module.html.erb, lib/bookmark_count_caching.rb
https://otwarchive.atlassian.net/browse/AO3-4495
Reverts otwcode/otwarchive#2454
=> AO3-4495 Cache the bookmark counts

app/controllers/collection_items_controller.rb, app/helpers/users_helper.rb, app/mailers/user_mailer.rb, app/models/collection_item.rb, app/views/collection_items/index.html.erb, app/views/comments/_commentable.html.erb, app/views/preferences/index.html.erb, app/views/user_mailer/added_to_collection_notification.html.erb, app/views/user_mailer/added_to_collection_notification.text.erb, app/views/user_mailer/invited_to_collection_notification.html.erb, app/views/user_mailer/invited_to_collection_notification.text.erb, features/bookmarks/bookmark_create.feature, features/collections/collectible.feature, features/collections/collection_invite.feature, features/other_a/preferences_edit.feature, features/step_definitions/collection_steps.rb, lib/collectible.rb, public/help/collection-preferences.html
https://otwarchive.atlassian.net/browse/AO3-2665
Reverts otwcode/otwarchive#2455
=> AO3-2665 Allow collection owners/mods to add/invite works to their collections

app/helpers/application_helper.rb
https://otwarchive.atlassian.net/projects/AO3/issues/AO3-4500
https://otw.16bugs.com/projects/4911/bugs/359269
=> AO3-4500 Sometimes ec.external_author_name can be nil

public/stylesheets/site/2.0/09-roles-states.css
https://otwarchive.atlassian.net/browse/AO3-4523
Both the Expand and Collapse options were showing on the fandoms list. We only want the one that applies to show.
=> AO3-4523 Fix collapse/expand fandoms link on dashboard

app/controllers/admin/banners_controller.rb, app/views/admin/banners/_banner_form.html.erb, features/other_a/banner_general.feature, features/step_definitions/banner_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4547
We want to make it so admins can fix typos or update fundraising totals in admin banners without turning the banner back on instead of having to ask poor james to do it from the console.
=> AO3-4547 Allow banner updates WITHOUT turning banner back on

app/controllers/tag_wranglers_controller.rb, features/step_definitions/tag_set_steps.rb, features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-4581
=> AO3 4581 cache the counts in the wrangling sidebar.

app/views/admin/_admin_options.html.erb, app/views/works/preview_tags.html.erb, features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-3597
- Admins can now edit a work's language when using Preview rather than Post Without Preview
- The button now says "Edit Tags and Language" because Language is not a tag and it was annoying me
=> AO3-3597 Fix editing work language on preview, rename admin option

app/views/works/edit_tags.html.erb, app/views/works/preview_tags.html.erb, features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-3597
* Only includes the invisible language field on the preview page for admins
* Updates a few page headings to say tags and language when you're an admin
=> AO3-3597 Only include language field on tag preview page for admins

app/models/potential_match.rb, factories/challenges.rb, spec/models/potential_match_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4128
The progress report was NOT fixed. I've reworked the way it was being done, and also added tests. Now hopefully working for reals. Tests running clean. 
=> AO3-4128-more thorough progress fix

app/controllers/user_invite_requests_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4573
=> AO3-4573 Text and link change for Request Invite for Friends page

app/models/chapter.rb
https://otwarchive.atlassian.net/browse/AO3-4514
Trigger cache invalidation when a draft chapter is posted
=> AO3-4514: Fix chapter count cache when draft is first posted

app/views/pseuds/_pseuds_form.html.erb, app/views/users/change_username.html.erb, features/other_a/pseuds.feature, features/users/user_rename.feature, public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-4578
=> AO3-4578 Change "fallback pseud" phrase on edit pseud page

app/controllers/devmode_controller.rb, lib/html_cleaner.rb
https://otwarchive.atlassian.net/browse/AO3-4567
These are minor fixes pointed out by the ruby upgrades
=> AO3-4567 Minor fixes for ruby upgrades

config/deploy/production.rb
https://otwarchive.atlassian.net/browse/AO3-4611
=> AO3-4611 Add new servers

public/stylesheets/site/2.0/02-elements.css, public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-4614
Some Android users were seeing a very light font on work summaries and various other place. Turns out there was a good reason for that: we were setting the font weight on blockquotes to 100, aka the thinnest possible.
Why this problem was only happening for some people, and only started now given this code was four and a half years old, I don't know. But it shouldn't happen for them now.
=> AO3-4614 Fix light font on Android

app/models/creation_observer.rb, features/other_a/gift.feature, features/step_definitions/preferences_steps.rb
https://otwarchive.atlassian.net/browse/AO3-3947
I added a check to CreationObserver so that it won't trigger the UserMailer's recipient_notification if the user has gift notifications turned off in their preferences. I also created three cucumber scenarios to test recipient notifications (corresponding to the three laid out in the description of issue AO3-3947).
(I hope this is okay! I tried to follow the guidelines in the wiki, but I've never tried to contribute code to an open-source project before.)
=> Fix for issue AO3-3947, with cucumber scenarios to test

app/models/admin_setting.rb, lib/skin_cache_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4466
=> AO3-4466 Reduce the one call to skins per page

app/models/admin_setting.rb, lib/skin_cache_helper.rb
Reverts otwcode/otwarchive#2332
=> Revert "AO3-4466 Reduce the one call to skins per page"

app/views/user_mailer/signup_notification.html.erb, app/views/user_mailer/signup_notification.text.erb, features/other_a/invite_queue.feature, features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4615
* Change `Please activate your account at: <a href="http://archiveofourown.org/activate/HOLYKEYSMASHOFLETTERSANDNUMBERSBATMAN">http://archiveofourown.org/activate/HOLYKEYSMASHOFLETTERSANDNUMBERSBATMAN</a>.` to `Please <a href="http://archiveofourown.org/activate/HOLYKEYSMASHOFLETTERSANDNUMBERSBATMAN">activate your account</a>.`
* Change "authors" to "creators"
=> AO3-4615 Exposed URL breaks confirmation email layout

public/stylesheets/site/2.0/03-region-header.css, public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-4597
Changes addressing the header misalignment, chapter edit button misalignment, and whitespace in secondary menus that occurred when implementing the button spacing.
=> AO3-4597 No vertical space separating rows of buttons

app/models/story_parser.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4628
This fixes a problem which occurs when importing a work (both manually or automatically) whose metadata contains non-ASCII characters. When these tags reach the Sanitise gem without specifying an encoding, it bombs out because it expects pure ASCII or UTF-8, but gets something it thinks is ASCII but actually contains Unicode characters.
I also add tests which reproduce the problem if you remove the UTF-8 encoding on the string passed to Sanitise.
This is a blocker for the ongoing Ink Stained Fingers import that is just waiting for the works with this problem to be imported.
=> AO3-4628 Incompatible character encodings: ASCII-8BIT and UTF-8

app/models/collection.rb, app/models/collection_item.rb, app/models/creation_observer.rb, features/collections/collection_anonymity.feature
https://otwarchive.atlassian.net/browse/AO3-4108
https://otwarchive.atlassian.net/browse/AO3-4367
Attempts to fix AO3-4108 (and AO3-4367) by removing the code for author reveals from the CollectionItem and Collection objects, and rewriting a similar system within CreationObserver's before_update function.
The bug AO3-4108, where works in two anon collections send out author subscription emails when only one collection does author reveals, meant that CollectionItem's notify_of_author_reveal needed to be able to check whether the item was in another anonymous collection (i.e. whether it would still be anonymous after the author reveal). In other words, when queuing up author subscription emails, it would be really nice to access the *new* value of item.in_anon_collection (the value that …
=> AO3-4108 (& AO3-4367) - Fix some problems with subscriptions and anonymous or unrevealed collections.

app/helpers/works_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4397
Reverts otwcode/otwarchive#2370
Put back in the list as it was not deployed
=> AO3 4397 Remove n+1 error in list of reciepients

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Fixes https://otwarchive.atlassian.net/browse/AO3-4619
Add templates to discourage issues and standardise pull requests, and CONTRIBUTING document so our Github repo looks like other Open Source repos.
See notes on [AO3-4619](https://otwarchive.atlassian.net/browse/AO3-4619)
Discussed briefly in chat.
What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](http://archiveofourown.org/admin_posts?tag=1)?
Ariana
What pronouns do you prefer (she/her, he/him, zie/hir etc)?
she/her
=> AO3-4619 - Add Github documentation and templates

app/models/prompt.rb
https://otwarchive.atlassian.net/browse/AO3-4273
Stop telling people to tell their challenge mods to contact Support about adding new canonical tags for challenges.
Refer to JIRA issue
=> AO3-4273 Don't tell mods to contact Support re challenge tags

app/models/prompt.rb
https://otwarchive.atlassian.net/browse/AO3-4273
Changes "by" to "through" in the error message for when you try to sign up using a non-canonical tag in a challenge that doesn't have a tag set
Refer to JIRA issue
mumble and me in the committee room
=> AO3-4273 Change preposition in a prompt error msg

db/structure.sql
This is just housekeeping and not worth an issue: structure.sql is automatically generated anytime you run db:migrate but should be checked in and kept up to date. (http://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumps-and-source-control)
Nothing has changed at all except this file is now up to date in the repository where before it wasn't. It could be tested on a dev environment by checking out the master branch and running `bundle exec rake db:migrate` and making sure that structure.sql does NOT change.
=> AO3-4648 tiny cleanup: checking in updated structure.sql

app/views/works/new_import.html.erb
https://otwarchive.atlassian.net/browse/AO3-4558
The "Import FAQ" link on the Post > Import Work page was broken, leading to a 500 error.
Clicking on the link in "You might find the Import FAQ useful." should lead to the importing section of the posting FAQ.
Additionally, the note above, saying "If you have trouble importing from another site, please let us know so we can improve this tool!" has been removed as this is no longer something we want to do.
=> AO3-4558 - Fix import FAQ link

Gemfile, Gemfile.lock, app/models/tag.rb
https://otwarchive.atlassian.net/browse/AO3-4641
Right now we have a number of failed jobs becuase the async job is running before the data is saved in mysql
I am afraid this one can't be tested as fixing anything as the failure will only occur when we have fast resque workers and test does not have that.
=> AO3-4641 Make it more likely new works will clear the Tag cache

app/models/abuse_report.rb, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4651
The check to make sure a work hadn't been reported to Abuse more than 5 times was broken. This fixes it and adds a test.
It's currently hot fixed on production.
Attempt to report a work to Abuse 6 times. The 6th time should fail.
=> AO3-4651 Abuse reports should only accept 5 reports per work

features/other_b/skin.feature
https://otwarchive.atlassian.net/browse/AO3-4616
The updated_at field only has resolution down to the second, not the millisecond, so if two updates to the same skin are performed within the same second, the cache key used to access the cached version of the data won't change between updates. But in order to ensure that caching always has the most recent version of the data, the cache key has to change whenever the underlying data changes.
This pull request adds a small delay to two of the automated skins tests, in an attempt to ensure that the cache key has changed when the data changes. This is a stopgap measure that will hopefully stop the intermittent Travis skin test failures until the larger caching problem is handled (likely by updating Rails).
This is an update to the automated …
=> AO3-4616 Add delays for the skin tests.

app/views/layouts/mailer.html.erb, app/views/layouts/mailer.text.erb, features/other_b/support.feature, features/step_definitions/email_custom_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4343
Stops displaying the words `sent_at` in the Support automated response email and instead starts displaying the date.
This should fix it everywhere it was happening, not just the Support automated response, because the problem was the mailer layout that we use for all the user mailers. So it probably also fixes https://otwarchive.atlassian.net/browse/AO3-4657
=> AO3-4343 Support emails say "sent_at" in footer

app/views/user_mailer/challenge_assignment_notification.html.erb, app/views/user_mailer/challenge_assignment_notification.text.erb, features/gift_exchanges/challenge_giftexchange.feature, features/step_definitions/challenge_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4652
https://otwarchive.atlassian.net/browse/AO3-4654
https://otwarchive.atlassian.net/browse/AO3-4656
AO3-4652: When you receive an assignment email in a gift exchange, it says "Rating: Choose Not To Use Archive Warnings" if (a) your recipient did not select a rating or (b) the challenge does not use rating tags. This makes it so "Rating:" is only included if the recipient specifies.
AO3-4654: All of the fields the requester explicitly set to "Any" should be listed in the email, like they are on the sign-up you can access by going through your dashboard.
AO3-4656: The link to your Assignments page should say "Assignments page" rather than "archive dashboard."
Refer to JIRA.
=> AO3-4652 AO3-4654 AO3-4656 Assignment email fixes

app/views/challenge/shared/_challenge_requests.html.erb, app/views/challenge_claims/_user_index.html.erb, app/views/challenge_signups/_show_offers.html.erb, app/views/challenge_signups/_show_requests.html.erb, app/views/prompts/_prompt_blurb.html.erb, app/views/prompts/show.html.erb, public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-4655
Fixes the alignment of the optional tags in challenge sign up prompt blurbs. (I moved the prompt class to the index that contains the prompts, not the prompts themselves, to bring it in line with the rest of the site -- we want to be able to do `.prompt .blurb` to style things, not `.prompt` and pray it's only a blurb.)
=> AO3-4655 Fix optional tag display on prompts

features/gift_exchanges/potential_matches.feature
https://otwarchive.atlassian.net/browse/AO3-4635
This adds a new automated test for the new potential match generation code, verifying that the correct set of potential matches is generated when signups have no tags, and matching is unconstrained.
It's a new automated test, so as long as it passes, I don't know that testing is necessary.
=> AO3-4635 Potential Match generation test for no tags, unconstrained matching.

app/views/comments/_comment_thread.html.erb, features/comments_and_kudos/comments_delete.feature, features/step_definitions/comment_steps.rb
https://otwarchive.atlassian.net/browse/AO3-1654
When a work has a comment thread that is very deeply nested, the thread doesn't display the most deeply-nested comments when you view the work -- instead, it displays the text `(%{count} more comments in this thread)`, and you can click on the `Thread` link for the parent comment to view the hidden comments. When all comments visible on the work's comments page are deleted, however, there are no `Thread` links to click on, so the deeply nested comments become inaccessible to anyone without a direct link.
As suggested in the bug report, this pull request makes the `%{count} more comments in this thread` text a link, making the nested comments accessible again.
The bug report has some steps that can be used for testing.
One thing to keep in …
=> AO3-1654 Make "n more comments in this thread" a link.

app/models/tag.rb, features/tags_and_wrangling/tag_wrangling_special.feature
https://otwarchive.atlassian.net/browse/AO3-3213
Given a tag `A a.k.a. B`, the system for generating URLs turns that into `A a*d*k*d*a*d* B`. When that kind of tag name is passed to Tag.find_by_name, it first replaces all substrings `*s*` with `/`, then `*a*` with `&`, then `*d*` with `.`, etc. So when processing `A a*d*k*d*a*d* B`, it would first replace the `*a*` sequence in the middle to make `A a*d*k*d&d* B`, and then would replace the `*d*` sequence in the middle to make `A a.k*d&d* B`. So it would be incapable of looking up the tag that the user wanted.
This changes the substitution code to use a single substitution with a regex, so that it will go through the tag name from left to right, replacing each escape sequence with the appropriate character as it goes.
I also added a couple …
=> AO3-3213 Fix tag unescaping for things like "a.k.a."

app/views/home/first_login_help.html.erb, features/other_a/banner_login.feature, features/step_definitions/banner_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4375
Updates the Tips & Tricks first login help banner to: https://docs.google.com/document/d/1qIIM4GUFJl7Su8h21oBgUMVR6tn0PbCZw7hLfOYWUtI
Also removes the dismiss button that was in the popup, 'cause that was weird and ugly and not worth making less ugly given it already exists on the banner.
=> AO3-4375 Update tips and tricks page

app/controllers/api/v1/import_controller.rb, config/routes.rb, spec/api/api_authorization_spec.rb, spec/api/api_works_spec.rb, spec/models/cache_master_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4662
Removes an old API controller which is no longer used for automated imports.
If the automated tests pass, this is working.
=> AO3-4662 - Remove the /api/v1/import route

app/mailers/user_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-4643
This checks that we have a subscription before trying to use it to send notifications
subscribe to a work.
update the work.
delete the subscription
After the notification would have been delivered go in to resque interface and see if you can find an error like:
Worker
ao3-app08:862 on MAILER at about 2 hours ago Retry or Remove
Class
UserMailer
Arguments
"batch_subscription_notification"
"62205766"
"[\"Chapter_18569068\"]"
Exception
ActiveRecord::RecordNotFound
Error
Couldn't find Subscription with id=62205766
=> AO3-4643 Deleting a subscription will leave an error in resque

app/controllers/admin/admin_users_controller.rb, features/admins/admin_manage_users.feature, features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4670
This extends the test suite and removes the controller action which allowed an admin to delete a users account which was not available in the user interface.
=> AO3-4670 Extend test suite to cover admin activating users accounts

features/admins/admin_languages.feature
https://otwarchive.atlassian.net/browse/AO3-4672
Test that an admin 
- can add a language
- control which languages appear on the support form
Tweaked the abuse language test to make sure _only_ the languages with "Abuse support available" set are included in the abuse form, since james_ pointed out it would be a good idea to check exclusion as well as inclusion.
=> AO3-4672 Admin language tests

features/gift_exchanges/challenge_giftexchange.feature, features/step_definitions/challege_gift_exchange_steps.rb, features/step_definitions/challenge_steps.rb, features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-4688
Tests that sign-ups and assignments are deleted when a gift exchange is deleted, and also ensures that the sign-up and assignment pages of exchange participants are still accessible after the exchange is deleted. 
These tests show https://otwarchive.atlassian.net/browse/AO3-3994 ("Deleting the gift exchange from a collection causes the Signups pages of participants to give Error 500") is fixed.
Commit 57fcbba contains the new tests; commit e381210 contains a bit of refactoring so we're not repeating ourselves so much when we just want to assume an exchange's assignments have been sent. Commit 86dc39a lets us delete a challenge without the going through the interface, since going to the settings page and clicking the button is already tested …
=> AO3-4688 Test gift exchange deletion

spec/sweepers/collection_sweeper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4711
This PR adds test coverage to the case where a 'record' (in this case a Work) sent to the 'get_collections_from_record' method of the collection_sweeper.rb file doesn't have any associated Collections. It should return an empty array. Tests now ensure that it does. 
No testing on behalf of QA is needed. Just confirm that our code coverage tools show that line # 41 in app/sweepers/collection_sweeper.rb is now covered.
=> AO3-4711 Improve coverage of CollectionSweeper

app/controllers/autocomplete_controller.rb
- [X ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
https://otwarchive.atlassian.net/browse/AO3-4686
Changes autocomplete results for potential matches to be sorted by quality. 
Go to potential matching page and go to either No Recipients or No Givers tab
Click in the empty text field and wait for the potential matches to pop up
Look at the signups of the first and last potential matches and compare to the person being matched
Match quality is ranked by:
number of prompts that match
highest number of tags that match among the prompts
So you should expect to see the first potential match (at least for someone with a lot of options) be a person who has two prompts that match, or at least more tags that match. …
=> AO3-4686 Sort potential matches by quality in autocomplete

app/controllers/api/v1/works_controller.rb, app/controllers/works_controller.rb, app/models/story_parser.rb, app/views/works/new_import.html.erb, features/importing/work_import.feature, features/importing/work_import_dw.feature, features/importing/work_import_lj.feature, features/other_b/subscriptions_fandoms.feature, features/step_definitions/tag_steps.rb, features/step_definitions/work_import_steps.rb, features/support/webmock.rb, features/works/work_create.feature, features/works/work_delete.feature, public/javascripts/application.js, public/stylesheets/site/2.0/07-interactions.css, spec/api/api_helper.rb, spec/api/api_works_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4636
Currently, the importer always detects tags in the content of the stories it imports and adds those tags to the imported work. This sometimes leads to rubbish tags (e.g.: "Warnings: fluffy bunnies") and in some cases where it detects text that isn't a valid tag, breaks the import. The `Override...` checkbox on the import form (and its API equivalent) only allows you to override tags if you provide some other content, but not to ignore detected tags completely.
This PR adds a `detect_tags` option in addition to the existing `override_tags`, to prevent all tags from being detected at all when some tags are overridden.
See Jira for testing notes
=> AO3-4636 turn off tag detection

app/mailers/user_mailer.rb, features/collections/collection_anonymity.feature
_(Is there anything I need to update the JIRA issue with?)_
https://otwarchive.atlassian.net/browse/AO3-3380
Before queuing up a subscription notification, the CreationObserver checks whether the work in question is anonymous (to make sure that subscription notifications won't inadvertently reveal anonymous authors). However, those checks only work if you post directly to an anonymous collection, so that the work has always been anonymous. It doesn't cover cases where someone accidentally forgets to add the collection when they first post the work, and then immediately adds it to the correct collection before batch subscription emails are sent.
This pull request adds an extra check to the UserMailer, to ensure that the work didn't suddenly become anonymous between the time the …
=> AO3-3380 Handle when a work becomes anonymous after queuing subscriptions, but before sending subscriptions.

app/helpers/application_helper.rb, features/importing/archivist.feature, features/step_definitions/archivist_steps.rb, features/step_definitions/user_steps.rb, features/support/user.rb
https://otwarchive.atlassian.net/browse/AO3-4692
Fixes a bug which caused only one external author created by an archivist to be displayed on imported works.
This also removes duplication in the byline code.
- check that existing stories have the same byline they normally have (including Anonymous)
- check that importing a work as an archivist with an author and co-author who do not have accounts on the Archive displays both authors in the format `name1 [archived by archivist], name2 [archived by archivist]`
=> AO3-4692 multiple external byline

app/models/external_author.rb, app/models/work.rb, features/importing/archivist.feature, features/step_definitions/archivist_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4692
Initial testing on my fix for AO3-4692 revealed that claiming a work (including automatic claiming when one author on an imported work already has an AO3 account) removes all other external authors from a work. This pull request fixes that issue.
See the issue for testing notes.
Note: this is currently broken on Test.
=> AO3-4692 - Preserve external authors when one author is claimed

app/models/external_author.rb, features/importing/archivist.feature
https://otwarchive.atlassian.net/browse/AO3-4692
If all the external authors on a work have claimed their accounts, the archivist account that created them is lingering pointlessly. This removes it at that point.
=> AO3-4692 - Remove archivist when all authors have been claimed

public/stylesheets/site/2.0/21-userstuff.css, public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-4474
small issue, but the fix suggested in the description works like a charm... i added
`
padding: 0 0.25em;
`
to **#worskin** in **21-userstuff.css** and tested it in safari, chrome, firefox and opera. i tried resizing the window and zooming in and out to see if any misalignment issues or clipping would occur but it seemed just fine 👍 i clicked around on various documentation pages and user pages to see if the tweak caused any unexpected spacing issues, but again, everything looked ship shape. 
0.25em was more than enough space to fix the problem, since it was only clipping long letters like t and f and l. could someone else also check it out in their own browser to make sure the extra padding doesn't cause any unexpected spacing issues?
=> AO3-4474 italicised/justified text being clipped

app/models/pseud.rb, features/other_a/pseud_delete.feature
https://otwarchive.atlassian.net/browse/AO3-3686
When deleting a pseud, the pseud's challenge signups and challenge assignments are transferred to the user's default pseud, but the existing code doesn't update the `pseud_id` associated with any of the pseud's prompts. The pseud has a `:dependent => :destroy` relationship with any prompts that belong to the pseud, so when `pseud.destroy` is called, the prompts (but not the signups associated with those prompts) are deleted. This results in blank, invalid signups.
This pull request modifies the pseud deletion code to update each prompt's `pseud_id`, and keep the prompts from being destroyed. I also wrote some cucumber tests to check whether the prompts stuck around after the pseud was deleted.
(As a side note: Prompts aren't indexed by …
=> AO3-3686 Keep prompts when deleting a pseud.

public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-4232
makes the "if you accept cookies from our site and you choose proceed..." note sit beneath the proceed and go back buttons on all screen sizes.
(second pull request; first one couldn't be altered) 😞
=> AO3-4232 "If you accept cookies from our site" note floats oddly on wide screens (PR2)

app/models/user.rb, features/admins/users/admin_find_users.feature, features/step_definitions/archivist_steps.rb, features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4721
Enabled admins to search for users by a partial email address.
Log in as an admin, go to the Find Users page and search for, for example, "gmail". Currently, this will only return users whose pseud includes "gmail". Now, it will also return users who email address includes "gmail".
This includes style changes. Review commit aa0e949 for the actual functionality changes
=> AO3-4721 - Perform partial match by email in admin user search

features/step_definitions/work_steps.rb, features/works/work_search.feature, spec/controllers/works_controller_spec.rb, spec/support/login_macros.rb
https://otwarchive.atlassian.net/browse/AO3-4719
This just refactors the works searching, there will be another pull along in a bit to actually add coverage.
No manual testing
=> AO3-4719 Refactor work search tests

features/comments_and_kudos/add_comment.feature
https://otwarchive.atlassian.net/browse/AO3-4769
Removes a TODO and tests more stuff. I've had this running on Travis for quite a while with no failures, so presume the previous flakiness was fixed.
None required
Cesy, she
=> AO3-4769 Removing a TODO in tests

spec/controllers/profile_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4785
Fix tests for profile_controller to get 100% coverage.
run `bundle exec rspec spec/controllers/profile_controller_spec.rb`
cresenne, she/her
=> AO3-4785 fix test where user's profile wasn't being destroyed properly

factories/related_works.rb, spec/controllers/related_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4707
Increases coverage of the related works controller. The redirect code `redirect_back_or_default(some_path)` is really old, so the best I could do for now is just check that it _does_ redirect, but not to where. It's better than nothing? (I'm going to update the last redirect in the fix for https://otwarchive.atlassian.net/browse/AO3-2151 and the new code will have the same behavior, but be properly testable. I could update the other redirects, too, if people want.)
There are two pending bits I couldn't figure out, but I left them because maybe someone can finish them off.
=> AO3-4707 Add some specs for related works

app/controllers/works_controller.rb, features/users/user_dashboard.feature
https://otwarchive.atlassian.net/browse/AO3-4795
Fix the filtering in a user dashboard ( and hopefully in a collection )
When viewing filtered results for a user or collection, and then sorting, the filter is removed.
Example:
Go to a user's dashboard and click on one of their fandoms. This shows you the filtered list of the works they have created in that fandom. The title of the page will for example be "1-3 works by ariana_paris in Testing".
In the right-hand Sort and filter bar, select a sort order (for example, "word count"), then click on the Sort and filter button.
Instead of getting the same 3 works, sorted by word count, you see the list of all the user's works sorted by word count. The Fandom filtering is gone.
=> AO3-4795 filtering by fandom in dashboard is broken

app/controllers/collection_participants_controller.rb, spec/controllers/admin/api_controller_spec.rb, spec/controllers/collection_participants_controller_spec.rb, spec/controllers/works_controller_spec.rb, spec/support/redirect_expectation_helper.rb
Notes:
* The collection lookup in load_participant_and_collection using collection.find raises an ActiveRecord error if the collection isn't found; since there is a case handling this I assumed it wasn't the desired behavior, so I changed it to .where(id: the_id).first which will return nil if the collection isn't found. Then the handling works as expected.
* The participant.approve_membership! did not previously appear to work as written.
https://otwarchive.atlassian.net/browse/AO3-4771
Rspec tests for the collection_participants_controller with small tweaks to the controller so functionality works as expected.
There are two minor changes: 
* When updating participants, when changing a participant from invited to member, it should now work
* When a participant is deleted between when the …
=> AO3-4771 Tests for the collection_participants_controller.

app/controllers/favorite_tags_controller.rb, app/models/favorite_tag.rb
https://otwarchive.atlassian.net/browse/AO3-4799
Adds mass assignment protection to favorite tags.
Refer to JIRA.
There's some discussion on the JIRA ticket about whether or not we need this.
=> AO3-4799 Strong parameters for favorite tags

app/controllers/works_controller.rb, spec/controllers/works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4549
It is possible to edit an existing work and save it without a fandom (see [AO3-4808](https://otwarchive.atlassian.net/browse/AO3-4808)). When this happens and the work's cached blurb expires, trying to view the work results in a 500 error because the code that generates the page title assumes there is always a fandom. 
1. edit an existing work to remove the fandom
2. get someone with database admin rights to kill the Rails cache
3. check that the work is still accessible, does not have a fandom in the blurb and that the page title says "No fandom specified" where it would normally have the fandom.
The underlying cause of works being saved without a fandom will be addressed in [AO3-4808](https://otwarchive.atlassian.net/browse/AO3-4808).
=> AO3-4549 - Stop page title creation from causing a 500 error when fandom is empty

app/helpers/series_helper.rb, lib/skin_wizard.rb, public/stylesheets/site/2.0/10-types-groups.css
https://otwarchive.atlassian.net/browse/AO3-4839
Adds a little circle to the series navigation on works so it's easier to read; refer to issue for example. It's not exactly BOT, but it's BOT-Concern-ish and we want it in this deploy.
Refer to issue.
=> AO3-4839 Add dividers to series navigation on works

Gemfile.lock, app/mailers/README, app/mailers/comment_mailer.rb, app/models/comment_observer.rb, config/initializers/resque_mailer.rb, spec/mailers/comment_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4644
Reduce the number of errors in resque so we can see any real problems
I suspect this needs the resque queues to be full to allow either the original comment or the parent to be deleted. We could simulate it by stopping the workers.
An example error looks like:
Worker
ao3-app03:12932 on MAILER at about 2 hours ago Retry or Remove
Class
CommentMailer
Arguments
"comment_reply_notification"
77000005
77033890
Exception
ActiveRecord::RecordNotFound
Error
Couldn't find Comment with id=77033890
=> AO3-4644 ensure comments are delivered.

app/controllers/admin/blacklisted_emails_controller.rb, app/models/admin_blacklisted_email.rb
https://otwarchive.atlassian.net/browse/AO3-4817
=> AO3-4817 AdminBlacklistedEmail Strong Parameters

app/controllers/admin/admin_users_controller.rb, app/controllers/challenge_signups_controller.rb, app/helpers/exports_helper.rb, app/models/user.rb, app/views/admin/_header.html.erb, app/views/admin/admin_users/_user_table.html.erb, app/views/admin/admin_users/bulk_search.html.erb, config/routes.rb, features/admins/users/admin_find_users.feature, features/admins/users/admin_manage_users.feature, features/gift_exchanges/challenge_giftexchange.feature, features/prompt_memes_c/challenge_promptmeme_claims.feature, features/step_definitions/web_steps.rb, features/support/paths.rb, spec/helpers/exports_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4716
Open Doors need to know if authors in external archives they are processing already have Archive accounts. This feature adds a new Bulk Email Search form in the Admin section which allows you to paste in a list of emails and then view which ones are associated with Archive users, and download the results as a CSV file.
The **Bulk Email Search** feature is a new entry in Admin section > **Manage Users**. When you paste a list of line-break separated email addresses into the form and press **Find**, you should see:
- a plain comma-separated list of email addresses that weren't found
- a paginated table of user accounts for all the email addresses on the list that were found (this is the same table that appears when doing a normal search by …
=> AO3-4716 Add bulk email search feature in admin section

app/models/chapter.rb, app/models/work.rb, features/importing/work_import.feature, features/step_definitions/work_import_steps.rb, features/works/work_edit.feature, lib/work_chapter_count_caching.rb
https://otwarchive.atlassian.net/browse/AO3-4827
We recently noticed that multi chapter imports had a word count that only included the first chapter when imported without preview. Any action that resaves the work after initial posting corrects the word count, but this isn't something Open Doors want to have to do for automated imports. This pull request fixes that situation by adding up all the word counts for all the chapters on a work when it is first posted.
See the Jira ticket
=> AO3-4827 Count the contents of all chapters when creating a work

app/controllers/user_invite_requests_controller.rb, app/helpers/mailer_helper.rb, app/views/user_mailer/admin_deleted_work_notification.text.erb, config/locales/en.yml
https://otwarchive.atlassian.net/browse/AO3-4306
https://otwarchive.atlassian.net/browse/AO3-4849
Change the subject line of the email to have a lower case a in admin.
Replace the old opendoors contact page with the new one.
Check the email
=> AO3-4849 Fix opendoors contact url, replace Admin with admin

app/views/user_mailer/delete_work_notification.text.erb, config/locales/en.yml
https://otwarchive.atlassian.net/browse/AO3-4305
- All text emails need their spacing fixed -- there should be a blank line between paragraphs
- The pseud doesn't show up in the text email that's delivered to the user who did not delete the work
- In the text emails, there should probably be the word "at" between "Support" and the URL, or the URL should be in parentheses or something 
- In the text emails, it would also be nice if we put quotation marks around the work title, like we do in the email for the work being deleted by an admin
=> AO3-4305 fix issues found on test

app/views/admin/admin_users/bulk_search.html.erb
https://otwarchive.atlassian.net/browse/AO3-4716
This addresses the copy-pasted `url-field-description` which should have been changed to `email-field-description` just for the sake of coherence.
Check the ids in the HTML - they will be used by screenreaders that use the `aria-describedby` attribute.
=> AO3-4716 Correct id on bulk email search footnote

spec/controllers/tag_set_nominations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4830
This is my first code change to the otwarchive repository, so I'm hoping someone can help set me straight on any otw style guidelines or best practices that I've disregarded!
This is to increase code coverage of tag_set_nominations_controller.rb. Code coverage in coveralls will increase from [68.34%](https://coveralls.io/builds/9916720/source?filename=app%2Fcontrollers%2Ftag_set_nominations_controller.rb) to [96.98%](https://coveralls.io/builds/9900548/source?filename=app%2Fcontrollers%2Ftag_set_nominations_controller.rb). \o/
Previously, tag_set_nominations_controller.rb was covered primarily with Cucumber tests. This code change will add additional unit test coverage.
Other open TODO items I'd like some help with:
There were 3 error …
=> AO3-4830 Extend tests for tag_set_nominations_controller

app/controllers/owned_tag_sets_controller.rb, spec/controllers/owned_tag_sets_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4835
Previously when tag_set is not found by load_tag_set, it would raise an ActiveRecord error and return a 500. Now, it redirects to the tag set path and displays a flash notice (the previously unreachable branch).
Navigate to /tag_sets/{some tag set id that doesn't exist} (i.e. /tag_sets/12345). It should redirect to /tag_sets and have a flash notice that says "What Tag Set did you want to look at?"
potatoesque, she/her
=> AO3-4835 Fix unreachable branch in owned_tag_sets_controller

app/controllers/owned_tag_sets_controller.rb, spec/controllers/owned_tag_sets_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4834 
Fixing an unreachable branch in owned_tag_sets_controller. If the restriction isn't found with the show_options action, redirect to the tag sets path and display a flash error.
Navigate to /tag_sets/show_options. It should redirect back to /tag_sets with a flash error saying, "Which Tag Set did you want to look at?"
potatoesque, she/her
=> AO3-4834 Fix unreachable branch in owned_tag_sets_controller

config/.rubocop.yml
https://otwarchive.atlassian.net/browse/AO3-4895
Stop Hound from commenting about Ruby 2.3 features.
As long as automated tests pass.
=> AO3-4895 Set RuboCop's Ruby version for Hound

features/step_definitions/tag_set_steps.rb, features/tags_and_wrangling/tag_set.feature, spec/controllers/tag_set_nominations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4908
This adds four new cucumber tests and a few new RSpec tests to handle the case of nominating characters & relationships (and editing character & relationship nominations) when the fandom nomination limit is set to 0.
I don't think manual testing is required -- as long as this passes automated tests, it's doing what it's supposed to.
=> AO3-4908 Tag set nomination tests when the fandom nomination limit is 0.

features/bookmarks/bookmark_create.feature, features/bookmarks/bookmark_external.feature, features/cassette_library/cucumber_tags/bookmark_external_work.yml, features/support/paths.rb, features/support/vcr.rb
https://otwarchive.atlassian.net/browse/AO3-4914
Test all creator's tag fields for external work bookmarks, plus minor tidying (fix scenario description, use label name, put in separate file) of existing external bookmark tests
No manual testing
=> AO3-4914 Test all creator's tag fields for external work bookmarks

app/models/collection.rb, features/collections/collection_navigation.feature, features/step_definitions/tag_steps.rb
https://otwarchive.atlassian.net/browse/AO3-2431
The fandom counts for collections are a little inconsistent. The fandom count in the sidebar includes all metatags for all fandoms used on works in the collection; the list of fandoms doesn't. This pull request changes the fandom count in the sidebar (and the fandom count in the collection's blurb) to skip inherited taggings, to make it match the query used to generate the list of fandoms.
The example given in the bug report no longer works, but there are very detailed steps on how to reproduce this issue in the bug report's comments.
=> AO3-2431 Make collection fandom count skip metatags

app/views/chapters/_chapter_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-4045
makes the chapter 'character limit exceeded' message relevant regardless of whether the user is posting the first chapter of a new work or a new chapter of an existing multi-chapter work.
=> AO3-4045 Change error message when chapter character count is too long

app/controllers/works_controller.rb, features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-4808
Following the PR for [AO3-4549](https://otwarchive.atlassian.net/browse/AO3-4549), which fixed a problem stopping the user from viewing a work that was saved with no fandom, this stops a user from saving a work with no fandom in the first place.
This also takes the opportunity to refactor the edit and create methods as they had diverged (creating this problem) and with them both having 100% coverage, this seemed a safe thing to do.
1. Edit a work that was previously posted
2. Hit the "x" next to the only fandom tag to remove it
3. Choose "Post Without Preview"
4. Now instead of a 500 error (or a 404 on Staging), the form should reload with the error message:
```
Sorry! We couldn't save this work because:
Please add all required tags. Fandom …
```
=> AO3-4808 Fix 500 error when a work is edited to have no fandom

app/controllers/challenge_signups_controller.rb, factories/challenges.rb, factories/tags.rb, spec/controllers/challenge_signups_controller_spec.rb, spec/controllers/owned_tag_sets_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4877
This fixes the bug introduced in release 0.9.180 which prevents gift exchange sign-ups from being downloaded as a CSV file.
Try to download the CSV for a gift exchange. This was consistently broken but should now work.
=> AO3-4877 Fix gift exchange sign-ups CSV downloads

app/sweepers/challenge_signup_sweeper.rb, app/sweepers/collection_sweeper.rb, app/views/collections/_collection_blurb.html.erb
https://otwarchive.atlassian.net/browse/AO3-2431
(The issue is discussed in the comments.)
My fix for inconsistent fandom counts (#2606) updates the function all_fandoms_count called by the view [collections/collection_blurb](https://github.com/otwcode/otwarchive/blob/master/app/views/collections/_collection_blurb.html.erb), but the caching on the collection blurbs means that the change won't immediately be reflected on the blurb. This pull request changes the cache version number for the collection blurbs, so that they will be regenerated with the correct fandom counts.
It also updates the collection_sweeper and the challenge_signup_sweeper, which use the collection blurb's cache key to flush the cache whenever a collection is updated.
I'm not sure whether manual testing is needed, but …
=> AO3-2431 Update collection blurb cache key so that the changes to all_fandoms_count are visible.

app/controllers/works_controller.rb, features/works/work_edit.feature, features/works/work_edit_tags.feature
https://otwarchive.atlassian.net/browse/AO3-4808
Fixes the Broken on Test issue where no message appears when using Edit Tags to remove the fandom.
See Jira.
=> AO3-4808 Display an error if fandom is removed when editing tags

app/controllers/locales_controller.rb, app/models/locale.rb
https://otwarchive.atlassian.net/browse/AO3-4783 
Implements strong parameters and ForbiddenAttributesProtection to Locale. It also adjusts error handling for both the `create` and `update` actions. In the current state, the error messages did not give the user specific reasons/errors causing the action failure. It not prompts the user with the proper error messages and gives them the ability to adjust their data properly.
2. Locales > New Locale
3. Fill out the form
4. Press "Create Locale"
5. You'll be back on the locales page where you can choose "Edit" in your new locale's row
6. Make changes to the form
7. Press "Update Locale"
None
he/him
=> AO3-4783 Implements strong params for Locale

app/views/comments/_single_comment.html.erb
https://otwarchive.atlassian.net/browse/AO3-4853
This should both make the tests more reliable and also make so we are less likely to have comments not appearing.
Create a comment and ensure it is visible.
=> AO3-4853 Improve cache busting for a single comment. ( Make tests and coverage more reliable )

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4937
Update nokogiri and associated gems
Check that imports still work as well as expected
=> AO3-4937 Update nokogiri and associated gems

app/controllers/application_controller.rb, app/controllers/tag_wranglings_controller.rb, app/controllers/tags_controller.rb, app/views/tag_wranglings/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4858
When attempting to sort the tags on a tag_wranglings page (e.g. test.ao3.org/tag_wranglings?show=relationships), the _initial_ click on the "Taggings" sort link would appear to tags in descending order by the number of taggings, giving you a URL like test.ao3.org/tag_wranglings?show=relationships&sort_column=taggings_count_cache&sort_direction=DESC 
However, the "Taggings" heading would _not_ take on the grey, pressed-button style that indicates it was currently selected, and clicking the heading a second time would _not_ sort the tags in _ascending_ order. 
This updates the logic around sorting tags to use `taggings_count_cache` instead of `taggings_count`
Make sure the "Taggings" heading on pages like …
=> AO3-4858 Tag wrangling pages should allow sorting by taggings_count_cache

spec/controllers/tag_set_nominations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4940
Fixed a single test in tag_set_nominations_controller_spec.rb in order to cover TagSetNominationsController:271-272, as originally intended.
Code change is only in spec file so this won't change any functionality for the user.
Code error was originally introduced as part of this merged PR: https://github.com/otwcode/otwarchive/pull/2728/files.
*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](http://archiveofourown.org/admin_posts?tag=1)?* cyrilcee
*What pronouns do you prefer (she/her, he/him, zie/hir etc)?* she/her
=> AO3-4940 Fix incorrect test in tag_set_nominations_controller_spec.rb

factories/locales.rb, spec/controllers/locales_controller_spec.rb, spec/models/locale_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4927
Extend tests for locales_controller.rb.
Add a factory for locales.
Anything that remains uncovered by tests is unused and will be removed in [AO3-4942](https://otwarchive.atlassian.net/browse/AO3-4942).
Check coverage increase. See JIRA issue.
=> AO3-4927 Extend tests for locales_controller.rb

lib/tasks/tag_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-4951
The rake tasks and most notably the ones that delete 0 use tags where not updated.
Create a 0 use tag and then get the rake task run and see if the tag has been delete
=> AO3-4951 Update tag rake tasks to work with taggings_count_cache 

app/controllers/challenge/gift_exchange_controller.rb, app/models/challenge_models/gift_exchange.rb
https://otwarchive.atlassian.net/browse/AO3-4860
This PR adds basic strong parameters to the GiftExchangeController and ForbiddenAttributes protection to the model. Based on a previous review, I left non-CRUD action params alone instead of using the new strong param method. If desired, I can update those `param[:gift_exchange]` references to use the new `gift_exchange_params` method quicky.
1. Log in
2. Browse > Collections > New Collection
3. Fill in required information and choose "Gift Exchange" for "Type of challenge, if any"
4. Submit
5. Fill in form with whatever combination of settings you like
6. Submit
7. Choose "Challenge Settings" from side bar
8. Edit form with whatever combination of settings you like
9. Update
No outside references
*What name do you want us to use to credit …
=> AO3-4860 Adds strong parameters to Gift Exchange

app/controllers/tags_controller.rb, features/tags_and_wrangling/tag_wrangling_unsorted.feature, spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4954
It's possible for an edit form to send back just the tag type and the fix taggings count (e.g. changing the type of an unsorted tag), leaving the controller to enforce strong parameters on an empty hash:
"Required parameter missing: tag"
To avoid this, we only apply strong parameters if params is not empty.
Change an unsorted tag to a fandom tag, then change it back. See test cases at:
- https://otwarchive.atlassian.net/browse/AO3-4954
- https://otwarchive.atlassian.net/browse/AO3-4907?focusedCommentId=348202&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-348202
=> AO3-4954 Check for empty params when updating tags

app/controllers/external_works_controller.rb, features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-4828
Adds a missing warning_strings param to ExternalWork as well as a cucumber test for this in the future.
2. Find a bookmark of an external work – http://test.ao3.org/external_works is giving a 500 error, but you can likely find one on http://test.ao3.org/bookmarks or http://test.ao3.org/users/testy/bookmarks
3. Follow the "Edit External Work" link
4. Change as much or as little information in the form as you want
5. Press "Update External Work"
None
he/him
=> AO3-4828 Adds warning_strings param

app/controllers/user_invite_requests_controller.rb, app/models/user_invite_request.rb
https://otwarchive.atlassian.net/browse/AO3-4960
This pull request adds strong parameter protection for the UserInviteRequest class. There's a mass assignment in the `UserInviteRequestsController#create` function. I believe this code is currently disabled on the live site, but there are some tests that use it in [invite_request.feature](https://github.com/otwcode/otwarchive/blob/master/features/other_a/invite_request.feature).
1. Log in as an admin.
2. Go to the Settings page.
3. Make sure that the "User can request invitations" checkbox is checked.
4. Update the Settings, and log out.
5. Log back in as a user.
6. Go to "My Dashboard", and click the "Invitations" button. Then click "Request Invitations."
7. Fill in the two fields and press "Send Request."
8. Log out.
9. Log in as an admin …
=> AO3-4960 Strong parameters for UserInviteRequests.

app/controllers/kudos_controller.rb, app/models/kudo.rb
https://otwarchive.atlassian.net/browse/AO3-4958
This pull request adds strong parameter protection for the Kudos class. There's a mass assignment in the `KudosController#create` function, so this pull request whitelists the two fields used in the new_kudo form.
1. Try to add a kudo to a work when logged out, with Javascript enabled.
2. Try to add a kudo to a work when logged in, with Javascript enabled.
3. Try to add a kudo to a work when logged in, with Javascript disabled.
4. Try to add a kudo to a work when logged out, with Javascript disabled.
In each case, the kudo(s) should appear on the correct work.
=> AO3-4958 Strong parameters for Kudos.

app/controllers/preferences_controller.rb, app/models/preference.rb
https://otwarchive.atlassian.net/browse/AO3-4959
This pull request adds strong parameter protection for the Preference class. There's a mass assignment in the `PreferencesController#update` function, so this pull request whitelists the fields listed on the preferences form.
1. Log in.
2. Go to the "My Preferences" page.
3. Check all of the boxes, and press "Update."
4. Go back to the "My Preferences" page and make sure that all of the boxes are still checked.
5. Uncheck all of the boxes, and press "Update."
6. Go back to the "My Preferences" page and make sure that all of the boxes are unchecked.
7. Try changing the site skin, time zone, and page title.
8. Go back to the "My Preferences" page to make sure that all of the changes you made are reflected.
=> AO3-4959 Strong parameters for Preferences.

app/controllers/works_controller.rb, app/models/work_search.rb
https://otwarchive.atlassian.net/browse/AO3-4961
Add strong parameters protection to the WorkSearch class (since it's a subclass of the Search class, which is a subclass of the ActiveRecord::Base class).
I added some steps for testing to the JIRA issue.
=> AO3-4961 Strong parameters for WorkSearch.

app/controllers/bookmarks_controller.rb, app/models/bookmark_search.rb
https://otwarchive.atlassian.net/browse/AO3-4962
BookmarkSearch is a subclass of Search, and Search is a subclass of ActiveRecord::Base. So this pull request adds strong parameters for the calls to `BookmarkSearch.new` in `BookmarksController#index` and `BookmarksController#search`.
I wrote some steps for testing in the JIRA issue.
=> AO3-4962 Strong parameters for BookmarkSearch.

config/routes.rb, factories/comments.rb, features/comments_and_kudos/inbox.feature, features/step_definitions/comment_steps.rb, spec/controllers/inbox_controller_spec.rb, spec/support/redirect_expectation_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4926
- Add specs for the controller.
- Add cukes for replying to inbox comments from the home page, both with and without JavaScript.
- Remove the route cancel_reply which has no action.
- Check that coverage for the controller is now at 100%.
=> AO3-4926 Extend tests for inbox_controller.rb

Gemfile, Gemfile.lock, features/support/env.rb, features/tags_and_wrangling/tag_comment.feature
https://otwarchive.atlassian.net/browse/AO3-4939
Improve the reliability of the tests 
=> AO3-4939 Improve reliability of timestamp-related tests for tag comments

app/controllers/works_controller.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4966
As part of the fix for the 500 error when no fandoms are present, I refactored the create method in the WorksController and introduced an `&& return` (in line with previous refactoring in the controller) which should have been an `and return` and caused a 500 error when it was hit.
Try to add a co-author with multiple pseuds to a new work (see Jira for more specific steps)
=> AO3-4966 Render co-author dialog when ambiguous or invalid pseuds are present

app/controllers/owned_tag_sets_controller.rb, spec/controllers/owned_tag_sets_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4890
When uses tries to navigate to /tag_sets/{some tag set id that doesn't exist}, message "What Tag Set did you want to look at?" is shown on red background to implicate an error has occurred, not just an informational message.
Navigate to /tag_set/12345 (or use any other nonexistant tag set id).
=> AO3-4890 Flash red error when loading nonexistent tag

app/models/external_author.rb, spec/models/external_author_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4875
If a work is imported from an external site, and external author is created with the author's email from that site. A claim email is sent to the email address; the user can then claim this external author identity to associate it with their AO3 account.
Currently, if the email address is the same on the external author and the user, future imports will be automatically transferred to the user. But if the emails are different, the works remain in a weird limbo with a broken byline that only mentions the archivist.
This code now checks if the external author is already claimed by a user and transfers the works even if the email addresses don't match.
1. As an archivist, import a work with an email address that doesn't match an existing …
=> AO3-4875 Claim external authors by id as well as email

app/controllers/tag_set_nominations_controller.rb, spec/controllers/tag_set_nominations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4872
This is a follow-up to a pull request review comment: https://github.com/otwcode/otwarchive/pull/2728/files#r102482816
In tag_set_nominations_controller.rb, there was code to return a flash message when a user tries to update or access a tag set or tag set nomination that does not exist. Those error handling paths were never reached because OwnedTagSet.find or TagSetNomination.find would immediately raise an ActiveRecord::RecordNotFound error if no record was found with the given id.
~~This code change makes that RecordNotFound error more explicit and strips out the unused error handling paths.~~
This code change makes it so that the flash messages and redirect behavior are actually reached.
The easiest way to test this is to:
1. Try to …
=> AO3-4872 Redirect and return flash message when tag set or nominations can't be found

public/stylesheets/site/2.0/03-region-header.css, public/stylesheets/site/2.0/08-actions.css, public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-4493
makes long unsubscribe text wrap inside button. 
for the text inside the unsubscribe buttons to wrap, the height must be set to auto and white-space must be set to normal... but if input[type="submit"] had been set to a height of 1.929em with a specific purpose in mind, we can also target only the buttons in the subscribe section with a selector like 
.subscription input[type="submit"]
that being said, i didn't notice any immediate changes in button heights when testing the change on other pages, but i'll continue to test different pages and check for possible height issues.
=> AO3-4493 Make long unsubscribe text wrap

app/controllers/tags_controller.rb, app/models/tag.rb, features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-1744
Currently, when you try to add a non-canonical fandom to a character or relationship tag, it will fail silently -- the non-canonical fandom won't be added as a parent (correctly), but the flash message says that the tag has been updated, and doesn't notify the wrangler that the fandom wasn't added. This pull request adds an error message when trying to add an association to a non-canonical tag, and updates the existing non-canonical fandom test to check for that error message.
The bug report has steps for reproducing the problem.
=> AO3-1744 Show error when wrangling tags into a non-canonical fandom.

app/views/home/diversity_statement.html.erb
https://otwarchive.atlassian.net/browse/AO3-4964
This Pull request updates the language used on the Archive's Diversity page. 
Ensure that the Diversity statement reads in part as:
"You are free to express your creativity within the few restrictions needed to keep the service viable for other users. The Archive strives to protect your rights to free expression and privacy; you can read about the details in our Terms of Service."
None.
=> AO3-4964 - Change wording on Diversity Statement

app/views/user_mailer/invitation.html.erb
https://otwarchive.atlassian.net/browse/AO3-4884
Our links were showing their HTML. Now they won't.
=> AO3-4884 Fix exposed HTML in invitation email

app/controllers/archive_faqs_controller.rb, app/helpers/language_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4548 
Resolves a BoT problem where if you created a translation of a question in one language (i.e. German), it would cause the original English version of the question to show up in all the other non-English languages even though you had not checked the ticky to make the question show up. 
Ensure that when you check a question as translated in one language (i.e. German) that it doesn't show up in any other language.
=> AO3-4548 Ensuring that translated questions keep to themselves

app/views/works/_standard_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-4105
in the work edit form there was a button under the series section that just said "delete" and it would delete an entire series. if a user wants to delete an entire series, they should do it from the series edit page, so that button's been removed. 
beside it was a button that just said "remove" and it removes the work you're currently editing from the series it's in. "remove" can be a bit vague because there's no confirmation when you click it, so it's been relabelled "remove work from series" which is a bit longer; but hopefully it clears up any questions about what the button does
confirm that the mysterious "delete" button in the series section of the work edit form is gone and the "remove" button is relabelled to "remove work from …
=> AO3-4105 Remove "delete" button for series in works edit form

app/models/bookmark.rb, app/models/tagging.rb, app/models/work.rb, features/step_definitions/tag_steps.rb, features/tags_and_wrangling/brand_new_fandoms.feature, features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-4963
This pull request moves the call to `Tag.update_tag_cache` from the Work's `expire_caches` function into a new callback in the Tagging class, which is triggered whenever a Tagging is created or destroyed. This ensures that the `taggings_count` will behave the same regardless of whether the new tag is used on a Work or an ExternalWork (or a Bookmark).
There are steps for replicating the bug in the JIRA issue.
=> AO3-4963 Modify new taggings_count code to handle brand new fandoms used on External Works.

app/controllers/application_controller.rb, app/controllers/locales_controller.rb, config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-4942
- Remove unused locales code in locales_controller and application_controller.
- Disable unused routes in locales_controller.
- Check that coverage for the locales_controller is now at 100%.
- Check that we can still create/edit locales.
Tests for this controller were added in https://otwarchive.atlassian.net/browse/AO3-4927.
=> AO3-4942 Remove unused locales code

app/controllers/opendoors/tools_controller.rb, factories/users.rb, features/importing/archivist.feature, features/step_definitions/archivist_steps.rb, spec/controllers/opendoors/tools_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4956
- Display an error message instead of raising 404 when a work ID cannot be found.
- Add controller spec for opendoors/tools_controller.rb.
- Add a scenario for updating a work's imported from URL.
See https://otwarchive.atlassian.net/browse/AO3-4956.
=> AO3-4956 Extend tests for opendoors/tools_controller.rb and change from 404 to flash error

app/views/comments/_single_comment.html.erb, app/views/comments/_single_comment_abbreviated.html.erb, features/comments_and_kudos/add_comment.feature, public/stylesheets/site/2.0/24-role-admin.css
https://otwarchive.atlassian.net/browse/AO3-4847
Allows admins to see a commenter's IP address
Ensure that a guest, an author and the commentator can't see the ip address.
Ensure that an admin can see the ip address.
=> AO3-4847 Allow admins to see ip address of commenter

app/views/share/_share.html.erb
https://otwarchive.atlassian.net/browse/AO3-4826
From JIRA:
>We're using an old version of the Tumblr share code – the parameters in the URL are no longer correct.
>
> * Our Tumblr share link code: https://github.com/otwcode/otwarchive/blob/master/app/views/share/_share.html.erb#L21
> * Tumblr share documentation: https://www.tumblr.com/docs/en/share_button
>
>For the link, you'll want to change the start to "http://tumblr.com/widgets/share/tool" and the "url" parameter to "canonicalUrl," "name" to "title," and "description" to "caption"
Refer to JIRA issue
=> AO3-4826 Tumblr share code produces wrong link text

app/controllers/comments_controller.rb, features/step_definitions/comment_steps.rb, features/tags_and_wrangling/tag_comment.feature, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4718
There are two closely related issues with the way that the `check_tag_wrangler_access` filter applies to comments on tags. This pull request attempts to address them.
I wrote some instructions on the issue for replicating this problem, as well as some other instructions for manual QA in the contributor chat.
This is a rewrite of #2612, since I realized while trying to merge that the issue was a little larger than I thought, and I wanted to add more tests (and get rid of one of the existing tests, which was inelegantly written).
=> AO3-4718 Fix permission checks for comments on tags.

app/controllers/opendoors/tools_controller.rb, spec/controllers/opendoors/tools_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4956?focusedCommentId=348917&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-348917
"archive" to "Archive", "url" to "URL".
Check flash error. See issue.
=> AO3-4956 Fix capitalization for flash error in opendoors/tools_controller

spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4981
Adds an automated test for the invitation email that just got internationalised.
=> AO3-4981 test for i18n of invite email

features/importing/work_import.feature, features/step_definitions/work_steps.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4993
Move tests from cucumber to rspec
=> AO3-4993 Refactor url caching testing to use rspec rather than cucumber.

app/models/redis_mail_queue.rb, features/other_a/autocomplete.feature, features/step_definitions/autocomplete_steps.rb, features/step_definitions/work_search_steps.rb, features/step_definitions/work_steps.rb, features/support/hooks.rb
https://otwarchive.atlassian.net/browse/AO3-4992
- Remove autocomplete-test-only-hook to clear Redis
- When clearing the mail queue, skip the DEL command if there are no keys, otherwise we get an error ("wrong number of arguments").
Just automated tests.
There's a code change in the mail queue, I'm not sure how we'd test that manually. I did run into the error because of a test though:
https://github.com/otwcode/otwarchive/blob/6e196e01b43255bfec5da5dcefed0f4dda218c3b/features/comments_and_kudos/kudos.feature#L110
=> AO3-4992 Clear Redis before each feature test

features/step_definitions/autocomplete_steps.rb, features/step_definitions/tag_steps.rb, features/tags_and_wrangling/tag_wrangling.feature, features/tags_and_wrangling/tag_wrangling_characters.feature, features/tags_and_wrangling/tag_wrangling_fandoms.feature, features/tags_and_wrangling/tag_wrangling_freeforms.feature, features/tags_and_wrangling/tag_wrangling_relationships.feature
https://otwarchive.atlassian.net/browse/AO3-4997
Enable pending autocomplete feature tests for tag wrangling.
Some "follow tag name link" actions become ambiguous when JavaScript is enabled because we have delete buttons with title containing tag names, so we need to switch to "Edit (tag name)".
On the tag edit page, we can refer to certain fields by their labels only when they don't already have any values pre-filled. If they do, their input fields will be preceded by a section of checkboxes to toggle existing values, and we have to refer to them by IDs. Example: "Add Fandoms" vs "tag_fandom_string_autocomplete".
Clean-up:
- Refer to the "Canonical" checkbox by its label
- Prefer the step "Given a (non)canonical (tag type)" over alternatives
- Fix a TODO in the media pages test …
=> AO3-4997 Resurrect autocomplete feature tests for tag wrangling

app/helpers/users_helper.rb, app/models/collection.rb, app/models/pseud.rb, app/models/skin.rb
https://otwarchive.atlassian.net/browse/AO3-4621
Current icons should be served by https, rather than http ( amazon icons ). New icons should be saved in the database as https...
Check the page source
=> AO3-4621 Fetch Icons via https

app/controllers/works_controller.rb, spec/controllers/works/miscellaneous_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4863
The error displayed by the reindex method was in a notice rather than an error flash message, so this corrects that.
If you can trigger reindexing as an ordinary user, check that the error is displayed in a red box - however, this is covered by the automated test and looking at the code, it's probably difficult to trigger manually.
=> AO3-4863 Make error in reindex method a flash error rather than a notice

config/routes.rb, spec/controllers/wrangling_guidelines_controller_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-4733
More tests.
Change "reorder" route to use the actual action name "update_positions"
The "confirm_delete" route has no action and will be implemented in [AO3-4974](https://otwarchive.atlassian.net/browse/AO3-4974).
No pain, only tests. Check that coverage for the controller is now at 100%.
=> AO3-4733 Extend tests for wrangling_guidelines_controller and correct route for reordering

app/views/works/_search_form.html.erb, public/stylesheets/sandbox.css, public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-3359
adds a search button to the top of the advanced search form, and removes top padding from the new button to preserve the balance/symmetry of the page. (tried to make sure the selector would only target that one submit button, since this styling isn't necessary for any other buttons i don't think...)
the changes shouldn't affect any other forms (or submit buttons) on the site.
=> AO3-3359 Add search button to top of advanced search form

app/models/pseud.rb, features/other_a/orphan_series.feature, features/other_a/orphan_work.feature, features/step_definitions/orphan_steps.rb
https://otwarchive.atlassian.net/browse/AO3-3733
https://otwarchive.atlassian.net/browse/AO3-4174
Currently, the orphaning code contains checks in `Creatorship.orphan` to avoid transferring ownership of works the user doesn't own to orphan_account. However, when orphaning a series that the user is a co-creator for, `Pseud.change_ownership` will be recursively called on all works in the series, without checking whether the user is a co-creator of those works. This results in orphan_account being added as a co-creator on all works in the series, regardless of whether the orphaning user was a co-creator before.
The same problem occurs when orphaning a work: `Pseud.change_ownership` is recursively called on all chapters in the work, meaning that orphan_account will be added as a co-creator on …
=> AO3-3733 AO3-4174 Fix orphaning shared series/works to avoid incorrectly adding orphan_account.

app/views/home/_intro_module.html.erb, features/admins/admin_invitations.feature
https://otwarchive.atlassian.net/browse/AO3-4407
on the homepage, logged out users were encouraged to ask friends for invites even when user invite requests were turned off in the admin panel. with this, the homepage only shows logged out users "you can join by getting an invitation from another user" when user invite requests are turned on
please make sure that when user invite requests are turned off, the homepage does not show logged out users "you can join by getting an invitation from another user"
and please make sure that when user invite requests are turned on, the homepage does show logged out users "you can join by getting an invitation from another user"
for good measure, please also check that when account creation is enabled, neither the invite queue nor the user invite is …
=> AO3-4407 Only mention user invites on homepage to logged out visitors when user invites are turned on

config/database.codeship.yml, script/prepare_codeship.sh
https://otwarchive.atlassian.net/browse/AO3-5021
Get codeship using mysql 5.7 which I think will be needed for the rails 4.0 change.
I am going to apply this to my copy of the 4.0 branch and see if it passes on codeship ( https://app.codeship.com/projects/14479/builds/25132225 )
=> AO3-5201 Move codeship to mysql 5.7

app/models/story_parser.rb, features/support/vcr.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5030
Add test for [AO3-2251](https://otwarchive.atlassian.net/browse/AO3-2251).
The original test, relying on an external site, was added in #67 and removed in #1536.
The cassette for this test (features/cassette_library/cucumber_tags/work_import_nul_character.yml) is still in the repository. I'm not removing it here because it might end up committed back (like some of the cassettes removed in [AO3-4968](https://otwarchive.atlassian.net/browse/AO3-4968) got added back in the Rails 4.0 upgrade). I'll remove it as part of [AO3-4488](https://otwarchive.atlassian.net/browse/AO3-4488), where I plan to delete all cassettes and .gitignore them permanently.
Automated.
=> AO3-5030 Add test for importing input with string terminators for Nokogiri

Gemfile, Gemfile.lock, config/s3.example
Bump the version of paperclip so we can use version 2 of the Amazon api
This isn't something that i can test at all in a dev environment I think....
"However, I think I have hit a bug! I get a 500 error when trying to either create a pseud with an icon or edit a pseud to have an icon." so test file uploads, icons, collections etc
=> AO3-5023 Bump paperclip version

lib/tasks/resque.rake
Currently neither the resque workers or the scheduler starts
Test things that require the resque workers/ Look at the resque interface on test and see that there are workers running
=> AO3-5023 Allow resque tasks to start

app/views/admin/_admin_nav.html.erb, app/views/admin/_admin_options.html.erb, app/views/admin/admin_users/confirm_delete_user_creations.html.erb, app/views/admin/blacklisted_emails/index.html.erb, app/views/admin_posts/show.html.erb, app/views/challenge_assignments/_maintainer_index.html.erb, app/views/collections/_header.html.erb, app/views/invite_requests/manage.html.erb, app/views/skins/_skin_actions.html.erb, app/views/users/change_username.html.erb, app/views/works/_standard_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5023, specifically https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=350327&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350327
Restores the confirmation popup message in a variety of places:
- Deleting works, bookmarks, or external works as an admin should have a confirmation popup
- Deleting news posts as an admin, both while on the post's edit page and the post itself, should have a confirmation popup
- As an admin, choosing the "Spammer: ban and delete all creations" option for a user and pressing "Submit" on the confirmation page for deleting creations should have a confirmation popup
- Deleting an invite request as an admin should have a confirmation popup
- As an admin, following the …
=> AO3-5023 Confirmation popup fixes

app/views/chapters/_chapter_form.html.erb, app/views/chapters/preview.html.erb, app/views/feedbacks/new.html.erb, app/views/works/_standard_form.html.erb, app/views/works/preview.html.erb
https://otwarchive.atlassian.net/browse/AO3-5023 
Specifically: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=350329&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350329
Restores the following behavior:
- Post Without Preview should get disabled with "Please wait..." on new chapter form
- Post should get disabled with "Please wait..." on chapter preview page
- Send should get disabled with "Please wait..." on support form
- Post Without Preview should get disabled with "Please wait..." on new work form
- Post should get disabled with "Please wait..." on work preview page
Also has style fixes concerning hash rockets, quotation marks, and line length.
Check that the behavior described above/in the JIRA comment happens
=> AO3-5023 Fix disabling form buttons on submission

spec/controllers/autocomplete_controller_spec.rb, spec/models/cache_master_spec.rb, spec/models/index_queue_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5045
Before each unit test, clear memcached, Redis, and Elasticsearch.
Similar to #2884 / [AO3-4992](https://otwarchive.atlassian.net/browse/AO3-4992), for feature tests.
=> AO3-5045 Clear caches before each unit test

app/decorators/homepage.rb
Specifically this comment: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=350618&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350618
When you are logged in and have more than three Marked for Later items, you see different items under "Is it later already?" each time you reload the homepage. This is because caching is broken -- we need an array, not ActiveRecord objects. See the discussion here: https://github.com/otwcode/otwarchive/pull/2917#discussion_r116371412 
Log in and add more than three items to your Marked for Later list. Go to homepage make sure "Is it later already?" shows three random works from your marked for later, and the works _do not_ change until your marked for later …
=> AO3-5023 Get arrays of readings and admin posts for homepage

app/controllers/downloads_controller.rb
Specifically the issue described in this comment: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=350617&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350617
This makes sure we don't include the site layout when making the files for our ePub.
Make sure you can download _and open_ an ePub on multiple devices/platforms/programs.
Sarken [19:35] 
Jumping over here to talk about the problem with ePub files on staging. Claire gave us a useful error message (`Line 192: XML declaration allowed only at the start of the document`), so I'm investigating, and I'm already finding interesting things.
[19:37] 
So an ePub is a container, basically, with a bunch of files inside it. I can find XML …
=> AO3-5023 Make ePub toc.ncx and content.opf stop using site layout

lib/tasks/admin_tasks.rake, lib/tasks/tag_tasks.rake
Specifically this comment: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=350900&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350900
Updates the finders in the skin and admin rakes so we can use them. It also changes a few find alls to find_each, because all is going to load everything into memory. 
Someone with database access will need to run the tasks for deleting unused tags, resending sign-up emails, and purging unvalidated accounts on staging. This also changes the reset common taggings, reset tag count, and update relationship has_characters tasks to the more efficient find_each, but I am not sure if we actually want or need to run those.
=> AO3-5023 Update finders in skin and admin rake files

app/controllers/application_controller.rb
Given that we are going to stop caching most of the pages in nginx we can stop doing the force logout for a bit
You could delete the user_credentials cookie and see if you get forced logged out.
=> AO3-5023 Comment out force logout

app/controllers/downloads_controller.rb, config/routes.rb, features/importing/archivist.feature, features/step_definitions/email_custom_steps.rb, features/support/paths.rb
Comment: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=351011&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-351011
Fixes a routing error that was preventing users from claiming imported works. There's a little bit of test tidying, too, because I was trying to track down several OD-related bugs, and I needed to understand what we were testing in some of these. :P Alas, this was the only one I could fix. 
You'll need a user with two email addresses: one they use for their AO3 account and one they don't. An archivist will need to import a work and list the non-AO3 email addresses in the external author information. While logged in, the user should follow the claim link in the email and …
=> AO3-5023 Fix logged in user claiming imported works

app/controllers/tags_controller.rb, features/support/paths.rb, features/tags_and_wrangling/tag_wrangling.feature
This comment: https://otwarchive.atlassian.net/browse/AO3-5023?focusedCommentId=351205&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-351205
When logged in as a wrangler, the Characters/Relationships/Freeforms/SubTags/Mergers links on pages like http://test.archiveofourown.org/tags/MASH%20(TV)/wrangle give a 404, which was actually disguising a 500.
Refer to JIRA
=> AO3-5023 Fix broken links for wrangling in a fandom

app/models/work.rb
Update cache key version number for hashed tag data due to Rails 4.2 error
=> AO3-5023 Update cache key version number for hashed tag data due to Rails 4.2 error

app/controllers/tag_wranglers_controller.rb
AO3-5023: Restore missing order clause to wrangling query
Just got dropped in the code update
=> AO3-5023: Restore missing order clause to wrangling query

app/models/feedback.rb, app/views/feedbacks/new.html.erb, features/other_b/support.feature, spec/mailers/feedback_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4953
* Makes the email field a **required** field for the Support form; and,
* removes the language in the flash notice saying that we accept anonymous feedback.
1. Ensure that blue flash-notice on Support form says: "Our spam filter does collect IP addresses, but we never see them."
2. Email field label should now read: "Your email (required)"
3. The email field cannot be blank.
4. The email field must contain a valid email address.
=> AO3-4953 - Change Support form to require email address

app/models/creation_observer.rb, features/other_a/orphan_work.feature, features/step_definitions/work_steps.rb, features/works/work_create.feature, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3223 
The current behavior is that when a coauthor is saved for a multichapter work, they are only saved as a coauthor for the first chapter. This change makes it so that they are saved as a coauthor for every chapter of the work. However, it does not change it so that each new chapter contains all the work's coauthors; they will only have the user who saved that chapter as an author, and all other coauthors have to be added manually.
* Create a multichapter work with one user.
* Add a second user as a coauthor for the entire work.
* As the second user, select "Edit Chapter" for any chapter except for the first--there should be no error banner, and the user should be able to edit that chapter as normal. …
=> AO3-3223 When saving a coauthor for a work, save for all existing chapters as well

app/models/work.rb, features/works/work_related.feature
https://otwarchive.atlassian.net/browse/AO3-3536
Displays the first validation error message for a newly-associated external work when it cannot be saved.
Edit an Archive work to add an associated external work with an unreachable URL.  Should see the error message "Parent work Url could not be reached. If the URL is correct and the site is currently down, please try again later." instead of "Parent work info would not save."
=> AO3-3536 Show validation error message when parent Url unreachable

app/helpers/application_helper.rb, features/support/paths.rb, features/works/work_related.feature
https://otwarchive.atlassian.net/browse/AO3-4272
Allow HTML in afterword list of anonymous remixes, so links to authors (available to authors themselves and admins) do not get escaped.
This is @astirya's fix (#2364) + tests.
https://otwarchive.atlassian.net/browse/AO3-4272
https://otwarchive.atlassian.net/browse/AO3-4948
=> AO3-4272 Allow HTML in afterword list of anonymous remixes

app/models/work_search.rb, app/views/works/_search_form.html.erb, features/search/works_info.feature, features/search/works_stats.feature
https://otwarchive.atlassian.net/browse/AO3-5020
When editing search, previously selected sort direction value should persist.
1. Go to the work search
2. Select a sort direction from the "Sort direction" dropdown, and any other parameters as needed.
3. Execute the search.
4. Edit Your Search.
5. See if your selected sort direction has persisted on the form
https://otwarchive.atlassian.net/browse/AO3-5017 introduced an automated test for this issue. It was previously commented out, but this pull request enables it.
=> AO3-5020 Remember work search sort direction field value

features/gift_exchanges/challenge_giftexchange_tagsets.feature, features/step_definitions/user_steps.rb, features/step_definitions/work_steps.rb, features/works/work_create.feature, features/works/work_delete.feature
https://otwarchive.atlassian.net/browse/AO3-5074
Enable pending autocomplete feature tests for works & challenges.
Log in before setting up tags in the single-fandom exchange scenario. If we're logged in, touching a tag will set its last wrangler, which runs the tag's after_update hook, which updates Redis for the tag's
fandom-specific autocomplete searches.
Add default pseuds to autocomplete in some user creation steps, similar to features/support/user.rb.
=> AO3-5074 Resurrect autocomplete feature tests for works & challenges

app/controllers/chapters_controller.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5066
Fixes issue where users could preview chapters of works they did not own.
1. Log in
3. Fill in required information
4. Press Post Without Preview
5. Follow Add Chapter
6. Fill in required information
7. Press Preview to create a draft
8. Copy the chapter's preview URL from your browser bar -- it will look like http://test.archiveofourown.org/works/###/chapters/###/preview
9. Log out
10. Log in as some other user
11. Paste the chapter's preview URL into your browser and press enter to go there
You should be redirected to the work the chapter belongs to with a message saying, "Sorry, you don't have permission to access the page you were trying to reach."
cresenne, she/her
=> AO3-5066 Fix error where users can preview any chapter

features/other_a/orphan_work.feature, features/other_a/reading.feature
https://otwarchive.atlassian.net/browse/AO3-5071
Adds a 1 second delay to make sure the cache on the byline expires when updating the work authors.
No manual testing is needed, but you might want to restart the other_a test group a few times to make sure the scenario consistently passes. It passed 5 times for me before submitting this.
=> AO3-5071 Intermittent test failures when orphaning co-authored multi-chapter work

features/users/user_delete.feature
https://otwarchive.atlassian.net/browse/AO3-5075
Adds a 1-second delay between posting a work and deleting an account to prevent an intermittent failure in users/user_delete.feature
No manual testing required, but you should restart the users group several times on Travis to make sure this scenario consistently passes. It's passed 4 times for me.
Note: https://otwarchive.atlassian.net/browse/AO3-5071 affects the same group of tests (but a different feature -- this issue is for user_delete, while AO3-5071 is for user_rename), so if you do see failures in the users test group, you'll need to check closely to see what's failing.
=> AO3-5075 Intermittent test failure on deleting a user who co-authored a work

features/step_definitions/orphan_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5078 & https://otwarchive.atlassian.net/browse/AO3-5080
Adds a 1-second delay to the orphaning step definitions to deal with two intermittent test failures in other_a/orphan_series.feature:
AO3-5078:
```
expected to find text "orphaneer (orphan_account)" in "Creator: orphaneer Series Begun: 2017-07-23 Series Updated: 2017-07-23 Stats: Words: 12 Works: 2 Complete: No" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:141:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:14:in `block in with_scope'
./features/step_definitions/web_steps.rb:14:in `with_scope'
./features/step_definitions/web_steps.rb:140:in `/^(?:|I )should see "([^"]*)"(?: within "([^"]*)")?$/' …
```
=> AO3-5078 AO3-5080 Fix two intermittent failures in orphan_series test

features/users/user_rename.feature
https://otwarchive.atlassian.net/browse/AO3-5070
Adds a 1-second delay to resolve an intermittent failure in the users/user_rename.feature scenario for changing your username updating search results. 
No manual testing required, but you should restart the users group several times on Travis to make sure this scenario consistently passes. It's passed about 9 times for me.
Note: https://otwarchive.atlassian.net/browse/AO3-5075 affects the same group of tests (but a different feature -- this issue is for user_rename, while AO3-5075 is for user_delete), so if you _do_ see failures in the users test group, you'll need to check closely to see what's failing.
=> AO3-5070 Intermittent test failure when changing username 

app/helpers/works_helper.rb, app/views/works/_standard_form.html.erb, features/works/work_create.feature
https://otwarchive.atlassian.net/browse/AO3-5069
Prevent 500 error when posting/previewing a new work in a series when other validation errors exist.
1. Log in
3. Fill in all required information EXCEPT a warning
4. Check "This work is part of a series"
5. Choose an existing series or fill in a name for a new one
6. Preview or Post Without Preview
You should see the edit form with a flash warning, the information you filled out in steps 4 and 5 should be persisted, and there should be no link to remove the work from the series. When you get rid of the warning the work should post as normal and be in the series.
Adding/removing existing works from series should work as before.
cresenne, she/her
=> AO3-5069 Prevent new works with series from 500ing when there are validation errors

features/other_a/orphan_work.feature, features/step_definitions/work_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5081
Adds a 1-second delay to the step for editing an existing work to add a co-author. Without this delay, the cache didn't have time to update, so we'd get intermittent test failures in a works/work_create (and probably a few other places I haven't noticed yet). 
The step is only used 5 times in our features, so this won't amount to a significant delay.
No manual testing needed, but we should keep an eye on Codeship the next several times it runs to see if this helped.
=> AO3-5081 Fix intermittent failure in works/work_create

app/views/redirect/show.html.erb, config/routes.rb, features/importing/work_import.feature, features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-5072
The form in http://archiveofourown.org/redirect did not work.
Go to http://archiveofourown.org/redirect
Paste in a URL that has been imported from another archive using the import work function
Press submit
If a redirected work is found, it should take you to that work with a message to update the original link if possible.
If one is not found, it should stay on/return to the redirect search page but present you with this message "We could not find a work imported from that url in the Archive of Our Own, sorry! Try another url?"
However, entering both imported & non imported urls currently takes me to a blank page in Safari.
=> AO3-5072 Fix redirect page

app/models/subscription.rb, spec/models/subscription_spec.rb
AO3 5008: Tweak subscription validation to prevent subscriptions to nonsubscribable models.
First, explicitly validate the types of objects you're allowed to subscribe to. Then add a condition to the subscribable validation so that you don't get a 500 error if subscribable_type is not a real model name, allowing failures to have a consistent format.
=> AO3 5008: Tweak subscription validation

features/importing/work_import_da.feature
https://otwarchive.atlassian.net/browse/AO3-5103
Changes the URL the Deviant Art image importing test was looking for so it stops failing.
No manual testing needed
=> AO3-5103 Deviant Art import test should look for https img src

app/models/tag.rb
https://otwarchive.atlassian.net/browse/AO3-5105
Replace length with count for large tag queries. On staging, the cache must be empty, because this code is running synchronously and it's slow for warning/rating tags even with the smaller amount of data there.
In the short term, posting on staging should be faster.
=> AO3-5105: Use count over length for large tag data

config/application.rb
https://otwarchive.atlassian.net/browse/AO3-5109
As a result of the Rails upgrade, all submit buttons were getting disabled after they were pressed, which caused problems like not being able to preview a work after correcting a validation error resulting from a missing title. 
Refer to JIRA
https://stackoverflow.com/a/44025628
http://edgeguides.rubyonrails.org/configuring.html#configuring-action-view
=> AO3-5109 Rails BOT: Don't auto disable submit buttons after they're pressed

app/models/application_record.rb
https://otwarchive.atlassian.net/browse/AO3-5111
Updates syntax in before save hook to remove deprecation warning.
The sanitizer version should still set properly, but there's no way to test that since we don't actually use it. Tests should run without a zillion deprecation warnings now.
=> AO3-5111: Fix attribute_changed deprecation message

app/controllers/inbox_controller.rb, app/views/inbox/_approve_button.html.erb, app/views/inbox/_reply_button.html.erb, app/views/inbox/show.html.erb, features/comments_and_kudos/inbox.feature, spec/controllers/inbox_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5108
Fixes strong parameter related issue causing errors on inbox filtering.
Inboxes should be filterable again.
=> AO3-5108 Rails BOT: Fix params issue with inbox filtering

app/models/collection_item.rb, config/application.rb
https://otwarchive.atlassian.net/browse/AO3-5110
In Rails 5.0 (#2958), we moved some code out of observers and into the models they actually pertain to, but our application.rb config was still trying to autoload these observers.
None beyond the regression test
=> AO3-5110 Rails BOT: Don't try to autoload observers that no longer exist

app/controllers/collections_controller.rb, app/models/user.rb, app/views/collections/_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5117
Fixes both a small and large bug with collection creation.
If a user with multiple pseuds tries to create a new collection, their default pseud should be automatically selected on the form. If they're feeling contrary and still unselect all of the pseuds, then the collection should still be created without erroring using the default pseud.
=> AO3-5117: Fix bug in collection creation when no pseud was selected

app/mailers/user_mailer.rb, app/models/challenge_signup.rb
https://otwarchive.atlassian.net/browse/AO3-5119
The Rails upgrade fixed a bug that was preventing us from sending an email when challenge sign-ups were deleted. Alas, this email had no text and no formatting, just attachments, so it's not a good email to be sending... and no one missed it, since it has been broken for years. Ergo, this removes the code for sending that email, bringing the behavior in line with what's currently on production.
(I didn't run our massive pile of challenge tests locally, so it would not surprise me if Travis fails and I need to update some tests.)
Refer to JIRA
=> AO3-5119 Rails BOT Don't send deleted sign-up email

features/other_b/series.feature, features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-3958
AO3-3958 was already fixed at some point, I'm just adding tests.
See issue.
=> AO3-3958 Test unescaped HTML in title field when editing work/series

config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-5137
Fixes routing errors for a variety of autocomplete fields, including admin posts, skins, and collection filtering
All the autocompletes should work now
=> AO3-5137: Add catchall route to fix autocomplete errors

config/.rubocop.yml
https://otwarchive.atlassian.net/browse/AO3-5139
Suppress Hound's suggestions similar to this:
> Prefer annotated tokens (like %s) over template tokens (like %{foo}).
None. I tried it locally using RuboCop, with/without the new setting.
```bash
rvm use 2.3.0
gem install rubocop
rubocop -c config/.rubocop.yml app/controllers/admin/admin_invitations_controller.rb
```
=> AO3-5139 Tell Hound to prefer template tokens

app/controllers/admin_posts_controller.rb, features/admins/admin_post_news.feature, features/step_definitions/admin_steps.rb, spec/controllers/admin_posts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5138
Makes sure admin post languages are properly loaded for all actions that need it, thereby preventing a 500 error that would occur when trying to create an admin post with an invalid translated_post_id.
I realized the specs didn't actually cover the proper scenario, but I left them in because why not.
See JIRA
=> AO3-5138 Prevent 500 error when admin post's translated_post_id is invalid

features/works/chapter_edit.feature, lib/creatable.rb
https://otwarchive.atlassian.net/browse/AO3-5130
The Rails 5.0 upgrade introduced co-creator notification, however the email template doesn't handle chapters. If the creatable is a chapter, we'll use the parent work in the notification instead.
See issue. In a local environment I have trouble sending actual emails, so I log them to check the contents:
```ruby
mail = UserMailer.coauthor_notification(pseud.user.id, creation.id, creation.class.name).deliver!
Rails.logger.info mail.body.parts.find { |p| p.content_type.match /html/ }.body.raw_source
```
=> AO3-5130 Rails BOT: Fix co-creator notification for chapter

app/controllers/user_sessions_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5129
Fixes issue with remember_me setting on login not being respected
Log in, click remember me, close browser, reopen - you should still be logged in
=> AO3-5129: Fix issue with remember_me amnesia

app/controllers/api/v1/base_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5142
Fixes the `ActionController::InvalidAuthenticityToken` that occurs when using the mass import API after the upgrade to Rails 5.
curl -L -X POST http://test.archiveofourown.org/api/v1/bookmarks
should return the text `HTTP Token: Access denied.`. And the temp site test site should be able to post stories to the API.
=> AO3-5142 Fix invalid authenticity token error in API

spec/api/api_authorization_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5142
Adds a test which temporarily turns on the forgery protection and verifies that the API still responds correctly (since AO3-5142 caused the API to return a 422 that resulted in a 404 on the remote site)
This is just one automated test.
=> AO3-5142 Add test to check that API works with forgery protection on

app/models/skin.rb
https://otwarchive.atlassian.net/browse/AO3-5147
Removes a period that seemed to be making bundle exec rake skins:load_site_skins fail with:
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/ao3app/app/releases/20170903111536/public/.stylesheets/site/2.0/01-core.css
Make sure the task runs and that you can change your site skin.
=> AO3-5147 Can't load site skins via rake task due to a period in the path

app/controllers/comments_controller.rb, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5148
Fixes issue where replying to a comment from your inbox, with filters set, would error after creating the reply and attempting to redirect you. Also fixes the same issue with the review action from the inbox, and adds a couple of checks for a potentially nil request.referer.
Replying to and approving comments from the inbox should work with or without filters set.
=> AO3-5148: Fix broken redirect when replying from inbox

app/views/layouts/_header.html.erb, app/views/user_sessions/_login.html.erb, app/views/user_sessions/_passwd.html.erb, app/views/user_sessions/new.js.erb, features/admins/admin_invitations.feature, features/admins/authenticate_admins.feature, features/other_a/invite_queue.feature, features/users/authenticate_users.feature, public/stylesheets/site/2.0/03-region-header.css, spec/requests/comments_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5153
Loads header login form with javascript to avoid form caching issues
Form should load when you click the link and go away when you click 'Close' and take you to the full-page login form when you don't have js enabled.
=> AO3-5153: Load header login form dynamically

app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5155
Skips loading page-related data for non-html requests that don't need it.
See issue.
=> AO3-5155: Skip default before_actions for non-html requests

app/models/tag.rb
https://otwarchive.atlassian.net/browse/AO3-5156
The end of the self.works loop in Tag.add_filter_taggings was misplaced, meaning that Tag.reindex_taggables and Tag.reset_filter_count are currently called once for each work in the tag, instead of being called once after all of the filter-taggings have been modified. This meant that the time required to make a new tag canonical is quadratic in the number of works, rather than linear (as it should be).
The purpose of this pull request is to move the end of the loop to the correct place, and hopefully reduce the runtime of Tag.add_filter_taggings.
Since this primarily affects runtime rather than functionality, there's not much to test. But it would be good to make sure that marking a tag as canonical still works as expected (i.e. the works …
=> AO3-5156 Fix misplaced loop end in Tag.add_filter_taggings.

public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-5166
Stops logging the authenticity token in the JavaScript console
See issue
=> AO3-5166 Stop logging the token in the JavaScript console

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5163
Reverts work complete-setting method to old code to fix bug where works going from complete to incomplete didn't have their status updated.
See issue.
=> AO3-5163: Revert work complete-setting method to old code

app/controllers/invite_requests_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5164
Fixes broken lookup form for invites when javascript is enabled.
Go to /invite_requests, add an email, and then look it up - the lookup should work and return the appropriate message.
=> AO3-5164: Ensure admin settings are loaded for invites js request

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/controllers/user_sessions_controller.rb, app/views/errors/auth_error.html.erb, config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-5160
Adds a new error page to handle Invalid Authenticity Token errors, to give users some context for the problem they're running into.
See issue.
=> AO3-5160: Add auth error page

app/controllers/application_controller.rb, public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-5169
Displays auth error message when attempting to submit kudos instead of doing nothing and only having a console error.
See issue.
=> AO3-5169: Improve auth error handling for kudos

features/importing/work_import_da.feature
https://otwarchive.atlassian.net/browse/AO3-5170
Updates our DA importing test to look for the proper image address, since the image has been moved. Sticks fingers in ears and goes lalalalala about the possibility that all images imported from DA are not broken. 
Make sure automated tests pass
=> AO3-5170 Update image address in Deviant Art import test

app/helpers/application_helper.rb, app/views/downloads/_download_afterword.html.erb
https://otwarchive.atlassian.net/browse/AO3-5042
This changes byline and comment links in download files to use absolute, rather than relative URLs.
STR are in the issue, but I found these simpler ones:
1. Log in
3. Fill in required information
4. Post Without Preview
5. Download > HTML
6. Open the downloaded file
Expected: the byline link in the preface and the "drop by the archive and comment" link in the afterword should be absolute.
Actual: those links are relative, so they have hrefs of `file://...` and are broken when viewing the downloaded file locally.
=> AO3-5042 Use _url for absolute links in bylines and download afterword

app/controllers/collections_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5050
Adjusts the collections page subtitle to match other pages like bookmarks, works, etc ([username] - Collections). 
I don't think this is necessary, it's a simple string change. No functionality was added or removed. 
No
MaxwellsDaemon
Him
=> AO3-5050 Modified collections page subtitle to match other controllers.

app/models/challenge_claim.rb, app/views/challenge_claims/_unposted_claim_blurb.html.erb, spec/models/challenge_claim_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5091
Fixes 500 error on claims page caused by deleted users
1. Create a prompt meme challenge and add some prompts
2. Make a throwaway user account
3. Claim a prompt with the new user account
4. Delete the user account
5. Try to access the claims page as the challenge mod
6. Hopefully don't get a 500 error, and see "deleted user" on the claim description instead
(if you do not fill this in, we will use your GitHub account name and will use "they" to avoid …
=> AO3-5091: Fix 500 error on claims page caused by deleted users

app/views/archive_faqs/_faq_index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5011
Moves the "notice" banner above the introductory sentence for a clearer flow of information.
=> AO3-5011 Reorder FAQ intro information

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-4748
On the Unposted Claims page prompt meme mods can see, stops the date a prompt was claimed from being partly hidden under the icon. (We don't usually use `px` for margins, but because we're dealing with an image here, we do. You can check line 49 of this file to see that `65px` is the same margin the headings above the claimed date have.)
Refer to JIRA
=> AO3-4748 Give date on unposted prompt meme claims proper margin

db/migrate/20170919143944_add_indexes_to_nominations.rb
https://otwarchive.atlassian.net/browse/AO3-5176
Add more indexes to tag nominations table for slow queries
Things should not blow up and should ideally run a bit faster
=> AO3-5176: Add more indexes to tag nominations

app/views/downloads/_download_afterword.html.erb, app/views/downloads/_download_chapter.html.erb, app/views/downloads/_download_preface.html.erb
https://otwarchive.atlassian.net/browse/AO3-5042
This changes three more byline instances in chapter partials to use `only_path: false`, in order to make absolute rather than relative links.
STR for chapter bylines are in the issue. I believe they would be similar for the other instances, except you'd need related works and a parent work.
=> A03-5042 Add only_path:false to byline calls in download partials

app/views/users/change_username.html.erb
https://otwarchive.atlassian.net/browse/AO3-5044
Update the warning note shown when changing username. 
Visit `/users/testy/change_username` (replace `testy`) and check that the warning note copy matches what's in the issue. Check that the links are correct.
=> AO3-5044 Update warning about changing username

app/helpers/application_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5085
Remove unused method locales_menu in application_helper, which should have been removed along with locales_controller#set, as part of [AO3-4942](https://otwarchive.atlassian.net/browse/AO3-4942).
Check that we can see the locale list and create/edit locales normally.
=> AO3-5085 Remove unused method locales_menu in application_helper

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4796
Now that we're on Rails 4 and the strong_parameters gem has been removed, we no longer need the [AO3-4795](https://otwarchive.atlassian.net/browse/AO3-4795) fix for filtering by fandom in dashboard.
There's an automated test for this already in #2683. For manual testing, see issue.
=> AO3-4796 Revert strong_parameters fix of AO3-4795

app/models/external_work.rb
https://otwarchive.atlassian.net/browse/AO3-5096
Removes duplicate method in the external work model and uses alias_method instead
No behavior should change. Bookmarks of external works should still be appropriately visible.
=> AO3-5096 Fix an old FIXME by removing a duplicate method

app/models/challenge_models/gift_exchange.rb, app/models/challenge_models/prompt_meme.rb, app/models/preference.rb, lib/challenge_core.rb
https://otwarchive.atlassian.net/browse/AO3-5094
Removes old duplicate code which was fixing an encoding issue that no longer seems to exist.
If you set your time zone to a zone with an ampersand (on your preferences or for a challenge), it should save properly and that should be reflected when you go back to the page.
(if you do not fill this in, we will use your GitHub account name and will use "they" to avoid making assumptions about your gender)
=> AO3-5094 Remove unneeded time zone hack

app/models/comment.rb, spec/models/comment_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5131
Prevents the uniqueness validation on comments from blocking deletion
Testing notes in ticket
=> AO3-5131 Skip uniqueness validation for deleted comments

app/controllers/downloads_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5159
Fixes issues with some pdf downloads erroring because of a wkhtmltopdf issue.
PDFs should generate correctly for all works.
=> AO3-5159 Fix broken pdf downloads by adding flag to disable javascript

app/views/comments/_comment_actions.html.erb
https://otwarchive.atlassian.net/browse/AO3-5144
Adds a 'parent thread' link to comments.
Reply to comments, see that the link appears and takes you to the right place.
=> AO3-5144 Add parent thread link for comments

app/views/users/change_username.html.erb
https://otwarchive.atlassian.net/browse/AO3-5044
Tweak wording in change username warning copy.
See issue - this PR changes "and" to "or" only.
=> AO3-5044 Change 'and' to 'or' in note about changing your username

app/controllers/collection_items_controller.rb, features/collections/collection_invite.feature, features/step_definitions/preferences_steps.rb
Forbid adding works belonging to others to unrevealed/hidden or
anonymous collections directly. Remove tests that assumed collection
moderators could do invite or add works to such collections.
Due to the removal of Carriage Returns at the end of lines please review by adding ?w=1 to the URL as per https://github.com/blog/967-github-secrets 
https://otwarchive.atlassian.net/browse/AO3-5016
This PR prevents moderators of collections from directly inviting or adding items to collections that are hidden or unrevealed. Item authors will still be able to add items to such collections. 
As User A, make an anonymous and/or unrevealed collection: 
1. Log in as User A
2. Browse > Collections > New …
=> AO3-5016 Forbid inviting items to anon collections

app/helpers/works_helper.rb, app/models/skin.rb, app/views/works/_standard_form.html.erb, factories/skins.rb, features/step_definitions/user_steps.rb, features/works/work_edit.feature, features/works/work_edit_multiple.feature, spec/helpers/works_helper_spec.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3704
Users can now add coauthors' work skins to works from the Edit Work page. Users still won't be able to add coauthors' work skins from the Edit Multiple Works page.
1. Create a work with a work skin
2. Add a co-author
3. Post work
4. Have co-author edit work
If bugfix is working, co-author should be able to edit work without original author's work skin getting stripped. They should also be able to add or remove their coauthor's work skin at any time.
=> AO3-3704 Users can add coauthor work skins to works

app/models/story_parser.rb, features/importing/archivist.feature
https://otwarchive.atlassian.net/browse/AO3-5058
This simplifies an error message that was too verbose as discovered when testing on Test.
Same as previously for this ticket.
=> AO3-5058 Simplify archivist error message when no email or author specified

features/importing/work_import_dw.feature
https://otwarchive.atlassian.net/browse/AO3-5189
This makes the DW importing tests use the `ao3testing` DW account instead of scraping the journal of a former volunteer.
Automated tests only, no functional changes.
=> AO3-5189 Amend the Dreamwidth tests to use the ao3testing journal

app/controllers/downloads_controller.rb, app/models/work.rb
https://otwarchive.atlassian.net/browse/AO3-5188
Remove the dependancy on the shared storage.
Do downloads work ?
=> AO3-5188 Remove the dependency on the shared storage for downloads.

app/controllers/downloads_controller.rb
https://otwarchive.atlassian.net/browse/AO3-*5188
Check the downloads work...
=> AO3-5188 (BOT) Make downloads synchronous

config/initializers/gem-plugin_config/sanitizer_config.rb, lib/tasks/after_tasks.rake, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5192
Adds code to upgrade embeds to https where supported and a rake task to update current chapters.
See issue.
=> AO3-5192: Convert embeds to https where appropriate

config/initializers/gem-plugin_config/sanitizer_config.rb, lib/tasks/after_tasks.rake, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5192
Expand https list
See issue
=> AO3-5192: Add sites to https list, rescue to after task

lib/tasks/opendoors.rake
https://otwarchive.atlassian.net/browse/AO3-5125
Adds a task to map Open Doors imports to their original urls via csv files
Will work with Ariana to test this - I believe you'll be able to see the updated import urls on the admin backend
=> AO3-5125 Map Open Doors temp site URLs to original site URLs

lib/word_counter.rb, spec/lib/word_counter_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5197
Fixes errors when running word count on empty strings
See issue.
=> AO3-5197: Avoid errors when word counting empty strings

lib/skin_wizard.rb
https://otwarchive.atlassian.net/browse/AO3-4840
Changing the header color from red in the skin wizard should also change the red border on the Reindex Work button.
Sorry for the low-priority pull request, but I was already in the file for #2721
=> AO3-4840 Skin wizard should change bottom border on Reindex Work button

features/other_b/series.feature, features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-5082
Adds a 1-second delay to tests for removing yourself as the co-author of a work or series, since the byline cache needs time to update. Comment out the test for removing yourself as the co-author of a series, since it turns out that's an actual bug. Refactor slightly to use the pretty step definition for checking the author(s) displayed on a work or series page.
No manual testing required, but keep an eye on Codeship and Travis to make sure this has improved the situation and we see fewer failures in other_b/series.feature and works/work_edit.feature.
=> AO3-5082 Intermittent test failure when removing self as co-author of series or work

db/migrate/20170922234741_add_index_to_preferences.rb
https://otwarchive.atlassian.net/browse/AO3-5183
Adds an index to the preferences table in hopes that it will speed up the approved skins page enough for us to access it again.
Can't really be tested
=> AO3-5183 Index preferences on skin_id

app/controllers/downloads_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5199
Skips generating unneeded html files that fill up disk space
Make sure mobi and epub generation still works
=> AO3-5199: Don't generate extra html files

app/models/abuse_report.rb
https://otwarchive.atlassian.net/browse/AO3-5201
Allow users to report users and works when using http://insecure.archiveofourown.org/abuse_reports
I think this can only be tested on beta.
=> AO3-5201 Add insecure to list of urls allowed to report

app/controllers/downloads_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5202
Fix a minor typo.
MOBI downloads should work on Kindle devices.
=> AO3-5202 Fix MIME type for MOBI downloads

app/models/search/bookmark_query.rb, features/bookmarks/bookmark_browse.feature, features/support/paths.rb
https://otwarchive.atlassian.net/browse/AO3-4815
Updates bookmark search to use user ids for filtering on user pages, which should also fix an issue with some bookmarks not appearing on user pages.
All of a user's bookmarks should appear on their user bookmarks page.
=> AO3-4815: Ensure correct results when browsing bookmarks by user

app/models/search/work_indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5213
Fixes the indexing type for the authors_to_sort_on field for works so that it can be used for sorting.
When works are reindexed, you should be able to sort by author without getting an error.
=> AO3-5213 Index authors on works correctly for sorting

app/models/work.rb
https://otwarchive.atlassian.net/browse/AO3-5212
Fixes the user ids indexed for works (in both the works index and the bookmarks index) to match the actual user ids and not the pseud ids. Also, I looked up a couple of new tag ids for work types, which is not especially significant at the present time but good to have if we're reindexing.
The correct works should appear on a /users/foo/works page
=> AO3-5212: Index correct user ids for works

app/helpers/users_helper.rb, app/models/search/bookmark_search_form.rb, app/models/search/query.rb, app/models/search/work_search_form.rb, features/users/user_dashboard.feature
https://otwarchive.atlassian.net/browse/AO3-5225
Fixes sidebar counts and uses user ids where available instead of pseud ids. Also simplifies things a bit since we already have default visibility logic in the query classes.
Sidebar counts should be correct when logged in or out for both works and bookmarks, on user pages and on pseud pages.
=> AO3-5225: Fix sidebar counts and scope by user id if a user is present

app/models/invite_request.rb, app/validators/email_veracity_validator.rb, db/migrate/20171030201300_add_simplified_email_to_invite_requests.rb, db/migrate/20171030220348_add_index_to_invite_queue_emails.rb, factories/invitations.rb, spec/models/invite_request_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5205
Prevents users from requesting invites multiple times for the same email address. Also fixes the validator to require a full domain.
See issue.
=> AO3-5205: Prevent sign ups with duplicate emails in the invite queue

spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5236
Changes timeframe in abuse report test to avoid conflicts where "1 month" is sometimes not far enough in the future for the report limiting tests to pass. 
Purely automated test-related.
=> AO3-5236: Change timeframe in failing test

app/controllers/invite_requests_controller.rb, spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5235
When the queue is disabled, users can still request invitations, even if those don't get sent out. Users should not be able to.
=> AO3-5235 Block requesting invitations when the queue is disabled

features/gift_exchanges/challenge_giftexchange.feature
https://otwarchive.atlassian.net/browse/AO3-5240
Reverts a test broken in the Rails 4 upgrade due to a change of timezone.
Automated test only.
https://otwarchive.atlassian.net/browse/AO3-4132 (original fix)
=> AO3-5240 Revert timezone in gift exchange test to Papua New Guinea again

config/initializers/gem-plugin_config/sanitizer_config.rb, lib/html_cleaner.rb, spec/lib/html_cleaner_spec.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4200
Adds rel="nofollow" to all <a> tags in sanitised fields to reduce their usefulness as SEO-boosters for spam.
See JIRA.
=> AO3-4200 Add rel=nofollow to links to reduce SEO usefulness for spammers

app/controllers/invite_requests_controller.rb, app/views/home/_intro_module.html.erb, app/views/invite_requests/_index_closed.html.erb, features/other_a/invite_queue.feature, spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4222
Fix links to news posts tagged "invitations" added in AO3-4222 and AO3-5235. Fix capitalization of "spam" in an error message to make it match the capitalization we use elsewhere.
Refer to JIRA
=> AO3-4222 Fix links to news post tag and capitalization of spam

app/controllers/invite_requests_controller.rb, app/views/invite_requests/manage.html.erb, features/other_a/invite_queue.feature, public/javascripts/application.js, spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5243
Uses JavaScript to make it so the page doesn't reload after the deletion of a given invitation request.
Refer to JIRA
=> AO3-5243 Use AJAX to delete invitation requests

app/controllers/invite_requests_controller.rb, spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4971
Display a notice instead of an error page when admins delete non-existent invite requests.
See issue.
=> AO3-4971 Display notice when deleting non-existent invite requests

app/views/admin_mailer/send_spam_alert.html.erb, app/views/admin_mailer/send_spam_alert.text.erb, app/views/user_mailer/invite_request_declined.html.erb
https://otwarchive.atlassian.net/browse/AO3-5247
Resque was loaded with errors like: 
```
undefined method `user_works_path' for #<#<Class:0x000000088772a8>:0x00000008874c88> Did you mean? user_works_url
```
This applies the helpful suggestion to the spam alert email _and_ the invite_request_decline email, which our our only two instances of `_path` helpers in mailers.
Refer to JIRA.
=> AO3-5247 Use _url helper in spam alert email

app/controllers/admin/settings_controller.rb, app/controllers/admin/spam_controller.rb, app/controllers/admin/user_creations_controller.rb, app/models/moderated_work.rb, app/models/work.rb, app/views/admin/_header.html.erb, app/views/admin/settings/index.html.erb, app/views/admin/spam/index.html.erb, config/routes.rb, db/migrate/20171031204025_create_moderated_works.rb, db/migrate/20171114212142_add_spam_hiding_to_admin_settings.rb, features/admins/admin_spam.feature, public/javascripts/select_all.js, public/stylesheets/site/2.0/08-actions.css, spec/models/moderated_work_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5234
* Adds spam work review page for admins
* Adds admin setting to control whether spam works should automatically be hidden or not
See issue
=> AO3-5234 Moderate Works

app/controllers/invite_requests_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5243
Makes sure we're finding the proper invite request to delete
Try deleting and invite request and make sure the right one gets deleted
=> AO3-5243 Use correct finder when destroying invite requests

spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4971
Add a test that fails without the fix in #3163.
=> AO3-4971 Add test for deleting the specified invite request

app/mailers/user_mailer.rb, app/models/work.rb, app/views/admin/settings/index.html.erb, app/views/user_mailer/admin_spam_work_notification.html.erb, app/views/user_mailer/admin_spam_work_notification.text.erb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5251
Adds a more specific email that goes out when a work is hidden as spam.
Mark a work as spam and determine that the correct email arrives.
=> AO3-5251: Add spam-specific hidden work email

app/models/moderated_work.rb, app/views/admin/spam/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5234
Adds a subnav with links to view already-reviewed works on the admin spam page. Also tweaks method return values to prevent misleading error messages when changes have actually gone through.
Should be able to view reviewed/approved works and should not get an error when changes have saved.
=> AO3-5234: Add links, fix false errors on spam page

app/models/moderated_work.rb, app/views/admin/spam/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5234
Allows admins to reverse approving spam works and updates some language
When you view approved works on the spam page and mark them as spam again, that should un-approve them and change the works back to spam and hide them
=> AO3-5234: Fix for unapproving approved works

app/views/readings/_reading_blurb.html.erb, features/other_a/reading.feature
https://otwarchive.atlassian.net/browse/AO3-4138
in reading history, changes "last viewed: (date)" and "viewed: (number)" to "last visited" and "visited"
please go to your reading history and confirm that the text bar under each work in your history now says "last visited: (date)" and "visited: (number)"
the initial pr was closed; sorry about that
=> AO3-4138 make reading history more linguistically accessible

config/initializers/gem-plugin_config/sanitizer_config.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5086
Allow embeds from the open subdomain for Spotify. According to the issue, we no longer need to support the old embed subdomain. 
See issue
=> AO3-5086 Update Spotify subdomain for embeds

app/controllers/admin_posts_controller.rb, features/admins/admin_post_news.feature, features/step_definitions/admin_steps.rb, features/step_definitions/generic_steps.rb
https://otwarchive.atlassian.net/browse/AO3-4187
When filtering news posts, if a language is selected, the tag dropdown will have all tags across all posts of that language, instead of being empty.
See issue.
=> AO3-4187 Fix empty tag dropdown when filtering news posts

public/help/skins-creating.html
https://otwarchive.atlassian.net/browse/AO3-5203
the use of paragraphs in the css help documentation was inconsistent.
please go to https://archiveofourown.org/help/skins-creating.html and check that the spacing is consistent throughout the document.
=> AO3-5203 giving CSS help documentation consistent spacing

spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5086
Fixes last test reference to old spotify subdomain
=> AO3-5086: Fix last reference to old spotify subdomain

app/models/bookmark_search.rb, app/models/search/bookmark_query.rb, app/models/search/bookmark_search_form.rb, app/views/bookmarks/search_results.html.erb, features/bookmarks/bookmark_search.feature, features/step_definitions/bookmark_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5230
- Parse date updated and date bookmarked filters
- Unescape < and > characters
- Avoid re-escaping < and > characters in search summary
- Remove unused references to "bookmarkable_word_count"
See issue.
=> AO3-5230 Fix range filters in bookmark search

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5254
Upgrades the elasticsearch gem to match the new version.
See general issue testing.
=> AO3-5254: Upgrade elasticsearch gem to 6.0.0

app/views/user_mailer/coauthor_notification.html.erb, app/views/user_mailer/coauthor_notification.text.erb, config/locales/en.yml, features/works/work_create.feature
https://otwarchive.atlassian.net/browse/AO3-5260
What it says on the tin 
Add a co-creator to a work and a series and check the resultant notif emails for names
=> AO3-5280 Add co-creator names to co-creator emails

app/controllers/works_controller.rb, app/models/search/query_cleaner.rb, app/models/work_search.rb, spec/controllers/works/default_rails_actions_spec.rb, spec/models/query_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5262
https://otwarchive.atlassian.net/browse/AO3-3576
Extracts the query cleanup code from the works controller into a separate class. Also ended up fixing the weird category-escaping-overreach bug.
Behavior should be the same, other than the category tag escaping, which should now be case-insensitive, but should only match when the letters are not part of larger words.
=> AO3-5262: Move query cleaning out of the works controller

app/models/search.rb, spec/models/work_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5229
Fix error encountered when a user enters a very large date in date search. Since we're really just concerned with things posted by contemporaneous people, a simple fix should suffice for now.
Entering a large value in date search should no longer error.
=> AO3-5229: Simple fix for ancient date errors

app/models/search/tag_query.rb
https://otwarchive.atlassian.net/browse/AO3-5265
Change the query type for tag names in tag search to allow people to do partial matching
Partial searches with asterisks should return results
=> AO3-5265: Switch tag name search back to a query string

app/models/search/bookmark_query.rb, spec/models/bookmark_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5264
Fixes bookmark search to use 'AND' as the default operator, to match other search behavior.
Bookmark searches for multiple words/terms should return results that match all of them, not any one of them.
=> AO3-5264: Set operator for bookmark search

app/controllers/people_controller.rb, app/controllers/related_works_controller.rb, app/controllers/users_controller.rb, app/decorators/pseud_decorator.rb, app/helpers/users_helper.rb, app/models/bookmark.rb, app/models/search/pseud_indexer.rb, app/models/search/pseud_query.rb, app/models/search/pseud_search_form.rb, app/models/search/query_result.rb, app/models/tag.rb, app/models/work.rb, app/views/people/_author_blurb.html.erb, app/views/people/_new_search_form.html.erb, app/views/people/index.html.erb, app/views/people/search.html.erb, features/collections/collection_navigation.feature, features/fixtures/filter_taggings.yml, features/other_a/pseuds_special_characters.feature, features/search/people_search.feature, features/step_definitions/user_steps.rb, spec/models/pseud_decorator_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5226
https://otwarchive.atlassian.net/browse/AO3-5151
Updates people search to add an autocomplete field and a fandom search. Also simplifies some unnecessary people pages that we weren't really using.
See issue.
=> AO3-5226: People Search

app/models/search/bookmarkable_query.rb, spec/models/bookmarkable_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5273
Fixes an issue where private bookmarks were being counted in filters if the work/series had other public bookmarks.
Because works/series/external works can have multiple bookmarks, the child filters have to be combined into one query of their own or else incorrect results may be returned. 
See issue.
=> AO3-5273: Fix child queries for bookmark filter data

app/helpers/application_helper.rb, app/views/bookmarks/_filters.html.erb, app/views/collections/_filters.html.erb, app/views/works/_collection_filters.html.erb, app/views/works/_filters.html.erb, public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5274
Uses [this technique](https://www.sitepoint.com/replacing-radio-buttons-without-replacing-radio-buttons/) to update the styling of the input elements on our filters with the specific goal of making it easier to tell if the selected item is selected for inclusion or exclusion as you scroll down the page.
Refer to JIRA
=> AO3-5274 Create visual distinction between exclusion and inclusion checkboxes

app/models/work.rb, spec/models/work_search_form_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5269
The hyphen should be escaped, otherwise we're removing the first character if it's anything in the range from "+" to "=".
See issue.
=> AO3-5269 Fix regex for getting sortable work authors

app/views/fandoms/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5277
Changes the class name on the Fandoms page media selection form so it won't get the `.filters` styling the was making the "Show" button huge. Code- and design-wise, the form's really not what we consider a filter, but I still went with "filter" rather than "navigation" so I wouldn't feel weird not changing the heading right above it. :P 
Refer to issue
=> AO3-5277 Shrink "Show" button on collection Fandoms page

app/models/search/bookmark_indexer.rb, app/models/search/indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5279
When the BookmarkIndexer tries to look up a bookmark that's been deleted, the object associated with the deleted ID will be nil. The parent_id function tries to call object.id if the object is nil; instead, it should take the object's ID as an argument and use that to access the information it needs.
Try deleting a bookmark, wait a while, and then check the logs to see if there has been an error.
=> AO3-5279 - Deleting bookmarks causes error in BookmarkIndexer.

app/models/external_work.rb, app/models/indexing/index_queue.rb, app/models/indexing/index_subqueue.rb, app/models/indexing/scheduled_reindex_job.rb, app/models/series.rb, app/models/work.rb, spec/models/index_queue_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5280
This pull request does three things to try to fix the indexing of ExternalWorks and Series:
1. Add Series and ExternalWork to the list of classes indexed by ScheduledReindexJob.
2. Refactor the logic of IndexQueue and IndexSubqueue so that IndexSubqueue won't handle ExternalWorks or Series (since it would cause IndexSubqueue.klass to fail with an error).
3. Remove the unnecessary `id: "external_work-#{id}"` field (and similar) from bookmarkable_json, since it apparently causes ES to error when re-indexing a document. (Credit to WendyBeth for figuring out this issue and the fix in #3122.)
Testing instructions are in the bug report.
=> AO3-5280 - Make the scheduled reindexing job index ExternalWorks and Series.

app/models/indexing/index_subqueue.rb
https://otwarchive.atlassian.net/browse/AO3-5281
Fixes the StatCounter indexing code in IndexSubqueue to avoid incorrect nesting.
See bug report.
=> AO3-5281 - Don't nest stat updates inside work field. [Old indexing code.]

app/models/tag.rb, app/models/tag_search.rb
https://otwarchive.atlassian.net/browse/AO3-5284
The purpose of this pull request is to modify the fields that are indexed for Tags to ensure that it's possible to search by type. Currently, the tags on the archive can be divided into three categories:
1. **Tags manually indexed with reindex_document, or indexed before the IndexSubqueue code was written.** These tags have their _type set to, e.g. "fandom" or "character," and since the search code currently only checks the _type field, these are the only tags that will be returned in the search.
2. **Tags indexed with the IndexSubqueue code.** These tags have their _type set to "tag" (meaning they won't be returned by the current search code) and the JSON documents that are sent to ES contain no fields relating to their type. In order to …
=> AO3-5284 - Fix searching tags by type. [Old indexing code.]

app/decorators/pseud_decorator.rb, app/models/search/pseud_indexer.rb, spec/models/pseud_decorator_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5278
Fixes 500 error when searching people, which happened because values were set to nil for users with no public works.
See issue.
=> AO3-5278: Fix pseud search error when logged out

features/gift_exchanges/challenge_giftexchange.feature, features/step_definitions/generic_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5289
Fixes failing timezone test caused by CI operating system upgrades (https://unix.stackexchange.com/questions/359684/why-is-timezone-displayed-as-a-number)
Only affects automated tests.
=> AO3-5289: Fix timezone feature failure

app/models/bookmark.rb, app/models/creatorship.rb, app/models/filter_tagging.rb, app/models/indexing/index_queue.rb, app/models/indexing/scheduled_reindex_job.rb, app/models/tag.rb, app/models/work.rb, features/search/people_search.feature
https://otwarchive.atlassian.net/browse/AO3-5292
This pull request fixes the issue with `[pseuds.pluck(:id)]` in Work.update_pseud_index, and adds several more callbacks to ensure that the pseud indexes are updated whenever an author is added or removed, and whenever a filterable fandom is added or removed.
In order to avoid the duplicate work that might occur when more than one callback is triggered at a time (e.g. when someone simultaneously adds a co-author and a fandom, or simultaneously posts the work while adding a co-author), I also switched over to using IndexQueue for all of the pseud reindexing. That way, since the IndexQueue stores all of the IDs to be indexed as a REDIS set, any duplicate calls should be ignored.
See the bug report for details.
=> AO3-5292 - Ensure people search is updated when works are posted, and cover more types of work editing.

app/models/search/async_indexer.rb, app/models/search/index_sweeper.rb, app/models/search/indexer.rb, spec/models/index_sweeper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5218
Adds a callback to successful_reindex to the IndexSweeper, so that when the Works index is updated in Elasticsearch, the cache will be busted for each of the work's pseuds, collections, and filters.
I also renamed "process_batch_failures" to "process_batch," because it's processing successes in addition to failures now.
This one's a bit hard to test since it's a caching issue, but hopefully there should be less of a delay before Works start showing up on various index pages.
=> AO3-5218 - Add successful_reindex callback.

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5294
Within a controller, current_user always contains either a User item, or nil. (Note that this behaves differently from User.current_user, which can contain an Admin item, a User item, or nil.) So when an admin is logged in, current_user is nil.
Currently, the WorksController calculates the cache key by *only* checking current_user, so the cache key for admins is the same as the cache key for logged-out users. As a result, if an admin views a Works page before a logged-out user, the logged-out user may be able to see restricted works from the cache. And if a logged-out user views a Works page before an admin, the admin may not be able to see restricted works on that page.
See the bug report for some testing steps.
=> AO3-5294 Fix cache key calculation for admins.

app/models/search/bookmark_query.rb
https://otwarchive.atlassian.net/browse/AO3-5291
The Browse > Bookmarks page can sometimes show restricted works as a result of caching.
When viewing the Browse > Bookmarks page with caching enabled, the BookmarksController sets :show_restricted to false. However, the definition of include_restricted? in the BookmarkQuery class will override the explicit :show_restricted value for logged-in users and logged-in admins. So the BookmarksController will put bookmarks of restricted works in the cache -- a cache that's shared with logged-out users.
This pull request fixes the definition of include_restricted? in the BookmarkQuery class so that if someone sets :show_restricted to false, the value won't be overridden.
(I don't think there's a way to have private bookmarks pop up on the Browse > …
=> AO3-5291 Prevent Browse > Bookmarks page from showing restricted bookmarks to logged-out users.

app/models/search/bookmarkable_indexer.rb, spec/models/async_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5309
This PR is intended to make the IndexSweeper's retries work properly with the three BookmarkableIndexer subclasses: BookmarkedWorkIndexer, BookmarkedSeriesIndexer, and BookmarkedExternalWorkIndexer.
Previously, each retry in IndexSweeper would append an extra suffix, resulting in incorrect failure handling. This pull request overrides BookmarkableIndexer.find_elasticsearch_ids to make sure that the suffix is stripped in indexSweeper before the ID is passed along to a BookmarkableIndexer and the suffix is re-added.
This one is very difficult to test manually. I think you'd have to deliberately modify the code to produce an error, and then watch the failure stores. One way to consistently produce errors is to modify the line `@batch << …
=> AO3-5309 Remove bookmarkable suffix in IndexSweeper.

app/controllers/feedbacks_controller.rb, app/mailers/admin_mailer.rb, app/models/feedback.rb, app/models/feedback_reporters/support_reporter.rb, app/views/admin_mailer/feedback.html.erb, app/views/admin_mailer/feedback.text.erb, app/views/feedbacks/new.html.erb, app/views/feedbacks/report.xml.erb, db/migrate/20180108220405_add_rollout_to_feedbacks.rb
https://otwarchive.atlassian.net/browse/AO3-5311
Adds a method for passing rollout information to Support (it's kind of unnecessarily complex because we might use rollout for two features, even though we do not currently). Uses said method to pass Elasticsearch version info to both the ticket tracker and mailing list.
Refer to Jira.
=> AO3-5311 Add user's rollout info to support tickets

app/models/search/bookmark_query.rb
https://otwarchive.atlassian.net/browse/AO3-5318
This PR changes the check in BookmarkQuery.type_filter to check whether the bookmarkable_type is present, instead of checking whether it's non-nil. This should make bookmark search work properly again.
See bug report.
=> AO3-5318 Fix for blank bookmarkable_type.

app/models/search/pseud_indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5302
Previously, if a user had bookmarked an item (work, series, external work) was hidden by an admin, the bookmark total in the people search results would include that work. This uses the [visible_to_all scope](https://github.com/otwcode/otwarchive/blob/c39b474a079243c52a956511b64a72d0ba956f80/app/models/bookmark.rb#L57) to fix that.
Refer to Jira
=> AO3-5302 Only count bookmarks of visible items for people search

app/decorators/pseud_decorator.rb, app/models/search/pseud_indexer.rb, spec/models/pseud_decorator_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5303
Currently, people search results are telling _everyone_, logged in or out, how many public bookmarks a user has of _both_ public and restricted items (works, series, external works). This makes it so logged out users see a total that only includes public bookmarks of public items, while logged in users continue to see a total that includes public bookmarks of both public and restricted items.
Refer to Jira
Builds off #3223 -- you could honestly just merge this and close that, as long as you update both issues.
=> AO3-5303 People search bookmark count should respect bookmarkable privacy

app/models/work.rb
https://otwarchive.atlassian.net/browse/AO3-5295
Tweaks crossover index logic so that a work with one fandom is never counted as a crossover, as that's proved to be technically possible via tag wrangling.
See issue.
=> AO3-5295: Never count a work with one fandom as a crossover

app/decorators/pseud_decorator.rb, app/models/search/pseud_indexer.rb, app/models/search/pseud_query.rb, spec/models/pseud_decorator_spec.rb, spec/models/pseud_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5304
For logged out users:
- If a pseud has works in the specified fandom, but all of them are restricted, do not include the pseud in search results.
- Do not include the restricted works in the fandom-specific total.
=> AO3-5304 Filter restricted works in people search by fandoms

app/models/search/work_query.rb, spec/models/work_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5299
For the "Date Updated" filter, the front-end sends date strings that may be unparseable for Ruby (e.g. 2017-12-32) or Elasticsearch (10000-12-31). Avoid 500s in these cases.
See JIRA.
=> AO3-5299 Rescue unparseable absolute date filters

app/models/search/indexer.rb, app/models/search/query.rb, app/models/search/tag_indexer.rb, app/models/search/tag_query.rb, spec/models/search/tag_query_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5265
This PR amends the tag search and query code such that the following examples are true:
* performs a case-insensitive search (AbC matches abc)
* performs a query string search (ab or cd matches ab cd)
* lists exact matches (without punctuation) at the top of the results (abc result lists abc or abc+ first)
* matches every token (d abc matches abc d and abc-d, but not abc or abc+)
* performs a wildcard search at the end of a term (abc* matches abcd and abcde)
* performs a wildcard search in the middle of a term (a*d matches abcd)
* performs a wildcard search at the beginning of a term (*cd matches abcd)
* preserves plus (+) character (abc+ matches abc+ and abc, but not abccc)
* preserves minus (-) character (abc-d matches abc-d, abc -d, abc …
=> AO3-5265 Change tag search back to querystring and ensure exact results are near top

app/models/bookmark.rb
https://otwarchive.atlassian.net/browse/AO3-5325
Reindexes pseuds if an admin hides (or unhides) a bookmark.
Refer to JIRA
=> AO3-5325 Reindex pseuds when bookmarks are hidden

app/models/search/bookmark_query.rb
https://otwarchive.atlassian.net/browse/AO3-5225
The bookmark count in the sidebar of pseud pages is broken, because the `BookmarkQuery.user_ids` function checks for the existence of `options[:pseud_ids]`, then uses `options[:pseud_id]` instead. This pull request fixes the typo (and fixes another issue that I noticed, where an admin could potentially be mistaken for the user with the same ID).
Log in as someone with multiple pseuds and at least one private bookmark, and check whether the private bookmark is included in the sidebar count for the pseud with the bookmark.
=> AO3-5225 Fix include_private? when pseud_ids are specified.

app/models/series.rb, app/models/work.rb, lib/bookmarkable.rb, spec/models/index_queue_spec.rb, spec/models/pseud_search_form_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5326
When a work or a series becomes (un)restricted, we need to reindex its bookmarkers so they get the correct public/general bookmark counts.
External works can't be restricted, so they're fine.
The new specs run the indexing jobs (instead of totally refreshing ES), similar to the feature tests in #3206.
=> AO3-5326 Reindex bookmarker pseuds when bookmarkables change restricted status

app/models/external_work.rb, app/models/series.rb, factories/series.rb, spec/models/pseud_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5327
When a work or a series or an external work becomes hidden by admin, we need to reindex its bookmarkers so they get the correct public/general bookmark counts.
Similar to #3236.
=> AO3-5327 Reindex bookmarker pseuds when bookmarkables change hidden by admin status

spec/models/pseud_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5327
~Without the reload call, update_attribute fails, with bookmarkable.errors containing an error with no messages. I don't know why this happens. Years from now, if you figure this out, please let me know.~
When a series and its work are first created, the series loads an empty collection of bookmarks, which stays unupdated when we pluck the bookmark IDs to reindex bookmarker pseuds, so no pseuds get reindexed. We need to reload the series.
The test was introduced in #3238.
=> AO3-5327 Fix the test that hides a series being bookmarked

app/controllers/admin/user_creations_controller.rb, app/views/admin/_admin_options.html.erb, app/views/series/show.html.erb, features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-5324
- Adds Series to the whitelist to prevent the 500 error that was stopping us from hiding them
- Makes it so the button to hide a series correctly says Hide Series (instead of Hide Work)
- Add a red lock to the series show page to make it clearer to the admin and the series owners that the series has been hidden
Log in as an admin, press the "Hide Series" button on a series, and confirm that a success message and a red lock icon appear. Use the "Make Series Visible" icon and confirm that a success message appears and the red lock icon goes away.
=> AO3-5324 Re-allow hiding of series by admin

app/controllers/invitations_controller.rb, app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-5319
Check ownership of invitations before allowing access.
Previously any user could access invitations, allowing reading private email addresses and stealing invitations. Now only the user who created the invitation or an admin may view them.
Some invitations code was also refactored to use a shared `load_invitation` method.
Invitations should be viewable by only the creator or an admin. Other users should receive an error, even if they attempt to access the invitation directly.
Issue was initially reported to ADT …
=> AO3-5319 Invitation ownership

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5339
Upgrade nokogiri to 1.8.2.
Posting and importing works should still work. See JIRA issue.
=> AO3-5339 Upgrade nokogiri to 1.8.2

factories/tags.rb, features/tags_and_wrangling/tag_wrangling_more.feature, spec/controllers/autocomplete_controller_spec.rb, spec/controllers/tags_controller_spec.rb, spec/controllers/works/default_rails_actions_spec.rb, spec/models/pseud_search_form_spec.rb, spec/models/tag_spec.rb, spec/models/work_search_form_exclusion_filters_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5337
Tags when first created are not canonical until wranglers make them. Tests should reflect that: only make canonical tags when we have to (for autocomplete, search indexing, etc.)
=> AO3-5337 Update factories to make non-canonical tags by default

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5336
Works tagged with multiple synonyms of the same relationship should still qualify as OTP.
See issue.
=> AO3-5336 Fix OTP filter to account for synonymous relationships

app/views/bookmarks/_filters.html.erb, public/help/bookmark-search-bookmarker-tags-notes-help.html, public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5355
The filters should now have fields for:
- Other work tags to include
- Other bookmarker's tags to include
- Other work tags to exclude
- Other bookmarker's tags to exclude
- Search bookmarker's tags and notes (note: this is named "Search within bookmarker's tags and notes" in the mockup")
This fields won't do anything yet. The "Search bookmarker's tags and notes" will have a help pop-up, but it is currently empty.
Refer to Jira
=> AO3-5355 Add new fields to bookmark filters

app/models/bookmark.rb, app/models/search/bookmark_query.rb, app/models/search/pseud_indexer.rb, features/bookmarks/delete_bookmarkable.feature, features/step_definitions/series_steps.rb, lib/bookmarkable.rb, spec/models/bookmark_query_spec.rb, spec/models/bookmarkable_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5340
The purpose of this pull request is to make sure that bookmarks of deleted items (works, series, or external works) don't completely disappear. In order to accomplish this, I made the following changes:
1. Modify the bookmarkable visibility filters in BookmarkQuery so that instead of requiring the bookmarkable be unhidden, unrestricted, and posted, it requires *not* having a hidden, restricted, or unposted bookmarkable. A non-existent bookmarkable can't have hidden_by_admin set to false, but it won't have hidden_by_admin set to true, so this reversal results in bookmarks of deleted works being included in searches. (This is inspired by Elz's plans several months ago.)
2. Modify the bookmark counts in the pseud search to include bookmarks of …
=> AO3-5340 Show bookmarks of deleted items.

spec/models/pseud_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5358
Stop using randomly-generated bookmarker pseud names.
No manual testing required. I had this run 10 times without failures on Travis by changing .travis.yml to use:
```yml
env:
- ES=1 TEST_GROUP="rspec spec" RUN=1
- ES=1 TEST_GROUP="rspec spec" RUN=2
- ES=1 TEST_GROUP="rspec spec" RUN=3
- ES=1 TEST_GROUP="rspec spec" RUN=4
- ES=1 TEST_GROUP="rspec spec" RUN=5
- ES=1 TEST_GROUP="rspec spec" RUN=6
- ES=1 TEST_GROUP="rspec spec" RUN=7
- ES=1 TEST_GROUP="rspec spec" RUN=8
- ES=1 TEST_GROUP="rspec spec" RUN=9
- ES=1 TEST_GROUP="rspec spec" RUN=10
```
The `RUN=X` part needs to be there, otherwise Travis smartly spawns only one job for 10 identical `env` entries.
=> AO3-5358 Fix intermittent test failure in pseud searches

features/support/hooks.rb
https://otwarchive.atlassian.net/browse/AO3-5305
The new UI is only enabled if ES 0.90 is not running. This is not a problem for the Travis build where there's only one active ES version per job, and new/old-search-only tests are disabled accordingly.
In the Codeship build, both ES versions are always active, which means the new UI is not available. We need to enable it specifically for the tests tagged new-search.
Codeship should pass.
=> AO3-5305 Fix new-search feature tests for Codeship

app/models/search/bookmark_query.rb, app/models/search/bookmarkable_query.rb, app/models/search/query.rb, spec/models/bookmark_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5305
There's a bug in the new bookmarkable query code: it's using the wrong name for the "Date Bookmarked" sort setting. (And it's also not handling a blank value for options[:sort_column] properly.) This pull request fixes that.
View the bookmarks for a Tag or a Collection and check the date of the first bookmarked item for each bookmarkable. They should be in decreasing order.
=> AO3-5305 Try to fix bookmark sorting.

lib/skin_wizard.rb
https://otwarchive.atlassian.net/browse/AO3-5355
Make sure the font, font color, and border colors on the new filters (especially bookmarks) get changed when you use the skin wizard.
Make and apply a skin wizard skin changing the accent color, text color, and font and then check how the new filters look.
=> AO3-5355 Update Skin Wizard for new filters

app/views/bookmarks/_bookmarkable_blurb.html.erb, public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5361
On a tag's bookmark page, change the link text from "View All" to "All Bookmarks." On that page and on an item's bookmark page, moves icon and "Bookmarked by" info a smidge to the left.
Refer to Jira
=> AO3-5361 Link text and alignment changes for bookmarks

app/helpers/application_helper.rb, public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5274
Changes the selector we use to bold the name of checked tags in the filters because Safari 8 and 9 don't support the one we use. This might not work.
Use the filter checkboxes in older versions of Safari.
=> AO3-5274 In filters, text of selected tag not bolded on old browsers

app/controllers/bookmarks_controller.rb, app/models/collection.rb, app/sweepers/challenge_signup_sweeper.rb, app/sweepers/collection_sweeper.rb, app/views/collections/_collection_blurb.html.erb, app/views/collections/_sidebar.html.erb, features/collections/collectible_closed_collection.feature, features/collections/collectible_moderated_collection.feature, features/collections/collectible_open_collection.feature, features/collections/collection_navigation.feature, spec/models/collection_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5364
This PR makes the bookmark counts in the sidebar of collections into *bookmarked item* counts, instead. It also changes the count in blurbs on the Browse > Collections page to match the sidebar counts, as well. (Since that blurb is cached, this necessitated some changes to the cache key to account for the difference in count and label when logged in/logged out or using new search/old search. Which in turn required some changes to the sweepers.)
I also noticed while testing that bookmark search and bookmark listings don't show bookmarks of restricted works to admins, so I fixed that to make sure that the numbers are consistent even when logged in as admin.
1. While logged in as an admin, check the bookmark count in the collection's sidebar …
=> AO3-5364 Turn collection bookmark counts into bookmarked item counts for new search.

app/models/search/bookmark_query.rb, app/models/search/bookmarkable_query.rb, app/models/search/query.rb, app/models/search/taggable_query.rb, app/models/search/work_query.rb, app/models/search/work_search_form.rb, features/search/filters.feature
https://otwarchive.atlassian.net/browse/AO3-5331
When non-existent tag names are entered into various fields, the search behavior is wrong:
1. When entered into the tag fields on the work search form, or the "Other tags to include" field on work listings, all non-existent tag names are concatenated and searched for in quotes (forcing all of the tag names to appear in order with no gaps).
2. When entered into any of the fields "Other work tags to include," "Other work tags to exclude," "Other bookmarker's tags to include," or "Other bookmarker's tags to exclude," on bookmark listings, or "Other tags to exclude" on work listings, non-existent tags disappear without a trace. They don't constrain the query at all.
This PR refactors the code for handling named tags. Given a list of named tags, …
=> AO3-5331 Try to fix handling of non-existent tag names in work search and bookmark listings.

app/controllers/bookmarks_controller.rb, app/models/search/bookmark_query.rb, app/models/search/bookmark_search_form.rb, app/models/search/bookmarkable_query.rb, app/views/bookmarks/_filters.html.erb, app/views/bookmarks/_search_form.html.erb, app/views/bookmarks/_search_form_old.html.erb, app/views/bookmarks/search.html.erb, features/bookmarks/bookmark_search.feature, features/search/filters.feature, features/step_definitions/bookmark_steps.rb, spec/models/bookmark_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5363
https://otwarchive.atlassian.net/browse/AO3-5355
The ES6 bookmark search form now has new fields, which correspond to new fields on bookmark filters in [AO3-5355](https://otwarchive.atlassian.net/browse/AO3-5355):
- Any field on bookmarked item (form) = Search within results (filters)
- Any field on bookmark (form) = Search bookmarker's tags and notes (filters)
- Bookmarked item's tags (form) = Other work tags to include (filters)
- Bookmarker's tags (form) = Other bookmarker's tags to include (filters)
=> AO3-5363 Split "Any field" and "Tag" fields on bookmark search

app/views/bookmarks/_search_form.html.erb, features/bookmarks/bookmark_search.feature, script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-5363
Rename "Any field on bookmarked item" to "Any field on work" and "Bookmarked item's tags" to "Work tags" to match the filters.
Labels should have the correct text, renamed fields should still work.
=> AO3-5363 Rename "bookmarked item" search fields to use "work"

app/models/search/taggable_query.rb, spec/models/bookmark_search_form_exclusion_filters_spec.rb, spec/models/work_search_form_exclusion_filters_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5331
Excluding non-canonical tags currently excludes those tags' mergers as well, making the behavior of exclusion filters asymmetric with the behavior of inclusion filters. This PR removes the mergers from the list of tags to be excluded.
1. Find a non-canonical tag with a merger.
2. Go to the merger's works listing.
3. Type the non-canonical tag into the "Other tags to exclude" field.
4. Press the "Sort and Filter" button.
5. Make sure that the only works excluded are those tagged with the synonym.
=> AO3-5331 Don't exclude mergers when excluding non-canonical tags.

app/helpers/application_helper.rb, public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5274
Reverts changes to the selector we use to bold the name of checked tags in the filters because it's even more broken in Safari 9 now.
Use the filter checkboxes in older versions of Safari. Nothing should inexplicably disappear.
=> AO3-5274 Revert "In filters, text of selected tag not bolded on old browsers"

CONTRIBUTING.md
Motivation: I had a bug to report, and I knew AO3 had a GitHub repository. So:
* I went to the GitHub repo. No issues tab.
* I see there’s a link to the list of known issues in the README. Click through to JIRA, get lost. Let’s try GitHub again.
* There’s a CONTRIBUTING.md, but no instructions for reporting bugs, just for fixing them!
* Poke around in JIRA a bit more, eventually stumble upon the text (hidden under an invisible scroll) that says “use the feedback form to submit bugs”.
I nearly gave up several times; this is meant to help people report bugs more quickly.
=> CONTRIBUTING.md: explain how to report a bug

public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5370
Fixes an issue where the labels in the filters would disappear in Safari 9 when you expanded the next filter section.
Try to use the filters in Safari 9, and then try to use them in other browsers to make sure I didn't break anything new.
=> AO3-5370 Fix vanishing filter label text in Safari 9

app/models/series.rb, app/models/work.rb, features/bookmarks/bookmark_search.feature, features/step_definitions/bookmark_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5376
Index series and work bookmarkable documents on whether or not they are complete so it is once again possible to search for `complete: true` on bookmarked items.
Refer to Jira
=> AO3-5376 Add complete field to series and work bookmarkables

app/models/search/bookmark_indexer.rb, app/models/search/work_indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5377
For bookmarks and works, we previously indexed all fields except [names of fields]. This had the potential to go very wrong, so now we index only [names of fields].
I did `names = Model.columns.map(&:name)`, `names.map &:to_sym`, and then pasted the output, so there wouldn't be too much room for human error in terms of typos in field names. I also did it in three separate commits to make it easier (possibly) to see what was removed from the whole list.
Refer to Jira
=> AO3-5377 Use whitelist, not blacklist, for indexing fields

app/models/user.rb, spec/models/search/pseud_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5383
Pseuds are indexed with the parent user's name, so they all need to be reindexed when the parent user changes name.
See issue.
=> AO3-5383 Reindex all pseuds of a user after changing its name

app/models/pseud.rb, app/models/search/work_indexer.rb, app/models/user.rb, app/models/work.rb, spec/models/bookmark_search_form_spec.rb, spec/models/work_search_form_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3468
When a work's author changes their username:
- authors_to_sort_on is a column: the work needs to be resaved, then reindexed, and we're doing so synchronously.
- authors_to_sort_on is a method: its value is up-to-date when called, the work doesn't need to be resaved, just reindexed, and we can use the asynchronous indexing queues.
We can drop the database column authors_to_sort_on whenever.
Also add a hook so when a pseud gets renamed, its works and bookmarks get reindexed.
See issue.
=> AO3-3468 Change authors_to_sort_on from a column to a method

app/models/challenge_assignment.rb, app/models/potential_match.rb
https://otwarchive.atlassian.net/browse/AO3-5389
If the Resque job for potential match generation/assignment generation ends up in the list of Resque failures, and failed jobs are rerun after the error has been fixed and the assignments have been sent out, then the restarted job will destroy all of the assignments that were sent out. (It will regenerate them, but because the assignment generation algorithm is randomized, this can sometimes result in different assignments. In addition, all `sent_at` values will be reset to nil, making the assignments inaccessible to gift exchange participants.)
This pull request makes it so that the two delayed jobs won't run if the challenge's `assignments_sent_at` date is set (that is, if the gift exchange moderator has pressed the "Send Assignments" …
=> AO3-5389 Avoid clobbering sent assignments.

.codeclimate.yml, features/support/env.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5393
Tell Code Climate to stop criticizing the test suite, among other things.
Also tell Codeship to stop trying to submit coverage reports: without authentication, we get this at the end of every step:
```
{"error": {"context": null, "reason": "Please provide the repository token to upload reports via `-t :repository-token`"}, "meta": {"status": 400}}
```
According to the CC merge check below:
> codeclimate — 336 fixed issues
Those are all from spec or step files.
=> AO3-5393 Update Code Climate exclusions

app/controllers/admin/admin_users_controller.rb, app/models/pseud.rb, app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-3468
On test, when renaming a user, the user's works are [reindexed inconsistently](https://otwarchive.atlassian.net/browse/AO3-3468?focusedCommentId=353750&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-353750). It's possible that reindexing is happening before the changes are saved in the database:
> There are two additional callbacks that are triggered by the completion of a database transaction: after_commit and after_rollback. These callbacks are very similar to the after_save callback except that they don't execute until after database changes have either been committed or rolled back. They are most useful when your active record models need to interact with external systems which are not part of the database …
=> AO3-3468 Reindex everything for username changes in after_commit

app/models/external_work.rb, app/models/series.rb, app/models/work.rb
https://otwarchive.atlassian.net/browse/AO3-5410
The simpler notation for parent documents somehow leads to errors like: "object mapping for [bookmarkable_join] tried to parse field [bookmarkable_join] as object, but found a concrete value".
`BookmarkIndexer.index_all` on production should finish quietly.
=> AO3-5410 Use object notation for relation in bookmarkable documents

app/views/inbox/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-5412
Makes it so you can see the radio buttons on the inbox filters again, using the new radio button style. Also tidies.
Refer to Jira
=> AO3-5412 Restore radio buttons on inbox filters

app/views/invite_requests/_index_open.html.erb
https://otwarchive.atlassian.net/browse/AO3-5418
Users wanting an invitation should be old enough.
The ToS link should work and there are no typos.
=> AO3-5418 Add GDPR information to the request invitation page

app/views/users/edit.html.erb
https://otwarchive.atlassian.net/browse/AO3-5419
When users edit their public profile, warn them that their profile is public, using the ToS.
The ToS link to the privacy section should work and there are no typos.
=> AO3-5419 Add GDPR information to the edit profile page

app/models/indexing/scheduled_reindex_job.rb, app/models/tag.rb, features/other_b/bookmark_indexing.feature, features/step_definitions/tag_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5353
Reindex series when canonical tag becomes syn, ensuring that bookmarks of the series will show up on the new canonical tag's bookmark listings.
Refer to Jira
=> AO3-5353 Reindex series when canonical tag becomes syn

app/models/bookmark.rb, app/models/pseud.rb, app/models/search/bookmarkable_indexer.rb, app/models/search/indexer.rb, app/models/tag.rb, app/models/work.rb, config/config.yml
https://otwarchive.atlassian.net/browse/AO3-5275
Makes it easier to modify the Elasticsearch index prefix if you're working on webdev or another shared environment.
=> AO3-5275 Centralize Elasticsearch prefix

app/views/works/_filters.html.erb, app/views/works/_search_form.html.erb, features/search/works_stats.feature
https://otwarchive.atlassian.net/browse/AO3-5368
Updates wording of "Status" portion of Works search/filter to match usual wording
[assuming new search is enabled] verify descriptions "All works", "Complete works only", and "Works in progress only" for:
- (Work Search) Search > Works > Status
- (Work Filter) Browse > Tags > Select AnyTag? > Filters > Status
~~helloworld PRs continue~~
=> AO3-5368 update wording of work status for page filter and search page

app/views/home/lost_cookie.html.erb
https://otwarchive.atlassian.net/browse/AO3-5398
Updates lost_cookie page text with workaround for being unable to log back in using corner login box after forced logout.
See Jira. Nothing automated since... temporary?
Describes workaround for [AO3-5396](https://otwarchive.atlassian.net/browse/AO3-5396) [Forced logout leaves user unable to log back in using corner login box].
I also wasn't able to recreate 5396 locally, but wouldn't mind trying again if it's something I just overlooked.
What I tried was setting `cookies.delete(:user_credentials)` for some arbitrary page's controller and navigating to it when logged in, which seemed to trigger `application_controller.logout_if_not_user_credentials` correctly with a logout + redirect. However at that point I seemed to log in just fine using …
=> AO3-5398 update forced logout message with login page suggestion

app/views/bookmarks/_search_form.html.erb, app/views/bookmarks/_search_form_old.html.erb, features/bookmarks/bookmark_search.feature
https://otwarchive.atlassian.net/browse/AO3-5374
Divides the bookmark search form up to be a bit less overwhelming. Refer to issue for screenshot.
All fields on the new bookmark search form should still work.
=> AO3-5374 Divide bookmark search form into field sets

script/create_admin.rb
https://otwarchive.atlassian.net/browse/AO3-5288
Updates the admin creation script to make it slightly easier to create more than one at a time.
This is a backend task that can only be run by someone with ssh access to the AO3 servers. (It has already been run multiple times on production as this is the script I've used the last few times I created admins there)
=> AO3-5288 Update script to generate multiple admins at a time

app/controllers/application_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/people_controller.rb, app/controllers/tags_controller.rb, app/controllers/works_controller.rb, app/helpers/search_helper.rb, app/models/search/indexer.rb, app/models/search/query.rb, app/models/search/query_result.rb, config/config.yml, features/step_definitions/search_steps.rb, features/step_definitions/work_steps.rb, features/works/work_browse.feature
https://otwarchive.atlassian.net/browse/AO3-5232
By default, each Elasticsearch index has index.max_result_window set to 10000. We increase it to 100000 and update the UI to match:
- Display the real, uncapped result count in the search header.
- Paginate search results only up to the limit.
- If users visit a page beyond the last result page, show the last page.
- On the last result page, if there are more results not shown, display a notice about the limit.
The limit will apply to:
- Search results for works/bookmarks/pseuds/tags
- Listings for works/bookmarks (of a tag/user/pseud/collection)
See issue.
=> AO3-5232 Limit search result count

app/models/search/bookmark_indexer.rb, app/models/search/work_indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5428
Sets the number of shards on the elastic search cluster.
Get an admin to use curl  for example:
```james_@elastic04:~$ curl -X GET "localhost:8201/_cat/indices?v"
health status index                    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   ao3_production_tags      EOfrTO0AS-yvltks0tsclg   5   1    6700754      1963506      2.2gb            1gb
green  open   ao3_production_bookmarks PuHTs8c3Q06Tz2HGx7GMzg   5   1   63794528            0     36.7gb         18.5gb
green  open   ao3_production_pseuds    mOT6HShOSOav7jf5D75xSQ   5   1    1571111       212730        1gb        519.9mb
green  open   ao3_production_works     5096D7qBTyG1HzC4T7nnnA   5   1    3889071       936128     20.2gb …
```
=> AO3-5428 Specify number of shards

config/.rubocop.yml
https://otwarchive.atlassian.net/browse/AO3-5434
Disable the cop [Style/RedundantSelf](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/RedundantSelf).
```bash
rvm 2.2.5 do rubocop -c config/.rubocop.yml app/models/external_work.rb
```
No "self" violations appeared.
=> AO3-5434 Tell Hound to stop caring about self

app/models/search/query_result.rb
https://otwarchive.atlassian.net/browse/AO3-5435
Makes sure we don't try calling `.any?` on `nil`, producing a 500 error. More info on the ticket.
Refer to Jira
Honestly, credit @redsummernight on this one -- I just happened to be in a position to do it while they went to bed
=> AO3-5435 Fix 500 error happening on some works pages on new Elasticsearch

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5430
In theory, a work should have filters for its own tags along with those tags' canonicals and inherited meta tags, but old data can be inconsistent.
Work.crossover should work the same as before: the added tests pass for both the old and new implementations.
See issue.
=> AO3-5430 Get crossover status from MetaTagging instead of FilterTagging

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5443
On new Elasticsearch's tag bookmark pages, the list of a bookmarkable item's recent bookmarks was overlapping the bookmarkable's stats and Save/Saved button. This makes the recent bookmarks clear those things.
Refer to Jira
=> AO3-5443 Make recent bookmarks clear bookmarkable stats and Save button

app/models/search/bookmark_indexer.rb, app/models/search/work_indexer.rb
https://otwarchive.atlassian.net/browse/AO3-5428
The previous version using `shards:` didn't work because the `shards` parameter is a single value, not a hash.
=> AO3-5428 Fix method call for create_index shard parameter

app/views/archive_faqs/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-5341
On /faqs/search-and-browse, adds a notice that the FAQ is outdated.
Go to the page, see if the banner is there. Go to another FAQ, make sure it is not there.
=> AO3-5341 Notify users Search and Browse FAQ is outdated

app/helpers/advanced_search_helper.rb, features/search/filters.feature
https://otwarchive.atlassian.net/browse/AO3-5452
Check to exclude a work tag and submit, then the same tag appearing in the "Bookmarker's Tags" exclude section should not be checked.
Check to exclude a bookmarker's tag and submit, then the same tag appearing in the work tag exclude sections should not be checked.
See issue.
Really should have been done in #3258, where I kept work tags and bookmarker's tags separate everywhere except the helper.
=> AO3-5452 Avoid having the same tag checked in multiple bookmark filter exclude sections

public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5446
Changes the border-color of the check/cross icon for selected checkboxes to be the same as the text color. This applies only to the new filters sidebar.
Select a checkbox in the new filters sidebar on staging, compare it to a selected checkbox on beta. The border needs to be darker on staging.
=> AO3-5446 style change for selected checkbox indicator in the new filter sidebar

app/views/works/_filters.html.erb
https://otwarchive.atlassian.net/browse/AO3-5454
https://otwarchive.atlassian.net/browse/AO3-5442
Removes the help text from the crossover section of the filters. Probably also fixes AO3-5442.
Refer to Jira
=> AO3-5454 Remove crossover help text from filters

app/views/kudos/_kudos.html.erb
https://otwarchive.atlassian.net/browse/AO3-5415
Uses `kudos.any?` instead of `kudos.length > 0` so we aren't counting all the danged kudos before accessing the cache. 
Refer to Jira
We're probably going to implement #3359, but it may need a few tweaks to make it less confusing. This is basically a quick, partial improvement.
=> AO3-5415 Favor kudos.any? over kudos.length > 0 for performance

app/helpers/advanced_search_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5227
Removes a method that's not called anywhere in the code (thereby bringing this file's test coverage up to 100%)
=> AO3-5227 Remove unused advanced_search_string method

app/models/search/tag_query.rb, config/config.yml, spec/models/search/tag_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5462
This PR adds a configurable number TAGS_PER_SEARCH_PAGE (defaulting to 50) that controls the default number of tags returned from a TagQuery.
See bug report.
=> AO3-5462 Change the number of tags displayed in the new tag search.

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5461
Currently, to check whether a work is a crossover, we compute the total number of top-level meta tags (top-level meaning "doesn't have any meta tags of its own"). This causes a problem when a single fandom has two top-level meta tags -- it counts as being unrelated to all other tags, including its own synonyms.
This PR revises the crossover code to check whether there exists at least one fandom on the work that has all of the top-level meta tags involved (thus meaning that all of the fandoms on the work are related to that one tag).
(Thanks to @redsummernight for figuring out this definition of a crossover!)
See the detailed steps on the JIRA issue.
=> AO3-5461 Revise the crossover check to look for a single fandom whose top-level meta-tags are equal to the set of all top-level meta-tags.

app/helpers/search_helper.rb, app/models/search/tag_query.rb, app/views/bookmarks/search_results.html.erb, app/views/people/search.html.erb, app/views/tags/search.html.erb, app/views/works/search_results.html.erb, config/config.yml, features/search/exceeding_maximum.feature, features/step_definitions/search_steps.rb, spec/models/search/tag_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5444
The PR extracts the "x Found" text at the top of works, bookmarks, tags, and people search into a single helper function search_results_found, which uses the unlimited_total_entries field whenever it's available. This means that when the number of search results is greater than 100000, the true number of search results will still be displayed (and not just capped at 100000).
See the bug report for test steps.
The full number of results needs to be visible on every page, not just the last page of results. So I deliberately set up the automated tests to cut down on the number of results per page, and check whether the number appears on the first of two pages. Because #3364 affects the number of tags displayed per page, I decided to include …
=> AO3-5444 Searches with more results than the max should show the total number of results.

app/models/search/work_query.rb, app/models/search/work_search_form.rb, factories/collections.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5463
This is missing in new search.
Unrevealed works should appear to all, while anonymous works should only appear if the logged in user is the author.
=> AO3-5463 Show anonymous & unrevealed works in user's Works in Collections

app/models/feedback_reporters/feedback_reporter.rb
https://otwarchive.atlassian.net/browse/AO3-4842
Formatting was previously being stripped before being sent to the Bugtracker. This was because of changed that occured in https://otwarchive.atlassian.net/browse/AO3-4216 . This was no longer desired behavior, so I have removed the format stripping from the 'description' field only. 
Submit an Abuse and Support request and make sure that formatting (italics, bold, newline, etc.) correctly show up on the Bug/Abuse trackers. 
Original issue that called for removing formatting: https://otwarchive.atlassian.net/browse/AO3-4216
=> AO3-4842 Stop stripping carriage returns from Support and Abuse request descriptions

app/models/bookmark.rb, app/models/pseud.rb, app/models/tag.rb, app/models/work.rb, spec/models/elasticsearch/rollout_elasticsearch_upgrade_spec.rb, spec/models/index_subqueue_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5470
The index_name functions in the Work, Bookmark, Tag, and Pseud classes are exclusively used in the IndexSubqueue (the old indexing class) to perform indexing. However, they're currently set up to return a different index name when use_new_search is enabled for all users. This means that once all users have the new search, all old indexing tasks will try to use the wrong index name, and fail.
This pull request changes the four index_name functions (in the ActiveModel classes, not the Indexer classes) so that they always return the name of the old index. It also adds a few tests to check that the index names are correct and the works are being indexed properly.
Switch on use_new_search for all users, create a new work, and wait a few minutes …
=> AO3-5470 Make Work.index_name always return the old index name (for IndexSubqueue compatibility)

public/stylesheets/site/2.0/08-actions.css, public/stylesheets/site/2.0/09-roles-states.css
https://otwarchive.atlassian.net/browse/AO3-5467
Makes sure we're using the same fallback fonts everywhere we should be -- that is, in all the non-IE stylesheets where the first two fonts are Lucida Grande and Lucida Sans Unicode.
Refer to Jira
=> AO3-5467 Standardize fallback fonts in certain places

public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5472
Resolves an issue where tapping checkboxes and radio buttons in the filters does not always work on iOS with VoiceOver.
Refer to Jira
This was caused by #3274, which is still needed to fix a bug that only occurs in Safari 9. It uses a browser-specific hack from https://browserstrangeness.github.io/css_hacks.html to make sure that fix is still applied where needed.
=> AO3-5472 Fix filter selection using checkboxes with iOS VoiceOver

app/models/feedback.rb, app/models/feedback_reporters/feedback_reporter.rb, lib/html_cleaner.rb, spec/miscellaneous/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4842
Adds a `<br />` between the paragraphs in Support and PAC tickets because the ticket tracker's paragraph styling doesn't have margins, so the paragraphs looked more like:
Paragraph 1
Paragraph 2
than like
Paragraph 1
Paragraph 2
even though they were correctly HTMLified as `<p>Paragraph 1</p><p>Paragraph 2</p>`
They are now rather horrifically done as  `<p>Paragraph 1</p><br /><p>Paragraph 2</p>` because a single empty `<p></p>` did not have sufficient line height to resemble a blank line, and `&nbsp;` or `&#160;` caused the tickets not to make it to the tracker, while an actual typed out space would get stripped and go right back to the line height not resembling a blank line.
Refer to Jira
=> AO3-4842 Add <br /> between paragraphs for Support and PAC tickets

public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5472
When using VoiceOver on iOS 10.3.1 (but not 10.3.3 or 11.4), the outline that indicates the selected item overlapped the right side of the filter. This fixes that.
Use VoiceOver on iOS 10.3.1 with the filters. Make sure to tap on the box, not the label text.
=> AO3-5472 Fix VoiceOver outline position in iOS 10.3.1

app/views/challenge_signups/_signup_form.html.erb, app/views/collections/_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-4579
informs users signing up for challenges that the creator of the challenge may have access to their email address and warns challenge creators about using email addresses for anything other than running the challenge. 
i think (?) javascript would have been necessary to dynamically add a mandatory tick box to the page when someone chooses to make their collection a challenge, and to remove the tick box if/when they unselect a challenge. in which case there would have to be a noscript workaround for that too. or if you have the mandatory tick box there all the time regardless of whether or not the user is making their collection a challenge, then people might get annoyed if they ignore that part of the form and then hit submit and receive an …
=> AO3-4579 Challenge signup/creation email address warning

app/controllers/application_controller.rb, app/models/admin_setting.rb, app/models/invite_request.rb, app/models/skin.rb, app/models/tag.rb, app/models/work.rb, app/views/users/confirmation.html.erb, lib/tasks/tag_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-4470
Adds a new wrapper method that utilizes caching for admin settings and calls that wherever we need the current settings. Also simplifies some class methods via delegation and adds extra caching for default skins.
Everything should continue to work as it did before, but with fewer database calls.
=> AO3-4470: Standardize caching of admin settings and default skin

app/controllers/bookmarks_controller.rb, app/controllers/works_controller.rb, app/helpers/users_helper.rb, app/models/collection_item.rb, app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-5167
Switches is_author_of? method to compare based on ids rather than objects, which should save on some db calls and memory. Also preloads the set of current works/bookmarks owned by the current user on index pages so that we don't have to run separate checks over and over.
Replaces https://github.com/otwcode/otwarchive/pull/3054 which was approved but then became hopelessly conflicted.
Nothing should change: appropriate footers for work and bookmark blurbs should appear if they're yours, and anonymity should be respected.
=> AO3-5167: Improve performance of ownership checks

Gemfile, script/prepare_codeship.sh
https://otwarchive.atlassian.net/browse/AO3-5287
FilterCount uses SPOP which requires 3.2. This is also to match the production Redis version.
Travis and Codeship should both pass.
See instructions on [installing a specific version of Redis on Codeship](https://documentation.codeship.com/basic/queues/redis/).
Note that Codeship's script installs new Redis into `${HOME}/bin`, so we have to run Redis with `redis-server`. `/usr/bin/redis-server` still points to the older default version (2.8.4).
=> AO3-5287 Install Redis 3.2.1 on Codeship

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5484
The updated crossover check from #3363 currently relies on the correctness of the meta-taggings table to return the correct results. Unfortunately, the meta-taggings table in production is missing some inherited meta-taggings, so this will return incorrect results for some works.
This PR modifies the crossover check to perform BFS when computing the list of all meta tags.
See bug report.
=> AO3-5484 Handle missing inherited meta tags when computing first-class meta tags for crossover check.

app/controllers/admin/settings_controller.rb, app/controllers/downloads_controller.rb, app/models/admin_setting.rb, app/views/admin/settings/index.html.erb, app/views/user_sessions/new.html.erb, db/migrate/20180712000145_remove_guest_downloading_off_from_admin_settings.rb, features/admins/admin_settings.feature, features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5474
Remove an admin setting we rarely use.
See issue.
=> AO3-5474 Remove admin setting for disabling guest downloads

script/travis_elasticsearch_upgrade.sh
https://otwarchive.atlassian.net/browse/AO3-5491
Wait for ES startup more reliably. The root URL can return 503 if ES is not completely ready, which fails wget.
Travis builds should (more) consistently pass.
=> AO3-5491 Use cluster health API to wait for Travis ES startup

script/get_user_data.rb
https://otwarchive.atlassian.net/browse/AO3-5486
* Writes out names of favorite tags
* Adjusts phrasing for collection roles
* Adds relevant IPs from audit table to IP list
* Adds lists of previous emails and usernames, if the user has changed their email or username
=> AO3-5486 Make user data output less confusing

app/views/bookmarks/_bookmarks.html.erb, app/views/users/_contents.html.erb, app/views/works/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5500
Small change to partial rendering syntax to use collection instead of looping and rendering each partial individually. Affects works index, bookmarks index, and user dashboard.
Works, bookmarks, and user dashboard pages should render correctly with no changes.
=> AO3-5500: Use collection syntax for partials

app/models/work.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5465
Currently, two fandoms are considered "related" for the purposes of the crossover check if one fandom's first-class meta tags are a subset of the other fandom's first-class meta tags. This means that if you have a fandom A with meta tags C and D, and a fandom B with meta tags D and E, then any work tagged with A and B counts as a crossover (because A has a meta tag C that isn't shared by B, and B has a meta tag E that isn't shared by A).
This pull request modifies the crossover check so that two fandoms count as "related" if they share a meta tag, meaning that fandoms A and B would count as related, and works tagged with both won't automatically count as crossovers.
Check to see whether works tagged "Captain America (Movies), The Avengers …
=> AO3-5465 Update crossover check to make two fandoms count as related if they share a meta tag.

app/mailers/user_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-5453
If the plain text attachment is encoded with 7bit, the email can have long lines that exceed the SMTP limit (998 octets), causing errors. With base64 encoding, attachments have line wrapping by default.
HTML attachments are already base64-encoded, this change just makes that obvious.
See issue.
=> AO3-5453 Encode deleted work email attachments with base64

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5496
Updates transaction isolation gem to fix confusing error messages when db transactions fail.
Make sure automated tests pass and the staging site doesn't blow up.
=> AO3-5496: Update transaction gems

public/500.html, public/502.html, public/503.html, public/507.html, public/nomaintenance.html
- "Search" dropdown now has Bookmarks and People in the correct order
- "FAQ" in the "About" dropdown now links to the correct FAQ page
- "About" dropdown now contains Wrangling Guidelines link
(Not sure how to request access for your JIRA board.)
https://otwarchive.atlassian.net/browse/AO3-5335
Updates the 500.html public-facing page with the correct links/ordering for dropdown menus.
Visit the Archive with a standard public-facing page (such as the index) and compare the Search and About dropdown menus on the navigation bar with these changes.
None.
digitalAlchemist, he/him
=> AO3-5335 Fix dropdown ordering on error pages

app/models/search.rb
https://otwarchive.atlassian.net/browse/AO3-5140
The regex on line 27 of app/models/search.rb matched any amount of the letter s instead of whitespace.
Refer to Jira issue.
=> AO3-5140 Fix Date search regex matches whitespace

app/views/chapters/_chapter_management.html.erb
https://otwarchive.atlassian.net/browse/AO3-4896
removes the "delete chapter" button that displays in the work/chapter view when a work has more than one chapter. to avoid accidental deletion, chapter deletion should only be accessible from the edit chapter or edit work view
please view one of your multi-chaptered works and ensure that there is no "delete chapter" button beside the "edit chapter" button above the chapter title
=> AO3-4896 remove delete chapter button from work/chapter view

app/views/downloads/_download_preface.html.erb
https://otwarchive.atlassian.net/browse/AO3-5019
Fix overlapping text in related works section on downloads.
See issue.  The new related works section should look like this:
=> AO3-5019 Fix text overlap in related works section on downloads

app/controllers/feedbacks_controller.rb, app/views/abuse_reports/new.html.erb, app/views/feedbacks/new.html.erb, features/other_a/abuse_report.feature, features/other_b/support.feature
This PR replaces https://github.com/otwcode/otwarchive/pull/3120, which got really complicated because of merge conflicts.
https://otwarchive.atlassian.net/browse/AO3-5190
When submitting an abuse or support form with an error (such as an invalid email address), chosen language should persist.
Follow the "Report Abuse" or "Technical Support and Feedback" link in the footer
Select a language other than English
Fill in required information, but in the URL field, enter a URL that will make the form error (e.g. enter http://test.ao3.org) or make another mistake such as entering an invalid email address
Submit
Includes two Cucumber tests
=> AO3-5190 Abuse and support form language on error

app/views/comments/_commentable.html.erb, app/views/works/_work_header_navigation.html.erb
https://otwarchive.atlassian.net/browse/AO3-5369
Work previous/next chapter navigations to anchor on main content
manual: pick multichapter work, verify that the previous/next chapter buttons in header navigation section and comment section skip past header/meta sections and start on main content (div id = workskin)  
automated: wasnt sure if there were any to add. asserting on anchor tag seems discouraged in capybara, and the existing examples (rspec) seemed more relevant had the anchor been passed by controller
~~Are there any other relevant issues / PRs / mailing lists discussions related to this?~~
~~*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](http://archiveofourown.org/admin_posts?tag=1)?*~~
~~*What pronouns do you prefer (she/her, …
=> AO3-5369 work previous/next chapter navigation to anchor on main content

script/check_syntax, script/prepare_codeship.sh
https://otwarchive.atlassian.net/browse/AO3-5509
Similar to #3394 but this time for Codeship.
Also fix the find command in check_syntax.
```
find: `{app,lib}': No such file or directory
```
=> AO3-5509 Wait for ES startup on Codeship

app/mailers/user_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-5453
If we specify an encoding, Mail will assume that the content is already encoded and not try to encode it. We'll do it ourselves.
See issue.
=> AO3-5453 Really encode deleted work email attachments with base64

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-4458
This reverts commit eb352ce870400b2ea2f2aeeae33fc56cc3b59478 (#3408).
2.7.0 has some issues, so we won't update for now:
```
https://github.com/mikel/mail/pull/1168
```
See issue.
=> Revert "AO3-4458 Update mail gem to 2.7.0 (#3408)"

app/controllers/archive_faqs_controller.rb, spec/controllers/archive_faqs_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5448
Return 404 instead of 500 for nonexistent FAQs, so these errors can stop showing up in New Relic.
See issue.
=> AO3-5448 Return 404 instead of 500 for nonexistent FAQs

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5420
Use the Archive's [em scale](http://otwcode.github.io/docs/front_end_coding/em-scale.html): 30px/14px = 2.143.
See issue.
=> AO3-5420 Add more line-height for stats links in blurbs

app/controllers/api/v2/bookmarks_controller.rb
https://otwarchive.atlassian.net/browse/AO3-4625
Fix a case of "undefined method 'url' for nil:NilClass" that happens on Staging when using the API to check if a bookmark already exists.
This will be tested with the rest of the new API.
=> AO3-4625 Make call to potentially missing bookmarkable safer

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5515
rubyzip 1.2.1 is affected by [CVE-2018-1000544](https://nvd.nist.gov/vuln/detail/CVE-2018-1000544) and only used by selenium-webdriver, a test-only dependency. We can remove both.
None.
=> AO3-5515 Remove rubyzip 1.2.1 and selenium-webdriver

app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5482
Sessions are stored in cookies, which has a 4KB size limit. If we store paths that are too long (e.g. filters with lots of exclusions), we will run into CookieOverflow errors.
Filter works, exclude some tags... some more tags... more tags... See issue.
=> AO3-5482 Avoid saving long paths in session cookie

script/gem_security.sh
None.
This only affects Windows, and the gem will be removed when we switch from Authlogic to Devise.
See also #3378.
=> Ignore vulnerability in ruby-ffi 1.9.18

.travis.yml, config/database.codeship.yml, config/database.travis.yml, script/prepare_codeship.sh, script/travis_configure.sh, script/travis_mysql.sh, script/travis_set_read_isolation.sh
https://otwarchive.atlassian.net/browse/AO3-4638
Have Travis use 5.7 latest (it has 5.7.23 and I can't get 5.7.22 from the APT add-on). Have Codeship use 5.7.22. In both cases we need to exclude ONLY_FULL_GROUP_BY from the SQL mode, or a lot of queries using GROUP BY would break.
=> AO3-4638 Use MySQL 5.7.22 in CI

app/controllers/challenge_signups_controller.rb, app/models/challenge_signup.rb, app/models/challenge_signup_summary.rb, app/views/challenge_signups/summary.html.erb, features/gift_exchanges/signup_summary.feature, features/step_definitions/challenge_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5382
This PR does the following:
1. It modifies the signup summary code so that it uses the Rails cache instead of the file system in order to generate the summary in background. This should ensure that the cached version is generated and saved in a place that's accessible to all servers, so that it can be displayed properly.
2. It moves all of the signup summary code into the `ChallengeSignupSummary` class.
3. In order to render the signup summary, it now uses [`ChallengeSignupsController.render`](https://api.rubyonrails.org/classes/ActionController/Renderer.html).
Find or create a gift exchange with enough sign-ups to display a summary (and too many sign-ups to have the summary generated live), and make sure that the summary displays.
=> AO3-5382 Store the signup summary in Memcached.

app/models/feedback_reporters/abuse_reporter.rb, app/models/feedback_reporters/support_reporter.rb, config/config.yml
https://otwarchive.atlassian.net/browse/AO3-5488
What it says on the tin. This will make it easier to switch Support to their paid account whenever they're ready.
In theory, we could just do ABUSE_PROJECT_PATH and SUPPORT_PROJECT_PATH and call it a day, but iirc, we originally avoided that because the whole long path (`authtoken=keysmash123&portal=ao3abuse&department=AO3%20Abuse`) would be a longer string to hunt for typos in in the event of brokenness.
Refer to Jira
=> AO3-5488 Make ticket tracker URLs more configurable

app/models/feedback_reporters/feedback_reporter.rb
https://otwarchive.atlassian.net/browse/AO3-5534
The request body is application/x-www-form-urlencoded which means plus signs need to be percent-encoded or they will be interpreted as spaces.
See issue.
@sarken, who tried out the fix locally.
=> AO3-5534 Encode form data in PAC/Support ticket requests

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5527
In the existing code, the error message "This invitation has already been used to create an account, sorry!" doesn't appear when the user has been deleted because it checks
```
invitation.redeemed_at && invitation.invitee
```
However, `invitation.invitee` is a polymorphic field based on `invitation.invitee_id` and `invitation.invitee_type`, so it will only be non-nil if the invitee (that is, the user account previously created) still exists in the database.
This PR changes that check so that it only examines `invitation.redeemed_at`. As far as I can tell, this matches the behavior in other locations:
https://github.com/otwcode/otwarchive/blob/db06765a8cfa5d300efabcbc33f4e39302aaf1a3/app/models/invitation.rb#L23 …
=> AO3-5527 Prevent users from using invitations that were previously used by a deleted user.

app/controllers/works_controller.rb, app/models/challenge_claim.rb, app/views/works/_notes_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5145
Fixes nil error when fulfilling a claim for a prompt with no description.
(Bonus round: don't make database calls from the view when avoidable)
See issue
=> AO3-5145 Fix potential nil errors on posting prompt fills

app/helpers/comments_helper.rb, features/collections/collection_anonymity.feature
https://otwarchive.atlassian.net/browse/AO3-4857
It fixes the notice telling anonymous creators that their comments on their own works will be anonymous. When commenting on a chapter, `find_parent` returns the work, not the chapter, so `parent.respond_to?(:work)` would always return false. This changes it to check whether `parent.is_a?(Work)` instead (so that checking `parent.anonymous?` won't fail on e.g. Admin Posts).
See JIRA.
=> AO3-4857 Fix anonymous creator comment message.

app/models/abuse_report.rb, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5540 
This PR fixes an issue where the abuse report form was unnecessarily strict on submitted urls. The form should now match urls of the form
* archiveofourown.org/users/cjrecord (no https://)
* https://archiveofourown.com/users/cjrecord (.com in place of .org)
* https://ao3.org/users/cjrecord (ao3 in place of archiveofourown)
and combinations thereof
Try submitting an abuse report with any of the above types of urls!
* Name: Lee
* Pronouns: She/her
=> AO3-5540 Altered regex in abuse_report.rb to accept alternate AO3 urls

db/migrate/20180909203857_drop_authors_to_sort_on.rb, features/fixtures/works.yml, test/fixtures/works.yml
https://otwarchive.atlassian.net/browse/AO3-5388
Migration to drop `authors_to_sort_on` from `works`. Also, remove `authors_to_sort_on` from the `works` fixtures. 
I didn't update `structure.sql` or `schema.db` because a number of other recent migrations didn't, and I didn't want to check in code unrelated to my change. I think we need another https://otwarchive.atlassian.net/browse/AO3-4851 . 
?? I did some searches in the dev environment and nothing broke ?? Relatedly, we should include adding indexes for elastic search into the dev env setup. I had to hack something together based on a spec file.
https://github.com/otwcode/otwarchive/pull/3289
bjohns, she/her/hers
=> AO3-5388 Drop authors_to_sort_on col

app/models/work.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5558
Make sure that when a user tries to add a pre-existing series to a work, they own the series they're trying to add.
On JIRA.
=> AO3-5558 Check series ownership.

Gemfile, script/gem_security.sh
https://otwarchive.atlassian.net/browse/AO3-5562
The bot needs the explicit Ruby version in the Gemfile. Change gem_security.sh to not fail Travis builds.
None.
=> AO3-5562 Use Dependabot for gem updates

app/models/search/work_query.rb, app/models/search/work_search_form.rb
https://otwarchive.atlassian.net/browse/AO3-5529
We accidentally started ordering users' collected works pages by score, not date updated. This puts it back.
Refer to Jira.
@redsummernight did the app/models/search/work_search_form.rb changes.
=> AO3-5529 Order collected works by date updated by default

config/.rubocop.yml
https://otwarchive.atlassian.net/browse/AO3-5567
Disable metrics cops about length: block, class, line, method, module.
The TrailingWhitespace cop has been moved from Style to Layout.
```
https://github.com/rubocop-hq/rubocop/pull/4278
```
None.
=> AO3-5567 Tell Hound to stop caring about length

script/prepare_codeship.sh, script/travis_elasticsearch_upgrade.sh
https://otwarchive.atlassian.net/browse/AO3-5570
Upgrade the tests to use Elasticsearch 6.5.0.
Refer to Jira
=> AO3-5570 Upgrade tests to use Elasticsearch 6.5.0

app/controllers/comments_controller.rb, app/helpers/comments_helper.rb, app/views/comments/_commentable.html.erb, features/comments_and_kudos/hidden_works.feature, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5561
Check if the work is unrevealed when viewing/modifying comments. Treat the work pretty much the same as if it's hidden by an admin, just with a different error message.
See issue.
> me: can I copy your homework (#3465)?
@tickinginstant: yeah, but don't make it too obvious
me:
=> AO3-5561 Fix comment permissions on unrevealed works

app/controllers/api/v2/base_controller.rb, app/controllers/api/v2/bookmarks_controller.rb, spec/controllers/api/v2/api_bookmarks_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5571
Fixes a crash in the mass import bookmark search.
See Jira ticket
=> AO3-5571 Add better error handling to bookmark import

app/models/work.rb, factories/works.rb, features/step_definitions/admin_steps.rb, features/step_definitions/rake_steps.rb, features/step_definitions/reading_steps.rb, features/step_definitions/work_steps.rb, lib/tasks/work_tasks.rake, spec/miscellaneous/lib/tasks/work_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5541
This PR makes it so that chapters are no longer deleted separately from their works in the draft deletion task. This should ensure that drafts are deleted in the same transaction as their chapters, so that there will be fewer works without chapters hanging around in the future.
In addition, I rewrote the draft purge task to make it more resistant to failures, and made it print out errors for all of the drafts that couldn't be deleted (instead of stopping as soon as one work deletion throws an error).
See the comments on JIRA.
=> AO3-5541 Make draft deletion more robust.

app/controllers/users_controller.rb, config/initializers/devise.rb, config/routes.rb
- Remove unused routes users#new and users#create, which have been moved to registrations_controller.
- Set password reset tokens to expire in 48h.
- Set remember me sessions to expire in 3 months.
=> AO3-2839 Fix Devise settings, remove unused code in users_controller

db/migrate/20181017032400_moves_users_to_devise.rb, db/migrate/20181201022717_change_failed_attempts_default.rb
When we ran the Devise migration on staging, we got:
```
== 20181017032400 MovesUsersToDevise: migrating ===============================
-- change_table(:users)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
No such column: users.failed_attempts
```
Maybe this happens because we try to rename and change the same column on a big table in one go? Let's see if moving `t.change :failed_attempts, :integer, default: 0` to its own migration helps.
On staging, first we run:
```sh
bundle exec rake db:migrate:up VERSION=20181201022717
```
This will do nothing because the column already has default 0, but it will allow us to migrate down, setting default back to null like before the Devise migration, because the …
=> AO3-2839 Use separate migration for failed_attempts default

app/controllers/application_controller.rb, app/views/home/lost_cookie.html.erb
Sign users out and redirect if they've lost their user_credentials cookie to prevent logged out users from seeing cached logged in pages. (We'll need this for admins, too, but that's a known issue, whereas this is something that was previously fixed.)
=> AO3-2839 Handle lost cookies for users

app/controllers/application_controller.rb
nginx checks for the cookies `user_credentials` and `admin_credentials` to avoid full-page caching if the page is from a logged in user or admin. These cookies should stick around (20 years) so users don't get redirected to /lost_cookie when they close and reopen browsers, which clears session cookies.
- Log in (as admin, as user, as user with "Remember Me" checked)
- Close the browser
- Reopen it, you should still be logged in, not get redirected to "Forced Logout"
@tickinginstant found the issue and the fix.
=> AO3-2839 Make full-page caching logged-in cookies permanent

app/controllers/users/registrations_controller.rb, features/users/user_create.feature, spec/controllers/users/registrations_controller_spec.rb
- Sign up with an invitation token, mess up on the form, get errors
- Fix the errors, click "Create Account"
- Get redirected to /invite_requests, no accounts were made, since the invitation token got lost when the form errors. This pull fixes that.
See issue.
=> AO3-2839 Keep invitation token when sign-up form is submitted

public/stylesheets/site/2.0/22-system-messages.css
Changes the CSS selectors we use for styling the new alert flash notice to prevent it from applying to admin banners.
Put up an alert admin banner and make sure it doesn't have any pink on it.
=> AO3-2839 Update selectors for alert flash messages

db/migrate/20181017032400_moves_users_to_devise.rb, db/migrate/20181222042042_add_unique_index_to_user_confirmation_tokens.rb
These columns should not have duplicate values. Reference the auto-generated migration from Devise:
https://github.com/plataformatec/devise/blob/8266e8557622c978e6927a635d62e245bf54f239/lib/generators/active_record/templates/migration.rb
On staging, run:
```rb
bundle exec rake db:migrate:down VERSION=20181201022717
bundle exec rake db:migrate:down VERSION=20181017032400
```
since we will need to rerun `20181017032400`.
Then retry up `20181017032400`, then `20181201022717`, then the new migration in this pull.
=> AO3-2839 Add unique index to Devise token columns

app/controllers/users_controller.rb, app/validators/email_format_validator.rb, app/views/users/mailer/reset_password_instructions.html.erb, app/views/users/sessions/_passwd.html.erb, app/views/users/sessions/_passwd_small.html.erb, config/locales/devise.en.yml, features/other_a/profile_edit.feature, features/step_definitions/profile_steps.rb, features/step_definitions/tag_steps.rb, features/step_definitions/user_steps.rb, features/tags_and_wrangling/tag_comment.feature, features/users/authenticate_users.feature, features/users/password_compatibility.feature, spec/miscellaneous/requests/comments_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5576
- Update subject and link style of the reset password email.
- Update notice after users change password.
- Update login forms to use "User name or email:".
- Request a password reset and check the resulting email.
- Change the password (from the profile editing section) and check the notice after.
- Check that login forms have "User name or email:". The registration form should still have "User name:", and a separate field for emails.
=> AO3-2839 AO3-5576 Update login forms, password reset emails, and password change notice

db/migrate/20181224173813_add_unique_index_to_user_emails.rb
https://otwarchive.atlassian.net/browse/AO3-5587
Enforce email uniqueness at database level, on just at Rails level.
The migration should run OK.
=> AO3-5587 Add unique index to user emails

app/views/users/change_email.html.erb
https://otwarchive.atlassian.net/browse/AO3-5576
Removes a note referring to emailing reset passwords.
Go to the change email page and make sure it no longer says "This must be your current password, not a reset password that was emailed to you."
=> AO3-5576 Remove outdated footnote on change email page

config/config.yml
https://otwarchive.atlassian.net/browse/AO3-5589
Adds password_check to the list of fields we don't want to sanitize because they're encrypted. If it's not in the list, it's impossible to change an existing password like `i<3ao3`.
This is already fixed on staging but it should be committed to the repo so it works on dev.
=> AO3-5589 Add password_check to list of encrypted fields

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5579
The gem bullet needs to be >= 5.7.3 to be compatible with Active Record 5.1.5 or later.
```
https://github.com/flyerhzm/bullet/pull/388
```
Check collection pages for users or works.
=> AO3-5579 Update bullet to 5.9.0

app/models/serial_work.rb, spec/models/serial_work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5580
This PR prevents an exception from occurring when trying to delete a SerialWork with no series, thus allowing works with orphaned SerialWorks to be deleted.
See JIRA.
=> AO3-5580 Prevent error in SerialWork after_destroy callback when series is nil.

app/controllers/collection_items_controller.rb, app/views/collection_items/_item_fields.html.erb, spec/controllers/collection_items_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5584
This PR modifies `CollectionItemsController#update_multiple` in several ways:
1. It checks whether the user has permission to perform the desired action.
2. It checks whether the IDs submitted to be updated are from assignments that belong to the correct user/collection, and silently excludes the ID if it doesn't belong.
3. It restricts the allowed parameters so that collection owners can't update `user_approval_status`, and the work's owner can't update `collection_approval_status`, `unrevealed`, or `anonymous`. (And neither one can update `collection_id`.)
Available on Slack, or the Wiki.
=> AO3-5584 CollectionItemsController permissions.

app/mailers/user_mailer.rb, app/views/user_mailer/invite_request_declined.html.erb, app/views/user_mailer/invite_request_declined.text.erb, config/locales/en.yml, spec/miscellaneous/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4310
Makes the invite request declined email translatable
Request an invite, get an admin to decline it, get an email notification, it shows in English with no errors.
Cesy, she/her
=> AO3-4310 Translate invite request decline email

app/models/search/tag_indexer.rb, app/models/search/tag_query.rb, app/models/tag.rb, app/models/tagging.rb, app/models/work.rb, config/config.yml, spec/models/comment_spec.rb, spec/models/search/tag_query_wrangling_spec.rb, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5493
This just sets up indexing/querying, without actually using it in the wrangling UI yet.
Move `TAGGINGS_COUNT_MIN_CACHE_COUNT` to config.yml, so we don't need to specify a default every time. Use this property for the tagging reindex limit, instead of hard-coding 100.
Tags are reindexed to get updated draft-only status in two ways:
- When taggings are created/destroyed; this currently only applies to characters, relationships, and freeforms, so we need to add fandoms.
- When works become posted; we need to add a reindex callback.
None(?), we have no UI for this yet.
=> AO3-5493 Allow searching for tags used only in drafts

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-5600
The fork we've been using was deleted.
See issue.
=> AO3-5600 Fix google_visualr git gem reference

app/views/skins/_header.html.erb
https://otwarchive.atlassian.net/browse/AO3-5198
remove the user count on all archive skins, since work counts sometimes display inaccurate numbers and it's not important enough to fix
1) visit https://archiveofourown.org/skins?skin_type=Site
2) click on any random skin and confirm there's no `Users: ###` count in the info
3) do the same for a work skin https://archiveofourown.org/skins?skin_type=WorkSkin
=> AO3-5198 remove user-facing count on all skins

app/models/download.rb, spec/models/download_spec.rb
Fix download file name transliteration, nothing groundbreaking, just putting things back the way they were.
https://github.com/otwcode/otwarchive/blob/5c29fc05e5f56019855970763b50f2efff928f4c/app/models/work.rb#L883-L887
Post works with Russian/Farsi/Chinese/Japanese/Hebrew titles and see what the downloaded file names are.
=> AO3-3880 Fix download file name transliteration

.travis.yml, script/travis_ebook_converters.sh, script/travis_mysql.sh
https://otwarchive.atlassian.net/browse/AO3-5607
https://docs.travis-ci.com/user/reference/xenial/
Travis offers MySQL 5.7 by default with this OS, so no need to bring in mysql-5.7-trusty or run mysql_upgrade.
Use the correct wkhtmltox package.
Cleanup:
- No need to specify the Ruby version in .travis.yml, since Travis can detect it from .ruby-version.
- Remove IRC notifications.
- Rearrange the build phases in the order they're run.
=> AO3-5607 Move Travis to Ubuntu Xenial 16.04

script/prepare_codeship.sh, script/travis_elasticsearch_upgrade.sh
https://otwarchive.atlassian.net/browse/AO3-5582
Changes the version of Elasticsearch in use on Travis and Codeship to be 6.5.2, which is currently in use on production.
No user testing required.
=> AO3-5582 Update elasticsearch on CI to 6.5.2

app/models/download.rb, app/models/download_writer.rb, public/stylesheets/ebooks.css
https://otwarchive.atlassian.net/browse/AO3-5622
Make sure mobi, epub, and azw3 downloads of works have images.
We do this by pointing [web2disk](https://manual.calibre-ebook.com/generated/en/web2disk.html) at the HTML download from which the mobi, epub, or azw3 file will be created. web2disk will download any images to a directory and create an xhtml version of the HTML download that updates the `img` elements' `src` attribute to point at the newly-downloaded images (this is a relative path; we're not keeping the images on our servers and hot linking to them for eternity). 
We then create a zip file of the downloaded images and xhtml file and tell ebook-convert to turn the zip file into the desired file type. (Previously, we just had ebook-convert turn the HTML download into a mobi, …
=> AO3-5622 Include images in mobi, epub, and azw3 downloads

app/controllers/application_controller.rb, app/controllers/downloads_controller.rb, app/helpers/works_helper.rb, app/views/works/_work_header_navigation.html.erb, features/step_definitions/admin_steps.rb, features/works/work_download.feature
Whoops -- we introduced a bug where, if a logged in user attempted to download a restricted work, they would receive a red flash error that said, "You are already signed in."
Log in and attempt to download a restricted work. It should work.
Also, make sure there is no Download option available on works that are drafts, unrevealed, or hidden by an admin. If you construct a download URL for one such work, you should be given a flash error telling you you cannot download a draft/unrevealed work/work that's been hidden by an admin.
Some discussion:
> bingeling [17:06]
> I think I may have found the line that is causing this
> 
> Sarken [17:07]
> \o/
> 
> bingeling [17:07]
> https://github.com/otwcode/otwarchive/blob/master/app/controllers/applic …
=> AO3-3880 Allow users to download restricted works

app/views/downloads/_download_afterword.html.erb
When rendering a work to be downloaded, Devise functions are unavailable, so all calls to `ApplicationHelper#byline` on items that could have `anonymous?` set to true need to have `visibility: 'public'` set.
See my comment on the issue.
=> AO3-3880 Prevent 500 error when downloading a work that has an anonymous work listed in "Works inspired by this one."

app/models/download_writer.rb
From the [ebook-convert documentation](https://manual.calibre-ebook.com/generated/en/ebook-convert.html#cmdoption-ebook-convert-toc-threshold):
> --toc-threshold
> If fewer than this number of chapters is detected, then links are added to the Table of Contents. Default: 6
So basically what was happening was, if the work had fewer than four chapters (because four actual chapters, plus preface and afterword equals six) and it had work or chapter endnotes, you'd end up with "notes" as a TOC entry. 
This was weird, since it's not like we were also adding entries for the beginning notes or summary. It was even weirder if you had multiple end notes because only _one_ of the endnotes would be linked because, by default, ebook-convert does not …
=> AO3-3880 Don't add "notes" entry to ebook table of contents

app/controllers/downloads_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5630
Use [around_action with begin/ensure](https://guides.rubyonrails.org/action_controller_overview.html#after-filters-and-around-filters) to run cleanup even when the action has errors.
Use Download.remove because if download generation fails, `@download` will be nil.
Confirm downloads still work on staging.
Locally, I tested this by removing the zip command (`sudo apt remove zip`), forcing epub generation to crash every time, and checking that the `/tmp/<work ID>` directory gets created then deleted properly.
=> AO3-5630 Always delete /tmp files after download generation

public/stylesheets/ebooks.css
https://otwarchive.atlassian.net/browse/AO3-5634
Adds whitespace between the tag sections and indents the list of tags from its faux heading, so ebooks now look like
```
Fandom:
Grace and Frankie
Relationship:
Frankie Bergstein/Grace Hanson
```
instead of like
```
Fandom:
Grace and Frankie
Relationship:
Frankie Bergstein/Grace Hanson
```
Refer to Jira.
Options were given and a vote was taken. The results were 🍎 9, 🍌 12, 🍪 2, and 🐟 1. Ergo, we are adding 🍌 whitespace.
=> AO3-5634 Add  🍌 whitespace to meta section of ebooks

app/controllers/downloads_controller.rb, app/models/download.rb, app/models/download_writer.rb, app/models/work.rb, features/step_definitions/work_download_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5631
Add the file type and current timestamp to the directory name. This means each generation has to stay with the same Download instance for proper cleanup, and the Download class methods become obsolete.
Having timestamped directory names means we need to freeze time so the tests can find the generated files.
Confirm downloads still work on staging.
Locally, I repeated the testing I did for #3528 as well.
=> AO3-5631 Make /tmp download directory unique per generation

script/prepare_codeship.sh, script/travis_elasticsearch_upgrade.sh
https://otwarchive.atlassian.net/browse/AO3-5621
Changes the version of Elasticsearch in use on Travis and Codeship to be 6.6.0
No user testing required.
=> AO3-5621 Update Elasticsearch on CI to 6.6.1

lib/devise_failure_message_options.rb
https://otwarchive.atlassian.net/browse/AO3-5604
changes the problems when logging in link from the outdated `admin_posts/1277` to `admin_posts/12035`
the new link doesn't exist on staging, so just test that when you hover over the link, you see the new path (12035)
=> AO3-5604 Problems When Logging In link in log in error message goes to outdated post

app/views/user_invite_requests/new.html.erb
https://otwarchive.atlassian.net/browse/AO3-4195
What does this PR do? 
Adds the "* Required Information" notice at the top of the request invites form and adds (*) next to each label.
Note: I realize the notice is a bit off from the form. Perhaps that can be fixed after the first initial pass. 
1. Log in as a user
2. My Dashboards
3. Click on "Invitations" button 
4. Click on "Request Invitations" button 
Are there any other relevant issues / PRs / mailing lists discussions related to this? None that I know of
*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?* Angela is just fine
(If you have an account on JIRA, please include the same name in the "Full name" field on your JIRA profile,
so we …
=> AO3-4195 Request more invites page required fields not sufficiently marked

app/views/tags/edit.html.erb
https://otwarchive.atlassian.net/browse/AO3-4881
moves the `last updated by` paragraph on tag edit pages to the top for convenience
2. Go to a tag's edit page, e.g. http://test.archiveofourown.org/tags/Testing/edit
3. Confirm the `last updated by xxx` information is now at the top of the page on all screen sizes as opposed to the bottom of the page
=> AO3-4881 wrangling admin: move "last updated by" paragraph under navigation

db/migrate/20190207034230_restore_default_empty_strings.rb
https://otwarchive.atlassian.net/browse/AO3-5611
These were unintentionally removed by the UTF8MB4 upgrade script.
I don't think we need to test much as long as the migration runs OK.
=> AO3-5611 Restore empty default values for certain string columns

app/views/users/sessions/_passwd_small.html.erb
https://otwarchive.atlassian.net/browse/AO3-4377
Fixes the problem where clicking "Remember me" in the header login form would put the focus on the wrong field if you were on the login page.
Go to the page and clicky clicky.
=> AO3-4377 Associate remember me label and field in header login form

app/views/tags/edit.html.erb
https://otwarchive.atlassian.net/browse/AO3-4881
Stops the last wrangled by info from wrapping around the comment button.
Log in as admin, go to a tag's edit page, and fiddle with the window size to confirm the info about who last wrangled a tag does not get squished.
=> AO3-4881 Fix text wrapping on last wrangled by info

app/views/series/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-5250
When you edit a series bookmark, the button to save your changes should say "Update" instead of "Edit."
Bookmark a series, edit that bookmark, confirm the button says "Update" instead of "Edit."
=> AO3-5250 Update button text when editing series bookmark

app/controllers/chapters_controller.rb, app/controllers/works_controller.rb, app/models/work.rb, features/works/chapter_edit.feature, lib/taggable.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5603
1. I overhauled the WorksController and the ChaptersController to try to eliminate the function `set_instance_variables`.
- I moved the code to build a blank item into `#new`, the code to build an item from params into `#create`, and the code to modify an existing item into `#update`.
- I moved the instance variable assignment into `load_pseuds` (for the ChaptersController) and `set_work_form_fields` (for the WorksController).
- I did a similar thing for `WorksController#set_instance_variables_tags`.
2. In the process, I cleaned up the before_action filters a little for both controllers.
3. I also refactored several of the functions that I was modifying, to make it easier to follow the flow of control.
- I moved the check for …
=> AO3-5603 Revise WorksController to eliminate set_instance_variables.

app/models/bookmark.rb
https://otwarchive.atlassian.net/browse/AO3-5647
Removes some bookmark code that used to be used in bookmark indexing, but is no longer used anywhere.
As long as this passes automated tests, I'm not sure any manual testing is required. But if you wanted to be thorough, you could try creating a bookmark on a brand new work and making sure it can be found with bookmark search.
=> AO3-5647 Remove unused bookmark code.

app/controllers/admin/settings_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/works_controller.rb, app/models/admin_setting.rb, app/models/bookmark.rb, app/models/work.rb, app/sweepers/collection_sweeper.rb, app/views/admin/settings/index.html.erb, app/views/collections/_collection_blurb.html.erb, app/views/collections/_sidebar.html.erb, db/migrate/20190323185300_drop_disable_filtering_from_admin_settings.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5473
This PR removes the `disable_filtering` admin setting, as well the functions `list_without_filters` and `collected_without_filters` that were used exclusively to implement the ES-free bookmark and work listings. It also removes some nearby scopes in the Work class that are either unused, or used only in the `list_without_filters` and `collected_without_filters` functions.
Note that you may want to view the diff ignoring whitespace, because there are a fair amount of indentation changes in the WorksController and BookmarksController.
See JIRA.
=> AO3-5473 Remove disable_filtering admin setting.

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5637
This PR modifies the code in `WorksController#index` that checks whether the list of works can be cached to ensure that it doesn't cache when either `params[:include_work_search]` or `params[:exclude_work_search]` is set.
See JIRA.
=> AO3-5637 Check include/exclude before caching in work listings.

app/models/story_parser.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5648
Preserves internal anchor links in imported documents
When importing a work which contains links to anchors within the document (eg: `#notes`), the links should no longer be turned into absolute links to the external site url.
=> AO3-5648 Keep anchor links intact in imported works

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5526
Modifies the line-height to 1.5 for stats 
Note: This should be done on a Windows machine
1. Look at the works to make sure it looks like these pictures from this ticket: https://otwarchive.atlassian.net/browse/AO3-5420
This was a correction for this change in this ticket: https://otwarchive.atlassian.net/browse/AO3-5420 
*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?* Angela
(If you have an account on JIRA, please include the same name in the "Full name" field on your JIRA profile,
so we can find you and assign you the issues you're working on.)
She
(If you do not fill this in, we …
=> AO3-5526 Too much space between stats lines on work blurbs

app/controllers/wrangling_guidelines_controller.rb, features/tags_and_wrangling/wrangling_guidelines.feature
https://otwarchive.atlassian.net/browse/AO3-4681
show confirmation that wrangling guidelines were successfully deleted, update wrangling guideline test
2. Admin Posts > Wrangling Guidelines > New Wrangling Guideline
3. Fill in required fields
4. Post
5. Follow "Wrangling Guidelines" link to return to list of guidelines
6. Select "Delete" for the guideline you just posted
7. Choose "OK" in the confirmation dialogue
8. You should see a confirmation message `Wrangling Guideline was successfully deleted.`
=> AO3-4681 Add success message when deleting wrangling guideline

app/models/admin_setting.rb
https://otwarchive.atlassian.net/browse/AO3-5598
> Setting `:race_condition_ttl` is very useful in situations where a cache entry is used very frequently and is under heavy load. If a cache expires and due to heavy load several different processes will try to read data natively and then they all will try to write to cache.
https://api.rubyonrails.org/v5.1.6.2/classes/ActiveSupport/Cache/Store.html#method-i-fetch
See issue.
=> AO3-5598 Set race_condition_ttl on cached AdminSetting

spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5653
These tests need to be in the "when report is not spam" block which stubs Akismetor.
Travis should be good.
=> AO3-5653 Fix intermittent AbuseReport alternate URL test failures

app/views/home/_intro_module.html.erb
https://otwarchive.atlassian.net/browse/AO3-5672
Remove hypens from nonprofit and noncommercial on homepage
Log out and look at the homepage.
=> AO3-5672 Remove hypens from nonprofit and noncommercial on homepage

app/models/download_writer.rb
https://otwarchive.atlassian.net/browse/AO3-5656
Fixes 500 error when the user tries to download the work with nil summary in the formats epub, azw3, or mobi.
Someone with access to the test server can manually set the summary of a work to nil and then try downloading it in the formats epub, azw3, and mobi.
lethnie, she/her
=> AO3-5656 Fix downloading works with nil summary

public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-5180
Modifies our narrow stylesheet so it prefers _not_ to break long words when they'll fit on a single line while still allowing long words that _need_ to be broken to break wherever. (See issue for illustration.)
Replaces #3069, which I added way too many files to when attempting to merge with master. (It didn't have merge conflicts; I was just annoyed by the outdated test failure. That'll teach me.) 
I'm just going to slap the ready to merge label back on it because there were no changes.
Refer to JIRA
=> AO3-5180 Better word breaking for mobile headings

app/models/common_tagging.rb, app/models/meta_tagging.rb, spec/miscellaneous/lib/tasks/tag_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-2452
It adds tests for the two deletion tasks, and fixes up some issues that arose when deleting MetaTaggings/CommonTaggings that were missing one or more tags.
=> AO3-2452 Fix CommonTagging/MetaTagging deletion tasks and add tests.

app/controllers/users_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5694
Makes `@fandoms = []` for the orphan_account so we can see if loading that list is the reason the orphan_account's dashboard has stopped loading. 
This is a temporary change (famous last words!) to help us diagnose the actual problem. If the orphan_account dashboard starts loading once this is deployed, we should come up with a new way of counting fandoms. If it doesn't start loading, we should remove this code and keep looking for the problem.
Refer to Jira.
=> AO3-5694 Don't load fandoms list on orphan_account user dashboard

app/controllers/admin/admin_users_controller.rb, app/models/user.rb, app/views/admin/admin_users/index.html.erb, features/admins/users/admin_find_users.feature
https://otwarchive.atlassian.net/browse/AO3-5099
Adds an option for exact string matching in admin user search.
Search for user names with exact matching checked.
I've also added feature tests for email and user names when exact is checked.
Tal Hayon
Please use he.
=> AO3-5099 Add option for exact string match for admin user search

db/migrate/20190611212339_add_unique_index_to_meta_taggings.rb
https://otwarchive.atlassian.net/browse/AO3-5697
This PR replaces the index on `meta_tag_id` for the `meta_taggings` table with a unique index on `(meta_tag_id, sub_tag_id)`.
For `pt-online-schema-change`, I believe the argument to `--alter` corresponding to this migration is:
```
ADD UNIQUE INDEX
index_meta_taggings_on_meta_tag_id_and_sub_tag_id
(meta_tag_id, sub_tag_id),
DROP INDEX
index_meta_taggings_on_meta_tag_id
```
The argument `--nocheck-unique-key-change` may also be necessary, since `pt-online-schema-change` tries to ensure that data will not be lost when adding a new unique index.
=> AO3-5697 Add unique index to meta_taggings table.

app/models/work.rb, app/views/tags/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-3953
Expire caches that can unwanted contain collection-scoped tag links (#3454).
See issue.
=> AO3-3953 Expire caches of work blurbs, metas, and links on tag pages

app/controllers/admin/admin_users_controller.rb, app/models/user.rb, app/views/admin/admin_users/index.html.erb, features/admins/users/admin_abuse_users.feature, features/admins/users/admin_find_users.feature, features/admins/users/admin_fnok.feature, features/admins/users/admin_manage_users.feature, features/step_definitions/archivist_steps.rb, features/tags_and_wrangling/tag_wrangling.feature, features/tags_and_wrangling/tag_wrangling_admin.feature
https://otwarchive.atlassian.net/browse/AO3-5099
https://otwarchive.atlassian.net/browse/AO3-5126
I updated the Admin Users page to split the "Name or email" query into separate "Name" and "Email" queries. I also changed the capitalization of "Search settings" to match the screencap included in the JIRA issue, and changed the text on the page to better reflect the new search options.
I also changed `User.search_by_role` so that it uses `distinct` instead of `select("DISTINCT(users.*)")`, which could produce incorrect result counts.
=> AO3-5099 & AO3-5126 Separate "Name or email" query into two fields, and fix the results count.

app/models/user_manager.rb
https://otwarchive.atlassian.net/browse/AO3-5097
Stops the "Fannish next of kin was updated" success message from being added when a user has a FNOK but the FNOK is not changed.
Refer to issue
=> AO3-5097 Don't display update success message when FNOK is unchanged

app/mailers/admin_mailer.rb, app/views/admin_mailer/send_spam_alert.html.erb, app/views/admin_mailer/send_spam_alert.text.erb, spec/miscellaneous/mailers/admin_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5549
This PR updates the spam report email so that it won't generate an error when a user's account is deleted after the spam report is generated, but before the email with that report is sent. Instead, it silently omits any missing users (and aborts the entire email if all listed users have been deleted).
See JIRA.
=> AO3-5549 Handle deleted users in spam alert.

app/controllers/tag_wranglers_controller.rb, features/tags_and_wrangling/tag_wrangling_admin.feature, features/tags_and_wrangling/tag_wrangling_more.feature
https://otwarchive.atlassian.net/browse/AO3-4682
adds a confirmation message when wranglers have successfully been unassigned from fandom. mimics the `wranglers successfully assigned` confirmation message. updates tests in:
`tag_wrangling_admin.feature`
`tag_wrangling_more.feature`
1. Log in as an admin or Tag Wrangler
2. Go to the Wranglers page: http://test.archiveofourown.org/tag_wranglers
3. Choose the "x" next to a wrangler's name to unassigned them from a fandom
4. If the action was successful, you should see a `Wranglers were successfully unassigned!` confirmation message
=> AO3-4682 add success message when unassigning wrangler from a fandom

app/controllers/works_controller.rb, features/works/work_dates_edit.feature
https://otwarchive.atlassian.net/browse/AO3-5691
Avoid the "translation missing" error. We have that error because in `@chapter.errors.each { |err| @work.errors.add(:base, err) }`, `err` is a hash thing with a `:base` key, so we nest them into `attributes.base.base`.
See issue.
=> AO3-5691 Fix error message when editing a work's publication date to the future

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5475
https://otwarchive.atlassian.net/browse/AO3-5658
1. Make sure that the error messages for `WorksController#update_multiple` have `.html_safe` applied so that they don't get escaped
2. Make sure that the work validations will be run even if the work is missing required tags. This will cause it to generate the error message about invalid tags when a work's only fandom is invalid, instead of just saying that no fandom was provided.
=> AO3-5658 Don't escape error messages on the Edit Multiple Works page, and make the invalid tag error message appear.

public/help/privacy-preferences.html
https://otwarchive.atlassian.net/browse/AO3-5658
Remove a sentence from the help pop-up
Make sure it's gone
=> AO3-5658 Remove sentence from privacy help pop-up

app/controllers/application_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/chapters_controller.rb, app/controllers/series_controller.rb, app/controllers/works_controller.rb, app/helpers/series_helper.rb, app/helpers/works_helper.rb, app/models/bookmark.rb, app/models/concerns/creatable.rb, app/models/external_work.rb, app/models/series.rb, app/models/work.rb, app/views/chapters/_chapter.html.erb, app/views/chapters/show.html.erb, app/views/users/_sidebar.html.erb, app/views/works/show.html.erb, spec/controllers/works/drafts_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5658
https://otwarchive.atlassian.net/browse/AO3-5751
The pre-existing code for handling who's allowed to see drafts and draft chapters was inconsistent. In particular:
- Admins could see single-chapter drafts, but not multi-chapter drafts.
- In a multi-chapter work with multiple creators, a draft chapter with only one creator was only visible to the other creator in chapter-by-chapter mode, not in view full work mode.
- A user invited to be co-creator on a single-chapter draft could see the work, but a user invited to be a co-creator on one chapter of a multi-chapter draft could not see the work.
- A user invited to be co-creator on an unposted work with a series could not see the series unless the series contained another work.
This PR tries …
=> AO3-5658 AO3-5751 Make the ability to view drafts more consistent, and add admin access to the user drafts page.

config/locales/en.yml, features/works/chapter_edit.feature
https://otwarchive.atlassian.net/browse/AO3-5658
One last tweak to the co-creator notification email text!
Add a series to a co-created work. Your co-creator should get an email with the new text. (You could also check by adding a chapter that lists your co-creator as a co-creator.)
=> AO3-5658 Update co-creator notification text

app/views/home/tos_faq.html.erb
https://otwarchive.atlassian.net/browse/AO3-5077
Fixes broken anchor links in the TOS FAQ page. 
Replaces #3127 
MaxwellsDaemon
Him
=> AO3-5077 Fix TOS FAQ Anchor Links

config/locales/devise.en.yml, features/admins/authenticate_admins.feature
https://otwarchive.atlassian.net/browse/AO3-5024
* Updates the error message you try to log in with an existing admin name with the wrong password.
* Tests aforementioned scenario.
* Tidies the tests in the relevant feature file:
* Consistent indenting and spacing.
* Updated scenario descriptions.
* Use the label text for the field names.
Try to log in as an admin using an existing admin username, but an incorrect password.
=> AO3-5024 Correct error message when entering wrong password for admin

app/views/users/delete_preview.html.erb, features/users/user_delete.feature
https://otwarchive.atlassian.net/browse/AO3-5688
* Changes remaining "co-author" to "co-creator."
* Improves indenting/spacing.
* Stops using hash rockets.
* Uses symbols rather than strings where possible.
* Uses double quotes for strings.
If you're feeling adventurous, I also have a version that makes it mostly translatable: https://github.com/otwcode/otwarchive/compare/master...sarken:AO3-5688_BOT_i18n?expand=1 ("Mostly" because I didn't change the way it handles the list of pseuds.)
=> AO3-5688 Change "co-author" to "co-creator" on delete preview page

app/controllers/tags_controller.rb, app/helpers/tags_helper.rb, app/views/tags/show_hidden.js.erb, app/views/works/_meta.html.erb, features/other_a/preferences_edit.feature, features/step_definitions/preferences_steps.rb, features/step_definitions/user_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5613
https://otwarchive.atlassian.net/browse/AO3-5613?focusedCommentId=355413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-355413
If you enable the “Hide warnings” preference, the “Show warnings” link in the work meta should once again show the warning tags.
* Grabs the tests from #3290, which originally revealed the problem.
* Refactors `blurb_tag_block(item, tag_groups=nil)` so the code branch responsible for handling the "Show warnings..." is a separate method (`show_hidden_tag_link_list_item(item, category, options = {})`).
* Updates views/works/_meta to use the new method.
There were a few variable names I wanted to change and some methods that could have had better names, but I wanted to keep it clear for …
=> AO3-5613 Fix revealing hidden warning tags in work meta

app/models/search/work_indexer.rb, app/models/search/work_query.rb, app/models/serial_work.rb, spec/models/search/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5652
Slightly changes and expands the series data being indexed with works. The behavior should be similar (with a small change from "series_titles:" to "series.title:") but the extra data should give us more to work with later on. General searches should also include the series title field, though at a lower priority than the work title.
See instructions in issue.
elz and redsummernight
=> AO3-5652 Index more series data

app/views/user_mailer/challenge_assignment_notification.html.erb, app/views/user_mailer/challenge_assignment_notification.text.erb, config/locales/en.yml, features/gift_exchanges/notification_emails.feature, features/step_definitions/challege_gift_exchange_steps.rb, features/step_definitions/challenge_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5613
https://otwarchive.atlassian.net/browse/AO3-5613?focusedCommentId=355425&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-355425
Prevents error when sending challenge assignment emails containing warning tags. Also ensures the Warning or Warnings label shows up.
* Create a gift exchange that allows users to including warnings in their requests and offers
* Have folks sign up for the exchange with warnings in requests and offers
* Run matching and send assignments
The participants should receive emails containing their assignment, including warning tags.
=> AO3-5613 Prevent error when challenge assignment email contains warning tags

config/application.rb, spec/miscellaneous/requests/security_headers_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5632
Adds a referrer policy to our headers.
Check the response headers on staging when you request a page. See issue for details.
=> AO3-5632 Set Referrer-Policy header

.travis.yml, script/travis_ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-5788
[Bionic](https://docs.travis-ci.com/user/reference/bionic) is closer to the production environment (Debian 10).
Codeship is already on Bionic (#3529).
=> AO3-5788 Move Travis to Ubuntu Bionic 18.04

lib/css_cleaner.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4080
This fixes the css regex so it doesn't fail on development.
I've removed the 'pending' state from the spec test for this bug. I will say this though, I've no idea why this works on production. This regex makes me cry tears of blood.
Tal.
Please use he.
=> AO3-4080 Fix css regex to support shadow box fully

config/.rubocop.yml
https://otwarchive.atlassian.net/browse/AO3-5758
Fix this error:
```
Error: The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
(obsolete configuration found in .rubocop.yml, please update it)
```
None.
=> AO3-5758 Fix renamed cop in rubocop 0.72.0

lib/html_cleaner.rb, lib/otw_sanitize/media_sanitizer.rb, spec/miscellaneous/lib/html_cleaner_spec.rb, spec/miscellaneous/lib/media_sanitizer_spec.rb
Allows standard html within audio and video tags instead of stripping it out
Post some html (paragraphs, links) within an audio or video tag
co-credit @redsummernight
=> AO3-5693 Allow standard html within audio and video tags

public/stylesheets/site/2.0/21-userstuff.css
Makes sure videos embedded with the `<video>` tag aren't bigger than 100% of the width of the container.
Post very large video, ensure it is not very large on a small screen.
=> AO3-5693 Restrict width of video elements

lib/otw_sanitize/media_sanitizer.rb, spec/miscellaneous/lib/media_sanitizer_spec.rb
If you use the boolean attributes `loop`, `muted`, or `default` in your media, the attribute value should be the same as the attribute name, e.g. `loop="loop"`, to be consistent with the way we handle our automatically-added boolean attributes, e.g. `controls`.
Use the aforementioned attributes when embedding audio or video, but do not include a correct value (or any value) -- for example, you might do `<video loop="potato" muted>`. After posting, edit your work to check that the HTML is updated to include a value that matches the attribute name (so for our example, the desired outcome would be `<video loop="loop" muted="muted">`).
=> AO3-5693 Supply values for whitelisted boolean attributes

lib/html_cleaner.rb, spec/miscellaneous/lib/html_cleaner_spec.rb
This is a hack until we switch to an HTML5 serializer.
See issue.
=> AO3-5693 Remove invalid closing tags on track and source elements

db/schema.rb, db/structure.sql
https://otwarchive.atlassian.net/browse/AO3-5194
Generate new versions of schema dumps from production:
```sh
bundle exec rake db:schema:dump    # Ruby dump
bundle exec rake db:structure:dump # SQL dump
```
Manually edit the resulting files:
- Ruby dump: Change the version in `ActiveRecord::Schema.define` to the latest migration timestamp. Then we need to check the existing pull requests for migrations and [bump their timestamps to later](https://stackoverflow.com/a/4047884).
- SQL dump: Remove [AUTO_INCREMENT values](https://stackoverflow.com/questions/2210719/out-of-sync-auto-increment-values-in-development-structure-sql-from-rails-mysql).
Replaces #3643.
Travis build should pass.
=> AO3-5194 Update schema and structure files

app/models/challenge_assignment.rb, features/gift_exchanges/challenge_giftexchange.feature
https://otwarchive.atlassian.net/browse/AO3-4571
When the work form is trying to figure out which assignment checkboxes ought to be checked by default, it checks whether each of the user's assignments is included in the work's assignments. This inclusion check calls the `ChallengeAssignment` class's equality check.
Because the `ChallengeAssignment` class includes `Comparable` and defines a comparison function `<=>`, the comparison function overrides the default rails equality check.  But the `<=>` function only checks the offering/recipients pseuds, not the assignment ID or the challenge name. This means that if a user has the same assigned recipient in multiple challenges, all of the assignments are treated as "equivalent" by the work form.
This PR removes the unnecessary comparison …
=> AO3-4571 Fix challenge assignment equality check.

public/stylesheets/site/2.0/16-zone-system.css
https://otwarchive.atlassian.net/browse/AO3-5616
Fixes a display issue with FAQ categories written in right-to-left languages. The fix is the one that was suggested on the JIRA ticket.
Check this page in the staging environment: https://test.archiveofourown.org/faq?utf8=%E2%9C%93&language_id=ar
Alix R
she/her
=> AO3-5616 Fix FAQ category display with RTL scripts

script/codeship/setup.sh
https://otwarchive.atlassian.net/browse/AO3-5749
Change --strip-components=1 to --strip-components=2 in tar.
Codeship should pass.
https://github.com/elastic/elasticsearch/issues/49417
=> AO3-5749 Fix Elasticsearch 6.8.5 on Codeship

Gemfile.lock, lib/html_cleaner.rb, spec/miscellaneous/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5826
Updates the nokogiri gem and fixes a test to reflect a resultant change in behavior.
Replaces #3692
=> AO3-5826 Update nokogiri to 1.10.5

app/helpers/users_helper.rb, app/models/search/bookmark_search_form.rb, app/models/search/work_search_form.rb, app/views/users/_contents.html.erb, app/views/users/_sidebar.html.erb, config/config.yml, features/bookmarks/bookmark_privacy.feature, features/step_definitions/search_steps.rb, features/users/user_dashboard.feature
https://otwarchive.atlassian.net/browse/AO3-5825
This cuts down on the number of Elasticsearch count queries.
Unlike [cached search results in WorksController](https://github.com/otwcode/otwarchive/blob/cccba97ecd7b4ab69ff22a00f3df9cddf7f22860/app/controllers/works_controller.rb#L103), cached keys for the counts are not timestamped and cannot be invalidated by e.g. [WorksOwner#update_works_index_timestamp](https://github.com/otwcode/otwarchive/blob/cccba97ecd7b4ab69ff22a00f3df9cddf7f22860/lib/works_owner.rb#L37-L43). The counts will lag
behind the actual search results.
See issue.
=> AO3-5825 Cache work and bookmark counts on dashboard sidebar

app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5832
Send response code 444 up the stack, where we can use it to render the right error page (so we still see errors in our error tracking system).
Turn Elasticsearch on staging off and expect the new error page (#3699).
=> AO3-5832 Return 444 for Elasticsearch errors

public/stylesheets/site/2.0/05-region-main.css
https://otwarchive.atlassian.net/browse/AO3-5362
This commit moves the background image on the 'login' page down and to the
right. This stops the image from being overlapped by banners
(eg: the 'Please log in' banner).
The issue suggests 2em down and 2em right, but with these dimensions,
the banner still overlapped the logo, and on mobile screens,
the logo overlapped the login text on the right. 0.5em was as far as it
could go! 3em seems to be the minimum it should move down.
*Without this patch applied, browse to:
http://127.0.0.1:7000/users/login
*Apply the patch, restart rails, refresh the page in the browser
*Try a few screen sizes in the web console 'responsive design' mode
Name: Z
Pronouns: she/her or they/them
=> AO3-5362 Move background logo down and right

app/views/users/confirmation.html.erb, config/brakeman.ignore, features/importing/archivist.feature, features/other_a/invite_queue.feature, features/other_a/invite_request.feature, features/step_definitions/invite_steps.rb, features/users/user_create.feature
https://otwarchive.atlassian.net/browse/AO3-5738
This PR updates the page users see after creating an account to contain the text indicated in the JIRA issue page. It also updates the related Cucumber tests.
- Set up an account
- Check if the correct text is shown
Alix R
She/her
=> AO3-5738 Update page that appears after account is set up

app/models/external_work.rb
https://otwarchive.atlassian.net/browse/AO3-5773
External Works have some characters such as ampersands encoded when posting, even when attempting to edit as an Admin. This PR makes sure the special characters are saved to the DB instead of their HTML encoded versions.
Just need to repeat the Jira ticket's steps on master vs on this branch.
bird
I like they :)
=> AO3-5773 Avoid re-escaping ampersands in titles of external work bookmarks

app/controllers/application_controller.rb, factories/bookmarks.rb, spec/controllers/bookmarks_controller_spec.rb, spec/controllers/works/default_rails_actions_spec.rb, spec/models/bookmark_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5838
Makes sure the bookmarks controller index action is covered a bit better by automated tests, particularly when the experimental caching setting is enabled. It also allows us to actually enable that setting in tests 😭 
=> AO3-5838 Expand test coverage of bookmarks controller index action

config/application.rb, spec/miscellaneous/requests/security_headers_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5818
Use strict-origin-when-cross-origin because:
- YouTube embedding can be [blocked based on domains](https://support.google.com/youtube/answer/6301625?hl=en) and they can block playback if referrer information is missing.
- We still want to avoid sending too much referrer information to other sites (see [AO3-5632](https://otwarchive.atlassian.net/browse/AO3-5632)), so sending just the origin (protocol + domain + port, without path or querystring) is a good compromise.
- Within the site, we do need to send the path and querystring, which we use to identify last known visited pages and to calculate hit counts (#2779).
This is also [Rails 5.2's default choice](https://guides.rubyonrails.org/v5.2/configuring.html#configuring-action-dispatch) for …
=> AO3-5818 Update Referrer-Policy for YouTube's embedding restrictions

Gemfile, Gemfile.lock, config/application.rb, config/config.yml, config/routes.rb, config/secrets.yml
https://otwarchive.atlassian.net/browse/AO3-5759
Reverts otwcode/otwarchive#3710.
We were getting redirected to `unicorn_write` and `unicorn_story` when following links (not just links with the lockup params, either) or submitting forms, so we're going to revert for now and try again once we have the proper staging site back.
Refer to Jira.
=> AO3-5759 Revert adding Lockup to remove password protection on staging

app/models/pseud.rb, app/models/user.rb
None.
Cached kudos should update when deleting users or changing default pseuds.
Orphaned kudos should appear somewhere.
[skip ci]
None, just comments.
=> Add TODOs for known issues with kudos cache expiration

features/other_b/series.feature
https://otwarchive.atlassian.net/browse/AO3-3847
Wait a few seconds for cache expiration to happen.
Automated. I got `TEST_GROUP="cucumber -r features features/other_b"` to pass 10 times consecutively on my fork's Travis.
=> AO3-3847 Add delays to make series in work blurb tests less flaky

app/controllers/works_controller.rb, public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-5845
Force the twitter share button to be visible. There are doubtlessly more elegant fixes but this works.
Stage the changes. Click share. Note that the share button is visible.
No.
derenrch
he/him
=> AO3-5845 Prevent Twitter share button from vanishing in Firefox and Chrome

app/views/home/_inbox_module.html.erb
https://otwarchive.atlassian.net/browse/AO3-5624
Rearranges the Reply, Mark Read, and Delete bottons on messages in the Unread Message section of the homepage from Delete, Mark Read, Reply, to Reply, Mark Read, Delete, to more closely mirror the order of these buttons on the comments section of works.
Go to https://test.archiveofourown.org/ and log in to an account. On the homepage, scroll to the Unread Messages section. Confirm that the buttons on the message(s) are Reply, Mark Read, and Delete, in that order, and that they work as expected. 
Nerine Luna Cyran, she/her
=> AO3-5624 Reorder buttons on homepage unread messages

public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-5184
In desktop Safari and on iOS browsers, you can't open the Advanced section of the skins edit page. This fixes that.
Refer to Jira.
=> AO3-5184 Make Advanced section of skins toggleable again in Safari

public/stylesheets/sandbox.css, public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-5845
Following the previous pull request for this issue, the Twitter share button still wasn't always appearing. It was especially stubborn in Chrome on Windows, refusing to load more often than not. Some testers and I experimented and determined setting the `width` and `height` in addition to `min-width` and `min-height` appeared to help, although it probably won't totally fix the problem.
Using Chrome on Windows, go to a work, press the "Share" button, and see if there's a Twitter button.
=> AO3-5845 Make the Twitter share button appear more often in Chrome on Windows

db/migrate/20200115232918_add_user_id_to_kudos.rb
https://otwarchive.atlassian.net/browse/AO3-5844
This PR adds a new (unused) user_id column and (not yet unique) index to the kudos table.
For staging + beta, use pt-online-schema-change --alter args:
up:
```
ADD COLUMN user_id INT 
ADD INDEX index_kudos_on_user_id (user_id)
```
down:
```
DROP COLUMN user_id 
DROP INDEX index_kudos_on_user_id (user_id)
```
Side note: I've seen migrations (outside of otw) that require a ptosc in specific environments wrap the migration code in a conditional a la:
```
def up
if Rails.env.production? || Rails.env.staging?
=begin
pt-online-schema-change command with ADD COLUMN and ADD INDEX in block comment
=end
else
end
end
def down
end
```
But I didn't see this done in any of our existing migrations. How do we normally prevent migrations from being run in …
=> AO3-5844 Migration to add user_id column to kudos table

db/migrate/20200115232918_add_user_id_to_kudos.rb
https://otwarchive.atlassian.net/browse/AO3-5844
According to comments in the [JIRA issue](https://otwarchive.atlassian.net/browse/AO3-5844), we no longer need to run "insert into schema_migrations..." now that rake db:migrate can run in all environments. So this PR removes this unnecessary comment.
Sorry about all the back and forth on this straightforward JIRA ticket, everyone! But since this is the first time we're adding the migration commands for staging and prod in the migration file as comments, hopefully this can serve as an example for future migrations to mimic.
Previous PR, already merged into otwcode/otwarchive:master: https://github.com/otwcode/otwarchive/pull/3723
=> AO3-5844 Remove unnecessary schema_migrations insert comment from migration

app/views/admin_posts/_admin_post.html.erb
https://otwarchive.atlassian.net/browse/AO3-5735
If a news post is written in a right-to-left language, this adds the `dir="rtl"` attribute to the header and userstuff divs.
2. Admin Posts > Post AO3 News
3. Fill in a title and content using a right-to-left language
4. Select appropriate language from the "Choose a language" menu
5. Press "Post"
6. Check the HTML source of the news post to make sure the `header` and `userstuff` divs both have the attribute `dir="rtl"`
=> AO3-5735 Add direction attributes for admin posts

app/controllers/admin/admin_users_controller.rb, app/models/user.rb, app/views/admin/admin_users/bulk_search.html.erb, features/admins/users/admin_find_users.feature, spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5233
This improves the bulk email search in the admin section so it looks for case insensitive emails and reports on the number of duplicates to make it easier to know how many matches there were.
This can be tested through the Admin interface. See Jira for the steps to reproduce the original bug.
=> AO3-5233 Case insensitive admin bulk email search

app/models/skin.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5796
Adds two new media query options for site skins: prefers-color-scheme: light and prefers-color-scheme: dark. These will let users create skins that automatically apply when their OS color scheme is set a certain way.  
Refer to Jira.
=> AO3-5796 Add prefers-color-scheme media query options for skins

app/views/admin/admin_users/bulk_search.html.erb, features/admins/users/admin_find_users.feature
https://otwarchive.atlassian.net/browse/AO3-5233
Remove the Not Found header when there are no emails found during a bulk email admin search
Search for email addresses that are all found and hopefully observe that there is no Not Founder heading randomly appearing on the page
=> AO3-5233 Remove Not Found heading in bulk admin search

script/get_user_data.rb
https://otwarchive.atlassian.net/browse/AO3-5863
When we updated to Devise, we started auditing IP addresses for some new things, or the names of the things we were already auditing changed. This updates the GDPR user data script in light of that.
- Add encrypted_password case to handle IPs recorded when someone changes their password.
- Add failed_attempts case to handle recorded IPs from failed login attempts, which are currently only logged in certain cases due to the way Devise updates the count of failed attempts.
- Add locked_at case to handle recorded IPs from the last failed login attempt before an account is locked due to too many login attempts.
- Clarify that the recently_reset case is from before the Devise change, and add a reset_password_sent_at case to handle IPs recorded …
=> AO3-5863 Add new Devise info to GDPR script

config/application.rb, config/locales/defaults/nl.yml
https://otwarchive.atlassian.net/browse/AO3-5857
Adds the nl.yml locale file from [the rails-i18n repo](https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale/) to our repo because it had gone missing.
We'll need to sync Phrase and confirm it shows up on the language list.
=> AO3-5857 Add rails-i18n locale file for Dutch (nl)

public/stylesheets/masters/reversi/reversi_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-4139
the notes on required fields are hard to read - this PR changes the text colour to white so that it can be read more easily
set your site skin to reversi, then try creating a new work or a new collection, and check that the notes on required fields have white text
=> AO3-4139 Reversi: Make notes on required fields easier to read

app/controllers/users_controller.rb, features/other_a/invite_queue.feature, spec/controllers/users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5316
- Change the message when activating a user account from "Signup complete! Please log in." to "Account activation complete! Please log in."
- Change the error message when activating an account that has already been activated to use `flash` instead of `flash.now`, so that the error message will show up after redirect.
- Change the other two errors in the `UsersController#activate` to redirect to `root_path` instead of a blank string. This doesn't actually change where it redirects to, but it makes the code a little clearer.
- Add a few new specs to increase coverage of the `activate` action.
See JIRA.
(Though I'm not sure whether the nginx changes have been applied to staging. If they haven't, that may need to be addressed before any of …
=> AO3-5316 Fix flash messages in UsersController#activate.

app/mailers/user_mailer.rb, app/models/collection_item.rb, app/views/user_mailer/anonymous_or_unrevealed_notification.html.erb, app/views/user_mailer/anonymous_or_unrevealed_notification.text.erb, config/locales/mailers/en.yml, features/collections/collection_anonymity.feature, public/help/collection-preferences.html
https://otwarchive.atlassian.net/browse/AO3-5028
This PR adds a new callback to the CollectionItem class that checks whether the maintainer is making the item unrevealed/anonymous when the work isn't already unrevealed/anonymous. If so, the callback sends a notification email to all of the work's creators.
See JIRA.
=> AO3-5028 Notify creators when a collection maintainer makes their work unrevealed and/or anonymous.

app/mailers/user_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-5028
Modify the mailer action introduced in #3738 to use an options hash instead of keyword arguments.
=> AO3-5028 Don't use keyword arguments in the mailer.
