app/views/user_mailer/anonymous_or_unrevealed_notification.html.erb, app/views/user_mailer/anonymous_or_unrevealed_notification.text.erb, config/locales/mailers/en.yml, features/collections/collection_anonymity.feature
https://otwarchive.atlassian.net/browse/AO3-5028
- Changes the subject lines of the anonymous/unrevealed notification from "Your work has become [status]" to "Your work was made [status]."
- Changes the info included in the email when the work is becoming both anonymous and unrevealed.
=> AO3-5028 Assorted text changes for the anonymous/unrevealed notification emails.

app/models/feedback.rb, db/migrate/20200221045607_drop_approved_from_feedbacks.rb
https://otwarchive.atlassian.net/browse/AO3-5807
- Remove the last references to `approved` in the Feedback class.
- Add a migration to drop the column from the table.
The migration is patterned after the one in #3750, so it uses the same technique: when run in staging or production, it prints out a list of commands to run that looks something like this:
```
== 20200221045607 DropApprovedFromFeedbacks: migrating ========================
Schema Change Command:
pt-online-schema-change D=ao3_test,t=feedbacks \
--alter "DROP COLUMN approved" \
--no-swap-tables --no-drop-new-table --no-drop-triggers \
-uroot --chunk-size=10k --max-flow-ctl 0 --pause-file /tmp/pauseme \
--max-load Threads_running=25 --critical-load Threads_running=400 \
--set-vars innodb_lock_wait_timeout=2 …
```
=> AO3-5807 Drop approved column from feedbacks table.

lib/tasks/after_tasks.rake, spec/miscellaneous/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5873
Adds an after task (`bundle exec rake After:update_indexed_stat_counter_kudo_count`) to update the kudos count on indexed works after the great kudos migration (#3750)  takes place.
Refer to Jira.
redsummernight and Sarken
=> AO3-5873 Task to update kudos count on indexed works

db/migrate/20200210013551_add_unique_indices_to_kudos_and_change_id_type.rb
https://otwarchive.atlassian.net/browse/AO3-5869
This PR performs three modifications to the kudos table:
- change the type of the primary key to `bigint`
- add a unique index on `commentable_id, commentable_type, user_id`
- add a unique index on `commentable_id, commentable_type, ip_address`
It's currently written so that instead of performing the changes on staging or production, it prints out the commands that need to be run (with the database name filled in using info from Rails). The output should look something like this:
```
== 20200210013551 AddUniqueIndicesToKudosAndChangeIdType: migrating ===========
Schema Change Command:
pt-online-schema-change D=ao3_test,t=kudos \
--alter "ADD UNIQUE INDEX index_kudos_on_commentable_and_user (commentable_id, commentable_type, user_id),
ADD …
```
=> AO3-5869 Modify the kudos table to make the ID a bigint, and add unique indices.

app/controllers/kudos_controller.rb, app/models/kudo.rb, features/comments_and_kudos/kudos.feature, public/javascripts/application.js, spec/controllers/kudos_controller_spec.rb, spec/models/kudo_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5868
When we add the uniqueness constraint at the database level (#3750), we'll have the error handling ready at the application level (people will see "left kudos here :)" as usual).
For the rare cases where users can get past the Rails validation and run into the (future) database constraint, we should catch `ActiveRecord::RecordNotUnique` exceptions, similar to what we do on user creations:
https://github.com/otwcode/otwarchive/blob/57e7cab589abc7cc666ddf4d3abe768d801b3493/app/controllers/users_controller.rb#L9-L24
See issue.
=> AO3-5868 Change kudo uniqueness validation to use users instead of pseuds

script/codeship/ebook_converters.sh, script/travis/ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-5893
downloads.wkhtmltopdf.org is deprecated.
Travis/Codeship should pass.
=> AO3-5893 Download wkhtmltox packages from GitHub

spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5892
Check contents of decoded emails. This is only necessary when we need to look for work titles in HTML emails; the other changes are just for consistency.
Travis.
This fix is the same as #3696.
=> AO3-5892 Fix intermittent failures in UserMailer specs

db/migrate/20200210013551_add_unique_indices_to_kudos_and_change_id_type.rb
https://otwarchive.atlassian.net/browse/AO3-5869
Running pt-osc with the initial larger parameters caused errors:
```
2020-03-16T08:30:38 Error copying rows from `otwarchive_production`.`kudos` to `otwarchive_production`.`_kudos_new`: 2020-03-16T08:30:38 DBD::mysql::st execute failed: WSREP has not yet prepared node for application use [for Statement "INSERT LOW_PRIORITY IGNORE INTO `otwarchive_production`.`_kudos_new` (`id`, `pseud_id`, `commentable_id`, `commentable_type`, `created_at`, `updated_at`, `ip_address`, `user_id`) SELECT `id`, `pseud_id`, `commentable_id`, `commentable_type`, `created_at`, `updated_at`, `ip_address`, `user_id` FROM `otwarchive_production`.`kudos` FORCE INDEX(`PRIMARY`) WHERE ((`id` >= ?)) AND ((`id` <= ?)) LOCK IN SHARE MODE /*pt-online-schema-change 142490 …
```
=> AO3-5869 Update parameters for pt-online-schema-change commands

app/controllers/stats_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5821
This commit forces the Y-axis of the barchart on the user stats page
to start at 0. Previously, the Y-axis would start at a
dynamically-calculated value based on the data in the chart.
This meant that the bars did not work as a visual
representation of the data, because a bar half the size of another
bar did not depict a value half the size of another value.
(eg: if bars depicted hitcount, and the Y-axis started at 50,
a fic with 100 hits would have a bar double the size
of a fic with 75 hits.)
This patch forces the Y-axis to start at 0, by setting the
Google Chart API `vAxis: {Minvalue}` parameter to 0.
* Without this patch applied, login to an account with
at least 5 works with significant traffic, and browse to: …
=> AO3-5821 Make Statistics bar chart Y-axis start at 0

script/codeship/ebook_converters.sh, script/travis/ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-5896
Avoid rate limiting at GitHub releases.
The Codeship script downloads into a cached directory, so we can use `wget -N` to skip re-downloading files unless newer than local. The Travis script doesn't download into cached locations, so the flag doesn't matter there.
Travis/Codeship should pass.
=> AO3-5896 Download wkhtmltopdf from media.transformativeworks.org

config/initializers/monkeypatches/cve_2020_5267.rb
https://otwarchive.atlassian.net/browse/AO3-5898
For CVE-2020-5267. This should be removed when we get to Rails 5.2.
See issue.
=> AO3-5898 Monkey patch XSS vulnerability in ActionView

app/controllers/stats_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5821
Tweaks the way the JavaScript-based chart displays on the Statistics page.
* Makes the bars a dusty version of our red instead of default Google blue
* Prevents the graph from showing negative numbers when all values are zero
Log in, go to your Statistics page, and check the color. Then switch to a year and/or stat that you have no data for and make sure no negative numbers are on the y-axis.
=> AO3-5821 Adjustments to Statistics chart display

features/other_a/abuse_report.feature, features/step_definitions/admin_steps.rb, features/support/env.rb, spec/mailers/admin_mailer_spec.rb, spec/models/abuse_report_spec.rb, spec/models/feedback_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5900
Tests for spam check failures need to override this behavior. In all cases, tests should not actually hit Akismet.
Without this PR, this test is failing pretty much every run on Travis:
https://github.com/otwcode/otwarchive/blob/6201f4e055e125590cf9c14f58676205d32a7b00/features/other_b/support.feature#L6
None.
=> AO3-5900 Make spam checks pass in tests by default

app/controllers/comments_controller.rb, app/views/comments/_comment_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5162
So we can cache individual work and chapter pages for logged-out users.
We still need jquery.cookie for the TOS prompts, however.
See issue.
=> AO3-5162 Stop preloading name and email on guest comment forms

features/importing/archivist.feature, features/other_a/orphan_pseud.feature
https://otwarchive.atlassian.net/browse/AO3-5904
Wait between posting/importing works and orphaning them so the byline cache can expire.
Also remove some "When the system processes jobs" steps which do nothing. See [AO3-5722](https://otwarchive.atlassian.net/browse/AO3-5722).
Tests should pass on Travis.
On my fork, I have Travis run:
```yaml
env:
- RUN=00 TEST_GROUP="cucumber features/other_a features/importing/archivist.feature"
- RUN=01 TEST_GROUP="cucumber features/other_a features/importing/archivist.feature"
- RUN=02 TEST_GROUP="cucumber features/other_a features/importing/archivist.feature"
- RUN=03 TEST_GROUP="cucumber features/other_a features/importing/archivist.feature"
- RUN=04 TEST_GROUP="cucumber features/other_a features/importing/archivist.feature"
- RUN=05 …
```
=> AO3-5904 Add delays to make orphaning tests less flaky

app/controllers/application_controller.rb, app/controllers/chapters_controller.rb, app/controllers/works_controller.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5906
Creates a new session cookie for users who have accepted the adult content warning. We can use this cookie to determine which cached page nginx should give a user.
Note: We had some trouble with the session cookie not being sticky enough for logins, which is why even a non-"Remember me" log in lasts two weeks. We might have to set the expiry on this to 2 weeks as well.
Refer to Jira.
=> AO3-5906 Move adult content warning acceptance to separate cookie

app/controllers/chapters_controller.rb, app/controllers/works_controller.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5906
This adds an arbitary header we plan on catching in nginx and turning in to a cookie.
Refer to Jira.
=> AO3-5906 Set view adult response header for nginx to convert to cookie

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5908
Makes an attempt at redirecting to a path rather than a URL after accepting the adult content warning on a multichapter work. The idea is to stop bouncing people on the insecure site to secure.
=> AO3-5908 Redirect to work_chapter_path after accepting adult content warning

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5908
If we give [redirect_to](https://api.rubyonrails.org/v5.1/classes/ActionController/Redirecting.html#method-i-redirect_to) a string without protocols, it automatically prepends the current protocol and host, making the URL absolute.
Instead we give it an options hash with which it will call url_for.
See issue.
=> AO3-5908 Redirect to a multi-chapter work's first chapter with a relative URL

app/views/layouts/_javascripts.html.erb
https://otwarchive.atlassian.net/browse/AO3-5915
Some browsers that support localStorage do weird things like stop you from putting anything in it in private mode. This means visitors using those browsers can't get past the GDPR TOS prompt.
So what we're doing here is testing setting something in localStorage and then, if that doesn't work, repurposing it to create (or update or remove) a cookie.
Refer to Jira.
Refer to code comments.
=> AO3-5915 Write TOS acceptance to cookie when localStorage not available

app/models/redis_hit_counter.rb
https://otwarchive.atlassian.net/browse/AO3-5905
Modifies the batch scanning code so that if it does retrieve an empty batch from Redis, it doesn't yield it to the block. This prevents issues if the batch is passed to, e.g. `SREM`, which won't accept an empty list as the second argument.
=> AO3-5905 Don't yield empty batches in the new hit count code.

app/models/redis_hit_counter.rb, config/resque_schedule.yml, spec/models/redis_hit_counter_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5905
This PR modifies how IP addresses are stored by the hit count code. Instead of having one set of IP addresses for each `(work, timestamp)` pair, we have one set for each timestamp, storing pairs of `(work, ip_address)`. This still ensures that we don't count multiple hits on a single work by an IP address within a short period, but has a few advantages over the old system:
1. Because all of the data for a particular day is stored in one set, it's easier to delete batches of data. In the old system, if there was a work that received 2 hits in one day, the associated set and its elements would have to be removed in a separate Redis command, only 2 items in a single command. This way, each deletion command should remove roughly the same number …
=> AO3-5905 Use one set for the hit count code.

app/models/chapter.rb, features/works/work_browse.feature
https://otwarchive.atlassian.net/browse/AO3-4750
If you reorder the chapters in a work, caching means the latest chapter linked in the blurb still points to the old last chapter.
Now we expire the cache.
Do what red did:
* Posted a work and added a chapter. The work blurb in listings showed 2/2, with a link to chapter 2.
* Reordered the chapters, so chapter 2 became chapter 1. The blurb showed 2/2 and linked to the former chapter 2, or the current chapter 1.
=> AO3-4750 Expire work blurbs when chapters are reordered

app/models/chapter.rb, features/works/work_browse.feature
https://otwarchive.atlassian.net/browse/AO3-4750
Makes sure we're expiring the work blurb and index caches when a work's chapters are reordered, ensuring we always have the correct recent chapter link.
=> AO3-4750 Expire work index caches when a work's chapters are reordered

features/support/formatter.rb
https://otwarchive.atlassian.net/browse/AO3-5757
Stop printing feature descriptions, which we don't set consistently.
Just tests. An example of the updated formatter in action: https://travis-ci.com/github/redsummernight/otwarchive/jobs/321432100.
=> AO3-5757 Print feature file names in Cucumber output

app/views/layouts/_javascripts.html.erb
https://otwarchive.atlassian.net/browse/AO3-5927
Sets `jQuery.fx.off` to true in the test environment, to disable jQuery animations.
=> AO3-5927 Disable jQuery animations in test environment

db/migrate/20200423205608_add_unique_index_to_filter_taggings.rb, spec/lib/tasks/tag_tasks.rake_spec.rb
This PR modifies the `filter_taggings` table to replace the existing index on `(filter_id, filterable_type)` with a unique index on `(filter_id, filterable_type, filterable_id)`.
The usual steps for testing a migration should be sufficient: run it, then roll it back, then run it again. That should ensure that both the migration and its reverse are working.
=> AO3-5667 Add unique index to filter_taggings table

app/controllers/troubleshooting_controller.rb, config/locales/views/en.yml, spec/controllers/troubleshooting_controller_spec.rb
- Rename the troubleshooting option from "Fix Meta Tags" to "Fix Metatags."
- Change "meta-tags/sub-tags" to "metatags/subtags" in the "Fix Tag Associations" description.
- Change the "Reindex Work" option so that it's only available to admins.
Make sure that the troubleshooting page for tags looks right.
=> AO3-5667 Update wording of some troubleshooting options, and change permissions on "Reindex Work" option.

app/models/concerns/filterable.rb, app/models/filter_updater.rb, app/models/indexing/index_queue.rb, app/models/indexing/scheduled_reindex_job.rb, lib/tasks/search.rake, lib/tasks/tag_tasks.rake, spec/lib/tasks/search_tasks.rake_spec.rb, spec/lib/tasks/tag_tasks.rake_spec.rb, spec/spec_helper.rb
We don't want the `Tag:reset_filters` task to hold up normal operations when it's being run, so we modify it to use the `reindex_world` queue for the asynchronous `FilterUpdate` jobs, and use the reindexing queue `world` (which maps to the `reindex_world` Resque queue) instead of `background` (which maps to the `reindex_low` Resque queue).
Because the `IndexQueue` doesn't normally reindex items added to the `world` queue, we additionally add a rake task `search:run_world_index_queue` that runs the `IndexQueue`s for the `world` queue. This task should be run after all of the filter updates are done and the `reindex_world` queue is empty. If it's run any sooner, there may be items that were added to the `world` queue that won't be reindexed. …
=> AO3-5667 Use the reindex_world queue for the Tag:reset_filters task (both the filter jobs and the reindexing jobs).

app/models/meta_tagging.rb, app/models/tag.rb, features/tags_and_wrangling/tag_wrangling.feature, spec/controllers/tags_controller_spec.rb
- If there's a metatag tree where A is the metatag of B is the metatag of C, and you decide that you want C to be the direct subtag of A instead of the direct subtag of B, the current way to do that involves removing B as C's metatag, waiting for the inherited association with C to be cleaned up, and then adding C as a direct metatag. This PR makes it possible to upgrade inherited metatags to direct metatags, to make the process easier for tag wranglers.
- In the current code, when you check the box to remove a metatag, it doesn't immediately remove the metatag. Instead, it queues up a job to remove the metatag. This means that the metatag remains on the edit page until the user refreshes (or, if the utilities queue is long, after the the …
=> AO3-5667 Allow metatags to be upgraded from inherited to direct, and make removing associations synchronous.

app/models/tag.rb
`Tag#queue_flush_work_cache`, which expires the work blurb cache (and the tag group cache), is currently called `after_commit`. As a result, adding or removing a single child or parent tag results in a number of `Tag#flush_work_cache` jobs being added to the queue.
Two from the touches when a `CommonTagging` is created or deleted:
https://github.com/otwcode/otwarchive/blob/2774866fa0f2760471b78e15a864582e3bdbb9b8/app/models/common_tagging.rb#L11-L12
Another two from the tag being saved twice in the controller:
https://github.com/otwcode/otwarchive/blob/2774866fa0f2760471b78e15a864582e3bdbb9b8/app/controllers/tags_controller.rb#L254-L256
And when the association is being deleted, another two jobs from the calls to `touch` in …
=> AO3-5667 Clear work blurb cache only when necessary.

app/controllers/application_controller.rb, app/views/layouts/_javascripts.html.erb
https://otwarchive.atlassian.net/browse/AO3-5948
Three cookies were set as "permanent", that being an expiration date twenty years in the future. The European ePrivacy directive recommends that cookies expire at most a year after being set -- while not strictly *required*, it's definitely a more reasonable delay.
Use your browser's developer tools to check the expiration date of the `accepted_tos`, `user_credentials` and `admin_credentials` cookies after having, respectively, accepted the ToS while logged out, logged in as a regular user, and logged in as an admin.
=> AO3-5948 Reduce some cookies' expiration date to one year

app/helpers/bookmarks_helper.rb
^ N/A
https://otwarchive.atlassian.net/browse/AO3-5422
This PR removes unused methods from bookmarks_helper - specifically get_bookmark_link_text and bookmark_link.
N/A - no functional changes.
he/him
=> AO3-5422 Remove unused methods in bookmarks_helper

app/helpers/users_helper.rb
^ N/A
https://otwarchive.atlassian.net/browse/AO3-5423
This PR removes unused methods in users_helper, specifically print_works and authors_header.
N/A - no functional changes.
he/him
=> AO3-5423 Remove unused methods in users_helper

app/helpers/comments_helper.rb
^ N/A
https://otwarchive.atlassian.net/browse/AO3-5425
This PR removes unused methods from comments_helper, specifically fallback_url_for_comment and fallback_url_for_top_level.
N/A - no functional changes.
he/him
=> AO3-5425 Remove unused methods in comments_helper

app/helpers/pseuds_helper.rb
^ N/A
https://otwarchive.atlassian.net/browse/AO3-5426
This PR removes the unused link_to_tag_with_count method from pseuds_helper.
N/A - no functional changes.
he/him
=> AO3-5426 Removed unused link_to_tag_with_count method from pseuds_helper

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5938
makes bottom borders visible again under stats (follow issue link for pictures)
on a windows device (or emulator) go to https://test.archiveofourown.org/users/testy/bookmarks and check that all stats links for each work (chapter count, bookmark count, collection count, comment count) have borders underneath them. try making your browser window smaller and check that borders under these links don't disappear when they're pushed down to a second line.
=> AO3-5938 Links in bookmark blurb stats have their bottom borders cut off (on Windows)

app/models/admin_setting.rb, config/initializers/archive_config/settings_for_admin.rb, features/other_a/invite_queue.feature, features/other_a/pseud_dashboard.feature, features/other_a/reading.feature, features/step_definitions/admin_steps.rb, features/support/hooks.rb, features/support/paths.rb, features/tags_and_wrangling/tag_cloud.feature, features/tags_and_wrangling/tag_wrangling_fandoms.feature, features/works/work_browse.feature, features/works/work_delete.feature
https://otwarchive.atlassian.net/browse/AO3-5936
- Add AdminSetting.default for use in both initializers and testing setups.
- Fix reading history tests, because with experimental caching, timestamps of readings are not relative.
- Simplify step definitions for setting up AdminSetting.first, remove step for turning on wrangling (it's on by default).
- Always clear cached results of "Latest Works" and "Latest Bookmarks" before checking them, as these caches never get expired by any user action.
None.
=> AO3-5936 Enable experimental caching in feature tests

app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5965
Modifies `display_auth_error`, which handles CSRF errors, so that it doesn't generate an error in New Relic on a JSON request.
Available in the bug report.
=> AO3-5965 Handle CSRF errors on JSON requests.

public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-5737
This PR moves the border and margin to the right for `blockquote` elements either with or inheriting the `dir="rtl"` attribute. The addition to the stylesheet is exactly the same as written in the Jira issue. Here is a comparison using [this news post](https://archiveofourown.org/admin_posts/13531) (with the HTML edited to add the `dir="rtl"` attribute to the blockquote):
Without the fix:
With the fix:
See testing instructions on the Jira ticket.
[AO3-5735](https://otwarchive.atlassian.net/browse/AO3-5735), once done and deployed, should mean admin posts in a RTL language wouldn't have to be edited to add the `dir="rtl"` attribute to all blockquote elements.
=> AO3-5737 Put border on right side for RTL blockquotes

app/controllers/troubleshooting_controller.rb, spec/controllers/troubleshooting_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5969
Modifies the "Update Tag Filters" troubleshooting option to use `Tag#mergers` instead of `Tag#synonyms`, because `Tag#synonyms` gives a nil error for any tag that is neither canonical, nor the synonym of a canonical.
See the bug report.
=> AO3-5969 Make "Update Tag Filters" troubleshooting option work for unfilterable tags.

app/controllers/series_controller.rb, app/helpers/series_helper.rb, app/models/series.rb, app/views/series/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-5930
This PR replaces the two calls to `serial_works.includes(:works).references(:works)`, which produces queries that enumerate all column names for both the `serial_works` table and the `works` table, with alternative queries.
See the bug report.
=> AO3-5930 Avoid calling serial_works.includes(:works).references(:works).

app/controllers/works_controller.rb, app/helpers/application_helper.rb, app/models/work.rb, app/views/works/edit_multiple.html.erb, db/migrate/20200613211440_add_comment_permissions_to_works.rb, lib/tasks/after_tasks.rake, spec/controllers/works/multiple_actions_spec.rb, spec/lib/tasks/after_tasks.rake_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5973
https://otwarchive.atlassian.net/browse/AO3-5881
- Add a column `comment_permissions` that will eventually be used to control whether comments are enabled, and whether anonymous comments are enabled.
- Add a rake task `After:copy_anon_commenting_disabled_to_comment_permissions` to copy the current values in `anon_commenting_disabled` over to the `comment_permissions` column.
- Fix up the Edit Multiple Works form so that it no longer presents mutually exclusive checkboxes for "Only show to registered users" and "Show to all." (I included this because I'd eventually like to get rid of the special values representing zero in the Edit Multiple Works form, so that the options for the new `comment_permissions` column look nicer. But this requires …
=> AO3-5973 AO3-5881 Add comment permission column, and start updating multiple works form.

app/views/tags/show_hidden.js.erb, factories/tags.rb, features/other_a/preferences_edit.feature, spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5771 (please fill in issue number and remove this comment)
Users can decide to hide archive warnings and/or freeform tags in their preferences. If they do, the tag lists they see on work list and detail pages will have "show warnings" / "show additional tags" links instead of the respective tag lists. Clicking on one of those links causes an AJAX request to `/tags/show_hidden` which returns a javascript file that replaces the link with custom-generated tag content.
Previously, the view for /tags/show_hidden generated links to the tag detail pages; however, the single location that uses the show_hidden functionality explicitly links to tag works, as can be seen here: https://github.com/otwcode/otwarchive/blob/030fa46/app/views/works/_meta.html.erb …
=> AO3-5771 Correct URLs in tag lists generated from "show hidden" links

app/controllers/works_controller.rb, app/models/work.rb, spec/lib/tasks/after_tasks.rake_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5973
The view `works/standard_form` in #3852 has radio buttons for the name `work[comment_permissions]`. But at the moment, the `WorksController` doesn't include `comment_permissions` in the permitted `work_params`. So if someone accesses the form from a worker running the new code, then submits the form to a worker that's still running the old code, the user's choice of `comment_permissions` would disappear and be reverted to the default.
The deploy involves restarting all the workers over the course of an hour, so we need to plan around the new form being submitted to the old controller, and vice versa. So this PR adds `comment_permissions` to the list of permitted `work_params`.
In addition, the new form in #3852 uses `enable_all`, …
=> AO3-5973 Make the WorksController forward-compatible.

.rubocop.yml, spec/lib/collectible_spec.rb, spec/models/tag_set_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5947
Rules mentioned in the issue but not added here, because their default values are already good:
- Having context descriptions start with unnecessary "should"s: [RSpec/ExampleWording](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecexamplewording)
- Having duplicate and scattered hooks: [RSpec/ScatteredSetup](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecscatteredsetup)
- Having "all" hooks that lead to state leaking between specs: [RSpec/BeforeAfterAll](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecbeforeafterall)
Extra:
- Start checking double quotes.
- Fix RSpec/Focus by removing the only use of "focus: true".
- Fix RSpec/EmptyExampleGroup by removing empty spec.
[skip codeship tests] …
=> AO3-5947 Add Hound rules for RSpec

app/views/admins/index.html.erb, config/locales/models/en.yml, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-5518
Adds some missing HTML to the admin index page, e.g. the `heading` class and the `<div class="admin userstuff">` container that was preventing the list of roles from showing as an actual bulleted list. Also does i18n for the text on that page.
Refer to Jira.
=> AO3-5518 Tweak admin index HTML and add i18n

app/models/admin.rb, db/migrate/20200707213354_add_unique_indices_to_admin_login_email.rb
https://otwarchive.atlassian.net/browse/AO3-5979
This PR updates validation on the `admin` model. Specifically, it:
- removes duplicate validation at the Rails level on admin `email` (this is already enforced by `validatable`)
- enforces admin `email` and `login` uniqueness at the DB level, by adding unique indices for them with a migration
As per the issue description:
> To test, run the migration on staging and make sure it's successful.
I have tested the migration runs locally.
n/a
Tom Milligan …
=> AO3-5979 Add unique constraints for login and email on the admins table

app/mailers/admin_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-5992
Call `stringify_keys` before calling `transform_keys(&:to_i)`, to cope with any symbols introduced by `Resque::Mailer`.
(I originally thought that `with_indifferent_access` would be sufficient, instead of `transform_keys(&:to_i)`, but it turns out that `with_indifferent_access` only handles symbols & strings, not numbers. So I still need the `to_i` step on top of something to get rid of the symbols.)
=> AO3-5992 Fix error with keys being converted to symbols in spam alert email.

factories/admin.rb, features/admins/admin_invitations.feature, features/admins/admin_post_news.feature, features/admins/admin_works.feature, features/admins/users/admin_abuse_users.feature, features/admins/users/admin_find_users.feature, features/admins/users/admin_fnok.feature, features/admins/users/admin_manage_users.feature, features/bookmarks/delete_bookmarkable.feature, features/comments_and_kudos/hidden_works.feature, features/comments_and_kudos/spam_comments.feature, features/importing/archivist.feature, features/other_a/invite_queue.feature, features/other_a/invite_request.feature, features/other_a/media.feature, features/step_definitions/admin_steps.rb, features/step_definitions/external_work_steps.rb, features/tags_and_wrangling/brand_new_fandoms.feature, features/tags_and_wrangling/tag_wrangling.feature, features/tags_and_wrangling/tag_wrangling_admin.feature, features/works/work_download.feature, script/create_admin.rb
https://otwarchive.atlassian.net/browse/AO3-5623
https://otwarchive.atlassian.net/browse/AO3-5980
https://otwarchive.atlassian.net/browse/AO3-5518
AO3-5623 AO3-5980 Fix minor issues with admin creation script
- Remove stray quote.
- Print filename so we can identify error messages.
- Sort wiki output by admins' created timestamps.
AO3-5518 Clean up feature steps to create admins
- Have one step for all types of admins.
- Use the admin role in the admin's username so we can reuse the admin later when we need the same role.
- Use a more specific role than "superadmin" whenever we can.
- Use the generic no-role admin if the feature under test is not yet locked behind any admin roles.
- Remove tests where admins reply to news post comments, as we won't do AO3-3685.
Run the script:
<details> …
=> AO3-5623 AO3-5518 Fix admin creation script, clean up admin-related feature steps

config/deploy/production.rb, config/initializers/new_relic.rb
https://otwarchive.atlassian.net/browse/AO3-5967
Currently all http connections go to a restricted proxy, this routes New Relic connections away from the proxy.
This can only be tested by Systems once the New Relic configuration is updated.
(Log on to the proxy and check that there are no connections to New Relic.)
https://discuss.newrelic.com/t/avoiding-a-global-proxy-config/104464
Please credit New Relic Ruby agent development team.
https://discuss.newrelic.com/t/avoiding-a-global-proxy-config/104464/4
=> AO3-5967 Ignore http_proxy for requests to New Relic collectors

factories/comments.rb, features/search/works_stats.feature, features/step_definitions/tag_steps.rb, features/step_definitions/work_search_steps.rb, features/step_definitions/work_steps.rb, features/works/work_share.feature, spec/controllers/chapters_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/helpers/inbox_helper_spec.rb, spec/requests/comments_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5999
Refactor comment factories so that they don't include all three of `pseud`, `email`, and `name`, and so that they default to having their commentable set to a chapter instead of a work.
Also modifies the structure of comment factories to use traits, so that it's easier to generate comments with different sets of properties. This reduces the amount of repetition on the factory definitions.
This is tests-only, so just check whether the automated tests pass.
=> AO3-5999 Make comment factories look more like real comments, and reorganize to use traits.

.rubocop.yml, app/controllers/admin/admin_users_controller.rb, app/models/user.rb, factories/users.rb, features/admins/users/admin_manage_users.feature, spec/controllers/admin/admin_users_controller_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5884
Previously, if an admin does not have permissions to update roles, and we don't include "roles" in the permitted attributes, the user's roles will be set to an empty array. Now we skip setting roles entirely in that case.
Also stop skipping validations when updating users, and show validation errors to admins, so admins can't accidentally break users by saving blank emails, etc.
See issue. Specifically:
- PAC admins clicking "Update" should not clear all roles of a user.
- PAC/Support admins should be prevented from entering invalid emails for a user (emails already in use, or blank strings).
=> AO3-5884 Fix deleting roles when admins can't update roles

app/controllers/application_controller.rb, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5897
Override `redirect_to` in the `ApplicationController`, so that we always call `check_for_flash` after `redirect_to` is called. `check_for_flash` is used to make sure that flash messages are displayed even on cached pages, and it's called as an `after_action` hook, but redirecting in a `before_action` hook skips `after_action` hooks.
=> AO3-5897 Call check_for_flash when calling redirect_to, so that flash messages are properly displayed even when the redirect occurs before_action.

app/controllers/challenge_claims_controller.rb, app/models/challenge_claim.rb, app/models/challenge_models/prompt_meme.rb, spec/controllers/challenge_claims_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4634
Restricts access to the unposted claims page to the maintainers of the challenge's collection. Users who are not maintainers can only access the page with their unposted claims.
* The challenge claims controller is not restricted to prompt memes, so using a method that is only implemented by prompt memes, `user_allowed_to_see_claims?`, could be brittle. I have chosen `user_allowed_to_see_assignments?` as a proxy for what a claim is roughly equivalent with - it's someone self-assigning themself to that request, more or less, and it's a method implemented in `ChallengeCore`, …
=> AO3-4634 Prompt meme claims access restriction

app/views/layouts/_javascripts.html.erb, app/views/layouts/_proxy_notice.html.erb, config/config.yml
https://otwarchive.atlassian.net/browse/AO3-5975
- Makes sure you won't see the proxy banner if you're on a subdomain we control, e.g. insecure.archiveofourown.org.
Refer to Jira
=> AO3-5975 Provide explicit list of non-proxy hosts

features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-6049
Jump ahead 1 second before marking the comment as spam, so the comment changes `updated_at` and has its cache expired.
=> AO3-6049 Fix intermittent failures in tests for marking spam comments

factories/users.rb, features/comments_and_kudos/comment_moderation.feature, features/importing/archivist_creatorships.feature, features/users/user_dashboard.feature, features/works/chapter_edit.feature, features/works/work_edit.feature
https://otwarchive.atlassian.net/browse/AO3-6049
- `spec/controllers/admin/admin_users_controller_spec.rb`: fix admin role factory to avoid reusing the same name and failing tests for changing roles.
- `features/comments_and_kudos/comment_moderation.feature`: jump ahead 1 second before editing a comment to expire its cache.
- `features/importing/archivist_creatorships.feature`: jump ahead 1 second before adding co-creators to expire the series' byline.
- `features/users/user_dashboard.feature`: jump ahead 1 second before adding more series to make sure "Oldest Series" stays oldest.
- `features/works/chapter_edit.feature`: jump ahead 1 second before adding a chapter co-creator to expire the chapter's byline.
- `features/works/work_edit.feature`: jump ahead 1 second before accepting a …
=> AO3-6049 Fix intermittent failures in tests for comments and more

.gitignore, .hound.yml, Gemfile, Gemfile.linters, Gemfile.lock, config/docker/Dockerfile
https://otwarchive.atlassian.net/browse/AO3-6048
Removes linters from the main Gemfile. Unfortunately, we were running into some errors loading Vagrant and Homebrew development environments because erb-lint switches the ERB parser to better-html. 
We're on the fence as to whether we're going to want to proceed with adding erb-lint to the Gemfile or not: using a different parser on dev means we risk encountering errors in dev that don't occur in other environments (e.g. the one preventing it from loading) _or_ that we might have errors that occur in production, but that we can't see on dev. Ergo, we're going to revert this for now.
Make sure development environments load.
Reverts otwcode/otwarchive#3895
=> AO3-6048 Revert "AO3-6048 Add linters to main Gemfile (and install pwgen)"

app/controllers/related_works_controller.rb, app/views/related_works/index.html.erb, features/step_definitions/work_related_steps.rb, features/works/work_related.feature
https://otwarchive.atlassian.net/browse/AO3-5357
Modify the related works page so that it no longer displays anonymous/unrevealed remixes on the remixer's related works page, and no longer displays remixes inspired by an anonymous/unrelated work on the original creator's related works page. (The same also holds for translations.)
Since I was in the area, I also made a few other changes to the `related_works/index` template:
- Omitted `html_safe` on all of the titles, since that's unnecessary for both [works](https://github.com/otwcode/otwarchive/blob/5333e396ca4be8238d40369d8533789bda6843dd/app/models/work.rb#L74-L77) and [external works](https://github.com/otwcode/otwarchive/blob/5333e396ca4be8238d40369d8533789bda6843dd/app/models/external_work.rb#L49-L52).
- Changed the phrasing from "A …
=> AO3-5357 Address issues with the related works page & anonymous/unrevealed works.

app/views/inbox/show.html.erb, features/comments_and_kudos/inbox.feature
^ had some problems with this - see comments.
^ I don't seem to have access to do this, sorry! I must have missed a step somewhere...
https://otwarchive.atlassian.net/browse/AO3-5820
This PR adds a "Select" label to the checkbox for bulk-selecting comments in the Inbox, to increase the clickable area and improve accessibility.
1. Log in
2. Find a work and leave a comment on it (or post a work)
3. Log out
4. Reply to the comment you left (or comment on your work)
5. Log in
6. Hi, username! > My Dashboard > Inbox
7. Click on "Select" and verify that the checkbox is selected.
*What pronouns do you prefer (she/her, he/him, zie/hir …
=> AO3-5820 Add "Select" label to checkboxes for inbox comments

app/views/comments/_comment_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5925
adds limited html instructions to logged out comment forms on works and news posts
1. go to https://test.archiveofourown.org and ensure that you're logged out
2. go to any news post and check that under the name and email fields in the comment form, there's an additional sentence `Plain text with limited HTML (?)` that leads to [this popup link](https://test.archiveofourown.org/help/html-help.html)
3. go to any published work and check that under the name and email fields you see the above text and link there, too
=> AO3-5925 Add limited HTML instructions to logged out comment forms

public/stylesheets/site/2.0/02-elements.css
https://otwarchive.atlassian.net/browse/AO3-5952
This PR replaces the alignment properties of table headers with CSS logical properties, in order to automatically flip them for right-to-left languages.
See Jira ticket. Note that CSS logical properties aren't compatible with 
See also AO3-5822 (#3828) and AO3-5737 (#3742) for similar text alignment issues.
=> AO3-5952 Fix table alignment in RTL languages

app/controllers/bookmarks_controller.rb, app/views/bookmarks/_bookmark_owner_navigation.html.erb, app/views/bookmarks/index.html.erb, app/views/bookmarks/share.html.erb, app/views/bookmarks/show.html.erb, app/views/share/_share.html.erb, app/views/works/share.html.erb, config/routes.rb, features/bookmarks/bookmark_share.feature, features/step_definitions/bookmark_steps.rb, features/step_definitions/share_steps.rb, features/step_definitions/work_steps.rb, features/support/paths.rb, features/works/work_share.feature, public/stylesheets/sandbox.css, spec/controllers/bookmarks_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5987
Moves the sharing options off of the bookmark pages and into their own controller, to be loaded dynamically when the user presses the "Share" button.
Make sure that you can still use the "Share" button on bookmarks - behaviour should remain unchanged.
Some edge cases that should be tested:
- JavaScript disabled
- Bookmark is private
- Work is unrevealed/part of an unrevealed collection
- Logged out user should not have option to share bookmark
There has already been very similar work done for the `works` page, which I used as a reference while writing this PR.
- Issue: …
=> AO3-5987 Defer generating share options for bookmarks

app/views/comments/_comment_form.html.erb, features/admins/admin_email_blacklist.feature, features/admins/admin_post_news.feature, features/step_definitions/comment_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6000
There have been increasing reports of people accidentally letting their browser autofill their real names on guest comments, so this PR changes the field names on the guest comment form from "Name:" to "Guest name:" and "Email" to "Guest email" to try and prevent that.
* Open a guest comment form on production in Chrome and see how form autofill works. Try that on staging and see if the autofilled values are different.
* Make sure the fields have new names, and label association works (clicking on the label puts the focus/cursor on the field next to it).
* Make sure you can still post guest …
=> AO3-6000 Rename fields on guest comment form to reduce chances of browser autofilling non-fannish names

app/views/prompts/_prompt_controls.html.erb
Note: I ran the tests (rspec and cucumber) and verified that everything passed in docker—if there's anything I should watch out for with the docker dev environment please let me know!
as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)?
https://otwarchive.atlassian.net/browse/AO3-6056
The confirmation message after selecting the "Drop Claim" button on a claimed prompt currently could imply that the prompt itself is being deleted. This updates the confirmation text to match the button text, and clarify that it's the claim that's being dropped/deleted, not the prompt.
No tests check this exact string, so no tests were added or updated for this change.
To test manually, if desired:
* Log in as a …
=> AO3-6056 Update confirmation text on the "Drop Claim" button for prompts

app/views/home/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5950
The Twitter timeline widget on the home page currently doesn't have the "Do Not Track" parameter set, and takes up way too much space on the page due to a missing `data-height` attribute. This PR fixes both issues by adding the `data-dnt="true"` attribute and setting the widget's height to the previous default of 600 pixels.
Check if the widget is displaying normally again (with a reasonable height). As mentioned on the Jira issue, there's not much of a way to see if the DNT parameter works as intended, but we can at least check if the cookies set by Twitter are different.
=> AO3-5950 Set "do not track" parameter and update homepage Twitter widget

app/controllers/home_controller.rb, config/locales/views/en.yml, features/other_a/homepage.feature
https://otwarchive.atlassian.net/browse/AO3-5924
Changes the page title for https://archiveofourown.org/donate to "Donate or Volunteer | Archive of Our Own" as suggested.
Verify page title on donate page.
The scenario in `feature/other_a/homepage.feature` has been extended to check this.
N/A
*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?* tlee911
*What pronouns do you prefer (she/her, he/him, zie/hir etc)?* he/him
=> AO3-5924 Adjust donate page title

public/stylesheets/sandbox.css
https://otwarchive.atlassian.net/browse/AO3-5987
* Remove unwanted border and dark text when hovering on visited share links
* Make sure the share link background color changes on keyboard focus
* Use our default font on the share buttons
* Do a little cleanup to make the CSS match our code style
Some day in the future, we should clean up all the various class names here to actually match our system -- then we can move it out of the sandbox file. I lack the enthusiasm to do that at the moment, though.
For focus styles:
* Click inside the text area with the share HTML
* Press your keyboard's Tab key to move to the Twitter link, and then press it again to move to the Tumblr link
* The background colors of the links should change, just like they do when you hover
For the visited share links: …
=> AO3-5987 Fix hover and focus styling on social media share links

app/helpers/application_helper.rb, app/views/admin/skins/index_approved.html.erb, app/views/admin_posts/_admin_post_form.html.erb, app/views/bookmarks/_external_work_fields.html.erb, app/views/challenge_assignments/_maintainer_index_defaulted.html.erb, app/views/collections/_filters.html.erb, app/views/collections/_form.html.erb, app/views/potential_matches/_assignment_with_request.html.erb, app/views/prompts/_prompt_form_tag_options.html.erb, app/views/skins/_skin_parent_fields.html.erb, app/views/tag_set_nominations/_review_individual_nom.html.erb, app/views/tag_set_nominations/_tag_nominations.html.erb, app/views/tag_set_nominations/_tag_nominations_by_fandom.html.erb, app/views/tags/edit.html.erb, app/views/works/_work_form_pseuds.html.erb, app/views/works/_work_form_tags.html.erb, public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-6083
Keeps part of the wanted changes from #3698, which I have now separated out into their own issue like I should've done in the first place.
* Uses HTML5 `data-*` attributes for the autocomplete's custom attributes. This means we don't get as many validation errors on our HTML now. 🎉
Refer to Jira.
Initially part of #3698 for [AO3-3306](https://otwarchive.atlassian.net/browse/AO3-3306).
=> AO3-6083 Use HTML5 data- attributes for custom autocomplete attributes

.github/workflows/automated-tests.yml, ACKNOWLEDGMENTS.md, README.md, config/cucumber.yml, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6082
- Update README and build status badge.
- Use all available concurrent jobs.
- Use colors for RSpec and Cucumber output in GitHub Actions.
- By default, both RSpec and Cucumber will print colors only if the output is TTY (as opposed to e.g. files), but [the default environment of GitHub Actions does not identify itself as running within a TTY enabled device](https://github.community/t/ansi-color-output-in-webview/17621). So we need to use options to force color in output. For RSpec, it's easy to do that just in CI by setting SPEC_OPTS. For Cucumber, I just do that in the default profile, instead of adding logic to check if we're running in CI.
- Also remove the deprecated "color" option of RSpec.
=> AO3-6082 Use colors in test logs and max concurrent jobs in GitHub Actions

app/controllers/collection_participants_controller.rb, app/views/collection_participants/_participant_form.html.erb, config/routes.rb, spec/controllers/collection_participants_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6091
This PR removes the unnecessary `collection_id` and `id` from the parameters in `collection_participant_params`. This makes the `update` action behave more like a normal nested resource (retrieving `id` from the URL).
I also modified the controller to use `find` and `find_by!` instead of `find_by`, so that it generates a 404 error instead of setting a flash message and redirecting when the collection or participant is invalid.
=> AO3-6091 Changes to the CollectionParticipantsController.

app/controllers/works_controller.rb, app/models/work.rb, spec/controllers/works/multiple_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6090
Finish off the TODOs from #3885, which drops the `anon_commenting_disabled` column from the works table.
We temporarily added `anon_commenting_disabled` to the list of `ignored_columns` (to try to avoid 500 errors during the migration). Once AO3-6016 has been deployed and the migration has been run, we need to remove it again, which is the purpose of this PR.
In addition, this PR deletes some extra code used for backwards-compatibility with the old Edit Multiple Works form.
=> AO3-6090 Finish TODOs from dropping the anon_commenting_disabled column from the works table.

lib/tasks/skin_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-6068
Fixes new installations (dev environments) to correctly load the default site skin so that CSS is available.
On a development environment:
1. Run reset_database.sh
2. Visit any page
3. Verify CSS is present and default site skin is used
https://otwarchive.atlassian.net/browse/AO3-6051
tlee911 (they/them)
Also @tickinginstant proposed this cleaner implementation over my hackery
=> AO3-6068 Load default skin in rake task

config/docker/Dockerfile
https://otwarchive.atlassian.net/browse/AO3-6048
Adds pwgen to the Dockerfile so we can create test users for development without needing to install any extra dependencies.  Take 2, without including lint dependencies which didn't work last time.  This is really a developer convenience change (environment setup).
Development setup only:
1. Build the docker environment
2. Create a new admin user without installing pwgen first
The original failed attempt that including lint dependencies:
https://github.com/otwcode/otwarchive/pull/3895
tlee911 (they/them)
=> AO3-6048 Add pwgen to Dockerfile

app/models/work.rb, spec/models/search/work_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6063
Modifies `comments_count`, `kudos_count`, and `bookmarks_count` so that they don't error if you call them on a work with no `stat_counter`. The stat counter should only be deleted when the work is deleted, but the stat counter is loaded after the work is, so it's not guaranteed to be available when indexing the work.
Even if we wrapped indexing in a transaction to try to get a consistent database view, the transaction isolation level is currently set at `READ COMMITTED`, so if the transaction deleting the work finishes after the work is loaded but before its stat counter is loaded, you'd still end up with a work with no stat counter. The only way to avoid errors is to lock the work during indexing so that it can't be deleted during that …
=> AO3-6063 Fix indexing works with no stat counter.

app/helpers/language_helper.rb, features/admins/admin_post_news.feature, features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6057
This PR adds support for showing the Persian language as a right-to-left language in admin posts.
Follow the original reprodction steps [in the ticket](https://otwarchive.atlassian.net/browse/AO3-6057), i.e.:
- sign in as a communications admin
- create the Persian language and locale
- create a new post in the Persian language
You should see the admin post shown in right-to-left layout:
instead of the current layout, which is left-to-right:
N/A
Tom …
=> AO3-6057 Make Persian (Farsi, fa) a right-to-left language

app/controllers/skins_controller.rb, app/views/skins/_skin_actions.html.erb, app/views/skins/confirm_delete.html.erb, config/locales/views/en.yml, config/routes.rb, features/other_b/skin.feature
https://otwarchive.atlassian.net/browse/AO3-5909
It currently isn't possible for a user to delete a skin without Javascript enabled. This is due to the fact that the HTML `a` element natively supports only GET requests, and that setting the request method to DELETE (actually handled by Ruby as a POST with an extra `method: :delete` parameter) requires the use of jQuery UJS.
A workaround for this is simply to replace `link_to` with `button_to`, which creates a form element natively supporting the generated POST request. This is possible in this case, because the "Delete" link was already styled as a button anyway.
See Jira ticket. Javascript can be disabled through the use of a browser extension such as NoScript.
Note that without JS, there is currently no confirmation: the skin gets …
=> AO3-5909 Delete skins without JavaScript

public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-5822
adds a `1.75` margin to the right of lists written in RTL languages and changes the left margin to `0`
go to https://archiveofourown.org/admin_posts/13294 and scroll down to the lists in the post. check that there is a margin to the right of each bullet. check that there isn't any left margin by making your browser window tiny and zooming in to create two lines of text per bullet. you can compare how the reversed margins look to the [english version of the same post](https://archiveofourown.org/admin_posts/12035).
=> AO3-5822 Reverse margins for lists written in RTL languages

public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-5791
Makes it so images in works, admin posts, etc can only be 100% of the container's width to avoid overflow/horizontal scrolling on screens smaller than the images. 
Refer to Jira.
~Don't merge until the post is ready -- hence "Deferred or Superseded."~ Post is ready! Just needs to go out a few days before deploy.
=> AO3-5791 Restrict width of user-inserted images

app/models/search/async_indexer.rb, app/models/search/index_sweeper.rb, app/models/search/indexer.rb, app/models/search/stat_counter_indexer.rb, spec/models/search/async_indexer_spec.rb, spec/models/search/index_sweeper_spec.rb, spec/models/search/stat_counter_indexer_spec.rb, spec/models/search/work_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6066
Add a bunch of checks for blank/nil batches, so that we can avoid producing `BadRequest` errors whenever we try to index an empty batch.
=> AO3-6066 Avoid errors when indexing batch is empty.

.rubocop.yml, app/models/pseud.rb, spec/models/search/bookmark_indexer_spec.rb, spec/models/search/pseud_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6064
This PR modifies the `user_login` method of the pseud class so that it returns `nil` if there is no user.
It also modifies `byline` (and `user_name`, which is used by `byline`) so that we don't get an error when calling it on pseuds with deleted users, because `byline` is also included in the pseud document:
https://github.com/otwcode/otwarchive/blob/bedbbef8c43585d97b5a56062355921e4c8f5fa7/app/models/search/pseud_indexer.rb#L35-L45
=> AO3-6064 Avoid DelegationError when indexing pseuds with deleted users.

config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-5909
The PR for this issue was broken on test due to what appears to have been a copy/paste error, this PR fixes the problem.
When deleting a skin with JS disabled (check the Jira ticket for instructions), make sure the confirmation message says "Are you sure you want to **_delete_** the skin "(insert screen here)"?", with no backslashes.
Fixes #3833.
=> AO3-5909 Fix the confirmation message when deleting a skin

public/javascripts/application.js
^ N/A - I don't think this behavior can be tested with the current automated testing?
https://otwarchive.atlassian.net/browse/AO3-3582
This PR fixes scrolling when loading comments via AJAX. Previously, this was handled with Livequery; now that it's using jQuery directly, we need to take into account that `.pagination` doesn't exist on page load. Follow-up to https://github.com/otwcode/otwarchive/pull/3798 (which introduced the bug while upgrading the version of the Livequery plugin.)
1. Visit a page with a large number of comments.
2. Press the "Show comments" button at the top of the page.
3. Scroll to the bottom of the page.
4. Press "next", …
=> AO3-3582 Fix scrolling when loading comments via AJAX

app/views/comment_mailer/_comment_notification_footer_for_tag.html.erb, app/views/comment_mailer/_comment_notification_footer_for_tag.text.erb, features/tags_and_wrangling/tag_comment.feature, spec/mailers/comment_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3765
Changes the links in tag comment notifications so that they point to the individual comment, and not the page for all comments on that tag.
=> AO3-3765 Fix links in tag comment notifications.

app/policies/admin_post_policy.rb, spec/controllers/admin_posts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6100
* Lets admins with the support role create, delete, and modify admin posts.
* Covers [the last untested line in the admin posts controller](https://codecov.io/gh/otwcode/otwarchive/src/0622729c9d4fca1ec7b611235bb5e318256ebd70/app/controllers/admin_posts_controller.rb).
Refer to Jira.
=> AO3-6100 Grant support admins access to admin posts

lib/otw_sanitize/embed_sanitizer.rb, lib/otw_sanitize/media_sanitizer.rb, lib/otw_sanitize/user_class_sanitizer.rb, lib/tasks/after_tasks.rake, spec/lib/html_cleaner_spec.rb, spec/lib/otw_sanitize/media_sanitizer_spec.rb, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6096
- Update the embed sanitizer to replace Dewplayer embeds with HTML5 audio tags.
- Add a rake task to re-sanitize existing works using Dewplayer embeds.
- Post a work using the old embed code, then after the staging deploy, run the rake and make sure the work is updated.
- Post a work using the old embed code after the staging deploy. The work should automatically be updated as well.
=> AO3-6096 Replace Dewplayer embeds with audio tags when sanitizing HTML

lib/otw_sanitize/embed_sanitizer.rb, lib/otw_sanitize/media_sanitizer.rb, lib/tasks/after_tasks.rake, spec/lib/html_cleaner_spec.rb, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6096
URL-encoded spaces in audio URLs of Dewplayer embeds get decoded when we [parse flashvars](https://helpx.adobe.com/flash/kb/pass-variables-swfs-flashvars.html), then the URLs with unencoded spaces get rejected as invalid by `URI` when we try to check their hosts in `MediaSanitizer`. We'll instead use `Addressable::URI` to parse URLs, which is more forgiving.
Also print out errored chapter IDs at the end of the rake task.
See issue.
=> AO3-6096 Handle encoded characters in Dewplayer audio URLs

app/controllers/tag_set_nominations_controller.rb, app/views/tag_set_nominations/_nomination_form.html.erb, spec/controllers/tag_set_nominations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6105
The `TagSetNominations` controller allows you to view pages like `/tag_sets/:owned_tag_set_id/nominations/:id` where the tag set nomination's `owned_tag_set_id` doesn't match the `owned_tag_set_id` specified in the URL. This modifies the `before_action` hooks to make sure that the only tag set nominations accessible for a given `OwnedTagSet` are nominations for that tag set.
=> AO3-6105 Prevent mismatches in OwnedTagSets for TagSetNominations.

config/application.rb, config/environments/test.rb, lib/tasks/database_seed.rake
https://otwarchive.atlassian.net/browse/AO3-5928
Disable schema dumping after migrations in all environments.
Because schema files are no longer updated when setting up CI tests, db:otwseed, which uses db:reset, which loads the outdated versions of schemas before seeding, fails if there are pending migrations. We need to set up the database and run migrations before seeding.
Also remove `config.active_record.schema_format` from test.rb, since it's already set in application.rb.
See issue.
=> AO3-5928 Disable schema dumping after migrations

app/models/chapter.rb, app/models/comment.rb, app/models/work.rb, config/config.yml, features/comments_and_kudos/comment_moderation.feature, features/comments_and_kudos/comments_delete.feature, features/step_definitions/comment_steps.rb, lib/plugins/acts_as_commentable/commentable_entity.rb
https://otwarchive.atlassian.net/browse/AO3-6108
Adds caching for various comment counts on works & admin posts. The cache is automatically expired when a comment is added, removed, or changes visibility, so it shouldn't affect the user experience, but it might reduce the server load a little.
=> AO3-6108 Cache comment counts.

features/comments_and_kudos/comments_adminposts.feature, features/step_definitions/web_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6027
Adds some extra tests steps to validate that admin post permissions are still displayed correctly when editing the post.
This PR changes testing only.
See #3919 for original implementation
=> AO3-6027 Test comment permissions on admin post edit form

app/controllers/comments_controller.rb, app/models/comment.rb, public/stylesheets/site/2.0/02-elements.css, public/stylesheets/site/2.0/07-interactions.css, public/stylesheets/site/2.0/08-actions.css, public/stylesheets/site/2.0/09-roles-states.css, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4709
* Stops checking comments for spam whenever they are saved. This will allow spam comments to be frozen/unfrozen and prevent errors when you freeze/unfreeze the same comments repeatedly for testing purposes. It will also prevent comments you manually marked as spam from getting reverted by the spam checker.
* Removes the `cursor: pointer` CSS style that was being applied to all manner of things. Now we defer to whatever cursor the browser chooses for specific elements. (This will stop the pointer from showing up on "Frozen" and other things with the `.current` style, incorrectly making it look clickable. It also means some clickable things like buttons will now have the default arrow cursor, because that's what browsers do for those.)
* …
=> AO3-4709 Comment freezing fixes

app/models/tag.rb, app/views/tags/edit.html.erb, features/tags_and_wrangling/tag_wrangling.feature, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6122
Removes changes that would prevent the use of certain tags or works or render works uneditable:
* unwrangleable validation check for fandom tags and tags that have no fandom
* visibility change on the unwrangleable checkbox for fandoms (arguably, this one could stay, though it may give us a false sense of security)
I didn't do a straight revert of #3891 because it would be nice to keep the test and syntax tweaks.  
Refer to Jira.
=> AO3-6122 Allow fandom tags and tags without fandoms to be unwrangleable

app/controllers/pseuds_controller.rb, app/controllers/users_controller.rb, features/users/user_dashboard.feature
https://otwarchive.atlassian.net/browse/AO3-5880
Don't display anonymous series on a user's page.
This change removes series that have anonymous works from the 'Recent series' section on a user's page. This brings it into line with the user's series page, where anonymous series are already not displayed, and fixes a user privacy issue.
- Create a new work, posting it to an anonymous collection and adding it to a new series
- Go to your dashboard, and see that the series is not included in the 'Recent series' section there
- Go to the page of the pseud that posted the series, and see that the series is not listed in 'Recent series' there either …
=> AO3-5880 Don't display anonymous series on user page

app/models/admin_post.rb, app/views/admin_posts/_admin_post_form.html.erb, config/locales/views/en.yml, features/admins/admin_post_news.feature, features/comments_and_kudos/comments_adminposts.feature, features/step_definitions/admin_steps.rb, spec/controllers/admin_posts_controller_spec.rb, spec/helpers/admin_post_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6124
Makes it so when you post a translation of an admin post, the translation inherits its comment permissions from the original admin post.
Also, if you update the comment permissions of an admin post that has translations, it updates the comment permissions of the translation.
Refer to Jira
=> AO3-6124 Keep admin post translation comment permissions in sync with original

app/views/user_mailer/claim_notification.html.erb, app/views/user_mailer/claim_notification.text.erb, config/locales/mailers/en.yml
https://otwarchive.atlassian.net/browse/AO3-6025
Fixes confusing wording in the Open Doors "Invitation to claim works" and "Works uploaded" notification emails.
See the Jira reproduction steps.
=> AO3-6025 Change wording in Open Doors emails

app/controllers/challenge_claims_controller.rb, app/models/challenge_claim.rb, app/models/prompt.rb, app/views/prompts/_prompt_controls.html.erb, spec/controllers/challenge_claims_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6011
There's currently a lot of redundant information passed to the `ChallengeClaimsController` -- the `claiming_user_id` should always be the current user, and the `collection_id` and `request_signup_id` can both be derived from the prompt. This PR refactors the parameters passed to the `ChallengeClaimsController` to avoid this redundancy.
I also cleaned up some unused/unusable code while I was in the area.
=> AO3-6011 Refactor parameters passed to the ChallengeClaimsController.

app/helpers/application_helper.rb, app/views/external_works/_blurb.html.erb, app/views/gifts/_gift_blurb.html.erb, app/views/profile/show.html.erb, app/views/readings/_reading_blurb.html.erb, app/views/series/_series_blurb.html.erb, app/views/series/show.html.erb, app/views/works/_work_blurb.html.erb, spec/helpers/application_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6131
* Adds user ID to user profiles
* Adds user ID to work blurb classes
* Adds creation ID to work, series, and external work blurb classes
* Cache that stuff!
* Standardizes the ID attributes so series and external works no longer have the` _blurb` suffix
* Tidy a bit
Although we usually put the most specific classes first, e.g. `own work blurb group`, I opted to put the user and creation IDs at the end of our standard classes, since they're not like our standard "styling the site" classes.
To cut back on repetition, I moved the `blurb group` part into the helper method. I could move the bits for checking if we include `own` and whether we use `work` or `series` into the helper as well, but I wasn't sure if it was worth the additional …
=> AO3-6131 Add user ID and creation ID info to blurbs, with a focus on work blurbs

.rubocop.yml, app/controllers/users/passwords_controller.rb, app/models/user.rb, app/policies/user_policy.rb, config/config.yml, config/locales/controllers/en.yml, features/step_definitions/user_steps.rb, features/users/authenticate_users.feature, lib/tasks/defaults.rake, spec/controllers/admin/admin_users_controller_spec.rb, spec/lib/tasks/defaults.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5525
Allows us to provide a list of user IDs in the config file that we do not want to send password reset emails to. Replaces an old (April 2018) hot fix that never made it into the repo.
This is one possible way to approach this. Two other options:
1. Place the check in the [Devise mailer's reset_password_instructions method](https://github.com/otwcode/otwarchive/blob/1f7610f25b28388bd6b2beb4715f2a80ece78ef7/app/mailers/archive_devise_mailer.rb#L11) _and_ include error message handling here in the controller. This would be slightly neater, since the error message could be inside the `super do |user|` block. However, that just makes it harder to send the email a reset email from the console in case of an emergency, or to one day allow …
=> AO3-5525 Block password resets for certain users

app/models/search/work_indexer.rb, lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-6147
This PR changes the work index to include a parent/child relationship (to be used for some creator information), and adds a rake task to update the index. This is to prevent the index from being incorrectly updated.
1. Run `rake After:update_work_mapping`.
2. From the rails console, run `$elasticsearch.indices.get_field_mapping(index: WorkIndexer.index_name, field: "creator_join")` and check that the result includes information about the `creator_join` field.
=> AO3-6147 Add task to update work index mapping for new creator join

app/models/search/indexer.rb, app/models/search/work_creator_indexer.rb, app/models/search/work_indexer.rb, app/models/search/work_query.rb, app/models/series.rb, app/models/work.rb, lib/tasks/search.rake, spec/controllers/works/default_rails_actions_spec.rb, spec/models/search/bookmark_search_form_spec.rb, spec/models/search/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6150
Move a copy of `user_ids` and `pseud_ids` to a child document, and make the usual `user_ids` and `pseud_ids` nil when the work is unrevealed and/or anonymous. Also modifies bookmarkables to make the `pseud_ids` nil when the bookmarkable is anonymous/unrevealed.
Also adds two tasks to reindex all works/bookmarkables without recreating the index (so that most searches will continue to work during the deployment).
=> AO3-6150 Move user_ids & pseud_ids into child document for work search.

app/models/concerns/taggable.rb, features/bookmarks/bookmark_create.feature
https://otwarchive.atlassian.net/browse/AO3-6145
When creating a bookmark with duplicate tags e.g. Mytag and MYTAG, a 500 RecordNotUnique error is no longer thrown on create. A lowercase version of the tag will be saved.
1. Either create a work and view it, or open any existing work
2. Click bookmark and add the tags "Duplicate" and "DUPLICATE" and create the bookmark
3. On your bookmark's page, the "bookmarker's tags" section for the bookmark should only show "duplicate"
*What name do you want us to use to credit your work in the [Archive of Our Own's Release …
=> AO3-6145 Fix error when saving bookmark with duplicate tags

public/help/additional-tags-help.html, public/help/categories-help.html, public/help/characters-help.html, public/help/relationships-help.html
https://otwarchive.atlassian.net/browse/AO3-6162
Removes all references to outdated /archive_faqs hyperlinks in help pop-ups related to posting new work (this string doesn't appear in any other locations). Also uses relative linking rather than absolute.
The files changed are:
- additional-tags-help.html
- categories-help.html
- characters-help.html
- relationships-help.html
1. Log in and go to the Post New Work page
2. Select the blue ? icon best to the Categories, Relationships, Characters, and Additional Tags labels
3. Hover over the "Tags on the …
=> AO3-6162 Fix FAQ links in Post New Work help pop-ups

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6157
Updates mime-types gem to 3.3.1 to deal with [an error message that happens with Ruby 2.7](https://github.com/mime-types/ruby-mime-types/pull/146). This also means switching from paperclip to kt-paperclip (#3989) and updating rest-client to 2.1.0.
Tests should run and pass, site should load, uploading and deleting icons should work.
Links in the Purpose section.
Sarken and Enigel (@CristinaRO), both she/her
=> AO3-6157 Switch to kt-paperclip and update rest-client and mime-types gems

features/support/capybara.rb
https://otwarchive.atlassian.net/browse/AO3-6169
This PR modifies the Poltergeist driver in JS tests so that it no longer loads anything from `platform.twitter.com`. Hopefully this will reduce the number of `StatusFailError`s on the homepage.
Rerun the automated tests a bunch of times to see if you get any `StatusFailError`s.
=> AO3-6169 Prevent loading twitter widgets during automated tests.

app/controllers/chapters_controller.rb, config/locales/controllers/en.yml, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4936
No more 500 errors when trying to display in chapter by chapter mode a work which has no fandoms.  The work will now display with fandom data missing.  Translation string was also added for "No fandom specified" (copied from existing entire work display).
- Locate a multi-chapter work which has no fandoms (either existing, or take advantage of AO3-4932, or with DB access delete the fandom tags)
- Set your view to both entire work and chapter by chapter to verify the work will render in both modes
- Verify the page title says "No fandom specified" in both modes …
=> AO3-4936 Fix 500 error when displaying a work missing fandom in chapter by chapter mode

test/fixtures/languages.yml
https://otwarchive.atlassian.net/browse/AO3-6072
Allows the support and abuse forms to work out-of-the-box for new development environments by setting English as the default language in the seed data.
- Reset your development database (via script/reset_database.sh) or build a new one
- Verify in the DB that support_available=1 and abuse_support_available=1 for English in the `languages` table
- Start the application and verify that both support and abuse forms default to English as language (instead of being blank) and that both forms can be submitted
Before:
After:
=> AO3-6072 Make English an available support/abuse language in fixtures

app/models/feedback.rb, db/migrate/20210603151906_remove_ip_address_from_feedbacks.rb, spec/models/feedback_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5408
New support requests will no longer store users' IP addresses in the database.  IP will still be sent to Akismet for spam detection, but address is not saved (will be null).
Also adds a DB migration which will drop the column in question.  I've done this in a way that is "reversible" in rails so the column can be added back, but the existing IP address data will be lost if we do need to roll this back (so if we care about recovering the data it should be backed up first).
Automated tests have been added in `feedback_spec.rb`
1. Submit a support request
2. Verify in the database that the value for …
=> AO3-5408 Stop storing IP addresses for support requests in the DB

public/stylesheets/site/2.0/02-elements.css, public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-6174
makes obnoxiously long titles wrap.
1. try creating a work with the title "a_really_obnoxiously_long_outlier_of_a_collection_name_for_this_google_code_issue_whee_i_am_so_happy_i_cannot_contain_my_joy_it_is_a_new_bug" and check that the title text wraps inside the blurb. click on the title and check that the title text also wraps inside the work.
2. try creating a collection with the same title. check that the title text wraps inside the blurb. click on the title and check that the title text also wraps inside the collection page.
3. try creating a news post with the same title. check that the title text wraps inside the landing page's news feed blurbs. click on the title and check that the title text also wraps inside the news post.
the …
=> AO3-6174 Make titles wrap inside blurbs and news/collection/work pages

spec/requests/rack_attack_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6177
- Use an in-memory cache instead of memcached.
- Use the `:login` sequence because `Faker::Name.first_name` may be too short.
- Use `Faker::Internet.public_ip_v4_address` because it's guaranteed not to be private IPs (10.0.0.0/8), which are safelisted and never throttled.
None. Tests pass [20x4 times](https://github.com/redsummernight/otwarchive/actions/runs/932672070) on my fork.
=>  AO3-6177 Fix flaky rate limiting specs

app/controllers/works_controller.rb, app/views/works/_hidden_fields.html.erb
https://otwarchive.atlassian.net/browse/AO3-6187
Removes `revised_at` from the list of hidden fields on the preview page, and removes it from the list of permitted attributes in the `WorksController`.
=> AO3-6187 Prevent passing revised_at as a parameter to the WorksController.

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5964
Update to #3993 
Quoting from the original:
> This is a one-time After task to:
> - Identify tags that have extraneous spaces in their name
> - Replace each space in their name with an underscore (_)
> - Output the list of tags with their ID, old name, and new name
In the event that the new name with underscores clashes with an existing tag, underscores will be added at the end of the tag name until we get something unique.
Automated tests have been added in `after_tasks.rake_spec.rb`
This can also be tested by creating tags with special spacing characters (may require database or console access) …
=> AO3-5964 Replace excess spaces in some tags

db/migrate/20210625232846_index_audits_on_remote_address.rb
https://otwarchive.atlassian.net/browse/AO3-5941
Indexes audits on remote address to speed up their retrieval and make AD&T cry with relief.
You do the migrate up, then you do the migrate down, then you do the hokey pokey and turn yourself around (and then migrate back up). 
```ruby
bundle exec rake db:migrate:up VERSION=20210625232846
bundle exec rake db:migrate:down VERSION=20210625232846
```
=> AO3-5941 Index audits on remote address

db/migrate/20210626010047_index_comments_on_email.rb
https://otwarchive.atlassian.net/browse/AO3-5922
Indexes comments on email to speed up their retrieval and make AD&T teary-eyed with relief. (We won't actually cry for this because audits are worse.)
Second verse, same as the first. You do the migrate up, then you do the migrate down, then you do the hokey pokey and turn yourself around (and then migrate back up). 
```ruby
bundle exec rake db:migrate:up VERSION=20210626010047
bundle exec rake db:migrate:down VERSION=20210626010047
```
=> AO3-5922 Index comments on email

lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-5964
https://otwarchive.atlassian.net/browse/AO3-6065
Ensures the rake tasks are listed in the order they should be run. 
- The space-fixing task is supposed to come before the task for cleaning up noncanonical categories and ratings ([AO3-5988](https://otwarchive.atlassian.net/browse/AO3-5988)) because "otherwise we may run into validation errors when we update tags, as we did in AO3-4275."
- The task to add Not Rated should go after the tasks for AO3-5988 "since some of the works without ratings actually have non-canonical ratings. Running it after also double checks no works slipped through the cracks without getting a rating added."
=> AO3-5964 AO3-6065 Reorder tag clean-up rake tasks

features/admins/admin_works.feature, features/works/work_edit_multiple.feature
https://otwarchive.atlassian.net/browse/AO3-6193
- features/admins/admin_works.feature: jump ahead 1s before updating external works so new bylines have a different cache key.
- cucumber features/works/work_edit_multiple.feature: jump ahead 1s before updating works so new bylines have a different cache key.
None. I have run each feature files 50 times on my fork.
=> AO3-6193 Fix flaky tests when editing works and external works

app/controllers/skins_controller.rb
https://otwarchive.atlassian.net/browse/AO3-6110
Don't allow the `child_skin_id` param to be set on `SkinParent` objects.
=> AO3-6110 Remove child_skin_id from allowed params in SkinsController.

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5988
Originally we were adding a task to fix just "Teen & Up Audiences", the only non-canonical rating on production. But [there are other non-canonical ratings on staging, so we still need a more generic task](https://github.com/otwcode/otwarchive/pull/4022#discussion_r656790379). 
See issue.
@CristinaRO and @tlee911; the task was added in #4022 but removed during review.
=> AO3-5988 Add task to replace all noncanonical ratings 

app/mailers/comment_mailer.rb, spec/mailers/admin_mailer_spec.rb, spec/mailers/collection_mailer_spec.rb, spec/mailers/comment_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples/mailer_shared_examples.rb
https://otwarchive.atlassian.net/browse/AO3-6165
Before sending reply notifications for guest comments (but not logged in comments), we should check if the comment's email is in the banned list. If it is, we should skip the notification.
Also make sure the subject of mailer specs is the mailer object, not the message object (returned by "deliver").
See issue.
=> AO3-6165 Skip comment reply notifications for guests with banned emails

app/views/admin/admin_users/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-6205
Allow admins viewing the admin user page to see the given user's ID.
1. Log in as a superadmin, support, or policy_and_abuse admin
2. Visit the /admin/users/USERNAME page for some user named USERNAME
3. The page's heading should read "User: USERNAME (USER_ID)" with the correct USERNAME and USER_ID
NightGlyde (she/her)
=> AO3-6205 Add user ID to admin user page

app/helpers/mailer_helper.rb, app/mailers/user_mailer.rb, app/views/user_mailer/admin_hidden_work_notification.html.erb, app/views/user_mailer/admin_hidden_work_notification.text.erb, config/locales/mailers/en.yml, features/admins/admin_works.feature, spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6206
Updates the content of the html and text versions, apply `style_bold` to `user`, apply `style_creation_link` to `work`, make `user` username instead of default pseud
1. Log in, making sure to use an account that's hooked up to an email address you can access
3. Fill in required information
4. Press "Post"
5. Make note of the URL
6. Log out
7. Log in as an admin with the role policy_and_abuse or superadmin
8. Go to the work you posted
9. Press "Hide Work"
10. Ensure the email text is as described below
If you have a Jira account with access, please update or comment on the issue with any new or missing testing instructions instead.
=> AO3-6206 Update text of email that is sent when an admin hides a work

app/models/invitation.rb, spec/models/invitation_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6094 
This persists the change to invitation.sent_at during send_and_set_date to the database. (Previously, it only occurred on the record in memory)
See JIRA ticket. After this fix, inspecting the sent invitation on e.g. /users/{username}/invitations/{sent_invitation_id} should both have a "Created at" timestamp (as before) and a "Sent at" timestamp listed (new).
AFAICT, originally introduced during https://github.com/otwcode/otwarchive/commit/c328cdd980a5ce985367a9b7ef52e8e2ded2ecd8, which fixed https://code.google.com/archive/p/otwarchive/issues/3115 .
=> AO3-6094 Correctly set sent_at during invitation after_save callback

app/controllers/users_controller.rb, features/other_a/profile_edit.feature
https://otwarchive.atlassian.net/browse/AO3-5049
This PR fixes a confusing error message when a user tries to change their email address to one already in use by another user.
See JIRA
=> AO3-5049 Fix confusing "email change" error message

app/controllers/users_controller.rb, features/other_a/profile_edit.feature, features/step_definitions/profile_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5049
This fixes the bug described in https://otwarchive.atlassian.net/browse/AO3-5049?focusedCommentId=357672 .
When trying to change a user's email address, enter two email addresses that don't match. An error should appear.
=> AO3-5049 Fix bug where error message was not shown immediately.

app/controllers/bookmarks_controller.rb, app/controllers/chapters_controller.rb, app/models/bookmark.rb, app/models/collection_item.rb, app/models/concerns/taggable.rb, app/models/external_work.rb, app/models/work.rb, app/validators/at_most_validator.rb, app/views/bookmarks/_external_work_fields.html.erb, app/views/works/_meta.html.erb, app/views/works/_work_form_tags.html.erb, config/config.yml, config/locales/models/en.yml, features/admins/admin_works.feature, features/bookmarks/bookmark_create.feature, features/collections/collection_anonymity.feature, features/step_definitions/external_work_steps.rb, features/step_definitions/work_steps.rb, features/works/chapter_edit.feature, features/works/work_create.feature, features/works/work_delete.feature, features/works/work_edit.feature, lib/bookmarkable.rb, lib/work_chapter_count_caching.rb
https://otwarchive.atlassian.net/browse/AO3-6153
- Limit the number of user-defined tags used on works to 75 (configurable).
- Limit the number of user-defined tags used on external works to 75 (configurable).
- Add assorted messages and error messages.
- Modify `BookmarksController` so that it no longer explicitly calls `@bookmarkable.save`. Instead, we rely on Rails' built-in behavior when saving objects that refer to other unsaved objects, and add some checks to the bookmark class to make sure that we only save the bookmark when the new external work is valid and has a fandom.
- Modify `CollectionItem#update_work` so that it skips validations when saving the work. This is so that works can be revealed/de-anoned even if they're over the tag limit.
=> AO3-6153 Limit maximum number of user-defined tags allowed on works & external works.

app/controllers/collection_items_controller.rb, features/bookmarks/bookmark_create.feature, features/collections/collection_anonymity.feature, features/collections/collection_invite.feature, features/works/work_delete.feature
https://otwarchive.atlassian.net/browse/AO3-6153
Makes it so that the "Add to Collection" button doesn't check the validity of the item being added to the collection.
=> AO3-6153 Don't check validity on collection invite.

app/models/collection_item.rb, features/collections/collectible_moderated_collection.feature, features/collections/collection_invite.feature, features/step_definitions/collection_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6153
Allow invalid works to be approved/rejected from collections, and allow users to accept/reject collection invitations on invalid works.
=> AO3-6153 Allow approval status changes for collection items on invalid works.

public/403.html, public/502.html, public/503.html, public/507.html, public/nomaintenance.html, public/status/index.html
https://otwarchive.atlassian.net/browse/AO3-6070
Updates the remaining insecure links on the error pages to point to HTTPS URLs:
* Twitter links on 502.html, 503.html, 507.html, nomaintenance.html
* Instructions on clearing your cache on nomaintenance.html
* Link to the OTW contact form on 403.html
Clicky the linky.
=> AO3-6070 Update error page links to use https

app/controllers/users_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5049
This makes it so both error and success messages only stick around for one page render instead of two (which looks weird right now)
Successfully change an account's email address. You should see a success message. Navigate to another page. You should no longer see the success message.
=> AO3-5049 Use flash.now to flash msg on same render

app/controllers/comments_controller.rb, config/locales/controllers/en.yml, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6038
This helps resolve the bug where a commenter can accidentally unmark a comment as spam by replying to it.
Note: this was already partially fixed by https://github.com/otwcode/otwarchive/pull/3963, which changed the `check_for_spam` validation to run only when new comments are created.
The main thing this PR adds is a validation check on the controller to ensure that the comment you're replying to (i.e. the "commentable", a.k.a. the "immediate parent", not to be confused with the "parent" a.k.a. "ultimate parent") is not marked as spam. And also updates to the rspec test for this.
(If I understand …
=> AO3-6038 Prevent replying to comments marked as spam

config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6120
The warning should not occur on https://secure.archiveofourown.org/ 
This can't be tested on staging, apart from noting that we have not got the warning on https://test.archiveofourown.org
=> AO3-6120 Add our IPs and secure URL to PERMITTED_HOSTS to hide proxy notice

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5372
This adds padding to the list of bookmarks on the recent bookmarks page `/bookmarks/` and the user bookmarks page `/users/${userName}/bookmarks`.
**New changes:**
1. Go to the `/bookmarks` page. There should be padding within the bookmark so the content isn't directly up against the borders anymore.
2. Go to the bookmark's list for any specific user (`/users/${userName}/bookmarks`). Same check as above ^
3. Bookmark a work. The gray "bookmarked by `{myUsername}`" bookmark should also have padding now.
**Things that should be unchanged:**
1. Go to the bookmarks for any specific work …
=> AO3-5372 Add padding to user bookmarks

app/controllers/prompts_controller.rb, app/views/works/_work_header_notes.html.erb, features/prompt_memes_b/challenge_promptmeme_posting_fills.feature
https://otwarchive.atlassian.net/browse/AO3-3828
When a work has been submitted to fulfill a prompt in a Prompt Meme collection, an automatically-inserted text in the work notes says so. This PR adds a link to the specific prompt to that text.
1. Post a work that fulfills a prompt
2. Look at the automatically-inserted text in the work notes
3. Note that it says: "In response to a prompt by CREATOR in the COLLECTION_NAME collection."
4. Note that the word "prompt" is a link to the prompt in question. …
=> AO3-3828 Link to prompt in the notes of a prompt fill

Gemfile, Gemfile.lock, app/models/tag.rb, features/tags_and_wrangling/tag_wrangling_admin.feature, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6188
This PR tightens the overly-broad regex that was being used to compare previous and new names for a tag. Before this pull request, no non-ASCII charactetrs were compared, so a tag wrangler could rewrite "ø" to "てりやき".
Now, only characters that are latin diacritical marks are stripped.
To test this, please try to rename a tag and ensure that, for example, "ø" can be renamed to "o", but not to "てりやき".
There are no other references that I'm aware of.
Daroc …
=> AO3-6188 Don't ignore any non-ASCII character when renaming tags

config/brakeman.ignore
https://otwarchive.atlassian.net/browse/AO3-6234
Updates the Brakeman ignore file, which appears to need it. We'll see how Hakiri feels.
```
brakeman -I
1. Inspect all warnings
2. Hide previously ignored warnings
3. Prune obsolete ignored warnings
4. Skip - use current ignore configuration
?  2
3 fingerprints are unused:
/Users/sarken/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/brakeman-3.7.2/bundle/ruby/2.3.0/gems/highline-1.7.8/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
04a2dece009c698540960269d024b874a42b71cf8e06e3216c41f8807e57f9b9
/Users/sarken/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/brakeman-3.7.2/bundle/ruby/2.3.0/gems/highline-1.7.8/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated …
```
=> AO3-6234 Update Brakeman ignore file

app/helpers/mailer_helper.rb, app/views/user_mailer/admin_deleted_work_notification.html.erb, app/views/user_mailer/admin_spam_work_notification.html.erb, app/views/user_mailer/claim_notification.html.erb, app/views/user_mailer/delete_work_notification.html.erb, app/views/user_mailer/invite_increase_notification.html.erb, app/views/user_mailer/invite_request_declined.html.erb, config/locales/mailers/en.yml
* Removes a link from the signature of emails relating to invitation requests 
* Removes extra blank line from the signature of the invitation request declined email
* Consistently refers to Support as "AO3 Support" in the Open Doors emails
* Adds quotation marks around the work title in the plain text version of the hidden work email
* Updates the style of the work link in the spam work HTML email
* Adds and uses helper method to style non-linked work titles in deleted work emails
Refer to Jira
=> AO3-6103 Additional standardization of email signatures, work titles, support links

app/mailers/user_mailer.rb, config/locales/mailers/en.yml, spec/mailers/user_mailer_spec.rb
Make the subject of the email that gets sent when you receive a gift sentence case rather than title case.
Refer to Jira.
=> AO3-6103 Make recipient_notification email subject sentence case

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-5372
This addresses the QA feedback left on the JIRA issue. With the margin-right in place for bookmark bylines, they should wrap on small screens now. I also increased the top and right properties on the datetimes in recent and user bookmarks - I forgot about how the datetimes having a smaller font-size would mean their `em` value is lower, oops. They should better match the positioning of the datetimes in bookmarks with an icon now.
Screenshots that have both types of bookmarks!
In JIRA.
This is addressing QA feedback on …
=> AO3-5372 Fix small-screen bookmark byline wrapping, increase top/right on bookmark datetimes

db/migrate/20210831214137_index_tag_nominations_and_tag_set_nominations.rb, db/migrate/20210831214137_index_tag_nominations_on_tag_set_nomination.rb, db/migrate/20210902040827_index_tag_set_nominations.rb
https://otwarchive.atlassian.net/browse/AO3-6209
Add an index starting with `tag_set_nomination_id` to the `tag_nominations` table using PTOSC, and add two indices (one starting with `pseud_id`, one starting with `owned_tag_set_id`) to the `tag_set_nominations` table.
=> AO3-6209 Indices for tag_set_nominations and tag_nominations tables.

app/models/challenge_assignment.rb, app/views/user_mailer/collection_notification.html.erb, app/views/user_mailer/collection_notification.text.erb, config/locales/mailers/en.yml, features/gift_exchanges/challenge_giftexchange.feature, spec/mailers/user_mailer_spec.rb
Converts the subject line of the assignment sent email to sentence case, and internationalizes that email.
I said I wasn't going to do this in AO3-6103 because the email's done differently than the others, but I forgot and did it. 🤷 
I put the text under the mailer rather than the challenge assignment model because it seemed a bit more sensible a place to look for it, but I can move it. I can also close this and make a new issue like I originally said I'd do.
Send the assignments for a gift exchange and make sure you get an email with the subject "Assignments sent."
=> AO3-6103 Sentence case assignment sent email subject, plus i18n

app/views/user_mailer/invalid_signup_notification.text.erb
https://otwarchive.atlassian.net/browse/AO3-6103 
Removes a stray signature.
Refer to Jira.
=> AO3-6103 Remove signature from invalid sign-ups text email

app/views/user_mailer/added_to_collection_notification.html.erb, app/views/user_mailer/added_to_collection_notification.text.erb, app/views/user_mailer/admin_hidden_work_notification.text.erb, app/views/user_mailer/admin_spam_work_notification.text.erb, app/views/user_mailer/anonymous_or_unrevealed_notification.html.erb, app/views/user_mailer/anonymous_or_unrevealed_notification.text.erb, app/views/user_mailer/invite_request_declined.text.erb, app/views/user_mailer/invited_to_collection_notification.html.erb, app/views/user_mailer/invited_to_collection_notification.text.erb, app/views/user_mailer/prompter_notification.html.erb, app/views/user_mailer/prompter_notification.text.erb, app/views/user_mailer/recipient_notification.html.erb, app/views/user_mailer/recipient_notification.text.erb, app/views/users/mailer/reset_password_instructions.text.erb, config/locales/mailers/en.yml, features/gift_exchanges/challenge_yuletide.feature, spec/mailers/user_mailer_spec.rb
- Makes collection titles links in HTML emails; wraps them in double quotes and includes their URL in text emails.
- Formats work titles with style_creation_link in HTML emails; wraps them in double quotes and includes their URL in text emails.
- Corrects the preferences URL. It previously used your default pseud name instead of your username.
- Removes an extra period after the name of a preference.
- Adds paragraph spacing to text emails.
- Removes indenting from text emails.
[Refer to Jira comment](https://otwarchive.atlassian.net/browse/AO3-6103?focusedCommentId=357885)
=> AO3-6103 Additional pre-translation email standardization 

app/views/home/tos_faq.html.erb, config/locales/mailers/en.yml
No tests added. As far as I understand, we do not verify exact content of sent emails and do not test any user-facing large bodies of text like TOS FAQ
https://otwarchive.atlassian.net/browse/AO3-6220
Added more changes to existing ones as per information from tester.
- I believe FAQ itself is not available on development environments, so couldn't check the links by following them, but they look consistent with FAQ provided on AO3.
- both text/html is updated in emails (English version as the only one present in the source code)
- could check it only through developer log, not actual email (didn't figure out which setting to change, …
=> AO3-6220 Update remaining collection FAQ links

app/views/user_mailer/challenge_assignment_notification.text.erb, config/locales/mailers/en.yml
Switch from `"%{collection_title}" (%{collection_url}) challenge` to `"%{collection_title}" challenge  (%{collection_url})`. 
Why? Because we have two instances of `"<%= @collection.title %>" collection (<%= collection_url(@collection) %>)` and one of `%{title} challenge (%{url})`.
I've renamed the key as well, since existing translations need updating now anyway. I didn't rename the corresponding key for the HTML version because those translations are still valid. We rename that one with i18n-tasks post-Phrase export.
=> AO3-6103 Shuffle URL position in challenge assignment email

app/views/feedbacks/new.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6222
* Removes the `footnote` class that was making a description too small
* Removes the ARIA connection between the email address field and IP notice (why did I ever do that?)
* i18n per original issue description
* We don't use `*_html` keys in emails, but we have them for other views, so wheee.
* Read contents of page and compare with text in issue
* Submit blank form and make sure error messages appear on summary and comment fields and "Send" button becomes "Please wait..."
=> AO3-6222 i18n Support form, fix text size issue, unlink email field & IP notice

app/views/abuse_reports/new.html.erb, config/brakeman.ignore, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6221
We announced purview change for Support and PAC; this updates the abuse form accordingly. The main support form changes were already merged, but additional changes are in #4085.
* Read the page text and compare to what is on production and what is in the issue
* Press "Submit" with all fields blank and make sure "Brief summary of Terms of Service Violation (required)" and "Your comment (required)" get errors displayed
I used the same structure for the keys as #4085 even when not quite necessary because the pages often mirror each other in structure/content/behavior and tweaks to bring them closer in line would not surprise me.
=> AO3-6221 Update and internationalize abuse form text

app/mailers/archive_devise_mailer.rb, app/mailers/comment_mailer.rb, app/mailers/kudo_mailer.rb, app/mailers/user_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-6109
There were a couple emails whose content we'd prepared for localization, but for which we hadn't updated the code to send the emails in the users' preferred locale. 
This ensures challenge_assignment_notification and admin_hidden_work_notification take a user's locale preference into account. It also updates some code comments.
For now: 
* As an admin, hide a work. Ensure the work creator gets an email saying the work was hidden.
* Send assignments for a gift exchange. Ensure the participants get emails notifying them of their assignments.
=> AO3-6109 Add missing with_locale for some internationalized mailers

public/javascripts/application.js
https://otwarchive.atlassian.net/browse/AO3-6252
If you submit kudos using JavaScript and run into a rate limit, you should get a meaningful error.
As a guest, submit more kudos than allowed in a given time period. Verify the error message appears. Also verify you get the usual "You have already left kudos here. :)" error if submitting duplicate kudos without going over the rate limit.
=> AO3-6252 Add error message for kudos rate limit

.github/workflows/automated-tests.yml, Gemfile, Gemfile.lock, docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-5671
- Update the gem version to 7.15.0 and fix a dependency conflict; faraday 1.4 and our current resque version expect different versions of ruby2_keywords.
- Update the elasticsearch container image in development and CI to 7.15.2. For CI, switch to docker.elastic.co because hub.docker.com does not yet have the version.
- Silence noisy "security features are not enabled" warnings in CI and development: https://github.com/elastic/elasticsearch/issues/78500.
CI should pass.
=> AO3-5671 Update Elasticsearch to 7.15

config/config.yml, config/initializers/archive_config/mail.rb
https://otwarchive.atlassian.net/browse/AO3-6263
Allow ssl config for email to be configable
On current debian 10 systems check email still flows ( Check sync and via workers, just one of each should be fine. )
Get systems to upgrade staging's systems to debian 11 and test again.
=> AO3-6263 Allow SSL for SMTP to be configurable

app/controllers/users_controller.rb, features/other_a/profile_edit.feature, features/step_definitions/profile_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6225
This PR makes it so that the email address confirmation is compared case-insensitively when a user changes their email.
Follow the Steps to Reproduce from the JIRA ticket, and ensure that no error message is seen.
None that I'm aware of.
Daroc Alden, they/them
=> AO3-6225 Make comparison of email addresses case-insensitive

app/models/admin_post.rb, app/views/admin_posts/_admin_post_form.html.erb, config/locales/views/en.yml, features/admins/admin_post_news.feature, features/step_definitions/admin_steps.rb, features/step_definitions/generic_steps.rb, features/tag_sets/tag_set_nominations.feature
https://otwarchive.atlassian.net/browse/AO3-6093
With code similar to the one in 7682597ae9f9a2b18144925154ca6dce32606570 assures the tags in translated admin posts are in sync with the tags in original
As per issue.
Notes:
1. For existing translations: tags will get updated if tags on the original translation are updated.
2. If A is original, B is translation of A, and C is translation of B (as we can do that apparently by forcing post id), all the tags are also in sync.
korrien, she/her
=> AO3-6093 Propagate tags from original admin posts to translations

app/models/chapter.rb, spec/controllers/chapters_controller_spec.rb
~~I'm pretty sure this is a fix for both issues - I'll do my best in JIRA to make note of that.~~ (Initially thought this would fix 2247 as well, but it doesn't quite cover all edge cases from that issue).
https://otwarchive.atlassian.net/browse/AO3-5926
This fixes the `fix_positions_before_destroy` method in the `before_destroy` chapter hook to make all subsequent chapters go down one position instead of up one.
**Extra details if anyone is curious:**
I stepped through the code a bit to figure out why this wasn't causing issues when a chapter besides the first one was deleted... as it turns out, the `fix_positions` method called in a chapter's …
=> AO3-5926 Fix chapter re-positioning when deleting chapter one

app/controllers/challenge/gift_exchange_controller.rb, app/controllers/challenge/prompt_meme_controller.rb, lib/challenge_core.rb, spec/controllers/gift_exchange_controller_spec.rb, spec/controllers/prompt_meme_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6189
Removes the code in `GiftExchangeController` and `PromptMemeController` that sets `Time.zone` to the challenge's time zone.
Also modifies the datetime string conversion in `lib/challenge_core.rb` so that it formats dates in the challenge's time zone.
See Jira.
=> AO3-6189 Don't set Time.zone in challenge controllers.

app/views/external_authors/claim.html.erb, app/views/user_mailer/claim_notification.html.erb, app/views/user_mailer/claim_notification.text.erb, app/views/user_mailer/invitation_to_claim.html.erb, app/views/user_mailer/invitation_to_claim.text.erb
https://otwarchive.atlassian.net/browse/AO3-6261
Fixes an outdated link to Contact Open Doors in two emails (both HTML and text versions) and one web page.
Per the ticket, import a work, twice, once with a email associated with an account, and once with an email not associated, both of which emails you have access to. Review the resulting emails to confirm the URL is updated.
I am not entirely certain how to access the updated web page to verify it, but I think it may be linked from the emails?
Please credit me (if this is a big enough fix to bother with credit) as "Jesse Weinstein (he/him)".
=> AO3-6261 Update Contact Open Doors link in work claim emails

spec/helpers/application_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6132
Fixes an intermittent test failure introduced in the tests for AO3-6132. Adding `user2` as a creator of the work in `spec/helpers/application_helper_spec.rb:248` causes the series to be touched, but the series object that has `touch` called on it is a different in-memory copy of the series defined in the `let` above. This causes the initial cache key to be computed incorrectly, which breaks the test.
=> AO3-6132 Fix intermittent failure in series blurb helper tests

.rubocop.yml, config/locales/README.md, config/locales/rails-i18n/pluralization/hr.rb, spec/lib/i18n/pluralization_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6262
Phrase follows CLDR rules, where Croatian uses [one/few/other](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#hr) but rails-i18n expects [one/few/other/many](https://github.com/svenfuchs/rails-i18n/blob/f6cc43ec8cfc08d0db7a06ca8299d7834c517a05/lib/rails_i18n/common_pluralizations/east_slavic.rb#L37).
See issue.
=> AO3-6262 Update pluralization rule for Croatian

app/models/admin_post.rb, features/admins/admin_post_news.feature
https://otwarchive.atlassian.net/browse/AO3-6093
Update after testing.
Hope I understood the issue and suggested solution correctly 😄 
Provided translation tags are not saved. However, when tag is updated on original post, old tag still shows up in search even though it was used only in that one post. As it has nothing to do with translation issue, did nothing with it.
korrien, she/her
=> AO3-6093 Prevent creation of translation tags in system

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6132
Adds a version number to the cache key so everything is expired on deploy.
=> AO3-6132 Version cache key for blurb CSS classes

config/locales/mailers/en.yml, spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6258
Updates the subject of the email a user receives on sign up, from `[AO3] Confirmation` to `[AO3] Activate your account`.
1. If not already enabled, turn on account creation (https://github.com/otwcode/otwarchive/wiki/Development-Data#creating-users).
2. Create a user (with valid email) via the "Create an Account!" button on the home page.
3. Check the email account for an email with the subject "[AO3] Activate your account".
**Brian Austin (he/they)**
=> AO3-6258 Update sign-up email subject

app/views/invitations/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-6269
Allows a user to click the "keysmash" label of an invitation rather than needing to select the radio box
1. Log in as a user who has unused invitations
2. Go to your invitations page: https://archiveofourown.org/users/USERNAME/invitations
3. Click/tap on one of the keysmashes – as in, the text itself – in the "Choose an invitation" section
Arianna Story (she/her)
=> AO3-6269 Allow invitations to be selected with their label

app/models/chapter.rb, app/models/story_parser.rb, app/models/work.rb, app/views/chapters/_chapter_form.html.erb, app/views/works/_standard_form.html.erb, features/step_definitions/work_steps.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6190
Stop using Time.now and Date.today in the work/chapter date calculations, because they return the time/date in the system time zone (UTC, for production), which doesn't match all of the times/dates that use the time zone set here:
https://github.com/otwcode/otwarchive/blob/72b975cf5ed90ce28cf212e84420aaccea871372/config/application.rb#L50-L53
This should prevent all future works from encountering https://otwarchive.atlassian.net/browse/AO3-5392, but won't address any pre-existing works with a `revised_at`/`published_at` mismatch.
I also modified `set_revised_at` so that redating to the current day will no longer set `revised_at` to noon UTC, even if noon UTC is in the future.
=> AO3-6190 Don't use Time.now and Date.today in the work/chapter date calculations.

app/jobs/application_mailer_job.rb, app/mailers/admin_mailer.rb, app/mailers/application_mailer.rb, app/mailers/collection_mailer.rb, app/mailers/comment_mailer.rb, app/mailers/kudo_mailer.rb, app/mailers/user_mailer.rb, spec/mailers/comment_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4037
Modify all mailers to retry on a deserialization error or a record not found error. It will try to send the email a total of 3 times, with 1 minute of delay between each attempt. If all three attempts fail, it will silently delete the mailer job, instead of bubbling up to the Resque failures list.
=> AO3-4037 Retry comment notifications when comment does not exist.

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5392
The field `revised_at` is used in work blurbs.
Also reset revised_at for non-backdated works if it's arbitrarily set in the past (possibly because of [AO3-6187](https://otwarchive.atlassian.net/browse/AO3-6187)).
Note that the actual bug was fixed in #4115. This is just to fix the dates on existing works.
Find an existing work from testy affected by the bug, run the task and check that the work now has consistent dates in blurb and meta.
=> AO3-5392 Add task to reset revised_at on backdated works

public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-5754
Moves the style tweaks from #3673 around a bit for future proofing. (The `LV_validation_message` gets applied to both success and failure messages, so it's good to keep general style stuff there.)
=> AO3-5754 Tweak implementation of live validation message styling

app/views/home/site_map.html.erb, app/views/layouts/_footer.html.erb, features/admins/admin_languages.feature, features/other_a/abuse_report.feature, public/403.html, public/445.html, public/500.html, public/502.html, public/503.html, public/507.html, public/nomaintenance.html
https://otwarchive.atlassian.net/browse/AO3-5619
Change the "Report Abuse" link text in the footer, site map and static error pages to "Policy Questions & Abuse Reports".
1. Go to archiveofourown.org
2. Scroll down the page and under "Contact Us", check if first link text has been changed
3. Repeat for static error pages and site_map. (Links are in the Jira ticket)
=> AO3-5619 Update Report Abuse link text in footer and site map

public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-5754
Increases the margin on the live validation messages from 13em to the 15em originally requested in the issue, since a larger margin appears necessary in Firefox.
=> AO3-5754 Increase right margin on live validation message for Firefox

app/views/users/_sidebar.html.erb
https://otwarchive.atlassian.net/browse/AO3-6249
Changes the "Pseuds" dropdown on /users/USERNAME/* pages to always read as "Pseuds" rather than showing the pseud that is currently being acted on
1. Log in as a user who has more than one pseud
2. Click the "Pseuds ↓" dropdown
3. Switch to another pseud
4. See that the "Pseuds ↓" dropdown is no longer changing :)
Arianna Story (she/her)
=> AO3-6249 Make Pseuds dropdown on user page sidebar always label itself as Pseuds

app/views/readings/_reading_blurb.html.erb
https://otwarchive.atlassian.net/browse/AO3-6227
Makes sure the blurbs for deleted works in your history have the `blurb group` classes that give it the proper behavior and style.
I did consider doing this in the `css_classes_for_creation_blurb(creation)` helper, but I couldn't think of another instance where it'll be necessary, plus I think this just makes the view tidier than when the logic was all crammed into the `class` attribute itself.
On the Jira issue!
=> AO3-6227 Restore missing classes to deleted work history blurbs

app/helpers/application_helper.rb, app/views/bookmarks/search_results.html.erb, app/views/layouts/_banner.html.erb, app/views/stats/index.html.erb, app/views/works/_adult.html.erb, app/views/works/search_results.html.erb
https://otwarchive.atlassian.net/browse/AO3-6289
There are a number of pages on the archive that want to link back to the current path, but with slightly different parameters. Currently, they accomplish this by passing `params.permit!` or `request.parameters` to `url_for`, with small modifications. This PR introduces a new function `current_path_with` that handles the path generation in a more consistent way.
The method is loosely modeled on the way that `will_paginate` generates page links, on the theory that the gem has enough users that most of its security issues have probably been ironed out.
=> AO3-6289 Introduce current_path_with instead of using params.permit!

app/models/work.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5392
Modifies the date calculation in `set_revised_at_by_chapter` so that it works even when `revised_at.to_date` doesn't match `published_at` for any of the chapters, while still preventing unnecessary changes to `revised_at`. This allows users to redate any existing works affected by AO3-5392. (New works were handled in #4115.)
=> AO3-5392 Simplify date computation in set_revised_at_by_chapter.

public/stylesheets/site/2.0/16-zone-system.css
https://otwarchive.atlassian.net/browse/AO3-6271
Makes sure the `float` from `.logged-in .splash .module` isn't applied to the header module in the marked for later blurbs, causing the icons and title to be misaligned.
Refer to Jira.
=> AO3-6271 Fix blurb icon position on homepage Marked for Later

app/controllers/admin/admin_users_controller.rb, app/models/user.rb, app/views/admin/admin_users/index.html.erb, features/admins/users/admin_find_users.feature, features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6230
Allows admins who can search users to search by user ID.
Refer to Jira.
=> AO3-6230 Let certain admins search by user ID

app/views/admin/admin_users/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-6230
Adds a description to the User ID field on admin user search form.
Log in as an admin who can manage users, go to Find Users, and confirm the note is under the User ID input.
=> AO3-6230 Add description to user_id field on admin search

app/mailers/comment_mailer.rb
https://otwarchive.atlassian.net/browse/AO3-6295
When trying to send a comment reply notification (or edited comment reply notification) where the person being notified has deleted their account, we should bail out instead of trying to send an email with a blank sender.
=> AO3-6295 Don't send comment reply notifications to deleted accounts.

spec/models/external_work_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6296
Stub example.org for all rspec tests, and stub the URL used in `./spec/models/external_work_spec.rb:34`.
=> AO3-6296 Use WebMock to stub external work URLs in specs.

spec/controllers/api/v2/api_bookmarks_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6296
Turns out there are some intermittent errors that my previous PR didn't catch in the spec for the bookmarks API. So I'm changing the way that WebMock is used in those tests.
=> AO3-6296 Use webmock for more intermittent errors.

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb
https://otwarchive.atlassian.net/browse/AO3-6228
Removes the `activerecord-mysql-reconnect` gem, and all of the references to it in the configuration files. This is half of what's needed to prevent reconnects from breaking up large transactions and causing inconsistencies.
(The other half is removing `reconnect: true` from `config/database.yml`, which is not under version control.)
=> AO3-6228 Remove the mysql reconnect gem, to prevent half-transactions.

Gemfile
https://otwarchive.atlassian.net/browse/AO3-6299
Modify the Gemfile so that the `newrelic_rpm` gem is only loaded in staging and production, not test or development.
=> AO3-6299 Stop using New Relic in the test environment.

config/application.rb, features/admins/users/admin_manage_users.feature, features/step_definitions/reading_steps.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6300
Stops setting Rails' timezone to US Eastern (and consequently starts using the default of UTC).
If you want, it can a) explicitly set it to UTC and/or b) remove the comments about how to change the Rails timezone.
Refer to Jira.
=> AO3-6300 Use default Rails time_zone (UTC)

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6085
The gem has been merged into nokogiri 1.12.0.
Remove its deprecation warnings (sparklemotion/nokogiri#2205).
See issue.
=> AO3-6085 Remove explicit dependency on nokogumbo

Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6275
When loading the Rails console, you get yelled at about Serbian pluralization already being loaded: https://github.com/svenfuchs/rails-i18n/issues/965
Updating should prevent being yelled at.
Run `bundle exec rails c` in your dev environment after updating.
h/t @redsummernight
=> AO3-6275 Update rails-i18n to 7.0.3

.github/labeler.yml, .github/labeler/awaiting.yml, .github/labeler/contents.yml, .github/labeler/review.yml, .github/workflows/labeler.yml
https://otwarchive.atlassian.net/browse/AO3-5819
This PR sets up the automatic pull request labeler action. It will run whenever a pull request is submitted, updated, or reopened, and it will automatically add ~~and/or remove~~ labels according to which paths are being modified.
~~It will also remove the two "Reviewed" labels and add back the "Awaiting Review" label any time the pull request is modified, which isn't exactly the desired behavior (it'd be better to add "Coder Has Actioned Review" instead of "Awaiting Review"), but I don't think it's possible to configure it to only add "Coder Has Actioned Review" if it previously had one of the "Reviewed" labels and "Awaiting Review" otherwise.~~
~~I picked this approach because it makes the set-up simpler, and I think re-adding "Awaiting …
=> AO3-5819 Automatically label pull requests.

config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb
https://otwarchive.atlassian.net/browse/AO3-6085
Cached data between Dalli versions 2 and 3 are [incompatible](https://github.com/petergoldstein/dalli/blob/313c2d84f45e20149c1b7ee4c1e8337f975791d9/3.0-Upgrade.md).
Site loads normally.
=> AO3-6085 Change memcached namespace in all environments

config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-6085
GitHub is [removing support for the unencrypted Git protocol](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
Not really related to the Rails update, but hey, it's in the way.
Deploy should work.
=> AO3-6085 Update Capistrano repository URL to use https

.gitignore, app/models/pseud.rb, lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6316
* Puts the pseud icons for staging under a different path so we can change those when testing without affecting production
* Add a task to fix invalid pseud icons, icon alt text, and icon comment text
Refer to Jira 
https://github.com/otwcode/otw-scripts/pull/18
=> AO3-6316 Use separate path for staging's pseud icons, add task to fix invalid pseuds

app/models/pseud.rb, spec/models/pseud_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3293
When we modify a pseud, touch any comments that belong to it to ensure the name and icon are updated.
Refer to Jira.
=> AO3-3293 Touch comments when pseud is changed

app/models/external_work.rb, app/validators/url_active_validator.rb, lib/url_helpers.rb, spec/models/external_work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6306 
When a user attempts to bookmark an external work, the backend checks that the URL they entered is not a dead link by sending it a HTTP HEAD request. The code to handle this accepts a response of 200, 301, or 302 as a live URL but since it was written before 307 and 308 redirects were added to the HTTP spec, it fails on websites that return those response codes. This PR fixes that.
1. Log in
2. Hi, username! > My Bookmarks > Bookmark External Work
3. Enter a URL that will give a response code of either 307 or 308, e.g. something from https://mangadex.org/ will give a 308
4. Fill in other required …
=> AO3-6306 Can't bookmark URLs with response codes of 308 or 307

app/models/abuse_report.rb, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6309
Updated abuse form error message to discourage over-reporting. 
Original: 
> URL has already been reported. To make sure the Abuse Team can handle reports quickly and efficiently, we limit the number of times a URL can be reported.
New:
>This page has already been reported. Our volunteers only need one report in order to investigate and resolve an issue, so please be patient and do not submit another report.
See issue.
Tara Rosenthal(she/her)
=> AO3-6309 Update abuse form error for over-reporting URLs

app/jobs/application_mailer_job.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples/mailer_shared_examples.rb
https://otwarchive.atlassian.net/browse/AO3-5955
https://otwarchive.atlassian.net/browse/AO3-5956
https://otwarchive.atlassian.net/browse/AO3-6294
Sometimes, if an object is deleted around the time that an email is sent about it, the email will successfully load certain objects (thus preventing an `ActiveRecord::RecordNotFound` error that might trigger a retry), but will then fail to load that object's associations. For example, if a user deletes their account around the time that they are supposed to receive an email, it's possible that the email job will be able to load the `User` object, but not the associated `Preference` object. This produces an error when we subsequently try to access the locale associated with the user.
This PR causes email jobs to be retried on two types of error: …
=> AO3-5955 AO3-5956 AO3-6294 Retry email sending on NoMethodError and ActionView::Template::Error

app/controllers/comments_controller.rb, app/helpers/comments_helper.rb, app/views/comments/_comment_form.html.erb, app/views/comments/add_comment.js.erb, config/routes.rb, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6185
Remove the unused `add_comment` and `cancel_comment` actions.
=> AO3-6185 Remove unused add_comment/cancel_comment actions.

app/models/abuse_report.rb, config/config.yml, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6274
Limits how many times per day an email address can submit an abuse report.
Refer to Jira.
=> AO3-6274 Limit number of abuse reports per email per day

app/views/tags/_search_form.html.erb, app/views/works/_search_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-5830
Remove blank option in the sort direction of Work & Tag Search
Check the list for "Sort direction" in Work and Tag Search pages show only "Ascending" and "Descending" options. 
https://github.com/otwcode/otwarchive/pull/4144
=> AO3-5830 Remove blank option in Work & Tag Search

app/views/users/passwords/edit.html.erb, config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-6334
So it can have different rate limits from the endpoint for requesting password resets.
See issue.
This is also covered by the scenario at:
https://github.com/otwcode/otwarchive/blob/59bb5ebc3ca4fa86056b410d922152905b8cc179/features/users/authenticate_users.feature#L51-L56
=> AO3-6334 Use a different endpoint for resetting passwords

spec/lib/zoho_auth_client_spec.rb, spec/lib/zoho_resource_client_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6156
Now we don't need to know how the client classes implement HTTParty.
Profile editing by admins will be in a follow-up PR.
None.
=> AO3-6156 Rewrite Zoho client specs to use WebMock

app/views/kudo_mailer/batch_kudo_notification.html.erb, app/views/kudo_mailer/batch_kudo_notification.text.erb, config/locales/mailers/en.yml
https://otwarchive.atlassian.net/browse/AO3-6254
Having `single_guest` under `left_kudos` wasn't working because it wasn't a standard pluralization key. This moves it so it'll work.
Ask Translation if it works.
=> AO3-6254 Move key for single guest kudos

.rubocop.yml, app/controllers/users_controller.rb, app/models/concerns/justifiable.rb, config/locales/models/en.yml, features/other_a/profile_edit.feature, features/step_definitions/admin_steps.rb, features/support/paths.rb, lib/zoho_resource_client.rb, spec/models/concerns/justifiable_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6156
Also add more specific error messages for failed ticket validations.
See issue.
=> AO3-6156 Skip logging admin activity for empty edits

app/views/kudo_mailer/batch_kudo_notification.html.erb, config/locales/mailers/en.yml, features/comments_and_kudos/kudos.feature, spec/mailers/kudo_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6256
Makes sure that when your work gets a single kudos, and that single kudos is from a guest, the "A guest" portion of "A  guest left kudos on #{work_link}" is red and bold in the HTML email.
Leave a single guest kudos (and no other kudos) on your work. Run `bundle exec rake notifications:deliver_kudos` and make sure the kudos is style correctly.
=> AO3-6256 Restore formatting on single guest kudos

app/models/search/bookmark_indexer.rb, app/models/search/bookmarkable_indexer.rb, app/models/search/bookmarkable_query.rb
https://otwarchive.atlassian.net/browse/AO3-6291
Refer to the issue's comments.
Unsure if I implemented suggestion correctly, as I am unable to reproduce the original failure and not sure of the setup.
Not sure if the "id - keyword" field simply can be renamed or if I should keep id with type "long" there as well.
Locally with dev data from testing I now had the opposite problem from reported - re-indexing bookmarks jobs failed because id was not found, so got error on fandom/bookmarks pages. Had to run indexing job to fix.
Not sure if same could happen on staging if it was possible to create new bookmarks, or if failing re-indexing job was …
=> AO3-6291 Rename bookmarkable id indexing field

Gemfile, Gemfile.lock, app/controllers/admin_posts_controller.rb, app/controllers/chapters_controller.rb, app/controllers/comments_controller.rb, app/decorators/comment_decorator.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/models/user.rb, app/views/comments/_comment_form.html.erb, app/views/comments/_comment_thread.html.erb, app/views/comments/_commentable.html.erb, config/environments/development.rb, spec/controllers/chapters_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/requests/comments_n_plus_one_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6333
When displaying a bunch of comments, try to avoid any database queries involving single comments. This should avoid the n+1 queries problem, where we load n comments in a single query, then perform 1 query for each of the n comments.
In particular, the actions that we address this for are:
- `CommentsController#show`
- `CommentsController#index`
- `CommentsController#unreviewed`
- `CommentsController#show_comments`
Because `CommentsController#index` uses the `comments/commentable` view, this should also reduce the number of comment-related queries in the actions that use that view:
- `WorksController#show` with the `show_comments` param
- `ChaptersController#show` with the `show_comments` param
- `AdminPostsController#show` with the …
=> AO3-6333 Try to reduce database queries when viewing comments.

app/policies/comment_policy.rb, app/policies/user_creation_policy.rb, app/views/comments/_single_comment.html.erb, app/views/works/_meta.html.erb, features/comments_and_kudos/add_comment.feature, features/comments_and_kudos/admin_info.feature, features/importing/work_import.feature, features/step_definitions/comment_steps.rb, public/stylesheets/site/2.0/24-role-admin.css
https://otwarchive.atlassian.net/browse/AO3-6148
1. Restrict the display of the IP addresses on works and comments so that only Superadmins and Policy & Abuse can see them.
2. Add a line displaying the email address of guest comments to Superadmins, Policy & Abuse, and Support.
See JIRA.
=> AO3-6148 Limit admin roles that can see IPs on works/comments, and show email for guest comments.

app/controllers/admin/banners_controller.rb, app/policies/admin_banner_policy.rb, app/policies/application_policy.rb, app/views/admin/_header.html.erb, factories/admin_banner.rb, features/other_a/banner_general.feature, features/step_definitions/banner_steps.rb, spec/controllers/admin/banners_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6342
Add a new policy class for `AdminBanner`s, with all permissions set to allow only four admin roles: superadmin, support, communications, and board. Also modifies the controller to call `authorize` for each action, and hides the "Banner" link for other admins.
=> AO3-6342 Limit ability to list, create, update, and destroy admin banners.

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb, test/fixtures/comments.yml
https://otwarchive.atlassian.net/browse/AO3-6351
Add a rake task `rake After:fix_2009_comment_threads` to fix comment threads, add some specs to confirm that it works the way it's supposed to, and modify the `test/fixtures/comments.yml` file to fix the seed data.
=> AO3-6351 Fix comment threads from 2009.

app/controllers/blocked/users_controller.rb, app/validators/not_blocked_validator.rb, app/views/blocked/users/_blocked_user_blurb.html.erb, features/step_definitions/comment_steps.rb, lib/acts_as_commentable/comment_methods.rb
https://otwarchive.atlassian.net/browse/AO3-6327
Minor fixes for comment blocking, as suggested in the post-merge review on #4237:
- a few tweaked comments
- order blocks by both `created_at` and `id`, instead of just `id`
- remove the unused info from the error added by `NotBlockedValidator`
- remove an unnecessary lazy quantifier
- change the title of the Blocked Users page
=> AO3-6327 Assorted fixes for the comment blocking code.

app/helpers/block_helper.rb, app/models/comment.rb, app/views/blocked/users/confirm_block.html.erb, app/views/blocked/users/confirm_unblock.html.erb, config/locales/views/en.yml, features/support/paths.rb, features/users/blocking.feature
https://otwarchive.atlassian.net/browse/AO3-6327
- Fix the 500 error that occurs when admins try to view a user's Blocked Users page.
- Add a Cancel button to the Confirm Block page and the Confirm Unblock page.
=> AO3-6327 Fix admin view of Blocked Users page, and add a Cancel button to the Confirm Block/Unblock pages.

app/controllers/blocked/users_controller.rb, app/views/blocked/users/confirm_block.html.erb, app/views/blocked/users/index.html.erb, config/locales/views/en.yml, spec/controllers/blocked/users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6327
- Handle when `blocked_id` is unspecified, so that users don't get a 500 error when they delete the `?blocked_id=NAME` section of the URL and go straight to `/users/NAME/blocked/users/confirm_block`.
- Add an extra bullet point to the "Blocking a user will not:" section of the description of blocking, to make it clearer to users that blocking a user will not hide their works/bookmarks.
=> AO3-6327 Handle nil blocked_id, and add a little extra information to the description of blocking.

app/views/blocked/users/confirm_block.html.erb, app/views/blocked/users/index.html.erb, app/views/collection_participants/_add_participants_form.html.erb, public/stylesheets/site/2.0/07-interactions.css, public/stylesheets/site/2.0/25-media-midsize.css
https://otwarchive.atlassian.net/browse/AO3-4659
* Makes the form prettier on smaller screens, e.g. tablets and phones -- the button and the text input were overlapping a bit because the min-width on the text input was too big for the space, so I've put them on separate lines to give the text input enough room.
* Reorders the bullet points on the block user form because we wanted the bit about not hiding works to be at the top.
On a phone or a tablet in portrait mode (or a browser with the font size cranked up and the window width narrowed), check the collection participant and blocked users pages and make sure the forms are decent looking and functional.
Also check the order of the bullet points on the block user form; the one about hiding works should be at the top.
=> AO3-4659 Tweaks to block user and collection participant forms

config/application.rb, spec/requests/security_headers_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6352
This PR adds a `Content-Security-Policy: frame-ancestors 'self'` header to the default response headers. I've also added a corresponding unit test.
There's a unit test in `spec/requests/security_headers_spec.rb`. The functionality can also be tested manually by opening the root page in a web browser, opening the developer tools and verifying that the `Content-Security-Policy` response header has been set.
printfn, they/them
=> AO3-6352 Add default Content-Security-Policy response header

app/views/series/_series_module.html.erb, app/views/series/show.html.erb, features/other_b/series.feature
https://otwarchive.atlassian.net/browse/AO3-5780
This uses `number_with_delimiter` to display bookmark counts on the series page or on the series bookmarks page with delimiters if they have more than 3 digits.
Note: it was unclear to me whether this issue also referred to number of works in a series, so I left that alone, but I can add that in if it should be included!
If you just want to see that the bookmark number still exists after this change, you can
1. create or find a work in a series
2. go to the series page
3. bookmark the series
a. verify that after "bookmarks:" there's a 1 that's a link
4. go back to the series page
a. verify that …
=> AO3-5780 Add thousands separators to long numbers on series pages

app/models/download.rb, spec/models/download_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5709
The pseud byline includes the user name when it's different from the pseud name, so we use the byline instead of the name for generating the `author_names`.
I've also added a bunch of specs for previously unspecced methods, so we can see what knock-on effects changing the way we generate `author_names` will have.
In addition to the metadata generator, `author_names` is also used to generate the `page_title` as `file_authors`, so it needs to be "filesystem safe" and on the short side.
Getting truncated at 24 characters could make one creator with a parenthetical name push all the others out of the listing. OTOH this can already happen with a pseud that's the same as the user name, so I guess we're not making it much …
=> AO3-5709 Use pseud byline for download authors

app/views/pseuds/delete_preview.html.erb
https://otwarchive.atlassian.net/browse/AO3-6159 
This PR corrects the text that's displayed when previewing the deletion of a pseud.
The instructions on the Jira issue should be enough.
Nothing to add.
C.M. Carreiro, she/they pronouns
=> AO3-6159 Corrected pseud deletion preview text

spec/models/download_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5709
#3609 predates #3615, so it's factory_bot now. Download specs are currently broken.
None.
=> AO3-5709 Remove factory_girl references from download specs

app/controllers/chapters_controller.rb, app/models/work.rb, app/views/chapters/manage.html.erb, features/works/chapter_edit.feature, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3846
Makes it so that draft chapters are displayed on the chapter rearranging page rather than excluded. This allows them to be rearranged in the same way as other chapters.
1. Create a multi-chapter work.
2. Add a draft chapter to the work.
3. Visit the work's Edit page.
4. Visit "Manage Chapters".
5. Verify that the draft chapter appears on the page.
6. Move draft chapter and save.
7. Verify that draft chapter number was updated.
Stephen Lewis
he/him
=> AO3-3846 Make draft chapters display on chapter rearrange page

.gitignore, script/docker/init.sh
* No, but not applicable
https://otwarchive.atlassian.net/browse/AO3-6358
Make installing docker easier if the installation script fails the first time.
No tests needed.
Bug created in response to struggles mentioned in #4254
irrationalpie, they/them
=> AO3-6358 Overwrite local configuration files in Docker init.sh

app/views/comments/_single_comment.html.erb, features/comments_and_kudos/add_comment.feature, features/comments_and_kudos/comment_moderation.feature, features/tags_and_wrangling/tag_comment.feature, features/users/user_rename.feature
https://otwarchive.atlassian.net/browse/AO3-6335
Fix the arguments to `cache` in `comments/single_comment`. I also switched to a simpler cache key, because we now have better tools to handle the intermittent test failures that `edited_at` was added to prevent.
=> AO3-6335 Fix comment cache expiration.

app/views/user_mailer/creatorship_notification.html.erb, app/views/user_mailer/creatorship_notification.text.erb, app/views/user_mailer/creatorship_notification_archivist.html.erb, app/views/user_mailer/creatorship_notification_archivist.text.erb, app/views/user_mailer/creatorship_request.html.erb, app/views/user_mailer/creatorship_request.text.erb
https://otwarchive.atlassian.net/browse/AO3-6307
* Remove unused variables from creatorship request emails.
* Use `@creation.class.name.downcase` instead of `@creation.model_name.human.downcase` for key names -- the latter will get the translated model name in the email locale, which will result in nonexistent keys like `.intro_capitulo` or `intro_obra` instead of `.intro_chapter` and `.intro_work`. 
Refer to Jira.
=> AO3-6307 Don't translate key names in creatorship emails

Gemfile, Gemfile.lock, app/mailers/user_mailer.rb, app/models/creatorship.rb, config/environments/development.rb, config/environments/staging.rb, config/initializers/monkeypatches/mailers_controller.rb, features/support/factories.rb, spec/spec_helper.rb, test/mailers/previews/application_mailer_preview.rb, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6307
Enable mailer previews in development and staging.
- Patch the preview UI to [hide the ribbon dev mark](https://github.com/dtaniwaki/rack-dev-mark#temporarily-disable-the-dev-mark).
- To make the previews' locale selector work, move the `I18n.with_locale` block outside the mailer methods.
- Wrap the previews in a transaction and roll back to avoid saving preview data to the database.
- Use factory_bot to generate preview data.
Simplify factory_bot setup.
- In development and test, include factory_bot_rails which automatically finds and loads definitions.
- In staging, install only factory_bot without loading it by default, because we don't want it used outside mailer previews where we explicitly require it.
The preview UI should be at …
=> AO3-6307 Add mailer previews for creatorship notifications

test/mailers/previews/application_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6307
We don't use factory_bot_rails in staging to avoid always loading factories, so we need to require factory_bot and manually load factory definitions instead.
The preview UI should be at https://test.archiveofourown.org/rails/mailers.
=> AO3-6307 Fix factory_bot loading for mailer previews

Gemfile
https://otwarchive.atlassian.net/browse/AO3-6307
We're missing the faker gem in staging.
I found a way to test this locally. By default `bundle install` will add every gem regardless of which group it's in. I used `bundle install --without development test production` in the Dockerfile to get only the staging set to reproduce the 500 error in mailer previews and verify the fix.
https://test.archiveofourown.org/rails/mailers loads.
=> AO3-6307 Fix faker loading for mailer previews

app/controllers/users/passwords_controller.rb, app/models/user.rb, features/step_definitions/user_steps.rb, features/users/authenticate_users.feature, lib/tasks/defaults.rake, spec/lib/tasks/defaults.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6371
Maims the English language in service of creating a user role that _only_ prevents password resets, not other forms of harassment.
Refer to Jira.
=> AO3-6371 Add no resets role

app/models/work.rb, features/works/work_related.feature
https://otwarchive.atlassian.net/browse/AO3-6144
Update the error text message to 
> You can't use the related works function to cite works by the protected user [name].
Main PR: https://github.com/otwcode/otwarchive/pull/4244 
=> AO3-6144 Update error text when citing a protected user's works

app/controllers/works_controller.rb, app/helpers/works_helper.rb, app/models/external_work.rb, app/models/related_work.rb, app/models/work.rb, app/views/works/_hidden_fields.html.erb, app/views/works/_standard_form.html.erb, app/views/works/_work_header_notes.html.erb, config/locales/models/en.yml, features/step_definitions/work_related_steps.rb, features/step_definitions/work_steps.rb, features/works/work_related.feature, lib/creation_notifier.rb
https://otwarchive.atlassian.net/browse/AO3-6379
Switches the related works code to use `accepts_nested_attributes_for` instead of a custom-built `parent_attributes=` function.
=> AO3-6379 Use accepts_nested_attributes_for for related works.

config/initializers/rack_attack.rb, spec/requests/rack_attack_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6344
Add "Retry-After" response header to "too many requests" responses so that polite clients know how long to back off for
- Change RATE_LIMIT_NUMBER in config.yml to 1 and navigate to the root page with the network tab open
- Refresh the page, you should see "Retry later"
- Check the response headers in the network tab to ensure that "Retry-After" is present
Name: nianeyna
Jira name: Nia Neyna
Pronouns: she/her
=> AO3-6344 Add retry-after header when rate limited

app/models/search/bookmarked_work_indexer.rb, app/models/search/indexer.rb, app/models/search/work_creator_indexer.rb, app/models/search/work_indexer.rb, app/models/work.rb, spec/models/search/bookmarked_work_indexer_spec.rb, spec/models/search/work_creator_indexer_spec.rb, spec/models/search/work_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6349
This PR uses `includes()` to try to reduce the number of database queries performed when reindexing works, in an attempt to make reindexing faster. On my machine this makes reindexing works 3-5x faster, but your mileage may vary.
=> AO3-6349 When reindexing works, try to perform fewer database queries.

app/mailers/comment_mailer.rb, features/comments_and_kudos/add_comment.feature
https://otwarchive.atlassian.net/browse/AO3-6311
Do not send a edited comment reply notification to creator of deleted comment
Follow instructions on JIRA.
EchoEkhi (He/Him/{/([A-Z][a-z]*)/g})
=> AO3-6311 Edited comment reply notification sent to creator of deleted comment

app/views/user_mailer/invite_increase_notification.html.erb, app/views/user_mailer/invite_increase_notification.text.erb, config/locales/mailers/en.yml, spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6280 
Fix inconsistent text in new invitations email, update some variable names to comply with i18n standards, add unit tests to check the updated new invitations email text 
How can the Archive's QA team verify that this is working as you intended
Run updated unit tests to verify that the invitations email text has been updated 
What name and pronouns should we use to credit you …
=> AO3-6280 Fix inconsistent text in new invitations email

app/models/user.rb, spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6370
Make the User email validation case insensitive. 
Same as written in Jira issue: 
1. Have an existing account with an email address, say `test@example.com`.
2. Get an invitation (or get a site admin to enable sign-ups without invitations).
3. Try to sign up for an account with the same email as your old account, but with a different case, like `TEST@example.com`, or `Test@example.com`.
Now it should redirect back to signup form with the error "Email has already been taken"
N/A
ellieyhc (she/her)
=> AO3-6370 Case insensitive email validation for User

.github/workflows/automated-tests.yml, features/step_definitions/work_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6384
The scenario "The user dashboard should list up to five of the user's works" of file `features/user/user_dashboard.feature` fails intermittently due to the works not necessarily always being created/indexed in the same order.
For example, "Work 2" can end up "older" than "Oldest Work", and thus the test fails because it expects "Oldest Work" to be out due to being too old.
This is an attempt at fixing that.
Run `docker-compose exec -e RAILS_ENV=test web bundle exec cucumber features/users/user_dashboard.feature:55` X times on master, and, for a value of X great enough, it should fail from time to time.
Do the same on this branch, and it should pass every time.
Note: Yes, it's quite possible the PR does nothing and this is just dumb luck. No …
=> AO3-6384 Fix intermittent user_dashboard test failures

app/models/user.rb, spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6361
Fix the text in the log when an admin changes a user's email.
See Jira ticket (note that the steps will need to be followed again, as any existing logs will have the old text).
Follow-up to #4302
What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)? **Brian Austin (they/he)**
=> AO3-6361 Fix admin email change text

features/step_definitions/autocomplete_steps.rb, features/step_definitions/external_work_steps.rb, spec/controllers/external_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6389
- Use example.org instead of dreamwidth.org in external work tests.
- Use `WebMock` to stub the URLs to prevent connection errors.
Make sure the automated tests pass.
=> AO3-6389 Stop using Dreamwidth URLs in external work tests.

app/views/stats/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-5779
Add thousands separator to long numbers on statistics page
Not sure here. In #4254 no automated tests were necessary except to see if the page loads at all. A "page loads at all" test already exists in `features/other_b/stats.features` and passes.
For manual testing, log into a user with a work with a word count > 1000, go to the stats page and verify that the thousand separator shows up.
I mostly referenced #4254 for what I should do.
Bilka (he/him)
=> AO3-5779 Add thousands separator to long numbers on statistics page

app/views/chapters/_chapter.html.erb
https://otwarchive.atlassian.net/browse/AO3-5719
When using "Entire Work", clicking on the link to chapter endnotes will navigate to the endnotes on the same entire work page, and not the chapter page.
See Jira issue. I didn't think adding an automated test was necessary, but I could add one if needed.
=> AO3-5719 Generate links to end notes without path

app/controllers/external_works_controller.rb, app/views/external_works/_blurb.html.erb, app/views/external_works/_work_module.html.erb, app/views/external_works/edit.html.erb, features/admins/admin_works.feature
https://otwarchive.atlassian.net/browse/AO3-2426
External works have language ID which can only be assigned when creating it. This set of changes will add UI elements to allow admins to change the language ID of an external work.
See the Jira issue.
#197
=> AO3-2426 Allow admin to change the language of an external work

app/controllers/users_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5677
https://otwarchive.atlassian.net/browse/AO3-6041
The `UsersController` is no longer used for creating `User` objects, so we can clean up some unused code.
=> AO3-5677 AO3-6041 Remove unused methods & rescue block from the UsersController.

app/controllers/autocomplete_controller.rb
https://otwarchive.atlassian.net/browse/AO3-6201
Removes 3 unused actions from AutocompleteController
* challenge_participants
* nominated_parents
* tag_in_fandom
=> AO3-6201 Remove unused actions from the AutocompleteController

app/controllers/admin/activities_controller.rb, app/policies/admin_activity_policy.rb, app/views/admin/_header.html.erb, spec/controllers/admin/activities_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6380
Limit access to `Admin::ActivitiesController` to admins with the roles `policy_and_abuse` and `superadmin`.
=> AO3-6380 Restrict access to the Admin Activities page to Policy & Abuse and Superadmins.

features/other_a/gift.feature, features/step_definitions/gift_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6398
- Fix the flaky test for re-accepting a refused gift.
- Re-enable one of the checks in that test, with an extra delay to make sure that it works consistently.
- Fix an additional flaky test in the same file that I discovered while testing.
I ran the test 40 times with no failures (and no flaky tests, either) here: https://github.com/tickinginstant/otwarchive/actions/runs/3064516500
=> AO3-6398 Try to fix flaky tests in features/other_a/gift.feature.

features/works/work_create.feature
https://otwarchive.atlassian.net/browse/AO3-6397
- Fix the flaky scenario "Inviting a co-author adds the co-author to all existing chapters when they accept the invite."
I ran features/works/work_create.feature 40 times in this run, with no failures or flaky tests: https://github.com/tickinginstant/otwarchive/actions/runs/3064732702/jobs/4948123437
=> AO3-6397 Try to fix flaky co-creator test in features/works/work_create.feature.

features/step_definitions/skin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6400
- Adds a simulated delay at the start of the "unapproved public skin" step, to try to prevent two public skins from being created during the same second and ending up sorted in the wrong order on the admin skin page.
I ran the features/admins/admin_skins.feature tests 40 times with no failures or flaky tests in this run: https://github.com/tickinginstant/otwarchive/actions/runs/3065242802/jobs/4949148966
=> AO3-6400 Try to fix the flaky test in features/admins/admin_skins.feature.

features/comments_and_kudos/hidden_comments.feature
https://otwarchive.atlassian.net/browse/AO3-6399
Add an extra delay before hiding the comment, so that the cache is expired when the comment is hidden.
No manual QA necessary. I ran the features/comments_and_kudos/hidden_comments.feature tests [50x](https://github.com/tickinginstant/otwarchive/actions/runs/3074547348/attempts/1) (and then [retried the test once](https://github.com/tickinginstant/otwarchive/actions/runs/3074547348) for good measure), and got no failures or flaky tests.
=> AO3-6399 Try to fix the flaky test in features/comments_and_kudos/hidden_comments.feature.

config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6160
Updates the text on the delete pseud page when the pseud you're deleting only has one bookmark.
Refer to Jira.
=> AO3-6160 Fix grammatical error on delete pseud page

features/prompt_memes_c/challenge_promptmeme_claims.feature
https://otwarchive.atlassian.net/browse/AO3-6403
There's a prompt meme test that assumes that September 20, 2022 is in the future. That's no longer true, so the test is failing. This PR uses time travel to make the test work again.
No QA required as long as this passes the automated tests.
=> AO3-6403 Fix prompt meme date test.

app/jobs/application_job.rb, app/jobs/instance_method_job.rb, app/jobs/tag_method_job.rb, app/models/concerns/async_with_active_job.rb, app/models/tag.rb, spec/models/tag_wrangling_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6356
- Create a new `InstanceMethodJob` class used to run instance methods on objects.
- Create a new `TagMethodJob` subclass that retries on `RecordNotUnique`.
- Create a new `AsyncWithActiveJob` concern that can be swapped in for the `AsyncWithResque` concern, as long as the class in question only uses instance methods for delayed jobs.
- Set up `Tag`s to use `AsyncWithActiveJob` and `TagMethodJob` to run wrangling tasks instead of `AsyncWithResque`.
=> AO3-6356 Use ActiveJob for asynchronous tag jobs.

.github/dependabot.yml
https://otwarchive.atlassian.net/browse/AO3-6410
Enable dependabot to submit PRs to update workflow actions to the latest version.
Most of this file is copied from https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions, but I also added a [labels](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels) parameter to try to get dependabot to submit the PRs for this with the right label.
=> AO3-6410 Let dependabot update workflow actions.

features/works/chapter_edit.feature
https://otwarchive.atlassian.net/browse/AO3-6406
Add a simulated delay to one of the chapter co-creator tests, so that the cache is expired when the co-creator request is accepted and we don't get an intermittent failure.
No manual QA required. I ran the test 50x [here](https://github.com/tickinginstant/otwarchive/actions/runs/3305268321), with no failures or flaky steps.
=> AO3-6406 Fix flaky chapter co-creator test.

app/models/work.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5628
Ensures that work chapter counts get properly updated when a draft chapter is added, which is important to ensuring that the "manage chapters" button shows up if there are two chapters and one is draft.
On Jira issue
Stephen Lewis, he/him
=> AO3-5628 Invalidate chapter count cache when saving drafts

app/helpers/mailer_helper.rb, config/locales/mailers/en.yml, config/locales/phrase-exports/zh-CN.yml, spec/helpers/mailer_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6290
Translate "Chapter # of [title]" in co-creation emails.
=> AO3-6290 "Chapter # of [title]" in co-creation emails is not translatable

app/helpers/search_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5781
Add thousand separator to search result totals and filterable indexes.
See Jira. (No automated tests needed as per previous delimiter related PRs.)
I added the thousand separator to all numbers in the heading of the index pages. Example for the works index:
Bilka (he/him)
=> AO3-5781 Add delimiter to search result totals and filterable indexes

config/initializers/gem-plugin_config/sanitizer_config.rb, lib/html_cleaner.rb, public/help/html-help.html, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5934
The purpose here is to add `<figure> `and `<figcaption>` into the set of allowed HTML tags. These tags are used to show pictures with captions (and more complex content).
For the expected behavior, see the Jira issue. Some of the aspects of the feature as written in the Jira issue are not satisfied exactly in this implementation (at least in its initial version), though.
- If a user tries to wrap `<figure>` with a `<p>`, they can't. It will result in 2 emtpty `<p>`s, one before `<figure>`, another after it. This may not be ideal, but I don't believe we can do much better. Ultimately, most browsers …
=> AO3-5934 Allow <figure> and <figcaption> HTML tags

app/controllers/challenge_signups_controller.rb, app/controllers/prompts_controller.rb, app/models/prompt.rb, app/views/prompts/_prompt_form.html.erb, factories/challenges.rb, factories/prompt.rb, spec/controllers/challenge_signups_controller_spec.rb, spec/controllers/prompts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6419
- Removes some permitted params in the `PromptsController` and `ChallengeSignupsController` that probably shouldn't be there.
- Adds an extra callback to the prompt class to make sure that it sets its collection from the signup.
- Cleans up some of the challenge-related factories.
=> AO3-6419 Clean up params for the PromptsController and ChallengeSignupsController.

.github/dependabot.yml, .github/workflows/automated-tests.yml
https://otwarchive.atlassian.net/browse/AO3-6410
- Restores the `.github/dependabot.yml` file originally created in https://github.com/otwcode/otwarchive/pull/4359 and then removed again in https://github.com/otwcode/otwarchive/pull/4368. We had to remove it because it was submitting PRs to all forks with no way to disable it, but [that behavior has since been fixed](https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/).
- Changes the `actions/cache` version number to be `v3` instead of `v3.0.11`. In Github Actions, the convention is to have the major version numbers like `v3` be updated every time a minor `v3.x.y` version is released. This means that by setting your version number to a major version, you automatically get rolling updates, and don't …
=> AO3-6410 Re-enable dependabot for Github Actions workflow updates.

.github/dependabot.yml
https://otwarchive.atlassian.net/browse/AO3-6424
Configure labels for all Dependabot gem update pull requests. [Disable normal version updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file) so this applies only to security updates.
None, until the next Dependabot pull request.
I'll delete the "Dependencies" and "ruby" labels when this is merged.
=> AO3-6424 Override Dependabot labels for gem updates

public/robots.public.txt
https://otwarchive.atlassian.net/browse/AO3-6436
Prevents CCBot from crawling the archive.
Refer to Jira.
=> AO3-6436 Disallow Common Crawl bot

app/views/tags/index.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6408
This PR attempts to fix the issue as described, changing `These are some of the most popular tags used on the Archive.` to `These are some of the most popular tags used in the collection.` on collection tag pages.
I don't have a Jira account with access, but I do have a Jira account on your Jira! You should be able to check localhost:3000/tags and see it has the original text, and go to localhost:3000/collections/TheFirstCollection/tags and see the new text.
No other references as far as I am aware of.
Camila Noceda (she/her)
Hello, hopefully I have formatted this right, please suggest any changes …
=> AO3-6408 Show different text for tag cloud on collections

app/controllers/series_controller.rb, features/other_b/errors.feature, spec/controllers/series_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5535
Remove series index, so accessing `/series` redirects to the homepage and gives a red flash error that asks, "Whose series did you want to see?"
As visible in the tests, trying to access the series of a user that does not exist like `/users/invalid_user/series` also redirects.
Previously, this page would throw a `ActiveRecord::RecordNotFound` error and 404. The behaviour I implemented here mirrors that of gift_controller, which also redirects for an invalid user name.
Trying to access the series of an invalid pseud (`users/valid_user/pseuds/invalid_pseud/series`) does not redirect. I left it with …
=> AO3-5535 Remove series index

app/controllers/gifts_controller.rb, features/other_a/gift.feature, spec/controllers/gifts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6417
With this PR, accessing the gifts page for a nonexistent user gives an error 404 instead of redirecting to the homepage.
Bilka (he/him)
=> AO3-6417 Make gifts page for nonexistent user 404

app/controllers/tag_wranglers_controller.rb, spec/controllers/tag_wranglers_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6224
Raise a 404 error rather than a 500 when accessing the wrangler page for a non-existent user.
See the Jira ticket's description. (Note: to test this locally, I had to flip https://github.com/otwcode/otwarchive/blob/master/config/environments/development.rb#L19)
**Brian Austin (they/he)**
=> AO3-6224 Return a 404 when wrangler is not found

app/models/log_item.rb, config/config.yml, lib/tasks/resanitize.rake
https://otwarchive.atlassian.net/browse/AO3-6421
The "note" field is actually [passed into controllers as "admin_note"](https://github.com/otwcode/otwarchive/blob/ecf05285ed2a5c654d6b447604e214ff02036e49/app/models/user_manager.rb#L16). "note" is in `FIELDS_ALLOWING_HTML` and the field gets paragraph tags when resanitized by the new task, but "admin_note" is not and always has any HTML tags stripped out.
Since the field has never really allowed HTML, we will remove "note" from `FIELDS_ALLOWING_HTML`, disable the "note_sanitizer_version" column, and remove LogItem from the resanitize task.
As an admin, update the roles of a user and check that new entries in "History of User Actions" don't have escaped paragraph tags.
For existing entries on staging that gained paragraph tags when we last …
=> AO3-6421 Skip resanitizing LogItem records

config/docker/Dockerfile
https://otwarchive.atlassian.net/browse/AO3-6409
ruby:2.7.3 is based on Debian Buster, but ruby:3.0.5 is based on Debian Bullseye, which has no installation candidate for phantomjs. For now, we'll pin the Debian release. From https://hub.docker.com/_/ruby:
> Some of these tags may have names like bullseye or buster in them. These are the suite code names for releases of [Debian](https://wiki.debian.org/DebianReleases) and indicate which release the image is based on. If your image needs to install any additional packages beyond what comes with the image, you'll likely want to specify one of these explicitly to minimize breakage when there are new releases of Debian.
Also use a newer bundler version for Docker to match Gemfile.lock.
None. I ran tests locally fine:
```sh
docker-compose up …
```
=> AO3-6409 Use ruby:3.0.5-buster image for development

config/initializers/monkeypatches/akismetor.rb
https://otwarchive.atlassian.net/browse/AO3-6453
The library uses the [removed method `URI.escape`](https://github.com/ruby/uri/issues/14).
See issue.
=> AO3-6453 Monkey patch Akismetor for Ruby 3

app/models/redis_hit_counter.rb
https://otwarchive.atlassian.net/browse/AO3-6452
Adds a call to `sort` in the hit counter code, so that stat counters will always be locked in a consistent order. This should prevent issues that arise when one worker has a lock on stat counter 1 and wants a lock on stat counter 2, while another worker has a lock on stat counter 2 and wants a lock on stat counter 1.
=> AO3-6452 Sort to reduce deadlocks in the hit count code.

config/initializers/active_record_schema_ignore_tables.rb, db/migrate/20230113225105_add_primary_key_to_roles_users.rb, db/migrate/20230113225128_add_primary_key_to_schema_migrations.rb
https://otwarchive.atlassian.net/browse/AO3-6456
https://otwarchive.atlassian.net/browse/AO3-6438
Add missing primary keys to:
- `roles_users` (no primary keys in any environment)
https://github.com/otwcode/otwarchive/blob/17384eb5024f0658c3f307b451096e2d2301b7ba/db/schema.rb#L985
- `schema_migrations` (no primary keys but only in staging/production; Rails [sets column "version" as the primary key](https://github.com/rails/rails/blob/c7b76db7784151c4b47c22e5b234fb2b4c16021f/activerecord/lib/active_record/schema_migration.rb#L38-L40) these days)
Also exclude [`innodb_monitor`](https://mariadb.com/kb/en/xtradb-innodb-monitors/) from schema.rb dumps.
Migrate up/down/up on staging.
=> AO3-6456 AO3-6438 Add missing primary keys and exclude innodb_monitor from schema dumps 

.rubocop.yml, app/jobs/readings_to_database_job.rb, app/jobs/redis_set_job.rb, app/jobs/redis_set_job_spawner.rb, app/jobs/stat_counter_job.rb, app/models/stat_counter.rb, config/config.yml, config/resque_schedule.yml, features/step_definitions/work_steps.rb, lib/redis_scanning.rb
https://otwarchive.atlassian.net/browse/AO3-6457
1. Introduce a library to make it easier to scan through redis sets in batches, and modify the existing `ReadingsToDatabaseJob` to use it.
2. Create a new abstract job class `RedisSetJob` with a linked job `RedisSetJobSpawner` that's designed around breaking Redis sets down into smaller batches, and then running one job per batch. This new system should be easy to extend to [tag counts](https://github.com/otwcode/otwarchive/commit/1556ede32fc7f2e1e97394e8d51ab0e677b8454f) and [readings](https://github.com/otwcode/otwarchive/commit/8691fea11e5dc1f1f5409693f16c213a1414fa14).
3. Create a `StatCounterJob` class extending the `RedisSetJob` class that calls `update_stat_counter` for all works with IDs in the `works_to_update_stats` set.
=> AO3-6457 Improve the scalability of the StatCounter job.

app/jobs/readings_job.rb, app/models/reading.rb, app/models/user.rb, config/config.yml, config/resque_schedule.yml, config/schedule.rb, features/other_a/reading.feature, features/step_definitions/reading_steps.rb, features/step_definitions/work_steps.rb, lib/tasks/reading_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-6459
Modify the readings code to use `RedisSetJob` and `RedisSetJobSpawner`, introduced in #4433, to try to get the reading job to recover better when it encounters errors.
=> AO3-6459 Use new batch code for readings to try to address LockWaitTimeout errors.

app/jobs/tag_count_update_job.rb, app/models/scheduled_tag_job.rb, app/models/tag.rb, config/config.yml, config/resque_schedule.yml, features/step_definitions/series_steps.rb, features/step_definitions/tag_steps.rb, features/step_definitions/work_steps.rb, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6458
Use the new `RedisSetJob` and `RedisSetJobSpawner`, introduced in #4433, to handle taggings count updates. Retries the job on deadlocks and on lock wait timeouts, so that hopefully the jobs will run more consistently.
=> AO3-6458 Use new batch code for tag count updates to try to address LockWaitTimeout errors.

lib/redis_scanning.rb
https://otwarchive.atlassian.net/browse/AO3-6462
Make the `scan_set_in_batches` method use `each_slice` to make sure that the batch sizes are more consistent. This should (hopefully) make the transaction sizes more consistent when processing readings.
=> AO3-6462 Make scan_set_in_batches return more consistent batch sizes.

.github/dependabot.yml
https://otwarchive.atlassian.net/browse/AO3-6472
In security updates like #4442, don't bump indirect dependencies like mini_portile2 and racc.
Comment `@dependabot recreate` on #4442 after this is merged.
=> AO3-6472 Skip indirect gem dependency updates

.github/dependabot.yml
https://otwarchive.atlassian.net/browse/AO3-6472
Reverts otwcode/otwarchive#4444. Recreating #4442 didn't remove the indirect dependency bumps as expected.
=> AO3-6472 Revert "Skip indirect gem dependency updates"

app/views/muted/users/confirm_mute.html.erb, app/views/muted/users/index.html.erb, config/locales/models/en.yml, config/locales/views/en.yml, features/users/blocking.feature, features/users/muting.feature
https://otwarchive.atlassian.net/browse/AO3-6365
Add a missing Oxford comma and change "official account" to "official user" because we realized we generally prefer "user" to "account."
- Try to both block and mute an official user and confirm the message says "user" and not "account"
- Mute someone, and then unmute them and make sure the confirmation page says "see their works, series, bookmarks, and comments on the site"
- Check the FAQ link on your muted users page and the mute confirmation page and ensure it is relative
=> AO3-6365 Text tweaks for muting and blocking

app/models/admin.rb, app/views/admin/mailer/reset_password_instructions.html.erb, app/views/admin/mailer/reset_password_instructions.text.erb, app/views/admin_mailer/set_password_notification.html.erb, app/views/admin_mailer/set_password_notification.text.erb, config/config.yml, config/locales/mailers/en.yml, features/admins/authenticate_admins.feature, features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6440
- Add a separate `ArchiveConfig.DAYS_UNTIL_ADMIN_RESET_PASSWORD_LINK_EXPIRES` variable for configuring how long admin password reset tokens are valid.
- Update both admin creation and admin password reset emails to mention the new value.
- Also update the admin creation email to say what to do if the set password link doesn't work.
- Create a new admin account for an email you have access to; ensure the email says the link is good for 5 days and the text is otherwise clear. Then delete said account.
- Request a password reset and ensure the email says the link is good for 5 days.
- Ideally wait 5 days to confirm the reset expires then and not in 7 days, but I think we're going to deploy before then, so we can double check on production. …
=> AO3-6440 Configure admin and user reset token expiry separately

config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6365
Update muted users limit to match blocked users limit.
=> AO3-6365 Update muted users limit

app/controllers/admin/passwords_controller.rb, app/controllers/users/passwords_controller.rb, app/models/admin.rb, features/admins/authenticate_admins.feature, features/support/paths.rb, features/users/authenticate_users.feature
https://otwarchive.atlassian.net/browse/AO3-6440
If you're logged in as an admin and try to access the new or edit user password pages, redirect to homepage with reminder to log out.
If you're logged in as a user and try to access the new or edit admin password pages, redirect to homepage with reminder to log out.
Log in as an admin and try to go to /users/password/new and /users/password/edit. You should be redirected with a friendly blue log out reminder.
Log in as a user and try to go to /admin/password/new and /admin/password/edit. You should be redirected with a friendly blue log out reminder.
=> AO3-6440 Restrict access to password reset pages

public/javascripts/livevalidation_standalone.js
https://otwarchive.atlassian.net/browse/AO3-6183
- Ensure span that holds the error message is included in the DOM on load and has role="alert" set. 
- Do not remove error message when invalid field is in focus. 
- Use aria-invalid and aria-describedby to associate the invalid field with the error span. 
See Jira issue. I've added an additional testing instruction in a comment.
Related open issue: https://otwarchive.atlassian.net/browse/AO3-3585
=> AO3-6183 Make live validation errors screen readable

app/controllers/bookmarks_controller.rb, app/controllers/works_controller.rb, app/decorators/bookmarkable_decorator.rb, app/decorators/pseud_decorator.rb, app/models/bookmark.rb, app/models/external_work.rb, app/models/search/query_result.rb, app/models/series.rb, app/models/work.rb, lib/searchable.rb, spec/requests/works_n_plus_one_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6475
Add a `scope()` function to the `QueryResult` class that lets you add scopes that you want to use when retrieving records from the database. This is passed as an optional `scopes:` argument to the `load_from_elasticsearch` function, and applied to the `ActiveRecord` relation before loading.
Also changes the `WorksController` and the `BookmarksController` to use the `for_blurb` scope for works, bookmarks, series, and external works.
Works are heavily cached, so by default we only call `includes(:pseuds)` for the work's `for_blurb` scope (this is necessary for `set_own_works`, which calls `work.pseuds.pluck(:id)` for each work in the listing when the viewer is logged-in, even when everything else is fully cached).
The other three types aren't …
=> AO3-6475 Let QueryResults use scopes, so that we can start work on reducing N+1 queries for works & bookmarks.

lib/otw_sanitize/embed_sanitizer.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6279
As stated in jira issue:
- metacafe.com shut down in August 2021
- ning.com does not appear to host videos any longer
- DailyMotion blocks all fanvids upon upload
PR removed metacafe.com, ning.com, and dailymotion.com from HtmlCleaner and OtwSanitize. 
Not sufficiently tested for unwanted results
Test case 1: 
a) try to embed nonfunctional link from listed sites into archive work
b) try to embed working link from listed sites into archive work
c) try to embed working link from i.e. youtube into archive work
d) try to embed nonfunctional link from i.e. youtube into archive work
Test case 2: 
a) …
=> AO3-6279 Remove defunct video sites from the embed sanitizer

app/controllers/challenge_requests_controller.rb, app/helpers/prompt_restrictions_helper.rb, app/models/challenge_models/gift_exchange.rb, app/models/challenge_models/prompt_meme.rb, app/models/offer.rb, app/models/prompt.rb, app/models/request.rb, db/migrate/20221205223816_remove_prompt_restriction_id_column.rb, factories/challenges.rb, spec/controllers/challenge_claims_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6435
- Drops `prompt_restriction_id` from gift exchanges and prompt memes.
- Removes all remaining references to it in code, including the challenge factories.
- Remove the unused `get_prompt_restriction` method in `app/helpers/prompt_restrictions_helper.rb`.
- Renames the `get_prompt_restriction` method for prompts/requests/offers to something that Rubocop likes better (see [Naming/AccessorMethodName](https://docs.rubocop.org/rubocop/cops_naming.html#namingaccessormethodname)), and simplify the code for Requests and Offers.
- Simplifies the definition for `title_required?`, `url_required?`, and `description_required?` in prompts.
=> AO3-6435 Remove prompt_restriction_id column from the gift_exchanges and prompt_memes tables.

config/initializers/gem-plugin_config/sanitizer_config.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6466
Allow details element to have an open attribute, as suggested in comments of the Jira issue.
See Jira.
Follow-up to previous PR for this issue, #4448 
irrationalpie, they/them
=> AO3-6466 Allow open attribute on details element.

.github/workflows/automated-tests.yml, .simplecov, Gemfile, Gemfile.lock, README.md
https://otwarchive.atlassian.net/browse/AO3-6485
Switch to Codecov GitHub Action, since the uploader gem we've been using is deprecated. Follow the [migration plan](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader).
See issue. Works on [this pull request](https://app.codecov.io/github/otwcode/otwarchive/commit/c59f4676409170359605c87f4e305c683cd13be1).
=> AO3-6485 Switch to Codecov GitHub Action

app/views/comments/_commentable.html.erb, features/collections/collectible_multiple_collections.feature, features/step_definitions/generic_steps.rb, features/works/work_view.feature
https://otwarchive.atlassian.net/browse/AO3-6118 (Please fill in issue number and remove this comment.)
Follow-up to #4348 in order to fix the add/invite form still being shown when JavaScript is off. Thanks to @tickinginstant for finding the bug!
https://otwarchive.atlassian.net/browse/AO3-6118?focusedCommentId=359763
What name and pronouns should we use to credit you in the [Archive of Our Own's Release …
=> AO3-6118: Hide non-JS collection form when invite disabled

config/initializers/gem-plugin_config/sanitizer_config.rb, lib/html_cleaner.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6466
The `open` attribute on `<details>` is a boolean, so the value doesn't matter, so you can theoretically specify it as `<details open>`. However, the sanitizer turns that into `<details open="">`. For consistency with some other boolean attributes [e.g. see media sanitizer](https://github.com/otwcode/otwarchive/blob/1f07422d813dab2acd810857b19b787273f47e3b/lib/otw_sanitize/media_sanitizer.rb#L110-L117), this PR has the sanitizer set the value of `open` to `"open"`, if `open` is present on a `<details>` element.
The automated tests this PR removes are being removed because I realized while testing …
=> AO3-6466 Handle boolean 'open' attribute more nicely.

.github/workflows/automated-tests.yml
https://otwarchive.atlassian.net/browse/AO3-6485
To reduce the chance of being rate-limited by GitHub.
None. On my fork, here's [a run without a token](https://github.com/redsummernight/otwarchive/actions/runs/4268648009/jobs/7431280296):
```
[2023-02-25T06:09:24.289Z] ['info'] -> No token specified or token is empty
```
Here's [a run with a token](https://github.com/redsummernight/otwarchive/actions/runs/4268724095/jobs/7431419026):
```
[2023-02-25T06:25:01.366Z] ['info'] ->  Token found by environment variables
```
Both [successfully uploaded coverage](https://app.codecov.io/gh/redsummernight/otwarchive/commits?branch=AO3-6485-token).
=> AO3-6485 Optionally use the Codecov upload token

app/models/creatorship.rb, spec/models/creatorship_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5521
Fix the behavior from #4251 to avoid saving an original creator for co-creator requests that have been rejected.
See JIRA
https://otwarchive.atlassian.net/browse/AO3-5521?focusedCommentId=359769
https://otwarchive.atlassian.net/browse/AO3-5521?focusedCommentId=359790
Thanks @redsummernight for the direction on fixing this! I was actually just starting to rabbit hole when you posted that comment.
=> AO3-5521 Avoid recording original_creator for rejected co-creations

app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-5666
Invalid username error message text was unclear: "Login must begin and end with a letter or number; it may also contain underscores but no other characters." Changed it to "Login must be 3 to 40 characters (A-Z, a-z, \_, 0-9 only), no spaces, cannot begin or end with underscore (\_).", per the Jira ticket comments.
In Jira ticket & comments. Should look like this for existing user and new user respectively:
pinkpurpleblue (she/her)
=> AO3-5666 clarify invalid username error message 

app/models/user.rb, app/views/users/registrations/new.html.erb, features/users/user_create.feature, features/users/user_rename.feature, spec/models/user_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5666
Changes all invalid username errors from "Login ..." to "User name ..." for consistency of language. Also switched out more HTML heavy error display logic for user creation, in favor of calling a function in a .rb file.
Jira ticket explains how to reach the error and verify the changed text — should look like this
You also may want to run user_rename.feature, user_create.feature, and user_spec.rb
pinkpurpleblue (she/her)
=> AO3-5666 changed invalid username error text

lib/tasks/skin_tasks.rake, spec/lib/tasks/skin_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6482
Makes sure that all of the skins in the chooser get cached when `rake skins:cache_all_site_skins` is run, because you can't use a skin in the chooser if it's not cached. 
Refer to Jira.
=> AO3-6482 Improve reliability of skins:cache_all_site_skins

app/models/abuse_report.rb, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6425
When you reported a chapter URL without including http or https at the start, the URL was coming back with the work ID at the front: `/works/1080706archiveofourown.org/chapters/2165131/`
This adds the scheme to the start of URLs so that won't happen.
I didn't have much time so I wanted to get something functional, but it is ugly. Please help me make it less ugly.
Submit an abuse report with a URL like archiveofourown.org/chapters/123 and make sure it doesn't error.
=> AO3-6425 Don't mangle reported chapter URLs without schemes

.github/workflows/automated-tests.yml, Gemfile, Gemfile.lock, app/views/external_works/fetch.js.erb, app/views/home/index.html.erb, config/docker/Dockerfile, config/initializers/gem-plugin_config/redis.rb, config/initializers/gem-plugin_config/webmock.rb, docker-compose.yml, features/admins/admin_skins.feature, features/bookmarks/bookmark_share.feature, features/collections/collection_anonymity.feature, features/other_a/hit_counts.feature, features/other_a/preferences_edit.feature, features/other_b/skin.feature, features/other_b/skin_public.feature, features/other_b/skin_wizard.feature, features/step_definitions/generic_steps.rb, features/step_definitions/web_steps.rb, features/step_definitions/work_steps.rb, features/support/capybara.rb, features/support/hooks.rb, features/works/work_share.feature, script/docker/init.cmd, script/docker/init.sh
https://otwarchive.atlassian.net/browse/AO3-6496
- Adds the `selenium-webdriver` library and the `webdrivers` library.
- Removes the `poltergeist` library and the code for installing `phantomjs`.
- Modifies the twitter widget on the homepage so that it's not displayed in tests, since Selenium doesn't offer native URL blocking.
- Removes the `I limit myself to the Archive` step, because Selenium doesn't offer native URL blocking.
- Modifies `docker-compose.yml` to add a separate `test` container that has access to a headless chrome container with selenium installed.
- Modifies most of the tests involving the Share modal to add the new `@site-skins` tag, because modals don't display properly without the site CSS loaded.
- Adds a custom screenshot driver to allow full-page screenshots on …
=> AO3-6496 Switch to Selenium instead of phantomjs for tests with JS enabled.

docker-compose.yml, script/docker/init.cmd, script/docker/init.sh
https://otwarchive.atlassian.net/browse/AO3-6496
- Adds the `--rm` option when calling `docker-compose run`, to avoid leaving behind dead containers.
- Changes the init scripts to use `rake db:migrate` instead of `script/reset_database.sh` for the test environment, because the development script already creates the database and loads the schema for the test environment.
=> AO3-6496 Add the --rm option to docker-compose run commands.

app/views/bookmarks/index.html.erb, app/views/bookmarks/search_results.html.erb, app/views/muted/_muted_items_notice.html.erb, app/views/series/index.html.erb, app/views/works/index.html.erb, app/views/works/search_results.html.erb
https://otwarchive.atlassian.net/browse/AO3-6476
Reposition and restyle the notice about muting affecting the number of items on a page so it better resembles the existing notice about items on a page.  
Refer to Jira.
=> AO3-6476 Update styling of muted users notice

app/views/comments/_single_comment.html.erb, features/other_a/pseuds.feature, features/users/user_rename.feature
Please do not review yet. I want to see if the CI behaviour matches something strange I see locally before marking as review-ready.
https://otwarchive.atlassian.net/browse/AO3-4120
Update the cache key for single comments to avoid displaying a stale commenter name
See Jira bug description for STR
Epic: https://otwarchive.atlassian.net/browse/AO3-5051
Comment by @tickinginstant with suggested solution: https://otwarchive.atlassian.net/browse/AO3-4120?focusedCommentId=358747
**Brian (they/he)**
=> AO3-4120 Prevent comments caching stale username and pseud

app/models/download.rb, features/works/work_download.feature, spec/models/download_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5734
To stop doing truncation and cleaning of the page title shown in the downloaded HTML file which seem unnecessary.
(Using Docker) Go to http://localhost:3000/works/107 and choose Download > HTML. Open the downloaded HTML file. The title (as shown in a browser tab) should read "Addding tags for stats purposes" instead of "Addding tags for stats"
Note: Title lines shown inside the screen (in bold text) should be fine before this set of changes and should remain that way. Also, the file name should be in ASCII before and after.
EDIT: I actually don't know if work IDs (107 here) of test data are same …
=> AO3-5734 Stop truncating and sanitizing page titles of HTML downloads

app/views/skins/_wizard_form.html.erb, public/help/skins-wizard-accent-color.html
https://otwarchive.atlassian.net/browse/AO3-2228
I've removed the handy list of colors link and the footnotes stating the default value as I believe they are no longer necessary. 
=> AO3-2228 Add color picker for skin wizard

app/controllers/application_controller.rb, app/models/media.rb, app/views/menu/_menu_fandoms.html.erb
https://otwarchive.atlassian.net/browse/AO3-6474
Remove `ApplicationController#set_media` so that we only load the media list for the menu when we actually need to load the tags to regenerate the cache.
=> AO3-6474 Only load media for the menu when needed.

public/403.html, public/445.html, public/500.html, public/502.html, public/503.html, public/507.html, public/nomaintenance.html, public/status/index.html
https://otwarchive.atlassian.net/browse/AO3-6499
Update the stylesheet URLs to point to stylesheet files that (should) actually exist on staging and production.
Visit the URLs listed in the issue and ensure they have style~
I have this vague, annoying feeling/recollection that we were using the wrong stylesheet URLs because the right ones didn't work, but let's give it a go.
It looked like public/status/index.html was using the wrong `@media` as in [AO3-4451](https://otwarchive.atlassian.net/browse/AO3-4451), so I've fixed that, too.
[AO3-4451]: https://otwarchive.atlassian.net/browse/AO3-4451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6499 Update stylesheet URLs on static pages

lib/tasks/database_seed.rake, script/reset_database.sh
https://otwarchive.atlassian.net/browse/AO3-6504
The task `db:otwseed` depends on `db:drop`, `db:create`, etc. so we shouldn’t be [running both in the development environment](https://github.com/otwcode/otwarchive/blob/ccd24c3697144cc303f17c0e19cc65ff24915a5b/script/reset_database.sh#L13-L21).
Tested locally by:
- Running the script from scratch: `./script/docker/init.sh`;
- Running `docker-compose run --rm test script/reset_database.sh` after the development environment has been set up and checking that only the test database is reset (and only once);
- Running `docker-compose run -e RAILS_ENV=staging --rm test script/reset_database.sh` and getting the error for an unsupported environment.
=> AO3-6504 Avoid resetting dev databases twice for Docker

spec/controllers/api/v2/api_works_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6512
Fixes that the tests in that `spec/controllers/api/v2/api_works_spec.rb` don't clean up all records created in `before(:all)`. This would leak records to other tests, see https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/BeforeAfterAll.
Before this PR, the following tests fail when run after api_works_spec.rb:
```
rspec ./spec/lib/tasks/after_tasks.rake_spec.rb:374 # rake After:remove_translation_admin_role remove translation admin role
rspec ./spec/helpers/works_helper_spec.rb:50 # WorksHelper#sorted_languages returns all languages sorted alphabetically
rspec …
```
=> AO3-6512 Fix api works RSpec tests leaking state

app/jobs/tag_method_job.rb
https://otwarchive.atlassian.net/browse/AO3-6509
Adds two `retry_on` calls to the `TagMethodJob` class, one for deadlocks and one for lock wait timeouts. Set to a wait of 5 minutes (plus or minus the default jitter) so that hopefully whatever job we're conflicting with has time to finish.
=> AO3-6509 Retry TagMethodJobs on deadlock and lock wait timeout.

app/views/skins/_wizard_form.html.erb, public/help/skins-wizard-accent-color.html
https://otwarchive.atlassian.net/browse/AO3-6514
Reverts otwcode/otwarchive#4366 to change the skin wizard color fields back to plain text fields.
Refer to Jira.
=> AO3-6514 Revert "AO3-2228 Add color picker for skin wizard"

app/models/tag.rb, features/step_definitions/tag_set_steps.rb, features/tag_sets/tag_set_associations.feature
https://otwarchive.atlassian.net/browse/AO3-6391
- Cleans up the `update_tag_nominations` function by (a) splitting it into two separate callbacks, one for updating and one for clearing, and (b) avoiding passing around `tag` as a variable (which is vestige of the fact that this code used to be in a sweeper at one point).
- Modifies the `update_tag_nominations` function so that it now sets `parented` similarly to the way that `TagNomination#set_parented` sets the value of `parented`. In particular: https://github.com/otwcode/otwarchive/blob/8e03660aaa2b470011109a0af187716bf34e575c/app/models/tagset_models/tag_nomination.rb#L77-L81
- Fixes the test "If a nominated tag and its parent are wrangled after approval it should still be possible to associate them" so that it now accurately reflects …
=> AO3-6391 Improve the tag callbacks for updating TagNominations.

app/controllers/collection_items_controller.rb, config/locales/controllers/en.yml
https://otwarchive.atlassian.net/browse/AO3-3867
Updates the "invited" link in the confirmation message to point to the page the work is actually on (the one for items awaiting user approval).
Invite someone else's work to your collection and follow the "invited" link in the confirmation message.
=> AO3-3867 Update link in invited to collection confirmation message

app/views/abuse_reports/new.html.erb, app/views/user_mailer/abuse_report.html.erb, app/views/user_mailer/abuse_report.text.erb, config/locales/mailers/en.yml, config/locales/views/en.yml, features/other_a/abuse_report.feature
https://otwarchive.atlassian.net/browse/AO3-6492
* Update the live validation errors on the form.
* Fix a link on the form.
* Revert a change to a test.
* Format the summary as plain text in the HTML email to avoid unwanted paragraph tags until [AO3-6519](https://otwarchive.atlassian.net/browse/AO3-6519) can be fixed.
* Make sure proper greeting appears in text email when no name is entered for the report.
Refer to Jira.
[AO3-6519]: https://otwarchive.atlassian.net/browse/AO3-6519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6492 Tweak abuse report form and email

app/views/home/_dmca.html.erb
Replaces "Chilling Effects" with "Lumen" on DMCA page
https://otwarchive.atlassian.net/browse/AO3-6516 
Updates the copy in the DMCA policy.
1) Visit https://archiveofourown.org/dmca
2) Verify references to "Chilling Effects" and "Chilling Effects Clearinghouse" have been changed to "Lumen"
N/A
paradoxe, they/them
=> AO3-6516 Replace "Chilling Effects" with "Lumen" on DMCA page

db/migrate/20230429120200_remove_automatically_approve_collections.rb, test/fixtures/preferences.yml
https://otwarchive.atlassian.net/browse/AO3-6119
Remove the automatically_approve_collections column from the preferences table with a migration
=> AO3-6119 Remove automatically_approve_collections from preferences

app/models/abuse_report.rb, config/config.yml, config/locales/models/en.yml
https://otwarchive.atlassian.net/browse/AO3-6044
Move the regex used to validate URLs in abuse reports to config.yaml. This will allow us to override it on test environment(s).
Listed in the Jira description.
=> AO3-6044 Use PERMITTED_HOSTS to validate abuse report URLs

app/policies/user_policy.rb, config/routes.rb
https://otwarchive.atlassian.net/browse/AO3-5499
Removes send_activation code from user policy and from routes because we removed the `send_activation` action in #4469.
=> AO3-5499 Remove send_activation code from routes and user policy

app/views/admin/admin_users/show.html.erb, config/locales/models/en.yml, config/locales/views/en.yml, features/admins/users/admin_manage_users.feature
https://otwarchive.atlassian.net/browse/AO3-5499
Lists a user's roles on the user admin page.
Modify a user's roles and ensure the list on the user's admin page updates as expected.
=> AO3-5499 List roles in user admin page meta

app/views/admin/admin_users/show.html.erb
https://otwarchive.atlassian.net/browse/AO3-5499
Changes the `note` class to `notes` so it properly clears the buttons. At some point I need to do this to a whole bunch of places. 🙃 
Go to the user admin page and shrink the width of your browser window and ensure the rest doesn't partially bunch up to the left of the buttons.
=> AO3-5499 Correct class name on user admin page note

app/helpers/admin_helper.rb, app/policies/user_policy.rb, app/views/admin/admin_users/_user_form.html.erb
https://otwarchive.atlassian.net/browse/AO3-6141
field on your Jira profile, so we can assign you the issues you're working on. …
=> AO3-6141 Disable user role checkboxes based on admin permissions

app/views/comments/_comment_form.html.erb
Reverts otwcode/otwarchive#4322 -- something came up, so we're bumping it to the next release
=> Revert "AO3-6243 Remove condition for comment form to be 'remote' to avoid CSRF token missing error"

app/controllers/application_controller.rb, app/controllers/autocomplete_controller.rb, app/controllers/downloads_controller.rb, app/controllers/invite_requests_controller.rb, app/controllers/users/registrations_controller.rb, app/views/comments/_commentable.html.erb, app/views/home/_intro_module.html.erb, app/views/invite_requests/_index_open.html.erb, app/views/invite_requests/_invite_request.html.erb, app/views/invite_requests/index.html.erb, app/views/invite_requests/status.html.erb, app/views/users/sessions/_passwd_small.html.erb, app/views/users/sessions/new.html.erb, app/views/works/_work_header_navigation.html.erb, spec/controllers/invite_requests_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6558
Removes the `fetch_admin_settings` hook, and replaces all uses of the variable `@admin_settings` with `AdminSetting.current`.
=> AO3-6558 Remove fetch_admin_settings hook.

app/controllers/pseuds_controller.rb, app/views/pseuds/index.html.erb, features/other_a/pseuds.feature
If cucumber tests are required, I would appreciate being paired with a coder who is okay with writing cucumber features, please.
https://otwarchive.atlassian.net/browse/AO3-5889
Adds pagination to the pseuds page.
alien, they/them
=> AO3-5889 Paginate pseuds using default per page setting

app/models/story_parser.rb, app/views/invitations/_invitation.html.erb, config/locales/views/en.yml, features/other_a/invite_request.feature, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3997
Fix additional issues found in AO3-3997, after #4390 
- As a user with the ability to import works, try importing with an ill-formatted email address. ("Archiving for others") It should show an error message (where no error was shown and importing succeeded).
- As a user with the ability to send invitations, try sending an invitation to an ill-formatted email address. It should show an error message (where it was missing previously).
Comments in the Jira link above, particularly https://otwarchive.atlassian.net/browse/AO3-3997?focusedCommentId=360179 .
=> AO3-3997 Fix for email address validation #4390

app/helpers/pseuds_helper.rb, app/helpers/users_helper.rb, app/views/users/_sidebar.html.erb, features/other_a/pseuds.feature
https://otwarchive.atlassian.net/browse/AO3-5901
Provides fallback text for the edge case of the New Pseud page, where `@pseud` is defined, but doesn't have a `name` yet.
If you have a Jira account, please …
=> AO3-5901 Pseud switcher text on the New Pseud page

app/views/tag_set_nominations/_tag_nominations_by_fandom.html.erb, config/initializers/monkeypatches/translate_string.rb
https://otwarchive.atlassian.net/browse/AO3-6567
Tries to improve the `translate_string`/`ts` function by making it use `%` instead of `I18n.translate`.
=> AO3-6567 Use % for translate_string instead of I18n.translate.

app/controllers/archive_faqs_controller.rb, spec/controllers/archive_faqs_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6545
If accessing FAQ with no specified locale or an invalid locale, redirect to last locale in session, then user preferred locale, then default locale.
As per JIRA. To be tested as guest, logged in standard user, and admin.
=> AO3-6545 Default FAQ to last valid locale instead of always English

public/stylesheets/site/2.0/07-interactions.css
https://otwarchive.atlassian.net/browse/AO3-6530
Adds a z-index to the validation message class so that it displays on top of the footer. Please let me know if you feel there's a better alternative solution!
Before:
After:
Instructions found within [the JIRA issue](https://otwarchive.atlassian.net/browse/AO3-6530) work well!
1. Log in
2. If you’re not testing on an iPhone SE 2, create a site skin to increase the font size on your live validation errors:
a. Hi, username! > My Dashboard > Skins > Create Site Skin
b. Fill in a title
c. Enter some CSS to change the font size of your live validation errors: .LV_validation_message { font-size: 20px …
=> AO3-6530 Display validation messages on top of footer

app/controllers/challenge_assignments_controller.rb, app/controllers/collection_participants_controller.rb, app/controllers/gifts_controller.rb, app/models/block.rb, app/models/challenge_assignment.rb, app/models/collection_item.rb, app/models/concerns/creatable.rb, app/models/creatorship.rb, app/models/gift.rb, app/models/mute.rb, app/models/pseud.rb, lib/creation_notifier.rb, spec/models/challenge_assignment_spec.rb, spec/models/owned_tag_set_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4867
https://otwarchive.atlassian.net/browse/AO3-4868
Changes the way that the `parse_byline` and `parse_bylines` functions are defined:
- The original functionality of `parse_byline` has been split into two functions: `parse_byline`, which returns a single pseud, and behaves like the old `assume_matching_login` option was enabled (if you call `first` on the result); and `parse_byline_ambiguous`, which returns an array of pseuds, and behaves like the old `assume_matching_login` option wasn't enabled.
- The function `parse_bylines` has been modified so that instead of allowing `assume_matching_login` as an option, it always calls the new, unambiguous `parse_byline`, because after AO3-4867 there are no cases where it should behave like …
=> AO3-4867 & AO3-4868 Prevent pseud ambiguity issues.

app/models/admin.rb, app/policies/comment_policy.rb, config/locales/models/en.yml, features/comments_and_kudos/admin_info.feature, spec/controllers/admin/activities_controller_spec.rb, spec/controllers/admin/banners_controller_spec.rb, spec/controllers/admin/blacklisted_emails_controller_spec.rb, spec/controllers/admin/skins_controller_spec.rb, spec/controllers/admin/spam_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/invite_requests_controller_spec.rb, spec/controllers/languages_controller_spec.rb, spec/controllers/locales_controller_spec.rb, spec/controllers/skins_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6536
Add elections admin role to allow them to hide, freeze and delete comments on news posts.
Elections and communications admins also have their deletion powers restricted to admin posts only.
EchoEkhi
=> AO3-6536 Add elections admin role

app/views/users/confirmation.html.erb, config/locales/devise/en.yml, config/locales/views/en.yml, features/other_a/invite_request.feature, features/step_definitions/invite_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6556
Update text that refers to account confirmation to refer to activation instead. Also, i18n the page. No test added, but there is a test that already covers the page that I modified.
See Jira.
Bilka (he/him)
=> AO3-6556 Update text to refer to account activation rather than confirmation

app/controllers/admin/blacklisted_emails_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/challenge_assignments_controller.rb, app/controllers/opendoors/external_authors_controller.rb, app/controllers/opendoors/tools_controller.rb, app/controllers/redirect_controller.rb, app/controllers/tag_set_nominations_controller.rb, app/helpers/series_helper.rb, app/models/work.rb, app/models/work_skin.rb, app/views/archive_faqs/show.html.erb, app/views/bookmarks/_bookmark_user_module.html.erb, app/views/menu/_menu_fandoms.html.erb, app/views/works/_search_box.html.erb, lib/css_cleaner.rb
https://otwarchive.atlassian.net/browse/AO3-6589
Rewrites some calls to `ts()` that used to pass user-generated text as part of the format string, potentially causing errors if that user-generated text contains a `%` sign.
=> AO3-6589 Don't call ts() on user-generated text.

app/views/home/_fandoms.html.erb, app/views/home/index.html.erb, config/locales/views/en.yml, public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-6553
Semantically, the list of media (plus All Fandoms) is a navigation
element, not a menu.
The preferred element to use would be `nav`, but we don't use this
anywhere else (yet), so for consistency I'm adding a `div` with the role
navigation.
(Per https://www.w3.org/TR/html-aria/#docconformance, `ul`s are not
allowed to have the role `navigation`.)
This is not strictly related to the a11y issue, but we're trying to add
i18n if we can when we touch a file. (Can remove if needed.)
If you have a Jira account …
=> AO3-6553 Better semantics and a11y for the media list on the homepage

app/models/preference.rb, spec/models/preference_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6549
Remove the ignore for the column that was deleted in #4505
Reference Jira
=> AO3-6549 Remove ignore of auto collection invite column

app/controllers/users_controller.rb, features/other_b/errors.feature, features/step_definitions/web_steps.rb, spec/controllers/users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5248
With this PR, accessing the user page for a nonexistent user gives an error 404 instead of redirecting to the people search.
Bilka (he/him)
=> AO3-5248 Change nonexistent user pages to 404

app/controllers/chapters_controller.rb, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6540
Fix the slip-up QA spotted.
Not technically my fault, it looks like update_positions was always allowed for suspended and banned users even before I started working on this ¯\_(ツ)_/¯ good job on wick for catching this!
https://github.com/otwcode/otwarchive/pull/4552
EchoEkhi
=> AO3-6540 Suspended and banned users should not be able to update chapter positions 

app/models/pseud.rb, app/models/user.rb, features/other_a/pseuds.feature, features/users/user_rename.feature, spec/models/pseud_spec.rb
until they are reviewed and merged before creating new pull requests. **(This updates a stale PR, hopefully this doesn't count towards my limit —but I can close one of mine if necessary.)**
https://otwarchive.atlassian.net/browse/AO3-5052
> Touches the all the series for a user or pseud when either of those are changed. This will bust the cache on the byline so that series blurb will show the updated pseud or username right away regardless of caching status.
This PR adds a spec on top of tlee911's changes.
See Jira issue
[tlee911’s PR.](https://github.com/otwcode/otwarchive/pull/4217)
tlee911
=> AO3-5052 Update series byline on username or pseud update

app/views/works/_adult.html.erb, config/locales/views/en.yml, features/importing/work_import.feature, features/other_a/reading.feature, features/works/work_browse.feature, public/stylesheets/site/2.0/08-actions.css
https://otwarchive.atlassian.net/browse/AO3-6480
* Adds a page heading to make the page more accessible to screenreader users, and tweak CSS to prevent extra space above our first-ever h2 landmark
* i18n
* Update text to be more accessible to our Chinese users
Refer to Jira
=> AO3-6480 Update text on adult content warning to improve accessibility

app/models/pseud.rb, app/models/series.rb, app/models/user.rb, spec/models/pseud_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5052
- Delete the series byline cache when user/pseud name changes instead of touching series.
- Remove a spec as the series `updated_at` doesn't change anymore
https://github.com/otwcode/otwarchive/pull/4605 Automated tests were already added here. 
=> AO3-5052 Delete cached series byline when updating pseud or username

.github/workflows/reviewdog.yml, .hound.yml
https://otwarchive.atlassian.net/browse/AO3-6590
Use reviewdog to run ERB lint on pull requests because Hound does not run it (despite being configured for it).
Demo PR from same repo: https://github.com/Bilka2/otwarchive/pull/1
Demo PR from forked repo: https://github.com/Bilka2/otwarchive/pull/2 (see reviewdog's docs on [Graceful degradation for PRs from forks](https://github.com/reviewdog/reviewdog#graceful-degradation-for-pull-requests-from-forked-repositories))
See Jira.
Bilka (he/him)
=> AO3-6590 Add reviewdog for linting ERB files

app/views/home/index.html.erb, public/stylesheets/site/2.0/26-media-narrow.css
https://otwarchive.atlassian.net/browse/AO3-6553
The two column layout breaks when we switch to `nav` because it relies on `nth-of-type` to apply styling to the odd-numbered modules. You can't do `.class:nth-of-type` without specifying an element (`div`), so things get complicated if we switch from `div` to `nav`.
In addition to the original testing instructions, log in to an account with no favorite tags and ensure the layout on the homepage is normal.
#4581 
alien originally asked if we could revert this because they have a lot on their plate, but when I realized what the issue was and asked if they'd mind me fixing it instead of reverting, they said it was fine.
=> AO3-6553 Use div with a role rather than nav element

config/deploy.rb
https://otwarchive.atlassian.net/browse/AO3-6599 
Currently the local config is not applied to machines which only run the scheduler.
Someone with accounts on the systems will have to log in to a machine which only has the scheduler running and check that database.yml for example is populated.
james_ (him)
=> AO3-6599 Apply local config on schedulers

script/docker/init.sh
Fixes the init.sh script on macOS, which does not support `cp -b`
Eliah Hecht, he/him
=> Omit -b option on macOS

app/controllers/comments_controller.rb, app/controllers/preferences_controller.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/models/user.rb, app/views/preferences/index.html.erb, config/locales/controllers/en.yml, config/locales/models/en.yml, config/locales/views/en.yml, db/migrate/20230819074500_add_guest_replies_off_to_preference.rb, features/comments_and_kudos/guest_comment_replies.feature, features/other_a/preferences_edit.feature, features/step_definitions/preferences_steps.rb, public/help/comment-preferences.html, spec/controllers/comments_controller_spec.rb, spec/models/comment_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6312
Add a preference to prevent logged out users from replying to your comments on news posts and other users' works. Guests can still reply to you on works you created or co-created.
See Jira.
Partial implementation in #4243.
Migration with departure gem based on #4528.
Help text for the admin emails feature removed because of [AO3-5043](https://otwarchive.atlassian.net/browse/AO3-5043).
Bilka (he/him)
[AO3-5043]: https://otwarchive.atlassian.net/browse/AO3-5043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6312 Add preference to prevent guest replies to comments

app/controllers/admin/admin_users_controller.rb, spec/controllers/admin/admin_users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6467?focusedCommentId=360436
Add the missing log when a fnok is replaced (akin to one deletion and one addition) 
1. Add AccountB as an FNOK for AccountA. Check it shows in both the logs of AccountA and AccountB
2. Update the FNOK for AccountA to be AccountC. Check the deletion of previous fnok shows in the logs of AccountA and AccountB, and the addition of the new fnok shows in the log of AccountA and AccountC.
=> AO3-6467 Track deletion of previous fnok on update

app/models/common_tagging.rb, app/models/tag.rb, spec/models/tag_wrangling_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6487
Shots in the dark at fixing the issue described in the ticket.
Because, while it's not issue reproducing it on staging:
Manually fixed tag:
```
curl -u "LOGIN:PASSWORD" "https://test.archiveofourown.org/autocomplete/character_in_fandom?term=bob&fandom[]=Your%20Organic%20Love" -H "Accept: application/json"
```
Tag left as is after synonymizing:
```
curl -u "LOGIN:PASSWORD" "https://test.archiveofourown.org/autocomplete/character_in_fandom?term=lindsey&fandom[]=Your%20Organic%20Love" -H "Accept: application/json"
```
~~I haven't been able to recreate the conditions for it in tests.~~
~~So trying to:~~
~~- Force the autocomplete refresh each time the association is updated, not only on create. It makes sense and is consistent with how the …
=> AO3-6487 More attempts at fixing autocompletes after a fandom is made a synonym

app/models/tag.rb, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6328 (Second PR)
Tries to ensure that when the number of uses of a large tag increases (e.g. when a work is posted), a reindex is triggered. After some investigation, it looks like the cached tag count prevents `write_taggings_to_redis` from being called when the tag has at least 1000 uses (`TAGGINGS_COUNT_MIN_CACHE_COUNT`). 
I am not 100% sure of this approach, which is to remove the old cached count in `after_update`. Another way I believe to be possible is setting the `taggings_count_cache` range in [ScheduledTagJob](https://github.com/otwcode/otwarchive/blob/660a67aae71f2e0dbfc0316727ce7ce160ed607a/ …
=> AO3-6328 Try to fix large tags not updating in uses sort

app/models/tag.rb, spec/models/tag_spec.rb
Reverts otwcode/otwarchive#4637
https://otwarchive.atlassian.net/browse/AO3-6328
It turns out our problem was simply not restarting the Resque workers 🤡
=> Revert "AO3-6328 Try to fix large tags not updating in uses sort"

app/views/external_works/fetch.js.erb
https://otwarchive.atlassian.net/browse/AO3-6618
Adds missing escaping to external work bookmark fields.
=> AO3-6618 Escape characters on bookmark fields fetched with JavaScript

app/views/downloads/_download_afterword.html.erb, app/views/downloads/show.html.erb, config/locales/views/en.yml, features/works/work_download.feature
https://otwarchive.atlassian.net/browse/AO3-5776
Replace "author" with "creator" in the download afterword that encourages commenting.
Did not do the bonus because counting the work creators looked quite complicated, at least when looking at the logic that bylines do. But maybe I missed some easy way to get all of a work's creators/external creators/anon status.
See Jira.
#4607 for the change to `downloads/show.html.erb`
Bilka (he/him)
=> AO3-5776 Remove mention of author from download afterword

.github/workflows/automated-tests.yml, app/models/download_writer.rb, config/docker/Dockerfile, script/gh-actions/ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-5629
Switches from wkhtmltopdf to Calibre for generating our PDFs while attempting to maintain a similar appearance. (We can't update our operating system until we make this change.)
Once we've tested on staging, we should post beforehand to let users know PDFs will be changing in appearance (and explain that this change is necessary). Here are the difference I noticed:
* the title and work notes are on a separate page, not right below the meta
* there is slightly more space in the top/bottom margins
* the font on the meta, work title, and "summary" and "notes" headings is, at least on my system, a serif rather than a sans serif, _but_, based on past experience with our downloads, I think this might be due to different default system fonts on my …
=> AO3-5629 Switch from wkhtmltopdf to Calibre for PDF downloads

app/models/download.rb, spec/mailers/user_mailer_spec.rb, spec/models/download_spec.rb, spec/support/shared_examples/mailer_shared_examples.rb
https://otwarchive.atlassian.net/browse/AO3-6625
Replaces the whitespace in download filenames with underscores to ensure the Calibre-generated table of contents works on EPUBs for Kindle. (Refer to Jira for more info on why this should fix it despite seeming unconnected.)
Refer to Jira.
=> AO3-6625 Replace whitespace in download filenames with underscores

app/views/downloads/_download_preface.html.erb, config/locales/views/en.yml, features/works/work_download.feature
https://otwarchive.atlassian.net/browse/AO3-6058
Add the translation(s) of a work to the links displayed at the beginning of a download.
Refer to Jira story
Follow-up to #4608 
@weeklies for the majority of the work in the linked PR
=> AO3-6058 Add 'translation into' to download preface

.github/workflows/reviewdog.yml, .hound.yml
https://otwarchive.atlassian.net/browse/AO3-6605
Add a Reviewdog action to run Rubocop. This will give us more flexibility to add custom cops and upgrade to the latest version of rubcop (and its plugins). Example of how Rubocop warnings will show up: https://github.com/brianjaustin/ao3-sandbox/pull/1/files (the specific message is from a custom cop).
Note: no changes in _what_ Rubocop flags are expected yet. Custom cops (and maybe other plugins?) will come in later PR(s)
1. Allow-list the action in this Github repository's settings (similar to #4604)
~2. Deactivate/remove this repository from our Hound account -- optional but recommended to …
=> AO3-6605 Add Reviewdog for Rubocop check

features/other_a/orphan_work.feature
https://otwarchive.atlassian.net/browse/AO3-6601
Fix flaky orphan work tests by adding a simulated delay before orphaning. This means the cache is expired when orphaning and we don't get an intermittent failure.
No manual QA required. I ran the test 50x [here](https://github.com/Bilka2/otwarchive/actions/runs/6833961787) (and them re-ran all of them once for good measure), with no failures. Only the "Scenario: I can orphan multiple works at once" [semi-regularly failed](https://github.com/Bilka2/otwarchive/actions/runs/6833928963) for me in previous runs, so I am not completely sure that the other tests are no longer flaky. But as long as they're not failing, I'd say it's fine.
Fix and workflow to test the fix based on #4372.
Bilka (he/him)
=> AO3-6601 Fix flaky orphan work tests

features/other_b/series.feature
https://otwarchive.atlassian.net/browse/AO3-6633
Fix flaky series co-creator test by adding a simulated delay before removing the creator as a co-creator. This means the cache is expired and we don't get an intermittent failure.
No manual QA required. I ran the test 50x [here](https://github.com/Bilka2/otwarchive/actions/runs/6834160438), with no failures. Before the fix, 50 runs resulted in [3 failures](https://github.com/Bilka2/otwarchive/actions/runs/6834091266).
Fix and workflow to test the fix based on #4372.
Bilka (he/him)
=> AO3-6633 Fix flaky series co-creator test

features/collections/collection_anonymity.feature
https://otwarchive.atlassian.net/browse/AO3-6632
Fix flaky collection anonymity tests by adding simulated delays before certain actions to ensure cache expiry and correct ordering of works sorted by age.
No manual QA required. I ran the test 50x [here](https://github.com/Bilka2/otwarchive/actions/runs/6847059993), with no failures. Before the fix, 50 runs resulted in a variety of [failures](https://github.com/Bilka2/otwarchive/actions/runs/6846844592), including in some tests in the same file that are not listed in the Jira issue. They are all fixed now.
[sarken's WIP](https://github.com/otwcode/otwarchive/compare/master...sarken:otwarchive:AO3-6632_test_runs) with [email failure](https://github.com/sarken/otwarchive/actions/runs/6793417579/job/18468631211#step:12:49) related to work …
=> AO3-6632 Fix flaky collection anonymity tests

features/other_a/orphan_pseud.feature, features/tags_and_wrangling/tag_wrangling.feature, features/users/user_delete.feature
```
Failing Scenarios:
cucumber features/tags_and_wrangling/tag_wrangling.feature:318 # Scenario: Can simultaneously add a grandparent metatag as a direct metatag and remove the parent metatag
```
Fix a test that has been (for unclear reasons) failing a lot lately. Issue partially diagnosed and solution provided [here](https://github.com/otwcode/otwarchive/pull/4646/files/9ba58b1067b227e38d6a0fb0e0f4ac88f72873b8#diff-af91bc4226f0dcaaa97808fb61ca2b2d1b33b4c174ea383afc40aab2b258b383) at first.
The CI should stop being red so often.
=> AO3-6638 Intermittent failure in cucumber tag_wrangling, orphan_pseud, and user_delete features

.erb-lint.yml, app/views/chapters/_chapter.html.erb
Use the [speculation rules API](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API) to add prefetching of the next chapter in supported browsers. (Currently, Chromium-based browsers such as Chrome, Edge, Brave, etc.) This prefetching happens in idle time and at low priority, so should not disrupt the reading experience. The result should be faster page loads for chapters 2+.
See https://otwarchive.atlassian.net/browse/AO3-6636
The parent issue https://otwarchive.atlassian.net/browse/AO3-6635 is also relevant.
Domenic Denicola, he/him
=> AO3-6636 Add speculation rules next-chapter prefetch

app/views/chapters/_chapter.html.erb
942f4a3bd2d66e9212d25b7b7d2ffec7dd710ded accidentally used the "eagerness" field, which is only supported in Chrome 121+. It isn't necessary in our case (the value we used, "eager", is already the default) so we can just remove it to fix prefetching in earlier versions of Chrome.
Fixes the speculation rules prefetch feature to work on earlier Chrome versions.
See [the Jira ticket](https://otwarchive.atlassian.net/browse/AO3-6636)
- https://github.com/otwcode/otwarchive/pull/4661
- https://github.com/otwcode/otwarchive/pull/4665
Domenic Denicola, he/him
=> AO3-6636 Fixup speculation rules next-chapter prefetch

app/views/chapters/_chapter.html.erb
This ensures that speculation rules prefetching is output, and cached, for all chapters.
This is an alternative to #4668.
Ensure the introduction of speculation rules next chapter prefetching causes the chapter to be evicted from cache, but then cached going forward under the new v5 cache key.
General testing instructions for the feature are on the issue, but for this caching issue specifically, @sarken suggests testing on works which had previously been generated this change, maybe?
- This comment https://otwarchive.atlassian.net/browse/AO3-6636?focusedCommentId=360659
- Discussions with @sarken …
=> AO3-6636 Update chapter cache key

app/views/chapters/_chapter.html.erb
See https://otwarchive.atlassian.net/browse/AO3-6636?focusedCommentId=360670.
Removes the rollout guard from the speculation rules next-chapter prefetch feature, since it interacts poorly with caching and was deemed unnecessary.
See instructions in https://otwarchive.atlassian.net/browse/AO3-6636.
The specific comment https://otwarchive.atlassian.net/browse/AO3-6636?focusedCommentId=360670.
Domenic Denicola, he/him
=> AO3-6636 Remove rollout guard for speculation rules

features/step_definitions/web_steps.rb, features/step_definitions/work_steps.rb, features/works/work_browse.feature, features/works/work_edit.feature, features/works/work_edit_multiple.feature, features/works/work_share.feature
https://otwarchive.atlassian.net/browse/AO3-6646
Intermittent test failures in features/works:
[Example run, also listed in wiki](https://github.com/Bilka2/otwarchive/actions/runs/6991522052/job/19022169603): [features/works/work_share.feature:68](https://github.com/otwcode/otwarchive/blob/819c435f5690a457ece0cbcb6b86dae197a1ba21/features/works/work_share.feature#L68) # Scenario: Share URL should not be used for post-login redirect
```
expected: "/works/1"
got: "/users/MadUser" (using ==) (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:263:in `/^(?:|I )should be on (.+)$/'
features/works/work_share.feature:84:in `Then I should be on the "Blabla" work page'
```
[Example run, also listed in wiki](https://github.com/Bilka2/otwarchive/actions/runs/6991306 …
=> AO3-6646 Fix flaky works tests

features/bookmarks/bookmark_create.feature, features/bookmarks/bookmark_search.feature
https://otwarchive.atlassian.net/browse/AO3-6645
[features/bookmarks/bookmark_create.feature:111](https://github.com/otwcode/otwarchive/blob/4ec559fb011ce2eba4b164a6b799f71eac9b2eec/features/bookmarks/bookmark_create.feature#L111) # Scenario: bookmark added to moderated collection has flash notice only when not approved
```
expected not to find text "The collection Five Pillars is currently moderated." in "Main Content While we've done our best to make the core functionality of this site accessible without javascript, it will work better with it enabled. Please consider turning it on! Example Archive beta User Navigation Hi, bookmarker! My Dashboard My History My Preferences Post New Work Import Work Log Out Site Navigation Fandoms All Fandoms Uncategorized Fandoms Browse Works Bookmarks …
```
=> AO3-6645 Fix flaky bookmarks test

config/application.rb, db/schema.rb
https://otwarchive.atlassian.net/browse/AO3-6639
Reverses the change in https://github.com/otwcode/otwarchive/pull/4669 that has the schema dump updated on any changes to dev. It ended up being problematic for tests, and since we don't always merge things fast, the potential for merge conflicts is... not great. I can work on some improvements, but for now let's just do what worked.
=> AO3-6639 Revert schema dump setting

db/migrate/20230430160300_remove_dead_column.rb, features/fixtures/external_works.yml, test/fixtures/external_works.yml
https://otwarchive.atlassian.net/browse/AO3-6314
Removes the "dead" column from the "external_works" table and removes its references in the fixtures. 
Automated tests 
=> AO3-6314 Remove column dead from external_works table

app/models/search/work_search_form.rb, spec/models/search/work_search_form_spec.rb
[AO3-6643](https://otwarchive.atlassian.net/browse/AO3-6643)
This PR fixes an error that occurs when attempting to sort by a column without a pretty name in a work search (e.g. the `id` or `expected_number_of_chapters` column).
Refer to the Jira issue.
Albert Pedersen (he/him)
[AO3-6643]: https://otwarchive.atlassian.net/browse/AO3-6643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6643 Fix error when sorting by columns without a pretty name

app/models/tag.rb, spec/models/tag_spec.rb, spec/spec_helper.rb
Hi! First time looking at the AO3 codebase - I wanted to learn a bit about Ruby and I'm a happy AO3 user so I set up an AO3 dev env and rummaged around Jira a little. Here is a very simple change for an existing ticket, please let me know if I'm missing anything.
(https://otwarchive.atlassian.net/jira/software/c/projects/AO3/issues/AO3-6626)
This pull request adds two additional characters to the regex of forbidden characters
The Archive's QA team can verify that this is working as intended by following the test steps set out in the Jira ticket, copy/pasted here:
>     Log in as a tag wrangler (e.g., testy)
> 
>     Create a new tag with a …
=> AO3-6626: stop tags from being added with Chinese or Japanese commas

app/controllers/admin_posts_controller.rb, spec/controllers/admin_posts_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5259
Deduplicates and orders by name the admin post tags for admin posts filtered by language.
Note: I couldn't face writing a cucumber step for "and the tag is present exactly once". I welcome ideas on how to test, whether a whole integration test even adds more value than length to the testing suite, etc. I am trying to be really restrained and not rewrite the entire `index` action to use a presenter, façade, or some other kind of service object that is easier to test. >.>
On Jira.
Are there other …
=> AO3-5259 Deduplicate and order admin post tags

app/helpers/application_helper.rb
Remove chatty ARIA attributes from char count elements, make those elements tab-focusable instead.
https://otwarchive.atlassian.net/browse/AO3-3217
Updates screenreader attributes on character count elements to prevent them from announcing the character count every time the user types. Instead, makes those elements tab-focusable.
Using a screenreader, try editing fields like such at "Title" on the user profile page.
Eliah Hecht, he/him
=> AO3-3217 Remove aria attributes from char counts

app/models/work.rb, spec/requests/works_n_plus_one_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6505
Adds `:approved_collections` and `:stat_counter` to the `includes` for the work blurb, reducing the number of database queries required on cache misses for the work blurb.
=> AO3-6505 Preload approved_collections and stat_counter for work blurbs.

app/views/works/_filters.html.erb, app/views/works/index.html.erb, features/works/work_browse.feature
https://otwarchive.atlassian.net/browse/AO3-3471
Fix the two bugs reported [here](https://otwarchive.atlassian.net/browse/AO3-3471?focusedCommentId=360724), namely:
- Conserve "owner" language_id when using filters
- Show "Filters" button on mobile
1. On a page like `/languages/en/works`, `/languages/de/works`, etc.
2. Try using the filters on both desktop and mobile versions
=> AO3-3471 Allow filtering on language specific /works page

app/views/invite_requests/_invitation.html.erb, app/views/invite_requests/show.js.erb, config/locales/views/en.yml
Second PR to fix some issues flagged by QA. 
https://otwarchive.atlassian.net/browse/AO3-6609
* Fix headings for JS and no JS invitation status info
* Fix lack of paragraph separation for text 
* Fix unescaped HTML in contact support link in status info
Check the status info with JS and no JS. 
https://github.com/otwcode/otwarchive/pull/4648
=> AO3-6609 Visual fixes for invitation status 

factories/admin.rb, factories/admin_blacklisted_email.rb, factories/users.rb, spec/controllers/invite_requests_controller_spec.rb, test/mailers/previews/application_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6386
This changes the generator for the emails of users and admins in tests and mailer previews to always produce valid email addresses.
This also fixes that the mailer previews [errored in local dev](https://github.com/otwcode/otwarchive/pull/4475#pullrequestreview-1329628736). The comment in the code is based on [the docs](https://thoughtbot.github.io/factory_bot/ref/find_definitions.html).
The preview UI should be at https://test.archiveofourown.org/rails/mailers and the creatorship mailer previews should not error when selecting languages such as `ja`, `vi` or `zh-CN`.
Bilka (he/him)
=> AO3-6386 Fix that email addresses in mailer previews were localized

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6626
Spoke to wrangling chairs and what we’re going to do is
- remove the commas
- if the tag can’t be saved because the comma-less version already exists, remove the comma and append “ - AO3-6626” to the end of the tag name so it can be found and dealt with by a wrangling admin
I’ve written a task that will do that:
`bundle exec rake After:remove_invalid_commas_from_tags`
Because tags can only be renamed by admins, the task will prompt you for your admin login. This is the whole thing, e.g., `admin-sarken`. 
If the login you enter cannot be found, it will tell you and the task won’t run.
If the login is found, the task will run and give you the new tag names.
Run the task, first trying an invalid admin login, and then trying a valid one.
=> AO3-6626 Add after task for removing invalid commas from tags

app/views/chapters/_chapter.html.erb, app/views/chapters/show.html.erb
Previously, we were adding the `<script type=speculationrules>` block inside the `_chapter` include. However, this means it was included on the "Entire Work" page, which is undesirable. (On that page, there would be no `@next_chapter` variable, so nothing would be rendered... and then that lack of speculation rules would be cached.)
We only want to preload the next chapter when we're looking at a single chapter in isolation. For this, it's best to put the `<script type=speculationrules>` in the `chapters/show` template.
https://otwarchive.atlassian.net/browse/AO3-6650
To ensure speculation rules are included on all single-chapter pages with a …
=> AO3-6650 Move speculation rules next chapter prefetch

app/models/invitation.rb, app/views/invite_requests/_invitation.html.erb, spec/models/invitation_spec.rb
Third PR to fix issues raised in QA. PR may need further tweaks. Currently does set sent_at and relies on updated_at as fallback. 
https://otwarchive.atlassian.net/browse/AO3-6609
Support resending and displaying status info of old invites without sent_at 
Try to check and resend an old invite
https://github.com/otwcode/otwarchive/pull/4685
=> AO3-6609 Fix status check of old invites without sent_at

.github/labeler/awaiting.yml, .github/labeler/contents.yml, .github/labeler/review.yml
https://otwarchive.atlassian.net/browse/AO3-6653
Hi, I'm the dumbass who saw the PR was passing and thought it meant we weren't using the config file they mentioned. (In my defense, we weren't. We had multiple ones with different names instead. 😆) Ergo, I am the dumbass who is hopefully fixing our config.
- I am not sure how it's going to feel about the rule for "Reviewed: Action Needed" -- it might still want `changed_files` in there.
- It checks paths starting with dot (e.g., `.github/`) by default now, so I took those out in a separate, easily reversible commit.
Merge and make sure the action works.
(Note: It'll fail on this because it's using the config from master, not the PR, which is where I went wrong with my life.)
[actions/labeler …
=> AO3-6653 Update labeler configuration syntax

.github/labeler/review.yml
https://otwarchive.atlassian.net/browse/AO3-6653
The "Reviewed: Action Needed" label is no longer getting removed when the coder pushes a commit after the label is replied. ("Coder Actioned Review" is getting applied.) This is a shot in the dark at fixing it. 
> It's the inverse of the condition to add "Coder Has Actioned Review." We have `sync-labels` set to true, which says, "Whether or not to remove labels when matching files are reverted or no longer changed by the PR"
>
>So I _think_ that means we'd be saying in the config file, "add the 'Reviewed: Action Needed' label if there are no changes in this commit," and then the sync setting would mean that since there are changes, the label would not apply, so it would get removed? Maybe? It's a whole lot of negating in here
I temporarily …
=> AO3-6653 Fix removal of Reviewed: Action Needed label

db/migrate/20230430160300_remove_dead_column.rb
https://otwarchive.atlassian.net/browse/AO3-6314
Use Departure / `pt-online-schema-change` for an external works migration. This table had ~450k rows when we ran the migration on 2023-01-06, so @zz9pzza hot fixed the migration to be on the safe side. We're adding the change to the repo as well.
N/A, this was already ran in production.
=> AO3-6314 Use Departure for external works migration

features/importing/archivist_creatorships.feature
https://otwarchive.atlassian.net/browse/AO3-6663
Intermittent test failure: https://github.com/otwcode/otwarchive/actions/runs/7410177559/job/20161893145
[features/importing/archivist_creatorships.feature:41](https://github.com/otwcode/otwarchive/blob/9ce7f82a0e0eaca675a7899222b805eed421b57c/features/importing/archivist_creatorships.feature#L41) # Scenario: Archivists can add users who don't allow co-creators to chapters
```
expected to find text "archivist, disallow" in "archivist" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:123:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:6:in `block in with_scope'
./features/step_definitions/web_steps.rb:6:in `with_scope'
./features/step_definitions/web_steps.rb:122:in …
```
=> AO3-6663 Fix flaky importing tests in features/importing/archivist_creatorships.feature

app/views/chapters/show.html.erb, app/views/hit_count/_include.html.erb
This includes delaying the hit count logging while prerendering.
https://otwarchive.atlassian.net/browse/AO3-6637
Per the discussion in https://otwarchive.atlassian.net/browse/AO3-6635, we've successfully completed a round of testing with prefetching the next chapter in idle time. This upgrades us to prerender them!
See instructions in https://otwarchive.atlassian.net/browse/AO3-6637.
(none besides the above)
Domenic Denicola, he/him
=> AO3-6637 Upgrade prefetch to prerender

app/views/blocked/users/_blocked_user_blurb.html.erb, app/views/muted/users/_muted_user_blurb.html.erb, app/views/pseuds/_pseud_module.html.erb, features/step_definitions/block_steps.rb, features/step_definitions/mute_steps.rb, features/users/blocking.feature, features/users/muting.feature
https://otwarchive.atlassian.net/browse/AO3-6572
~Reduce database work.~
If you're logged in as an admin with access to users' Blocked Users and Muted Users pages, you'll now be able to see the date and time blocks and mutes were created. 
The format is just plain old `2023-04-26 03:23:09 UTC`, like the way we display creation dates for, e.g., admin posts and admin activities.
1. Log in as a user and block and mute some users, noting the date/time you do it.
2. Make sure there are no dates/times displayed on the blurbs on your Blocked Users and Muted Users pages.
3. Log in as a superadmin, policy_and_abuse, or support admin and access the Blocked Users and Muted Users pages for the user from step one. Make sure the dates and times are there and they are correct.
=> AO3-6572 Show admins when blocks and mutes were created

features/other_a/orphan_account.feature
https://otwarchive.atlassian.net/browse/AO3-6681
Intermittent failures in cucumber features/other_a/orphan_account.feature: https://github.com/otwcode/otwarchive/actions/runs/7863503924/job/21454202626 https://github.com/otwcode/otwarchive/actions/runs/7434126817/job/20227944782
[features/other_a/orphan_account.feature:38](https://github.com/otwcode/otwarchive/blob/c6379417caea816c4abc272a650b985676435bbb/features/other_a/orphan_account.feature#L38) # Scenario: Orphan all works belonging to a user, add a copy of the pseud to the orphan_account
```
expected to find text "orphaneer (orphan_account)" in "Main Content While we've done our best to make the core functionality of this site accessible without javascript, it will work better with it enabled. Please consider turning it on! Example …
```
=> AO3-6681 Fix flaky orphaning account test

public/stylesheets/site/2.0/15-group-comments.css
https://otwarchive.atlassian.net/browse/AO3-6265
Fixes the issue where RTL text within comments is incorrectly left-aligned.
I was unable to think of a good way to automatically test this -- open to suggestions. Here's a screenshot from my dev environment though:
Write a comment on work with text like `<p dir="rtl">Some text goes here</p>`, and make sure it appears right-aligned within the comment box.
Eliah Hecht, he/him
=> AO3-6265 Use text-align start in comments

app/models/challenge_models/gift_exchange.rb, config/locales/models/en.yml, spec/models/gift_exchange_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5803
Require at least 1 request and offer per gift exchange signup. This avoids weird behavior when the requirements are 0. Also fixes the problem where 'allowed' values below 'required' were permitted.
Refer to Jira ticket
=> AO3-5803 Set minimums for gift exchange requests/offers

app/views/comments/_single_comment.html.erb, features/comments_and_kudos/add_comment.feature
https://otwarchive.atlassian.net/browse/AO3-3463
Fix inconsistent time zones in comments.
=> AO3-3463 Move time_in_zone out of comment cache blocks

app/views/admin_posts/_sidebar.html.erb
https://otwarchive.atlassian.net/browse/AO3-6575
On the AO3 News page, the sidebar has the role `menu`, but its direct children do not have a relevant ARIA role (e.g. `menuitem`).
The list shouldn't be a menu in the first place, but a navigation. The preferred element to use is `nav` (rather than a `div` with the role navigation).
What name and …
=> AO3-6575 Turn News posts sidebar into navigation

app/helpers/prompt_restrictions_helper.rb, public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-5803
When errors are displayed for fields like required requests per sign-up, the fields should be highlighted in red but not break the flow of the form. This fixes the issue where error highlighting takes up the whole line (refer to https://otwarchive.atlassian.net/browse/AO3-5803?focusedCommentId=360957).
New look:
**NOTE:** This will require recaching skins to show up properly.
=> AO3-5803 Make errors for challenge limits display inline

app/views/comments/_single_comment.html.erb
https://otwarchive.atlassian.net/browse/AO3-3463
I noticed an issue with the cache keys in the code of the [original PR](https://github.com/otwcode/otwarchive/pull/4610). The records are embedded in the key instead of using the [Rails cache dependency algorithm](https://api.rubyonrails.org/v6.1.7/classes/ActionView/Helpers/CacheHelper.html#method-i-cache) to generate the keys based on the records' updated_at timestamp as before.
On my local dev instance the cache keys look like this (for 1 user comment and 2 guest comments):
Before this PR:
```
memcached-tool 127.0.0.1:11211 dump | grep -a "add ao3-v2-dev:views/comments/"
Dumping memcache contents
add ao3-v2-dev:views/comments/_single_comment:d746d9d5ce8afaa44af98c5537a29737/[#<Comment%20id:%20228,%20pseud_id:%2025,%20comment_content:%20[F …
```
=> AO3-3463 Fix comment cache keys to depend on record updated_at again

app/controllers/languages_controller.rb, app/models/search/work_query.rb, spec/models/search/work_query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6667
Avoid counting
* Admin hidden
* Unrevealed
* Non-posted
* (if browsing as a guest) restricted
works in the languages count page. Previously, the code (that was inefficient and hit the database) didn't include this, but it's weird that searching does, so we might as well fix it while we're here.
This is a follow-up to https://github.com/otwcode/otwarchive/pull/4714.
=> AO3-6667 Avoid counting non-visible works for languages page

app/controllers/application_controller.rb
https://otwarchive.atlassian.net/browse/AO3-6679
This PR removes the session cookie migration logic introduced as part of https://otwarchive.atlassian.net/browse/AO3-6629. The migration logic was added to ensure users did not get logged out when the session cookie format was changed. More than two weeks (browser TTL of session cookie) have passed since the release, so the migration logic is no longer necessary.
Users should stay signed in and no errors should be observed.
Albert Pedersen (he/him)
=> AO3-6679 Remove session cookie migration logic

app/models/collection.rb, app/models/pseud.rb, app/models/skin.rb, config/environments/production.rb, config/environments/staging.rb
https://otwarchive.atlassian.net/browse/AO3-6647
Fix a 500 error that occurs when trying to get the URL of an icon uploaded to s3:
```
3.1.4 :018 > begin
3.1.4 :019 >   u = User.where(login:"zz9pzza").first
3.1.4 :020 >   puts u.pseuds.first.icon.url
3.1.4 :021 > rescue => exception
3.1.4 :022 >   puts exception.backtrace
3.1.4 :023 >   raise # always reraise
3.1.4 :024 > end
/home/ao3app/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych.rb:322:in `safe_load'
/home/ao3app/app/shared/bundle/ruby/3.1.0/gems/kt-paperclip-7.1.0/lib/paperclip/storage/s3.rb:432:in `find_credentials'
/home/ao3app/app/shared/bundle/ruby/3.1.0/gems/kt-paperclip-7.1.0/lib/paperc …
```
=> AO3-6647 Fix paperclip with no paperclip patch

app/controllers/related_works_controller.rb, spec/controllers/related_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-2151
Update the redirect when destroying a `RelatedWork` to go back to the main work edit form instead of throwing a 404.
=> AO3-2151 Redirect to work edit on related work deletion

features/other_a/help.feature
https://otwarchive.atlassian.net/browse/AO3-6596
Update the first login help feature test to not check for flash messages. While these should show up (and do in local development), there's something more complex (caching? probably caching?) going on in staging/production that means it doesn't. A follow-up will be filed to fix that behavior, as it shows up in several places as listed in https://otwarchive.atlassian.net/browse/AO3-6596?focusedCommentId=361109.
=> AO3-6596 Update first login help test to reflect stage/prod

.github/workflows/reviewdog.yml
https://otwarchive.atlassian.net/browse/AO3-6696
Use the `BUNDLE_ONLY` environment variable to install only the linter gems in the reviewdog linter github action workflows. Installing less gems should hopefully speed up the workflows.
No manual testing needed, simply see if it runs correctly on new PRs/pushes for PRs (including this PR). I tested it on my fork and the workflow was fine and reported the added errors: https://github.com/Bilka2/otwarchive/pull/9
Based on the [updated readme](https://github.com/reviewdog/action-rubocop/commit/53401726feff8cfe2342d0d85f3c1406bbf5ba93) of action-rubocop which I found when reviewing #4766. However, this change is independent of the update of the action.
Bilka (he/him)
=> AO3-6696 Change reviewdog workflows to install only linter gems

app/views/collections/_collection_blurb.html.erb, features/collections/collection_participants.feature, features/step_definitions/collection_steps.rb, features/step_definitions/generic_steps.rb
* [x ] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x ] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [ x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
* [x ] Do you have fewer than 5 pull requests already open? If not, please wait
https://otwarchive.atlassian.net/browse/AO3-6676
Makes sure that the text "Leave" is present …
=> AO3-6676 Remove participant memoization causing Leave button to appear on all collection blurbs

public/status/index.html
https://otwarchive.atlassian.net/browse/AO3-6689
Adds a missing JavaScript file to https://test.archiveofourown.org/status/index.html. Now clicking a menu like "About" won't take you somewhere; it'll just keep the menu open.
Go to https://test.archiveofourown.org/status/index.html and make sure the page works, paying special attention to the behavior when clicking on the dropdown menus.
field on your Jira profile, so we can assign you the issues you're working on.
*Please note that if you do not fill in …
=> AO3-6689 Fix JavaScript for dropdowns on status index

features/admins/admin_works.feature, features/other_b/series.feature
https://otwarchive.atlassian.net/browse/AO3-6701
Fix flaky series test by adding a simulated delays before creating the works. This means the cache for the previous works is correctly expired when the new work is created, so the link is present in the meta and we don't get intermittent failures.
Fix flaky admin works test by adding a simulated delay before marking a comment as not spam. This means that marking the comment as not spam correctly expires the cache of the comment, so the comment text is shown and we don't get  intermittent failures.
No manual QA required. I ran the admin work test 50x [here](https://github.com/Bilka2/otwarchive/actions/runs/8453192741) and the series test 50x [here](https://github.com/Bilka2/otwarchive/actions/runs/8452841603), with no failures. Before the …
=> AO3-6701 Fix flaky admin works and series tests

app/views/tags/show.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-4696
Adjust the wording of the description of canonical tags and move the link to the relationship tags of the fandom after the description.
See Jira.
Bilka (he/him)
=> AO3-4696 Adjust wording of description of canonical fandom tags

app/models/admin.rb, app/policies/admin_banner_policy.rb, app/views/admin/banners/_navigation.html.erb, app/views/admin/banners/index.html.erb, config/locales/models/en.yml, config/locales/views/en.yml, features/other_a/banner_general.feature, spec/controllers/admin/banners_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6486
Create a `development_and_membership` admin role that allows DevMem to edit banners, but not create or delete them. 
Refer to Jira.
=> AO3-6486 Add development_and_membership admin role

.rubocop.yml, rubocop/cop/cucumber/regex_step_name.rb, rubocop/cop/i18n/default_translation.rb, rubocop/cop/i18n/deprecated_helper.rb, rubocop/cop/i18n/deprecated_translation_key.rb, rubocop/cop/migration/large_table_schema_update.rb, rubocop/rubocop.rb, spec/rubocop/cop/cucumber/regex_step_name_spec.rb, spec/rubocop/cop/i18n/default_translation_spec.rb, spec/rubocop/cop/i18n/deprecated_helper_spec.rb, spec/rubocop/cop/i18n/deprecated_translation_key_spec.rb, spec/rubocop/cop/migration/large_table_schema_update_spec.rb, spec/rubocop_spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6691
Adds custom Rubocop rules to automatically flag some things we have to do manually in PR review. For example, using departure for large tables.
=> AO3-6691 Custom cops for house rules

rubocop/cop/README.md
Jira ticket: https://otwarchive.atlassian.net/browse/AO3-6691
Adds additional documentation for custom rules added in https://github.com/otwcode/otwarchive/pull/4763
=> AO3-6691 Add Readme for custom RuboCop cops

config/locales/views/en.yml, rubocop/cop/i18n/deprecated_helper.rb, spec/rubocop/cop/i18n/deprecated_helper_spec.rb
None, typo fix (for AO3-6691).
Remove the dot at the end of the sentence with the link to the I18n wiki page because by the GitHub Actions log viewer parses it as part of the link (which then goes nowhere): https://github.com/otwcode/otwarchive/actions/runs/8529536784/job/23365517628#step:4:161
Also, normalize en.yml because it's not normalized. The spec for it is failing on `master` but GitHub Actions isn't reporting the failure. I'm looking into that.
None, this is an automated test and a typo fix.
Bilka (he/him)
=> AO3-6691 Remove dot from link in custom cop

spec/lib/tasks/search_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6703
In the `search:index_tags` test, rescue the SystemExit exception raised by the `exit` call in the rake task, so that RSpec doesn't exit early.
The issue is in automated testing, no manual QA needed.
The early exit caused a failed test on `master` in `spec/lib/i18n` to not get reported by GitHub Actions. It should get reported now, so **the RSpec test should fail on this PR**. No other test should fail. The i18n test itself is fixed in #4779.
Bilka (he/him)
=> AO3-6703 Fix that some tests didn't run due to exit call in rake task

app/models/pseud.rb, features/collections/icon.feature, features/step_definitions/icon_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6608 (Please fill in issue number and remove this comment.)
Delete alt text associated with a pseuds Icon when the icon is deleted.
see Jira!
Claire C she/her
=> AO3-6608 Delete Alt Text With Pseud Icon

app/views/profile/show.html.erb, features/other_a/profile_edit.feature
If the user's location is set to empty-string, omit the "I live in" section on their profile
https://otwarchive.atlassian.net/browse/AO3-6594
Hides the "I live in" section on the profile if the location is set to empty-string
Update your location to empty, make sure the corresponding section does not display on the profile view.
Eliah Hecht, he/him
=> AO3-6594 don't show location section if empty

Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6297
The MimeMagic removal commit d40d751 had some extra changes in the Gemfile.lock that led to various gems getting downgraded. Most likely this was caused by a merge conflict. This commit reverts the extra changes.
No extra testing.
I noticed this because nokogiri got downgraded to a vulnerable version and dependabot opened #4784 to upgrade it again.
Comparison between this branch and master before d40d751: https://github.com/otwcode/otwarchive/compare/test-0.9.367.5...Bilka2:AO3-6297-bot. Shows that after this PR, only following things are changed in the Gemfile.lock:
* The originally intended removal of MimeMagic.
* Update of net-smtp from 0.4.0 to 0.5.0. This was also introduced with d40d751. I decided not to revert it because it's a …
=> AO3-6297 Revert accidental gem downgrades in MimeMagic removal

app/views/user_mailer/claim_notification.html.erb, app/views/user_mailer/claim_notification.text.erb, config/locales/mailers/en.yml, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-4308
=> AO3-4308 Update claim email text with t's suggestion

public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-6570
Set word-wrap to break-word on the error element so that the text wraps properly and does not overflow.
Log in. 
Head to Import Work and enter a long external URL
Import it more than once and make sure the element doesn't spill out of the box - make your browser window small. 
Claire C
If you have a Jira account, please …
=> AO3-6570 Import Work error message overflows for long URLs

lib/html_cleaner.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6087
This will retain non-printable characters entered by the user in various places including the chapter text, comment, etc. They are necessary for representing characters in some languages.
Apparently the special characters caused problems to the parser in the past. While the details are unclear, we tentatively believe that is not the case any more.
Try entering text with zero-width joiner, zero-width non-joiner, and word joiner into the main text of a work, or into a comment. They should remain.
I believe this will also affect emojis with gender variants (and maybe other variants), as reported in …
=> AO3-6087 Stop removing non-printable Unicode characters

app/controllers/readings_controller.rb, app/controllers/works_controller.rb, features/other_a/reading.feature
https://otwarchive.atlassian.net/browse/AO3-5506
Don't include hidden works in reading history
* Require works to be visible to mark for later
* Hide draft works and hidden by admin works from the reading history
* Test for visibility of hidden by admin works in reading history
An automated test for hidden by admin works not being visible in the reading list is included. This may be tested manually by adding a work to a users reading list, an admin hiding it, and then viewing the users reading list and confirming it's absence.
Accessing a URL for a draft work like http://localhost:3000/works/110/mark_for_later (manually replace 110 with the id …
=> AO3-5506 Don't include hidden works in Readings

test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6704
Use `ArchiveConfig.APP_HOST` to create the URL for the abuse report in the abuse_report mailer preview. That way it uses a staging URL on staging.
See Jira.
Bilka (he/him)
=> AO3-6704 Use URL from current host in abuse report response mailer preview

config/initializers/gem-plugin_config/redis.rb, config/initializers/gem-plugin_config/resque.rb
https://otwarchive.atlassian.net/browse/AO3-6706
With some work I've done (and will do after this is merged) on the systems side, this will let us use Redis Sentinel to support automatic failovers when one Redis server becomes unavailable. This is better for High Availability and situations where we need to upgrade software/hardware.
For reviewers: I'd recommend turning whitespace diff off, since I made changes there to satisfy Rubocop.
=> AO3-6706 Support Sentinel config for Redis clients

app/views/user_mailer/feedback.html.erb, app/views/user_mailer/feedback.text.erb, config/locales/mailers/en.yml, features/other_b/support.feature, features/step_definitions/email_steps.rb, spec/mailers/user_mailer_spec.rb, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-5351
I18n-ising the remaining text in the feedback (support ticket) response emails. I didn't add a preview since I did that already in #4772.
=> AO3-5351 Make remaining text in feedback response i18n-able

factories/users.rb, test/mailers/previews/admin_mailer_preview.rb, test/mailers/previews/comment_mailer_preview.rb, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6017
Fix Error 422 "Validation failed: User name has already been taken" in some mailer previews on staging. This is done by using generated and thus hopefully unique user names when creating users for the previews.
Visit https://test.archiveofourown.org/rails/mailers/admin_mailer/comment_notification_official and https://test.archiveofourown.org/rails/mailers/comment_mailer/comment_reply_sent_notification and make sure they display working emails, not "Error 422".
Bilka (he/him)
=> AO3-6017 Use unique names for users in mailer previews

config/initializers/gem-plugin_config/redis.rb
https://otwarchive.atlassian.net/browse/AO3-6706
Fixes the redis initializer to properly launch during tests (when not using Docker or CI)
Issue identified by @sarken in https://otwarchive.atlassian.net/browse/AO3-6706?focusedCommentId=361335
=> AO3-6706 Fix Redis test config for non-docker

app/controllers/readings_controller.rb, app/decorators/homepage.rb, app/models/reading.rb, factories/readings.rb, spec/controllers/readings_controller_spec.rb, spec/models/reading_spec.rb, spec/models/search/homepage_decorator_spec.rb
Move `.or()` inside `.merge()` to prevent showing deleted works from other user's reading lists showing on all users' reading lists.
Fix for bug in AO3-5506 implementation: https://otwarchive.atlassian.net/browse/AO3-5506?focusedCommentId=361327
https://github.com/otwcode/otwarchive/pull/4781/ excluded admin works and never published works from the reading list. 
However there was a bug. `.or()` needs to be moved inside `.merge()` to ensure the generated SQL is correct. Previously deleted works from other users' reading lists were being shown for all users.
Bad SQL:
```
SELECT `readings`.* FROM `readings` LEFT OUTER JOIN `works` ON `works`.`id` …
```
=> AO3-5506 Don't include hidden works in Readings: fixed query

app/models/search/bookmark_indexer.rb, features/bookmarks/bookmark_search.feature, features/step_definitions/bookmark_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6522
Change the Elasticsearch analyzer for boorkmarker and creators so that numbers in names (like "testy2") are not ignored when searching.
I think the instructions given in the Jira issue will work. When testing in a local environment, you might need to (re)index new users and bookmarks you might have to create, and activate resque.
n/a
=> AO3-6522 Use standard analyzer for bookmarker and creators on bookmark search

app/models/search/work_indexer.rb, features/fixtures/works.yml, features/search/works_info.feature
https://otwarchive.atlassian.net/browse/AO3-6537
Titles may contain numbers and users expect to be able to search by them. I would like to change the analyzer from simple to standard, because [simple](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-simple-analyzer.html) ignores numbers.
See the Jira ticket.
I have a similar pull request at https://github.com/otwcode/otwarchive/pull/4647 (not yet merged). The other one is for bookmark search.
=> AO3-6537 Use standard analyzer for work title search

app/models/search/work_indexer.rb, app/models/work.rb, features/search/works_info.feature, features/search/works_tags.feature, features/step_definitions/work_search_steps.rb, spec/models/search/work_indexer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6729
Separate the fandoms and relationships `includes` in the WorkIndexer into two separate method calls. If they are combined, the second set of tags ends up with tags of the first type in their return value. So, in this case the Fandom tags ended up in `relationships`. `relationships` is used in `#otp` to determine OTP status, so that gets messed up by the extra Fandom tag(s). 
I adjusted the existing N+1 spec that was added together with the `includes` in #4291 to make sure `#otp` hits the line that queries the [merger](https://github.com/otwcode/otwarchive/blob/47cc03880769f4256456598e94eed99a8d6e0faf/app/models/work.rb#L1251).
This preload going wrong is most likely a Rails bug, I found a few Rails 7.0+ issues related to preloading leading …
=> AO3-6729 Fix searching for otp: true

app/views/comments/_comment_form.html.erb, features/comments_and_kudos/comment_moderation.feature
https://otwarchive.atlassian.net/browse/AO3-6739
If you accessed at a work with moderated commenting enabled in chapter-by-chapter mode, it said "Chapter" (the i18n key, which was wrong -- there's not a dedicated notice for chapters) instead of "This work's creator has chosen to moderate comments on the work. Your comment will not appear until it has been approved by the creator." 
Now it uses the right key and says the big long thing.
Refer to Jira.
https://github.com/otwcode/otwarchive/pull/4790
=> AO3-6739 Display moderated commenting notice on individual chapters

public/stylesheets/site/2.0/07-interactions.css, public/stylesheets/site/2.0/13-group-blurb.css, public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-6616
webkit did something terrible that affected the position of various form elements, most notably:
- the bottom Sort and Filter button on the filters has relocated to the top
- the notes options on the posting form has migrated upward to interfere with other form options
Full details are in the issue.
We'll want to test Safari 17 to make sure the issue is fixed _and_ at least one older version of Safari, plus Firefox and Chrome (any version), to make sure we didn't break anything new.
I diagnose the issue in [this comment](https://otwarchive.atlassian.net/browse/AO3-6616?focusedCommentId=360502).
=> AO3-6616 Fix floating and displaced form elements in new webkit

.rubocop.yml, Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6763
Due to the reviewdog changes, the rubocop error "An error occurred while Layout/BlockAlignment cop was inspecting ..." now makes the [action fail](https://github.com/otwcode/otwarchive/actions/runs/9941472849/job/27460594122). Previously this error also occurred but didn't affect the check status.
Updating rubocop gets rid of the error. This new version doesn't add any new cops, so we don't need to evaluate them.
I updated the TargetRubyVersion to 3.1 because according to https://docs.rubocop.org/rubocop/1.65/configuration.html#setting-the-target-ruby-version it should be the oldest Ruby version that we support. (This also means that the rubocop parser won't choke on Ruby 3.1 syntax.)
The action should succeed on this PR.
Bilka (he/him)
=> AO3-6763 Fix rubocop error by updating it

.github/workflows/phrase-export-checks.yml
https://otwarchive.atlassian.net/browse/AO3-6756
Adds a GitHub Action workflow. The workflow lists all redundant English keys that should be removed from Phrase. The check will show as failed if there are any and the list will be available as workflow artifact. Furthermore, the workflow runs the consistent interpolations check for all locales and uploads its result. If there are no redundant keys on Phrase then it also runs the unused keys check for all locales. The check will show as failed and the unused keys will be available as workflow artifact if there are any unused keys.
The workflow runs automatically when making a pull request from a branch named `phrase-translations`. Phrase does this when exporting strings to GitHub, so it should be fully automatic.
[Demo …
=> AO3-6756 Add i18n-tasks workflow for Phrase export PRs

.github/workflows/reviewdog.yml
https://otwarchive.atlassian.net/browse/AO3-6763, broken on test II
Sets fail_on_error for the reviewdog action so that the check is shown as failed when rubocop or erb-lint find an error. Currently the check shows as passed, see e.g. #4875.
Merge this into a PR with rubocop or erb-lint warnings and make sure that the reviewdog check on the PR fails.
Example PR: https://github.com/brianjaustin/otwarchive/pull/1
Bilka (he/him)
=> AO3-6763 Set github action check to fail if reviewdog finds an error

config/initializers/sentry.rb
https://otwarchive.atlassian.net/browse/AO3-6742
Make the Sentry initializer work on Resque workers by not expecting the rack environment to always exist
Refer to Sarken's comment on the Jira ticket
=> AO3-6742 Fix sentry initializer for Resque workers

app/helpers/tag_sets_helper.rb, docker-compose.yml, features/step_definitions/tag_set_steps.rb, features/support/paths.rb, features/tag_sets/tag_set_nominations.feature
https://otwarchive.atlassian.net/browse/AO3-6784
Fix error 500 when trying to view "My Nominations" or "Review Nominations" when a nominated tag was in the wrong category and that tag is a synonym or a canonical. This was discovered because AO3-6783 inserts the blank tag (a Fandom tag on staging) into other tag nomination categories, like character or relationship.
See Jira.
Bilka (he/him)
=> AO3-6784 Fix error 500 on nominations show/index with tag in wrong category

app/controllers/autocomplete_controller.rb, app/models/tagset_models/cast_nomination.rb, app/models/tagset_models/tag_nomination.rb, features/other_a/autocomplete.feature, features/step_definitions/tag_steps.rb, features/support/paths.rb, features/tag_sets/tag_set_nominations.feature
https://otwarchive.atlassian.net/browse/AO3-6783
If a tag nomination is blank (empty string for tagname) because it is meant to be destroyed, don't modify it in `before_save` and exclude it from certain validations.
`Tag.find_by(name: "")` where name is an empty string returns the broken blank tag. Tag nominations that are meant to be removed have an empty string for the tag name. So,  `Tag.find_by_name(tagname)` in TagNomination's `before_save :set_tag_status` returns the broken blank tag and its name is used to set the `TagNomination.tagname`. This means the nomination that was meant to be destroyed by  `after_save :destroy_if_blank` is no longer blank, instead it contains all the information from the broken blank tag so it doesn't get destroyed. There is no way to get rid of this tag …
=> AO3-6783 Fix that removing a tag nomination would result in a blank tag nomination

app/controllers/tag_wranglers_controller.rb, app/policies/tag_wrangler_policy.rb, app/policies/wrangling_policy.rb, app/views/tag_wranglers/show.html.erb, factories/wrangling_assignments.rb, features/tags_and_wrangling/tag_wrangling_admin.feature, spec/controllers/tag_wranglers_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6759
Update the `TagWranglersController` to verify the current admin has the right roles to access each action
=> AO3-6759 Check admin roles for actions in TagWranglersController

app/controllers/admin/admin_users_controller.rb, app/controllers/application_controller.rb, config/i18n-tasks.yml, config/locales/controllers/en.yml, features/admins/users/admin_abuse_users.feature
https://otwarchive.atlassian.net/browse/AO3-6728
Fix "Spammer: ban and delete all creations" option for PAC admins and delete the comments properly
=> AO3-6728 Delete comments properly for spammer bans

app/models/admin.rb, app/policies/comment_policy.rb, app/policies/user_creation_policy.rb, app/policies/user_policy.rb, config/locales/models/en.yml, features/admins/admin_works.feature, features/comments_and_kudos/admin_info.feature, features/importing/work_import.feature, spec/controllers/admin/admin_users_controller_spec.rb, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6010
Add a role for our Legal folks, along with some permissions for that role
=> AO3-6010 Add role for Legal

lib/css_cleaner.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5441
Adds support for the possible CSS `filter` functions.  See the [MDN for CSS Filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#syntax) for full details.
Put the following into a skin and make sure that after saving, the output matches the input and you don't get any error messages. Note that this won't actually do anything useful; it's just to make sure all the values are accepted.
```css
/* <filter-function> values */
.a  { filter: blur(5px);}
.b { filter: brightness(0.4); }
.c { filter: contrast(200%); }
.e { filter: drop-shadow(16px 16px 20px blue); }
.f { filter: grayscale(50%); }
.g { filter: hue-rotate(90deg); }
.h { filter: invert(75%); }
.i { filter: opacity(25%); }
.j { filter: saturate(30%); }
.k { filter: …
```
=> AO3-5441 Allow filter functions for CSS filter

app/jobs/report_attachment_job.rb, spec/jobs/report_attachment_job_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6563
Fix the error identified by Sentry by passing a new `FeedbackReporter` to the `send_attachment!` call in the background job. I tried passing the `reporter` from the `AbuseReport`, but it's not serialisable so that didn't work.
=> AO3-6563 Fix reporter for abuse download attachment

app/views/admin/admin_users/_user_creations_summary.html.erb, app/views/admin/admin_users/creations.html.erb, app/views/admin/admin_users/show.html.erb, config/locales/views/en.yml, features/admins/users/admin_manage_users.feature, features/step_definitions/admin_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6539
If an admin manually entered a URL with incorrect pagination params for user creations, they would see a page saying the user had no works or comments. Now it will not say that, but it will display empty list boxes with pagination links (if applicable) to be more consistent with other pages on the site.
I also:
* updated the heading on the user creation summary list boxes to say, "X - Y of Total Items"
* removed the `role="navigation"` from two lists, because that's not a valid way to use that attribute
* switched to `span_if_current` in the navigation, which is a little unnecessary, but never a bad idea for consistency
* added a "Creations" navigation item as a breadcrumb on the User Creations page
[What needs …
=> AO3-6539 Update user creation summary h3s and pagination behavior

app/jobs/report_attachment_job.rb, app/models/abuse_report.rb, app/models/feedback_reporters/feedback_reporter.rb, lib/zoho_auth_client.rb, lib/zoho_resource_client.rb, spec/jobs/report_attachment_job_spec.rb, spec/lib/zoho_auth_client_spec.rb, spec/lib/zoho_resource_client_spec.rb, spec/models/feedback_reporters/feedback_reporter_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6563
* Fix scopes for Zoho to get the required UPDATE permissions for attaching a file
* Force HTTParty to treat the HTML string as a file by using `StringIO` with a workaround
=> AO3-6563 Fix Zoho attachment calls to force multipart upload

app/views/admin_posts/show.html.erb, features/admins/admin_post_news.feature
https://otwarchive.atlassian.net/browse/AO3-6010
Change the permissions check for admin nav on the show admin post (news post) page to make sure admins who can moderate comments actually see that button. (I also updated edit/delete to check the exact permissions, instead of the generic `can_post?` in case those become different in the future.)
We discussed this in chat elsewhere, and while it's not really related to the issue at hand, it will reduce confusion in the long run so we can do it now.
=> AO3-6010 Show admin post actions to the correct roles

.gitattributes, features/tags_and_wrangling/tag_wrangling_fandoms.feature
https://otwarchive.atlassian.net/browse/AO3-6804
Fix flaky tag wrangling fandoms test by going directly to the tag edit page instead of following a link.
Also, make some changes to `.gitattributes` to fix the line endings of script files on Windows. This means that it is no longer necessary to manually set the line endings git configuration on Windows to get the scripts to run in Docker.
No manual QA required. Without the fix, [20 test runs](https://github.com/Bilka2/otwarchive/actions/runs/10656468709) resulted in 12 failures. With the fixes [40 test runs](https://github.com/Bilka2/otwarchive/actions/runs/10656444471) result in no failures.
Bilka (he/him)
=> AO3-6804 Fix flaky tag wrangling fandoms test

app/controllers/works_controller.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6796
This PR fixes a 500 error when `@fandom` variable in `WorksController#index` was `nil`. 
Now the `@fandom` is retrieved using `find` which will raise an `ActiveRecord::ErrorNotFound` and redirect to 404 if the id is invalid.
Access the following URL: `users/testuser/works?fandom_id=29292929`
It will raise an `ActiveRecord:: RecordNotFound` and be displayed as a 404 in production.
What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)? 
AliceLsr (feminine pronouns)
You can find me on Jira and assign it to …
=> AO3-6796 fix 500 error when trying to access user's works for invalid fandom_id

app/mailers/archive_devise_mailer.rb, app/models/user.rb, app/views/users/mailer/reset_password_instructions.html.erb, features/step_definitions/email_custom_steps.rb, features/users/authenticate_users.feature, test/mailers/previews/archive_devise_mailer_preview.rb, test/mailers/previews/kudo_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6772
Create reset_password_instructions mailer preview. Modify devise's mail sending to move the I18n.with_locale call so the locale dropdown in the mailer preview will work.
See Jira.
Bilka (he/him)
=> AO3-6772 Create reset_password_instructions mailer preview

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6749
In Low Vision Default:
* Brings the dropdown menus out from behind the top-level menu items in mobile.
* Ensures the background of the open top-level menu item is red on all screen sizes.
An admin with the superadmin role will need to copy the updated CSS into Low Vision Default *before* merging (to ensure it gets recached on deploying):
2. Skins > Approved Skins
3. Locate Low Vision Default in the table and click the title to open the skin show page
4. Follow the Edit link at the bottom to access the skin edit page
5. Copy the entire contents of public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css from this pull request
6. Paste into the CSS field on the skin edit page
7. Press Update to save …
=> AO3-6749 Fix main navigation position and color in Low Vision Default

config/locales/models/en.yml
https://otwarchive.atlassian.net/browse/AO3-4728
Customise the error that happens when a user tries to subscribe to a work (or other subscribable) after someone deletes it.
Various AD&T members for drafting the message copy
=> AO3-4728 Error message for subscribing to deleted item

app/controllers/works_controller.rb, spec/controllers/works/default_rails_actions_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6796
This PR is a follow up of this previously merged PR, after QA analysis: https://github.com/otwcode/otwarchive/pull/4898
The scenario this PR fixes is the following: 
> Tried one more test, where I completely deleted all numbers from the fandom_id (https://test.archiveofourown.org/users/testy/works?fandom_id=), which resulted in an Error 500!
Now, `fandom_id` will be ignored if  null.
Look at the test scenarios described in this issue: https://otwarchive.atlassian.net/browse/AO3-6796
And test again for "Tried one more test, where I completely deleted all numbers from the fandom_id". Expected …
=> AO3-6796 - fix QA returns for 500 error on fandom_id

app/controllers/comments_controller.rb, spec/controllers/comments_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6686
Switch back to polymorphic_path in the comments controller, since it's a bit more elegant than forcing `only_path`
(automated testing is enough for this)
=> AO3-6686 Bring back polymorphic_path

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6749
* In Low Vision Default, the top-level menu items sometimes had dark text when open, making them hard to read. Now they'll have light text.
* Adjusted the selector used on the site name in the header because it was weightier than it needed to be.
Make sure to follow the instructions in the Deploy Notes before setting to QA.
* To test the top-level menu items, refer to the second item in the Testing section of the Jira issue.
* To test the selector change, ensure the site name in the header remains white when you hover over it, give it keyboard focus, and click on it.
=> AO3-6749 Fix top-level menu item text color in Low Vision Default

app/views/subscriptions/index.html.erb, config/locales/views/en.yml, features/other_b/subscriptions.feature
https://otwarchive.atlassian.net/browse/AO3-4728
Update the I18n key for subscription bylines to make links render as links instead of `<a href="...`.
https://otwarchive.atlassian.net/browse/AO3-4728?focusedCommentId=361551
@Bilka2 for identifying where the bug was
=> AO3-4728 Allow HTML in subscription byline

.github/workflows/reviewdog.yml, app/models/tag.rb, features/tag_sets/tag_set_nominations.feature
https://otwarchive.atlassian.net/browse/AO3-5538
Changed `after_save :update_tag_nominations` on tags so that renaming a tag updates tag set nominations using the previous tag name, treating them as if the tag with the previous name was deleted. As per Jira, it does **not** rename the nomination.
See Jira.
I looked into the root cause of this issue while looking at the errors related to the blank tag in tag set nominations, see the [Jira comment](https://otwarchive.atlassian.net/browse/AO3-5538?focusedCommentId=361426).
Bilka (he/him)
=> AO3-5538 Update tag set nominations with old tagname when renaming tags

CONTRIBUTING.md, README.md
https://otwarchive.atlassian.net/browse/AO3-6815
Updates CONTRIBUTING.md to indicate to the user not to create duplicate support requests to try to limit the number of total support tickets.
Updates README.md to add the information about otw-coders@transformativeworks.org as a way of contacting the volunteers.
Just read over changes. No functionality changes.
Mugdha Gupta
She/Her
=> AO3-6815 Update Contributing Information

.github/workflows/automated-tests.yml
https://otwarchive.atlassian.net/browse/AO3-6824
Fix automated tests after GitHub updated the the action runner to Ubuntu 24.04 by installing the ImageMagick package.
Tests should pass on this PR.
You can also see the failing tests in [#4940](https://github.com/otwcode/otwarchive/pull/4940/commits/9e7f7bd02d4caf930efb1ee6f0d43b4c93851183) with the fixed tests visible with the [next commit](https://github.com/otwcode/otwarchive/pull/4940/commits/1ef675ee9602739fa98c987d77435883ff02d27a).
Bilka (he/him)
=> AO3-6824 Install imagemagick in automated tests

app/helpers/bookmarks_helper.rb, app/models/tag.rb, app/views/bookmarks/_bookmark_blurb_short.html.erb, app/views/bookmarks/_bookmark_user_module.html.erb, features/tags_and_wrangling/tag_wrangling_admin.feature
https://otwarchive.atlassian.net/browse/AO3-6825
When a wrangler or admin renames a tag, any bookmark blurbs using that tag should reflect the change. 
Refer to Jira.
Sarken
=> AO3-6825 Update bookmark blurbs when bookmarker's tags are renamed

config/config.yml, factories/tags.rb, features/importing/work_import.feature, features/search/works_tags.feature, features/step_definitions/work_import_steps.rb, lib/tasks/after_tasks.rake, public/help/warning-help.html, public/help/work-search-text-help.html, script/gift_exchange/tag_seed.json, spec/controllers/api/api_helper.rb, spec/lib/tasks/after_tasks.rake_spec.rb, test/fixtures/tags.yml
https://otwarchive.atlassian.net/browse/AO3-6831
* Adds two rake tasks: 
* `bundle exec rake After:add_suffix_to_underage_sex_tag` to rename the Underage Sex freeform to Underage Sex - Freeform
*  `bundle exec rake After:rename_underage_warning` to rename the existing Underage warning to Underage Sex
* Updates tests, configuration, and documentation to reflect the rename
None needed, already tested.
The TOS update itself will contain this change:
> 3. https://ao3.org/first_login_help   (https://github.com/otwcode/otwarchive/blob/1bdb4441e193ca269bb31f8c4a78ab5db7d1b663/app/views/home/first_login_help.html.erb#L125-L126) 
"and "Underage"" should be "and "Underage Sex"" 
This is because the TOS update internationalizes the text from that file, so there was no clean way to include the change …
=> AO3-6831 Rename the Underage warning tag

public/stylesheets/site/2.0/21-userstuff.css
[https://otwarchive.atlassian.net/browse/AO3-5421](https://otwarchive.atlassian.net/jira/software/c/projects/AO3/issues/AO3-5421?)
Adds `line-height` to list item tags within `.userstuff` class.
See Jira ticket
anechol (she/her)
=> AO3-5421 Adds line-height to userstuff list items

app/views/home/index.html.erb
https://otwarchive.atlassian.net/browse/AO3-4283
Makes HTML tag and classes of the Marked for Later module on the homepage consistent with the ones on the History and Marked for Later pages
1. Have a work marked for later
2. Create and use a site skin that attempts to target history blurbs, e.g.: `ol.reading .blurb { background: pink; }`
3. The Marked for Later blurbs on the homepage should have pink backgrounds
n/a
slavalamp (they/them)
same name on Jira
=> AO3-4283 make HTML and classes on the Marked for Later module consistent

public/stylesheets/site/2.0/21-userstuff.css
* [x ] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x ] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
https://otwarchive.atlassian.net/browse/AO3-5951
This PR ensures that unordered lists in work summaries or bookmark notes appear with items listed horizontally in blurbs. With this change, they now stack vertically, each with a black circle in front of them, like they display in the summary on the work itself.
Log in …
=> AO3-5951 Fix lists displaying inline in userstuff blurb areas

app/controllers/users_controller.rb, app/views/layouts/application.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6376
This PR adds conditional rendering of the singularised `controller_name` (User) based on whether the `controller.action_name` has 'change' in it (as in *change*_password, *change*_email etc.).
Follow the instructions in the description of the Jira ticket. 
N/A
phthallo [Annabel Quach] (they/them)
=> AO3-6376 Remove "User" from username, password and email change page titles

app/controllers/challenge_assignments_controller.rb, app/controllers/users_controller.rb, app/mailers/user_mailer.rb, app/models/challenge_assignment.rb, app/models/collection.rb, app/models/potential_match.rb, config/locales/mailers/en.yml, config/locales/models/en.yml, features/gift_exchanges/notification_emails.feature, features/step_definitions/email_custom_steps.rb, spec/mailers/user_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6268
Cesium-Ice, they/them
field on your Jira profile, so we can assign you the issues …
=> AO3-6268 Fix All challenge owners/moderators get CCed in "Assignments sent" notification

public/stylesheets/site/2.0/14-group-preface.css
https://otwarchive.atlassian.net/browse/AO3-6244
Fixed styling of links in preface on hover, in which underline was incorrectly added.
Follow Jira's Steps to reproduce:
1. Log in
3. Fill in required fields
4. For "Notes," check "at the beginning"
5. Include a link, e.g., <a href="#">Link</a>
6. Post
7. On a computer, hover over the link. 
8. Confirm underline is not added in addition to bottom border.
N/A
Paola Solari (she/her)
=> AO3-6244 Fixed underline added to some links in preface on hover

app/views/chapters/_chapter_form.html.erb, app/views/chapters/preview.html.erb, app/views/works/edit_tags.html.erb, app/views/works/new_import.html.erb, app/views/works/preview.html.erb, config/locales/views/en.yml
[https://otwarchive.atlassian.net/browse/AO3-6842](https://otwarchive.atlassian.net/browse/AO3-6842)
Mirrors the Content Policy and TOS FAQ reminder notice from AO3-6838 onto the chapter form, chapter preview, edit work tags, import work, and work preview forms.
lydia-theda
=> AO3-6842 Add Content Policy notice to all work forms

app/views/home/_dmca.html.erb, features/other_a/homepage.feature
No changed functionality.
https://otwarchive.atlassian.net/browse/AO3-6829
Update the DMCA page with the new html.
Go to https://archiveofourown.org/dmca and check for the new content.
I have a Jira account but no editing access. …
=> AO3-6829 updates to the dmca policy

config/initializers/cookie_rotator.rb
https://otwarchive.atlassian.net/browse/AO3-6812
Change the cookie rotator to force everyone to be backwards compatible (when before it didn't actually do anything :sob:)
Bilka (he/him)
=> AO3-6812 Modify cookie rotator to accept SHA256 cookies

app/mailers/user_mailer.rb, app/models/external_author.rb, features/importing/work_import.feature, features/step_definitions/work_import_steps.rb, spec/mailers/user_mailer_spec.rb, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6771
Change the claim_notification mail sending to respect the locale preference of the user the email address belongs to. At the same time, fix the locale selector in the email preview.
See Jira.
Bilka (he/him)
=> AO3-6771 Fix that claim_notification didn't respect user's locale preference

app/models/abuse_report.rb, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6832
If the URI indicates a comment or a work's comment thread, don't attach an HTML download of the work to the ticket.
Bypass/Comment out initial report send, fill in dummy `ticket_id`  ([link](https://github.com/otwcode/otwarchive/blob/dfaa140ed3b2d221d03d298040a94392fd6673b0/app/models/abuse_report.rb#L109C5-L120C31)), then verify `attach_work_download` returns early for non-work URLs
Jake Faulkner
=> AO3-6832 Don't attach work download to abuse report if provided comment URL

public/stylesheets/site/2.0/21-userstuff.css, spec/models/abuse_report_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6622
Adjusts the margins for `.userstuff` `dl` and `dd` elements within `.faq` containers to be smaller.
These margins can be seen on the `/faq` path (although there does not seem to be any FAQ data on my local...)
calm (they/them)
=> AO3-6622 Decrease margins on definition lists in FAQs

app/controllers/languages_controller.rb, app/policies/language_policy.rb, app/views/languages/_form.html.erb, config/locales/controllers/en.yml, config/locales/views/en.yml, spec/controllers/languages_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6792 
Adds support and policy_and_abuse roles to language policy + validation to disallow support and policy_and_abuse roles to edit certain fields in the form
If you have a Jira account, …
=> AO3-6792 Admins with the support and policy_and_abuse roles should be able to edit languages

app/controllers/feedbacks_controller.rb, app/helpers/skins_helper.rb, app/models/feedback.rb, app/models/feedback_reporters/abuse_reporter.rb, app/models/feedback_reporters/feedback_reporter.rb, app/models/feedback_reporters/support_reporter.rb, app/views/feedbacks/new.html.erb, config/locales/views/en.yml, spec/controllers/feedbacks_controller_spec.rb, spec/helpers/skins_helper_spec.rb, spec/models/feedback_reporters/support_reporter_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6232
Adds custom field to Zoho tickets for the submitter's IP address, referer, and the skin they're using at the time of submitting a support ticket
The names in this PR will need a final approval from support before merging, to make sure they've created the fields in Zoho as required
=> AO3-6232 Include IP, referer, skin in support tickets

app/controllers/languages_controller.rb, features/admins/admin_languages.feature
https://otwarchive.atlassian.net/browse/AO3-6792
Fix bug that QA found
field on your Jira profile, so we can assign you the issues …
=> AO3-6792: fix logic to account for the fact that language_params can be blank

lib/css_cleaner.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6864
Match the whole string when checking URL values in the CSS cleaner.
Bilka
=> AO3-6864 Disallow URLs followed by something else in CSS

app/controllers/feedbacks_controller.rb, app/views/feedbacks/new.html.erb, features/other_b/support.feature, features/step_definitions/support_steps.rb, spec/controllers/feedbacks_controller_spec.rb
Fixes an issue where referrer is always the support ticket form, plus a test I missed in #4989.
=> AO3-6232 Fix referer for support tickets

app/controllers/tag_set_nominations_controller.rb
Doc change, no Jira.
Add a comment to tag_set_nominations_controller.rb to explain how the limit for showing tag set nominations for review works. Mention that https://otwarchive.atlassian.net/browse/AO3-3764 exists to change this behaviour.
There is a flash notice shown to users when there are more nominations than the limit.
Based on internal discussion.
Bilka
=> Add comment about tag set nomination review limit

test/fixtures/roles.yml, test/fixtures/roles_users.yml
https://otwarchive.atlassian.net/browse/AO3-6866
Make the role setup for new local dev environments and tests match production.
Automated tests should pass. I also recreated my local dev database with `./script/reset_database.sh` and confirmed that the roles are created.
Bilka
=> AO3-6866 Add no_resets and protected_user user roles to test fixtures

app/helpers/collections_helper.rb, app/helpers/skins_helper.rb, app/helpers/users_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5578
Update the manual calls to `(.processed).url` to use the Rails URL helper instead. This will set a URL that CloudFlare can proxy, versus the current direct link to S3.
=> AO3-5578 Use rails_blob_url to allow ActiveStorage caching

app/controllers/invite_requests_controller.rb, config/locales/controllers/en.yml
… Requests
https://otwarchive.atlassian.net/browse/AO3-5843 
This changes and updates the browser page title from Invite Requests to Invitation Requests on the Invitation Requests page.
If "Invitation Requests" page is rendered, browser title page should display "Invitation Requests | Archive Of Our Own" instead of "Invite Requests | Archive Of Our Own". 
What name and …
=> AO3-5843 change Invite Requests browser page title to Invitation Requests

lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-5578
Update the icon copy tasks to try to be nicer to the prod database (in particular the pseuds table).
=> AO3-5578 ActiveStorage copy script performance fixes

.github/workflows/automated-tests.yml, docker-compose.yml
https://otwarchive.atlassian.net/browse/AO3-6873
Upgrade Elasticsearch for dev and automated tests so that I can use Linux Kernel version 6.12
Automated tests should pass.
Bilka
=> AO3-6873 Upgrade Elasticsearch for dev and automated tests

lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-5578
Try and reduce the load on the database, we might be able to remove the sleep.
james_/Him
=> AO3-5578 Add a transaction to Psued image migration

lib/tasks/after_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-5578
Does as little as possible with an open DB connection (and using the DB in general, mostly by offloading the work onto pulling from S3 directly)
=> AO3-5578 Try to be nicer to the database when copying icons

public/help/skins-creating.html
https://otwarchive.atlassian.net/browse/AO3-6862
Minor help document change: replace a "fake" domain with the official IANA example domain (and use https)
I also did a quick search for other incorrect example URLs. I didn't find any public ones, though I did find
https://github.com/otwcode/otwarchive/blob/6a471a1447cedbed74c9090c5d0f11669a599914/spec/controllers/api/v2/api_works_spec.rb#L21-L25
but since that's just a test, probably fine. Also, a good amount of http (not s) links, but those mostly get redirected to HTTPS by modern browsers anyhow.
https://github.com/otwcode/otwarchive/blob/6a471a1447cedbed74c9090c5d0f11669a599914/features/fixture …
=> AO3-6862 Use official example domain

app/helpers/comments_helper.rb, app/views/comments/unreviewed.html.erb, features/admins/admin_works.feature, features/step_definitions/web_steps.rb
https://otwarchive.atlassian.net/browse/AO3-5977
Hides the "Approve All Unreviewed Comments" button if an admin is viewing a work with comment moderation turned on.
Jake Faulkner
=> AO3-5977 Hide "Approve All Unreviewed Comments" button from admins on works

app/models/concerns/justifiable.rb, app/views/pseuds/_pseuds_form.html.erb, app/views/users/edit.html.erb, config/locales/models/en.yml, config/locales/views/en.yml, features/other_a/profile_edit.feature, features/other_a/pseuds.feature, spec/models/concerns/justifiable_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6587
This pull request will allow AO3 Support staffers to copy/paste Ticket ID numbers from their internal tools. This copied data often includes an "#" character, which staffers have to manually erase. 
Previously, a live validation check would prevent staffers from hitting the "Update" button. Now, live validation is removed and the initial "#" is automagically stripped from the copied Ticket ID before validation.
Validation will allow an "#" in the first character position. If an "#" or any other character is in any other position, validation will fail.
Automated tests were updated to check for the above validation conditions, they can be manually checked as follows:
1. Copy the ticket ID from the ticketing platform and note that it comes …
=> AO3-6587 Allow # as initial character in Ticket ID Field when editing a profile or pseud

factories/tags.rb, test/mailers/previews/user_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6848
Solves that the first few visits of https://test.archiveofourown.org/rails/mailers/user_mailer/user_mailer/challenge_assignment_notification_filled would result in an error 422 because the preview would try to create tags that already exist in the archive by generating more unique tag names.
Step 3 and 4 from the original issue.
Bilka
=> AO3-6848 Create unique tags for mailer preview

Gemfile, Gemfile.lock
https://otwarchive.atlassian.net/browse/AO3-6889
Add the rack-timeout gem so we can cut off long-running requests that are causing performance issues
Caveats: https://github.com/zombocom/rack-timeout/blob/main/doc/risks.md
We should also be aware that this can negatively impact downloads. Those can already be a bit iffy performance-wise, and I've noticed longer works can be in the minutes range to complete requests. Perhaps we _want_ to cut those off earlier though 🤔
=> AO3-6889 Add rack-timeout gem

Gemfile, Gemfile.lock, config/config.yml, config/initializers/puma_worker_killer.rb
https://otwarchive.atlassian.net/browse/AO3-6890
=> AO3-6890 Add puma worker killer gem

config/config.yml
With my Systems hat on, I saw that we can't actually use these in `conf/puma.rb`. So no point in keeping them here and causing confusion.
=> AO3-6890 Remove unusable config

config/resque_schedule.yml
https://otwarchive.atlassian.net/browse/AO3-6897
Change run_background_reindex_queue to run every 11 minutes to hopefully overlap less with other jobs and other database load spikes.
Bilka
=> AO3-6897 Change run_background_reindex_queue to run every 11 minutes

app/models/collection_item.rb, features/bookmarks/bookmark_create.feature, features/collections/collection_notification.feature
https://otwarchive.atlassian.net/browse/AO3-6872
Skips the attempt to notify creators when an archivist adds a non-work (a bookmark) to a collection.
Also adds a test to verify that a notification is still sent when a work is added to a collection by an archivist.
See instructions on the Jira issue.
N/A
marcus8448 (he/him)
=> AO3-6872 Only notify creators when a work is added to a collection by an archivist

config/config.yml, public/help/skins-creating.html, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6766
* Updates config.yml to allow the `color-scheme` CSS property
* Refer to the testing instructions in the ticket for sample CSS code
David Bilsky/Ironskink (He/Him)
=> AO3-6766 Allow color-scheme in skins

app/models/tag.rb, features/step_definitions/tag_steps.rb, spec/models/tag_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6777
Forbid tag names that consist exclusively of Unicode characters from the [format category](https://www.compart.com/en/unicode/category/Cf) because they end up looking blank.
See Jira.
This validation is based on the fact that AO3-6087 created this bug by no longer stripping these characters from tag names.
Bilka (he/him)
=> AO3-6777 Fix that tag names could be blank

app/controllers/tags_controller.rb, app/helpers/tags_helper.rb, config/locales/controllers/en.yml, spec/controllers/tags_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6859
Only check auth if the tag is banned, so non-wrangler admin roles can view normal tags.
Drop comment that doesn't describe the action anymore.
Tweak check so wrangler tools are fully hidden for non-wrangler admins.
Fix test that was calling the wrong (?) action.
I'm not fully certain why the auth check was added to #show, so I'm assuming that it was meant to only apply to Banned tags.
Jake Faulkner
=> AO3-6859 Fix admins being disallowed from tags pages

config/locales/models/en.yml, spec/models/bookmark_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6820
Change the error message from "Pseud must exist" to "Pseud can't be blank".
Refer to Jira.
https://otwarchive.atlassian.net/browse/AO3-6820?focusedCommentId=362235
Bilka
=> AO3-6820 Update error message to "Pseud can't be blank"

.github/PULL_REQUEST_TEMPLATE.md
None, doc change.
Add some more instructions to the PR template based on common mistakes and some feedback from a contributor. The comment will show up in the template but not the final PR, so it's a great way to give "how to use this" instructions, I saw it in the rails repository.
Bilka
=> Add more instructions to pull request template

app/jobs/async_indexer_job.rb, app/models/search/async_indexer.rb, config/environments/production.rb, spec/lib/tasks/notifications.rake_spec.rb, spec/models/search/async_indexer_spec.rb, spec/models/search/index_sweeper_spec.rb, spec/spec_helper.rb
https://otwarchive.atlassian.net/browse/AO3-6901
Move the asynchronous part of [AsyncIndexer](https://github.com/otwcode/otwarchive/blob/671cdb9273be76984a14957bfe7e44f0c7bfd841/app/models/search/async_indexer.rb#L56) to Active Job.
I thought about setting `config.active_job.queue_adapter = :test` for all of the test environment, but that broke too many things, including all Cucumber tests expecting emails sent with `deliver_later`. On top of that, pre-7.2 Rails does not consistently follow that setting which complicates things (https://github.com/rails/rails/pull/48585). I'm keeping test updates simple for now.
See issue.
=> AO3-6901 Use ActiveJob for asynchronous indexing

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/readings_controller.rb, app/controllers/works_controller.rb, app/helpers/application_helper.rb, app/helpers/pagination_helper.rb, app/views/bookmarks/index.html.erb, app/views/readings/index.html.erb, app/views/works/index.html.erb, config/brakeman.yml, config/initializers/gem-plugin_config/pagy.rb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6880
As per ticket.
Visible (frontend) differences from will_paginate:
- `rel="prev"` and `rel="next"` have disappeared but seem to be obsolete anyway (cf https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading)
- Weird `title` attributes (all equal to an untranslated "pagination" string) have not made the cut
- Blank space characters between `<li>` tags have been removed. In other words, the HTML was previously `</li> <li>` and is now `</li><li>`. This means the pagination is slightly more compact looking. Maybe need to add back some padding in CSS?
- will_paginate was always showing the first two and the last two items in the list (`1 2 ... <> ... 312 313`) while pagy only shows the very first and …
=> AO3-6880 Use pagy gem for pagination on select pages

.github/workflows/reviewdog.yml
https://otwarchive.atlassian.net/browse/AO3-6909
It gets ahead of the dependabot PR to update the action so that we can bundle the input change in the same PR. This is the same change as #4975 but for erblint instead of rubocop, now that the erblint action also supports the new flag.
Bilka
=> AO3-6909 Bump tk0miya/action-erblint to 44c5fe3

test/fixtures/admins.yml, test/fixtures/users.yml
https://otwarchive.atlassian.net/browse/AO3-6904
This PR modifies two fixture entries: admins.yml and users.yml. In each, one of the users has their encrypted password changed from the hash to a function that allows the password to be read in plaintext.
CJ G
=> AO3-6904 Set passwords of testuser and testadmin in fixtures to known values

config/config.yml
https://otwarchive.atlassian.net/browse/AO3-6893
@zz9pzza referenced [this blog post](https://www.percona.com/blog/dont-auto-pt-online-schema-change-for-tables-with-foreign-keys/). Our options:
- `rebuild_constraints` is safest but slow since it involves copying data from the old to the new table.
- `drop_swap` is fast but risky and not rollback friendly.
- `auto` is not a real third option, it picks between the first two by estimating how long it takes to copy data between the two tables.
Since we're using MariaDB, rebuilding constraints as an online operation can be fast (not requiring a full table copy) [as long as we disable `foreign_key_checks`](https://mariadb.com/kb/en/innodb-online-ddl-operations-with-the-inplace-alter-algorithm/#alter-table-add-foreign-key):
> InnoDB supports …
=> AO3-6893 Use rebuild_constraints to modify foreign keys

config/initializers/monkeypatches/departure.rb
https://otwarchive.atlassian.net/browse/AO3-6893
Add a monkeypatch to avoid not unlocking the lock Rails migrations acquire via `GET_LOCK()`. Workaround for https://github.com/departurerb/departure/issues/110 until I (or someone else) can PR a fix.
Thanks to @scottsds for helping test this!
=> AO3-6893 Patch departure to prevent DB locking error

config/initializers/monkeypatches/departure.rb
https://otwarchive.atlassian.net/browse/AO3-6893
I did this the wrong way in in #5068 , and testing did not hit the right parts to trigger the original bug. This pulls from the linked issue directly to fix things. (Good news, I think this means the upstream fix will be pretty simple... hopefully)
=> AO3-6893 Patch departure the right way to prevent lock issues

app/controllers/series_controller.rb, config/locales/controllers/en.yml, spec/controllers/series_controller_spec.rb
https://otwarchive.atlassian.net/issues/AO3-6769
The browser page title for a mystery series should say “Mystery Series | SITE NAME” instead of just "Mystery Series".
1. Log in
2. Create an unrevealed collection
a. Browse > Collections
b. Press “New Collection”
c. Fill in “Collection name” and “Display title”
d. Tick the checkbox for “This collection is unrevealed”
e. Press “Submit”
3. Create a series in the collection
a. On the collection’s page, press “Post to Collection”
b. Fill in the required fields in the work form
c. Tick the checkbox for “This work is part of a series”
d. Fill in “Or create and use a new one“
e. Press “Post”
4. Go to the …
=> AO3-6769 Fix series browser page title for mystery series missing site name

app/models/language.rb, db/migrate/20241227165942_add_unique_index_to_languages.rb, db/schema.rb, lib/tasks/language_tasks.rake, spec/models/language_spec.rb, spec/models/search/bookmark_search_form_spec.rb, spec/models/search/work_search_form_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6868
This adds two form validations to the language form on the `/languages/<language abbreviation/edit` page:
* validates that the display name is not a duplicate
* validates that the abbreviation is 4 characters or fewer 
Also:
* added rake task to check for duplicate language names before running migrations
* `rake db:check_language_name_duplicates`
* fixed some existing tests that were failing on the new validations and rubocop
1. Login as an admin
2. Go to `/languages`
3. Click `Edit` on any of the languages
4. Change the display name to one that already exists
5. Change the abbreviation to …
=> AO3-6868 Add language form validation

app/helpers/mailer_helper.rb, app/views/admin_mailer/set_password_notification.html.erb, app/views/admin_mailer/set_password_notification.text.erb, app/views/user_mailer/_work_info.html.erb, app/views/user_mailer/_work_info.text.erb, app/views/user_mailer/abuse_report.html.erb, app/views/user_mailer/abuse_report.text.erb, app/views/user_mailer/challenge_assignment_notification.html.erb, app/views/user_mailer/challenge_assignment_notification.text.erb, config/locales/mailers/en.yml, spec/helpers/mailer_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6903
Remove the extra spaces after the labels in the `challenge_assignment_notification` and `abuse_report` mailers. Convert the `challenge_assignment_notification` to use the existing methods for adding the `metadata_label_indicator`. Address a todo to remove the word "work" from those methods, separated into an extra commit for easier reviewing.
Also, make the rating label in challenge_assignment_notification pluralize because I realized that I forgot that in the initial preview changes.
Refer to Jira.
Bilka
=> AO3-6903 Remove extra spaces after colons in mailers

app/controllers/pseuds_controller.rb, spec/controllers/pseuds_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6790
When navigating to an edit page for a pseud that doesn't exist (`/users/valid_user/pseuds/fake_pseud/edit`), we should return a 404 error 
Steps to reproduce, from JIRA:
1. Log in
2. Attempt to access the edit pseud page for a nonexistent pseud on your account. For example, if you are logged in as testy and don't have a pseud named annoying_error, enter the following URL in your browser: https://test.archiveofourown.org/users/testy/pseuds/annoying_error/edit
1. Log in as an admin who can edit pseuds (policy_and_abuse or superadmin)
2. Attempt to access the edit pseud page for a nonexistent pseud …
=> AO3-6790 Raise 404 when attempting to edit pseud that doesn't exist

app/models/search/query.rb, spec/models/search/query_spec.rb
https://otwarchive.atlassian.net/browse/AO3-4735
To make the title search not fail with an stand-alone "-" between words.
Queries like the one given in the Jira issue should work now when entered in "Title" under "Work info" in the search page.
Note that the system won't check whether a field has "-" or not anyway. `some - thing` will effectively the same as `some thing` in queries.
=> AO3-4735 Don't treat "-" as NOT when it is alone

public/stylesheets/site/2.0/12-group-meta.css
https://otwarchive.atlassian.net/browse/AO3-6888
Fixes the alignment of tags and stats in work meta when the lines wrap.
I used `margin-block`, `margin-inline`, `padding-block`, and `padding-inline` because there's a slight improvement when
- a containing element (such as the `dd` or `ul`) has `dir="rtl"` applied, and
- the list of tags includes both English and a RTL language
The improvement? The comma was on the left of the English tag (i.e., it obeyed the direction rules of the container) instead of the right.
We won't ever actually encounter that scenario with the current code, but hey, let's do it anyway.
Refer to Jira.
#1919 and #1930 
=> AO3-6888 Better align tags and stats in work meta

app/helpers/tags_helper.rb, app/views/tags/show.html.erb, features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-3945
Order the subtag list on tag pages by name.
PR Limit: 7 out of 5
Using reviewer bonus:
https://github.com/otwcode/otwarchive/pull/4264
https://github.com/otwcode/otwarchive/pull/4721
Bilka
=> AO3-3945 List subtags in alphabetical order

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css, public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-6737
I told james_ to remove some styles in #4808 ([AO3-6725](https://otwarchive.atlassian.net/browse/AO3-6725)) and I was wrong; when we removed them, the recent bookmarks on tag bookmark listings got too narrow and (in Low Vision Default) acquired all sorts of silly borders.
This puts that area back to the way it was.
Refer to Jira.
#4808 // [This comment ft. me being wrong](https://github.com/otwcode/otwarchive/pull/4808#issuecomment-2111323863)
#4825
#4846
[AO3-6725](https://otwarchive.atlassian.net/browse/AO3-6725)
[AO3-6725]: https://otwarchive.atlassian.net/browse/AO3-6725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AO3-6725]: …
=> AO3-6737 Fix display of recent bookmarks module

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6737
Fixes the display of bookmark blurbs on filterable index pages, so they are 100% rather than 75%.
Note that a superadmin needs to copy this CSS into Low Vision Default and Systems needs to recache the skins.
1. Log in
2. Choose "Low Vision Default" from the list of skins in the footer
3. Go to a page that would usually show bookmarks with filters, like https://test.archiveofourown.org/users/USERNAME/bookmarks
4. Verify the blurbs take up about 100% of their allotted width rather than 75%
- [Comment with screenshot of the issue](https://otwarchive.atlassian.net/browse/AO3-6737?focusedCommentId=362781) 
- [Comment with explanation of the issue](https://otwarchive.atlassian.net/browse/AO3-6737?focusedCommentId=362785)
=> AO3-6737 Bookmark blurbs should be full width on Low Vision Default

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6737
If there's no landmark heading between the floated subnavigation and the index of blurbs, the blurbs get a bit squished off to the left. This lets them extend to the right.
1. Log in
2. Apply Low Vision Default skin 
3. Go to a work
4. Bookmark the work
On the page you see after bookmarking the work, the blurb should no longer have a gap on the right the approximate width of the “My Bookmarks” button
=> AO3-6737 Make index clear nav in Low Vision Default when no landmark is present

public/stylesheets/masters/low_vision_default/low_vision_default_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6737
Adds padding to the bookmarker module as long as we're examining its faults.
Make a bookmark. Look at it. There should be white space around its content, keeping it far-ish from the border. It should look okay in a variety of window sizes.
The box sizing and padding usually comes from the default blurb stylesheet, which we drop for Low Vision Default.
=> AO3-6737 Add padding to bookmarker module

app/models/abuse_report.rb, app/models/comment.rb, app/models/feedback.rb, app/models/work.rb, spec/models/abuse_report_spec.rb, spec/models/comment_spec.rb, spec/models/feedback_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6544
Lets the spam checker know if it's checking 
- content from a guest or (on the Suport and PAC contact forms) someone who is logged in but has entered an email address that isn't the one on their account
- content from a contact form, blog (admin post) comment, or fanwork comment (as opposed to a fanwork)
Refer to Jira
* [Akismet comment check docs](https://akismet.com/developers/detailed-docs/comment-check/)
* A June 21, 2023 email discussion with the Akismet devs saying this would be nice to eventually have
=> AO3-6544 Send comment_type and user_role to spam checker for tickets and comments

app/views/abuse_reports/new.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6922
Updates the wording and links of the "Description of the content you are reporting" note
per discussion in jira+slack
lydia-theda
=> AO3-6922 (BOT) fix link abuse form footnote

features/search/filters.feature, features/step_definitions/search_steps.rb
https://otwarchive.atlassian.net/browse/AO3-6943
Add some indexing and waiting steps to the search filters features to make sure the dashboard count and its cache are up to date.
No manual QA required. Without the fix, [20 test runs](https://github.com/Bilka2/otwarchive/actions/runs/13882003791) resulted in 12 failures. With the fixes [20 test runs](https://github.com/Bilka2/otwarchive/actions/runs/13882215668) result in no failures.
PRs with failures:
#5096 https://github.com/otwcode/otwarchive/actions/runs/13869384770/job/38814060572
#5100 https://github.com/otwcode/otwarchive/actions/runs/13865383071/job/38803258894 (with partial fix)
Bilka
=> AO3-6943 Fix flaky search filtering tests

app/controllers/autocomplete_controller.rb, features/other_a/autocomplete.feature
https://otwarchive.atlassian.net/browse/AO3-6439
Fix the pseud autocomplete on the people search page when typing a space into the field
Bilka
=> AO3-6439 Fix pseud autocomplete on people search page when searching for a space

app/models/collection.rb, app/models/pseud.rb, app/models/skin.rb
Issue: https://otwarchive.atlassian.net/browse/AO3-6955
hi i'm melo, i run superlove. i contacted the address `otw-coders@transformativeworks.org` about a potential fix for GIF icons not animating after the active storage migration, because i did a similar migration on my own site and noticed the same problem, and managed to fix it last night. i got a response that recommended i do a pull request so i've done so.
i'm unable to test this on a personal developer instance because my own dev instance is an experimental dockerized production instance that's not up to date, so keep that in mind.
=> AO3-6955 fix gif icons not animating

app/views/tags/show.html.erb, features/other_b/fandoms.feature, features/tags_and_wrangling/tag_fandom_relationships.feature
https://otwarchive.atlassian.net/browse/AO3-6751
Ensures period in the fandom tag page for fandoms with periods is properly escaped in the URL. Changed fandom_path(@tag.name) to fandom_path(@tag) in the app/views/tags/shot.html.erb file on line 32
1) Go to https://archiveofourown.org/tags/Harry%20Potter%20-%20J*d*%20K*d*%20Rowling
2) Follow the 'Relationship tags in this fandom' link,
3) You should get a link that is properly escaped like this: https://archiveofourown.org/fandoms/Harry%20Potter%20-%20J*d*%20K*d*%20Rowling
Emily Wiegand (she/her)
=> AO3-6751 Fix "Relationships by Character" url for fandoms with periods

app/models/story_parser.rb, spec/models/story_parser_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5744
Handle relative redirects in work importing by using the original request host for relative redirect targets instead of trying to directly go to a target like `/856.html`. 
More candidate URLs for testing are multichapter works on otwarchive sites because they do a relative redirect to the first chapter. E.g. https://squidgeworld.org/works/34491 redirects to /works/34491/chapters/76104
Bilka (he/him)
=> AO3-5744 Fix following relative redirects in work importing

public/stylesheets/site/2.0/18-zone-searchbrowse.css
https://otwarchive.atlassian.net/browse/AO3-5596
Makes fandom boxes in All Fandoms have no big gaps when they're displayed in two columns and have unequal height
1. Open the All Fandoms page
2. The browser window width needs to be such that the fandoms are displayed in two columns and a box on the left needs to be taller than the box to its right, you might need to resize the window to achieve that. (For reference, for me this happens with all window widths between 880-1572px right now, but it might vary based on fandom sizes/fonts/etc)
3. There should not be a big empty space below the left box
n/a
slavalamp (they/them)
=> AO3-5596 Make boxes on All Fandoms page clear properly

.erb-lint.yml, app/controllers/invite_requests_controller.rb, app/models/admin_setting.rb, app/models/invite_request.rb, app/views/admin/admin_invitations/index.html.erb, app/views/admin/settings/index.html.erb, app/views/invite_requests/_index_closed.html.erb, app/views/invite_requests/_index_open.html.erb, app/views/invite_requests/_invite_request.html.erb, app/views/invite_requests/status.html.erb, config/config.yml, config/locales/controllers/en.yml, config/locales/views/en.yml, config/resque_schedule.yml, features/admins/admin_invitations.feature, features/other_a/invite_queue.feature, features/other_a/invite_request.feature, features/step_definitions/admin_steps.rb, spec/controllers/invite_requests_controller_spec.rb, spec/models/invite_request_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6913
https://otwarchive.atlassian.net/browse/AO3-6597
Change the invite queue check to run every hour so that it can be configured to send invitations every N hours.
Finish off the i18n of the pages because the strings had to be touched anyway.
Refer to both Jira issues.
PR Limit: 7 out of 5
Using reviewer bonus:
#4893
#4912
Bilka
=> AO3-6913 AO3-6597 Allow queue to send invitations every N hours

app/views/works/_work_header_notes.html.erb, features/prompt_memes_b/challenge_promptmeme_posting_fills.feature, features/prompt_memes_c/challenge_promptmeme_claims.feature
https://otwarchive.atlassian.net/browse/AO3-6877 
A work that fulfills a prompt is posted with a note: “In response to a prompt by whoever in the Collection Title collection.” The collection title is used in this note now instead of the collection name. 
Emily Wiegand (she/her)
=> AO3-6877 Change collection name to title for notes on works that fill prompts

app/views/orphans/_orphan_pseud.html.erb, app/views/orphans/_orphan_series.html.erb, app/views/orphans/_orphan_user.html.erb, app/views/orphans/_orphan_work.html.erb, app/views/users/change_username.html.erb, app/views/works/_adult.html.erb, app/views/works/confirm_delete_multiple.html.erb, public/stylesheets/masters/reversi/reversi_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6961
Updates some HTML classes to ensure we have consistent styling of caution text, and updates Reversi so the caution text isn't the same color as regular text.
Refer to Jira.
=> AO3-6961 Fix incorrect classes on caution text and update Reversi styling of caution text

public/stylesheets/site/2.0/22-system-messages.css
https://otwarchive.atlassian.net/browse/AO3-6957
Fix highlight error for form fields outside definition lists.
Isabel Nunes (she/her)
=> AO3-6957 Fix highlight for form fields outside dl's

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/views/errors/timeout.html.erb, app/views/errors/timeout_error.html.erb, config/locales/controllers/en.yml, config/locales/views/en.yml, config/routes.rb, spec/controllers/errors_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6911 
1. Add a page under `/timeout` that is returned should the app controller encounter `Rack::Timeout::RequestTimeoutException`. 
2. Added a test that the page is rendered on that route.
3. Added a test that the `auth_error` page is rendered on its route to `errors_controller_spec.rb`
*Needs Systems change*, see story for details
I added a unit test that this page can be routed too, but I do not think there is a way to test the actual timeout rescue except from an integration test. [See the docs here.](https://github.com/zombocom/rack-timeout/blob/main/doc/exceptions.md) If I'm missing something or …
=> AO3-6911 Add error page for Rack::Timeout::RequestTimeoutException

app/models/skin.rb, spec/models/skin_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6935
Change the validation so you no longer get a confusing error 500 when your skin title matches another one except for capitalisation.
Bilka
=> AO3-6935 Change skin title uniqueness validation to case insensitive

app/models/comment.rb, config/locales/models/en.yml, spec/models/comment_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6956 
This pull request changes the error message upon posting a duplicate comment from "This comment has already been left on this work. (It may not appear right away for performance reasons." to the more descriptive (and accurate) "You’ve already left this comment here. (It may not appear right away for performance reasons.)"
niic (he/him)
=> AO3-6956 Corrected error message for duplicate comments

public/stylesheets/site/2.0/10-types-groups.css
https://otwarchive.atlassian.net/browse/AO3-6896
word-wrap the text so it won't go over the div and cause awkward horizontal scroll.
- change your username to a long username (40 char)
- leave kudos in a work
- check if the text goes over the div
- also go to `/works/[work_id]/kudos` to check if it goes over the div
Michelle Tanoto
=> AO3-6896 Fix long username in kudos going over container

features/admins/admin_works.feature, features/comments_and_kudos/inbox.feature, features/comments_and_kudos/spam_comments.feature, features/step_definitions/admin_steps.rb, features/step_definitions/comment_steps.rb, features/step_definitions/orphan_steps.rb, features/step_definitions/pseud_steps.rb, features/step_definitions/work_steps.rb, features/works/work_create.feature, features/works/work_delete.feature, features/works/work_edit.feature, features/works/work_notes.feature, features/works/work_share.feature
https://otwarchive.atlassian.net/browse/AO3-6965
Optimize the feature tests by using FactoryBot to create works. Only touches files where the speedup was significant (more than 15% and more than ~10 seconds) or there were some other issues with the tests - refer to the commit messages.
The automated tests should pass. 
Based on a conversation from April 2022 where ticking instant said:
> It would be nice to find more ways to save time in tests. A lot of `I post the work` steps could probably use `FactoryBot` instead (though we might need to switch `User.current_user` to being set in an `around` hook, so that it can be cleared after each request).
Bilka
=> AO3-6965 Optimize feature tests by creating works with FactoryBot

features/other_a/autocomplete.feature, lib/autocomplete_source.rb
https://otwarchive.atlassian.net/browse/AO3-6945
Makes autocomplete treat | as a word delimiter, which should make it parse queries like "taylor|skitter" correctly and not take 3-50 times longer to search when the query has " | "
slavalamp (they/them)
=> AO3-6945 Treat vertical bar (pipe, |) as a word delimiter in autocomplete

app/models/kudo.rb, config/locales/models/en.yml, features/comments_and_kudos/kudos.feature, lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb, spec/models/kudo_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6401
Adds an error message if you're logged in with your official account and try to leave kudos. Also adds a task to clean up any kudos from existing official accounts.
Note: There are only 22 official accounts and I'm sure very few, if any, kudos from them, so I wasn't overly concerned with batching or performance for the task.
Refer to Jira.
=> AO3-6401 Prevent official user accounts from leaving kudos

lib/otw_sanitize/embed_sanitizer.rb, spec/lib/html_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3524
Add 4shared.com to the list of allowed embed sources (more information on the ticket, linked above). I also ran Rubocop, since the allowlisting was a very small change.
=> AO3-3524 Add 4shared.com to allowed embeds

app/controllers/related_works_controller.rb, app/views/related_works/index.html.erb, config/locales/controllers/en.yml, config/locales/views/en.yml, spec/controllers/related_works_controller_spec.rb
https://otwarchive.atlassian.net/issues/AO3-6938
- Fix Related Work's index view title not showing the username on Related Works page
- Fix Related Work's index view heading to use i18n instead.
1. Go to https://archiveofourown.org/users/[user]/related_works
2. Check the page title and the heading of the page
Michelle Tanoto
**Note:** I would like to be invited to the Jira as this is my first pull request :)
=> AO3-6938 Fix Related Works page missing username in browser page title

public/stylesheets/masters/reversi/reversi_site_screen_.css, public/stylesheets/masters/snow_blue/snow_blue_site_screen_.css
https://otwarchive.atlassian.net/browse/AO3-6962
* Fixes the background color of tag set nominations in Reversi.
* Fixes the hover styling of certain types of actions on the tag set review pages in Reversi and Snow Blue.
Refer to Jira.
=> AO3-6962 Fix color issues on tag set nomination review pages in Reversi and Snow Blue

app/controllers/users_controller.rb, app/views/users/change_email.html.erb, config/locales/mailers/en.yml, spec/mailers/archive_devise_mailer_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6388
Use [flash.now](https://api.rubyonrails.org/classes/ActionDispatch/Flash/FlashHash.html#method-i-now) for errors on change_email so that they don't stick around too long. (It renders, instead of redirects, so they should only stay for the current action).
This can't be reliably reproduced. One person should test the instructions from the previous BOT PR to make sure the errors still show up in general (https://otwarchive.atlassian.net/browse/AO3-6388?focusedCommentId=365222)
Second commit per Lydia's request.
Bilka
=> AO3-6388 Fix flash error sticking around on change_email

db/migrate/20181222022628_remove_recently_reset_from_users.rb, db/migrate/20250421192808_remove_recently_reset_from_users.rb
https://otwarchive.atlassian.net/browse/AO3-5862
Update the old migration (that was never actually applied per the ticket above) to use Departure and have a more recent timestamp.
=> AO3-5862 Use Departure to really delete users.recently_reset

app/models/comment.rb, features/comments_and_kudos/hidden_comments.feature
https://otwarchive.atlassian.net/browse/AO3-6757
When a comment is hidden by an administrator, the contents are replaced with a placeholder and are no longer visible to users (other than the user who posted the comment, if it was by a registered user). However, they are still visible to admins. This PR will strip the IMG tag from comment content, and leave a plain URL in its place.
=> AO3-6757 Remove image embeds when hiding comments

app/models/redis_mail_queue.rb
https://otwarchive.atlassian.net/browse/AO3-5919
Remove the call to `REDIS_KUDOS.keys`, which scans the whole Redis database, in favour of using an intermediate set to keep track of which things an author has gotten kudos on.
=> AO3-5919 Use intermediate set to avoid KEYS in kudos delivery

app/controllers/owned_tag_sets_controller.rb, factories/tags.rb, lib/tasks/after_tasks.rake, spec/controllers/owned_tag_sets_controller_spec.rb, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5714
Non-canonical characters associated with canonical fandoms _look_ like they're associated when added to a TagSet, but in prompts, they aren't treated that way (either for autocomplete or, after https://github.com/otwcode/otwarchive/pull/5140 is merged, for situations when fandom-only is selected). This PR updates the categorization to show these tags under the association-needed section instead to reduce confusion.
I cleaned up a few Rubocop complaints as well, which changed indentation. I'd recommend using the "hide whitespace" option when reviewing, to make the diff a bit more comprehensible
=> AO3-5714 Do not treat non-canonical tags as fandom-associated in TagSets

lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5714
Fix the rake task so it ignores validation errors (raised when the `TagSetAssociation` for the set, fandom, and child tag already exists)
=> AO3-5714 Skip association creation when a TagSetAssociation exists

.github/workflows/automated-tests.yml, script/gh-actions/ebook_converters.sh
https://otwarchive.atlassian.net/browse/AO3-6988
Change our direct uses of `apt-get` to `cache-apt-pkgs-action` so that the result can be cached.
I also tried out caching all the apt packages in the same step, however that means that uncached runs have to install libvips and calibre even if they don't need it, which slows them down a lot. By keeping the caches separated by step nothing gets slowed down if there is a cache miss.
We have to add the action to the Allow specified actions and reusable workflows list (https://github.com/otwcode/otwarchive/settings/actions) to get it to run in this repo.
Run without existing caches: https://github.com/Bilka2/otwarchive/actions/runs/14889581675
Run using caches, with massively reduced install times for ebooks/libvips: …
=> AO3-6988 Use cache-apt-pkgs-action in automated tests

public/stylesheets/site/2.0/11-group-listbox.css
https://otwarchive.atlassian.net/browse/AO3-6844
What it says on the tin.
Follow the steps on the issue to create a tag set with Unassociated Characters & Relationships and then confirm the blue banner is not pressed right up to the edges of the listbox.
=> AO3-6844 Change padding on listbox notice to margin

app/mailers/archive_devise_mailer.rb, app/views/admin/mailer/password_change.html.erb, app/views/admin/mailer/password_change.text.erb, app/views/users/mailer/password_change.html.erb, app/views/users/mailer/password_change.text.erb, config/initializers/devise.rb, config/locales/mailers/en.yml, features/admins/authenticate_admins.feature, features/other_a/profile_edit.feature, features/step_definitions/tag_steps.rb, features/support/user.rb, features/users/authenticate_users.feature, spec/mailers/archive_devise_mailer_spec.rb, test/mailers/previews/archive_devise_mailer_preview.rb
https://otwarchive.atlassian.net/browse/AO3-6973
When a user changes or resets their password they will be emailed.
Do the same for admin password resets.
Bilka
=> AO3-6973 Add email when user changes or resets password

app/controllers/users_controller.rb, app/models/admin_setting.rb, app/views/users/confirmation.html.erb, config/config.yml, config/initializers/devise.rb, config/locales/views/en.yml, features/step_definitions/invite_steps.rb, lib/tasks/admin_tasks.rake
https://otwarchive.atlassian.net/browse/AO3-6975
This PR updates the `purge_unvalidated_users` rake task to use the admin setting `days_to_purge_unactivated`. It also adds a `DAYS_TO_CONFIRM_EMAIL_CHANGE` to config.yml and updates all the spots that `ArchiveConfig.DAYS_TO_PURGE_UNACTIVATED` was used.
=> AO3-6975 Fix days_to_purge_unactivated admin setting and DAYS_TO_CONFIRM_EMAIL_CHANGE

app/controllers/chapters_controller.rb, app/controllers/works_controller.rb, app/models/work.rb, features/other_a/reading.feature, spec/controllers/chapters_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6267
Prevents "update available" from appearing when a draft chapter added by only bumping the work version when a posted chapter is modified.
marcus8448 (he/him)
=> AO3-6267 Only update work version on posted chapters

features/works/work_view.feature
https://otwarchive.atlassian.net/browse/AO3-6092
Add a automated test
Hamham6, it/its
=> AO3-6092 Add automated test to check chapter titles display in entire work view when work has only a single posted chapter

app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-6995
Try to prevent errors when dropping the column by adding it to ignore_columns.
The migration should be run in the next deploy after the one that this PR is included in, and then it should be run shortly before that deploy.
None.
Bilka
=> AO3-6995 Add recently_reset to ignored_columns

app/views/tags/edit.html.erb, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6967
Adding a save button to the top of the tag edit page for tag wranglers.
Check Jira issue
Grayson von Goetz (they/them)
=> AO3-6967 add save button to top of tag edit page

app/models/admin_setting.rb, app/views/admin/settings/index.html.erb, config/locales/views/en.yml, features/admins/admin_settings.feature
https://otwarchive.atlassian.net/browse/AO3-4190
Fix that sending invitations from the queue would update the "last updated" date for the admin settings.
The update being attributed to the wrong admin no longer appears to be an issue from what I could see, neither are the different timezones.
Bilka
=> AO3-4190 Fix admin settings last updated date being modified by invitation sending

app/controllers/comments_controller.rb, app/controllers/feedbacks_controller.rb, db/migrate/20250515095633_change_user_agent_limit.rb, spec/controllers/comments/default_rails_actions_spec.rb, spec/controllers/feedbacks_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-3818
Increases the limit of the user_agent column for comments and feedback to 500. This is based on me going through the errors related to this column on Sentry for the last 3 days. The longest user agent was 443 characters, most were just slightly below 300. I picked 500 to play it safe.
If the user agent is longer, it will be truncated because per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/User-Agent), the end of the string is for extensions so truncating those shouldn't impact Akismet too much, as all the important info is still there. The one long string just had a baffling amount of extensions, like current font scale so I really don't think it matters if that gets truncated.
Bilka
=> AO3-3818 Increase user_agent limit for comments and feedback

app/controllers/inbox_controller.rb, config/locales/controllers/en.yml, features/other_a/page_title.feature
https://otwarchive.atlassian.net/browse/AO3-6937
Fix the browser tab title on the user's inbox page to: `user - Inbox | Archive of Our Own`
1. Visit a user’s inbox page
2. Confirm the page title in the browser tab displays as `user - Inbox | Archive of Our Own`
3. Confirm that other page titles are not affected
kitbur
=> AO3-6937 Fix inbox page title to show username

app/views/works/show_multiple.html.erb, config/locales/controllers/en.yml, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6993
This PR changes the code to not show the "edit multiple works" form if the user does not have any works.
Before change:
After change:
=> AO3-6993 Show message instead of edit works form when user has no works

app/jobs/invite_from_queue_job.rb
https://otwarchive.atlassian.net/issues/AO3-6948
Report `InviteFromQueue` runs to Sentry. I deliberately didn't set the config required for upserts, since we want to be able to set the interval via the UI (because this runs based on the value set via the admin UI, not necessarily every hour)
=> AO3-6948 Monitor InviteFromQueueJob with Sentry

app/controllers/collection_items_controller.rb, app/controllers/works_controller.rb, spec/controllers/collection_items_controller_spec.rb, spec/controllers/works/works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6166
Prevent access to the add to collection page and chapter navigation page for unrevealed/hidden works.
Make unrevealed work. Log in as another user and try to access:
* the page for inviting the work to a collection (https://test.archiveofourown.org/works/###/collection_items/new)  
* the work’s chapter index (https://test.archiveofourown.org/works/###/navigate)
Bilka
=> AO3-6166 Fix two more pages showing unrevealed/hidden work title

app/models/invite_request.rb, app/models/user.rb
https://otwarchive.atlassian.net/browse/AO3-6996
Removes unnecessary `ignored_columns` from `invite_request.rb` and `user.rb`.
`ignored_columns` were from:
- [AO3-6995](https://otwarchive.atlassian.net/browse/AO3-6995)
- [AO3-5962](https://otwarchive.atlassian.net/browse/AO3-5962)
kitbur
[AO3-6995]: https://otwarchive.atlassian.net/browse/AO3-6995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6996 Remove no longer needed ignored_columns from models

app/policies/admin_setting_policy.rb, spec/controllers/admin/settings_controller_spec.rb
* ~~Tests were not added because a) this was a small change that was easily manually tested, and b) I couldn't find tests covering other permissions for `policy_and_abuse` archive settings. That being said, if I missed tests or if I should add tests, please let me know and I'll be happy to add them.~~
https://otwarchive.atlassian.net/browse/AO3-6235
This allows admins with the `policy_and_abuse` role to toggle invitation requests via Archive Settings.
The JIRA ticket already has test instructions. However, additional testing can cover edge and negative cases:
* For an admin with additional roles including `policy_and_abuse`, test if you can …
=> AO3-6235 Allow policy_and_abuse admins to toggle invite requests in settings

app/helpers/works_helper.rb, app/views/works/_work_header_notes.html.erb, config/locales/views/en.yml, spec/helpers/works_helper_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6515
- Fix 500 error for work end notes without posted chapters. 
- Do not use instance variable `@work` for helper function. 
- Fix issue in view not having right syntax highlighting in GitHub.
- i18n
See issue.
=> AO3-6515 Fix 500 error for work end notes without posted chapters

app/policies/user_policy.rb, spec/controllers/admin/admin_users_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6588
Allow Open Doors admins to give the no_resets role to user accounts.
=> AO3-6588 Allow Open Doors and Support admins to set no_resets role

app/controllers/works_controller.rb, spec/controllers/works/drafts_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6273
Tentative fix of the work word_count sometimes being nil when posting a draft through the post_draft route.
From my understanding, the issue is that `set_word_count`, when doing a read on the database [here](https://github.com/otwcode/otwarchive/blob/master/app/models/work.rb#L831), can sometimes query a version of the db where the first chapter hasn't been updated to `posted=TRUE`, thus counting nil.
My proposed solution is to get the data directly from the object, who I think should be up to date in all cases (all Ruby code is called synchronously). Might be a placebo however, as I'm not sure how to reproduce the issue locally or in tests.
In theory, as per JIRA. However, I'm not sure how often the bug appears.
=> AO3-6273 Word count blank when posting from draft

app/controllers/comments_controller.rb, app/models/comment.rb, spec/controllers/comments/freeze_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6373
Remove `@comment.save` and use a transaction for freezing/unfreezing comments
Also tidy up existing spec tests.
=> AO3-6373 Allow comments by blocked user to be frozen, unfrozen

.rubocop.yml
Considering this a docs PR.
I recently used the list of large tables to find tables with high ids. In the process I noticed that a few large tables were missing, so this adds them. I added all tables that I checked and that have a current record count of over 400 thousand.
| Table name  | Max id | count |
| ------------- | ------------- | ------------- |
| chapters | 173_392_018  |  |
| invite_requests | 47_903_377 | 79_317 |
| potential_matches | 35_575_468 | 74_445 |
| active_storage_attachments | 21_749_020 |  |
| active_storage_variant_records | 13_161_289 |  |
| tag_sets | 8_184_766 | 2_650_269 |
| challenge_assignments | 3_333_973 | 194_908 |
| blocks | 2_725_009 | 802_264 |
| meta_taggings | 2_668_861 | 611_707 |
| collection_preferences | 2_083_342 | 450_268 |
| related_works | …
=> Update the list of large tables in rubocop

public/help/skins-creating.html
Took 7 minutes
https://otwarchive.atlassian.net/browse/AO3-7025
Fixed the type in skin creation css style guide, changed the name of the property `oice-family` to `voice-family`
As mentioned in the issue, go the `new skin creation form`, click on the `help section` and search for `voice-duration` the property after that should be named as `voice-family`.
Abhinav Gupta, he/him
=> AO3-7025 Fix typo in voice family property

app/controllers/skins_controller.rb, features/other_b/skin.feature
https://otwarchive.atlassian.net/browse/AO3-7033
Add the skin title to the browser page title for the skin show page. We should at some future point move the `hmtl_safe` call to the title attribute on the model instead of sprinkling it into views, similar to how it's done with works. I suspect Brakeman will complain but it's fine because it's sanitized.
Bilka
=> AO3-7033 Include skin title in browser page title for skin show page

db/migrate/20250628175658_add_index_to_comments_name.rb
https://otwarchive.atlassian.net/browse/AO3-7004
This PR adds an index to the comments table on name to make looking up guest comments by name faster.
Run the migration on staging.
=> AO3-7004 Add index to comments on name

app/controllers/collections_controller.rb, spec/controllers/collections_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7042
Change collections index to 404 if the object you're trying to view the collections of doesn't exist.
Bilka
=> AO3-7042 Change collections index to 404 for nonexistent objects

config/initializers/gem-plugin_config/webmock.rb, spec/controllers/api/v2/api_bookmarks_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7065
Change webmock to only connect to Capybara requests on start, not all of them, which could result in unexpected connection failures for normally stubbed requests.
Five runs without problems after the change: https://github.com/Bilka2/otwarchive/actions/runs/16387864713
This breaks the "returns an error message if the URL is on AO3" test, which was previously hitting a 404 on example.com. External works can generally be created for AO3 URLs, there is no check for this in the external work model, despite what https://github.com/otwcode/otwarchive/blob/c1d52a8b76b1b76da4879f009d1e5f703e13d97a/app/controllers/api/v2/bookmarks_controller.rb#L164 implies. The creation usually fails on production/staging because it's always using a HTTP URL and …
=> AO3-7065 Fix flaky bookmarks v2 API tests

public/stylesheets/site/2.0/21-userstuff.css
https://otwarchive.atlassian.net/browse/AO3-7006
Updates `21-userstuff.css` stylesheet to move list items inwards such that markers do not overlap with profile photos.
Leave a comment on a work with the content `<ul><li>item</li></ul><ol><li>item</li></ol>`
Here are locally-tested before and after screenshots:
Before:
After modifying `list-style-position`:
theamandawang (she/her)
=> AO3-7006 Move list markers in comments inwards

app/controllers/works_controller.rb
https://otwarchive.atlassian.net/browse/AO3-5476
Removes references to the `pseud_id` parameter when editing multiple works, and removes reference to an edit button when creating a new work.
1. Create two or more works
2. Navigate to the “Edit Multiple Works” page from the dashboard
3. Edit multiple works and confirm that your changes were successful
4. Verify that no edit button exists when posting a new work
ktibur
=> AO3-5476 Remove unused code in works_controller

public/stylesheets/masters/dark_mode/README.md, public/stylesheets/masters/reversi/README.md, public/stylesheets/masters/snow/README.md, public/stylesheets/masters/snow_blue/README.md
N/A -- documentation update
Updates the README files for Snow, Snow Blue, Reversi, and Dark Mode to instruct you to set the `@media` to `screen` when setting up the skins. Doing so prevents them from being used when printing.
Low Vision Default specifies an `@media` already: `all`. This appears to be correct/desirable given its simplified layout.
=> Update skin README files to provide information on media

app/models/work_skin.rb, config/locales/models/en.yml, lib/css_cleaner.rb, public/help/skins-creating.html, spec/lib/css_cleaner_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7094
**Please do review the code! This is a draft because I'm waiting on some additional text changes from Docs, not because the code is unfinished.**
- The text about dashes being allowed got eaten in some drafting back and forth with Docs; this restores it.
- The css_parser gem downcases all properties to normalize them. This was a problem because CSS variables are case-sensitive: if you entered `--RED: #900`, it would get converted to `--red: #900` and would no longer work when trying to access it with `var(--RED)`. To handle this, I've chosen to downcase the `var()` function and remove any reference to uppercase letters being allowed in variable names. (more info) 
- Help text explaining this to come.
- I removed a line of code downcasing …
=> AO3-7094 Decrease case-sensitivity for custom properties/variables

app/controllers/challenge_signups_controller.rb, spec/controllers/challenge_signups_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-5552
Removes the unused no_signup code path and the corresponding test.
Refer to Jira.
Samridhi
=> AO3-5552 Remove unreachable no_signup code and update tests

app/helpers/tags_helper.rb
https://otwarchive.atlassian.net/browse/AO3-5769
Makes "Choose Not To Use Archive Warnings", "Creator Chose Not ..." on blurbs' icon block. I know pluck would be more efficient but it doesn't take display_name. would performance impact be considerable?
In addition to testing instructions on Jira, you can hover on warning's icon to see the title attribute.
ömer faruk and he/him would be nice.
=> AO3-5769 change name to display_name, wrong phrasing to correct constant

app/controllers/readings_controller.rb, app/views/readings/index.html.erb, config/locales/controllers/en.yml, config/locales/views/en.yml, features/other_a/reading.feature
https://otwarchive.atlassian.net/browse/AO3-6581
This PR updates the heading and page title for the "Marked for Later" page, as well as registers both the "History" and "Marked for Later" strings with the i18n system. 
Jamis Gelvin (they/them)
=> AO3-6581 Update heading + page title for "Marked for Later" page

config/locales/models/en.yml, spec/models/language_spec.rb
https://otwarchive.atlassian.net/issues/?filter=13119&selectedIssue=AO3-6914
This updates the UI to use "Abbreviation" instead of "short" in error messages for better consistency when adding a new language with an abbreviation longer than 5 characters.
=> AO3-6914 Update language short field to display as Abbreviation in error messages

spec/lib/tasks/database_seed.rake_spec.rb, spec/spec_helper.rb, test/fixtures/admin_settings.yml, test/fixtures/collections.yml, test/fixtures/external_works.yml
https://otwarchive.atlassian.net/browse/AO3-7110
Use WebMock to stub out requests to livejournal/dreamwidth that keep failing, e.g. https://github.com/otwcode/otwarchive/actions/runs/17314839517/job/49155766858. Also flip the `account_creation_enabled` setting as discussed in Slack.
Automated tests should pass.
Bilka
=> AO3-7110 Fix flaky database seed spec

app/controllers/users_controller.rb, config/locales/controllers/en.yml, config/locales/views/en.yml
https://otwarchive.atlassian.net/browse/AO3-6924
This moves a few browser page title translations for users_controller from the views locale file to the controllers locale file. This was done because the browser page title is set in the controller, not the view. It also renames the key from `browser_title` to `page_title` as requested in the linked issue.
I wasn't sure if I should move all `browser_title` items or just the three mentioned in the issue. I also wasn't sure if I should refactor all the `browser_title` keys to `page_title`. So I played it safe and just edited what I moved. Please let me know if I should go back and move/refactor those other items!
Kylia Miskell (they/them)
=> AO3-6924 Move browser page title translations for users_controller to locale file for controllers

CONTRIBUTING.md
A documentation change in order to bring more attention to the need for issue status updates in the contributing process. 
Also, it attempts to:
* Improve documentation links
* Improve brevity
=> Include Jira status changes in CONTRIBUTING.md

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-6026
The tags in collection blurbs are indented just a tiny bit due to the landmark. 
Fortunately, we already solved this issue for the fandom tags in work blurbs ([AO3-4153](https://otwarchive.atlassian.net/browse/AO3-4153)/#1919) many years ago, so we only need to tweak the CSS selector. 
Look at a collection blurb with tags. The first tag should be aligned with the collection title.
[AO3-4153]: https://otwarchive.atlassian.net/browse/AO3-4153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AO3-6026 Fix alignment of tags in collection blurb

lib/fandom_crossover.rb
https://otwarchive.atlassian.net/browse/AO3-6026
This reduces the amount of N+1 queries in the fandom crossover check. I spotted two more N+1 queries in the logs:
1. When loading the mergers for `all_without_syns`
2. When loading the metatags for `meta_tag_groups`
The first can be mostly be avoided by getting only the merger_ids and continuing to do the conditional in Ruby, but doing that [in the database](https://mariadb.com/docs/server/reference/sql-functions/control-flow-functions/ifnull) instead has an additional benefit: I can make it return an `ActiveRecord::Relation` instead of a plain array.
And that `ActiveRecord::Relation` allows the `includes` in spot two, and that one should be pretty obvious for why it helps. It doesn't help for the `until` loop lower in the method that gets …
=> AO3-6026 Reduce N+1 queries in fandom crossover method

app/models/bookmark.rb, lib/tasks/after_tasks.rake, spec/lib/tasks/after_tasks.rake_spec.rb
Fixes the following problems with backfilling collection tags:
* series tags are missing
* public bookmark of hidden work leads to the work tags being included
* public bookmark of restricted work leads to the work tags being included
* tags of unrevealed works are included
=> AO3-6026 Fix collection tag backfill issues

features/collections/collection_browse.feature, spec/models/bookmark_spec.rb, spec/models/bookmarkable_spec.rb, spec/models/collection_item_spec.rb, spec/models/collection_spec.rb, spec/models/search/collection_indexer_spec.rb, spec/models/work_spec.rb
https://otwarchive.atlassian.net/browse/AO3-6026
Cover the testing steps for Collection blurb Works count and Collection blurb Bookmarked Items count with automatic tests instead because the blurb caching interacts so badly with updates that manual testing is not feasible. (Problem is that the blurb cache updates with info from ES before ES updates for the changes, so the stale data is cached for the whole blurb cache expiry time which is up to 2 hours).
Works:
Counts general vs public: public work, restricted work, hidden work, rejected work all in collection_spec.rb
Updating counts:
* adding work: created in collection_item_spec.rb and work_spec.rb
* restricting, hiding: work_spec.rb. unhiding code is same as hiding so no need to test
* approving, rejecting: collection_item_spec.rb
* …
=> AO3-6026 Cover all Collection blurb count steps by automated tests

.github/workflows/deploy.yml
https://otwarchive.atlassian.net/browse/AO3-6133
Add a manually-triggered workflow that we can use to deploy to staging, as a replacement for Cloudship (which is going EOL in 2026). I also parameterized a lot using GitHub environments in case we want to try with production (of course with an approver list) later.
**NOTE:** before merging, we should disable the cloudship deploy so we can test this properly
=> AO3-6133 Deployment workflow to replace Codeship

app/controllers/collections_controller.rb, spec/controllers/collections_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7141
Change the sort order on the user's collection page and the collection's subcollection page to default to sorting by title, like it used to.
Bilka
=> AO3-7141 Fix sort order on user's and collection's collections page

app/models/user_manager.rb, spec/models/user_manager_spec.rb
[https://otwarchive.atlassian.net/browse/AO3-5640](https://otwarchive.atlassian.net/browse/AO3-5640)
This PR fixes a bug when logged in as admin. Currently, if an admin logs in, navigates to a user's admin detail page, enters text in the "Notes" field, does not select any of the Warnings and Suspensions options, and selects "Update", the notes field is cleared and a brief flash occurs with nothing added to the user's record. This PR makes it so that instead, an error appears with the message, "You must choose an action to perform." Tests have also been updated accordingly.
Testing can be done by trying this behavior in the test environment (i.e. …
=> AO3-5640 Empty flash message displays when an admin enters notes on a user account without selecting a warning or suspension option

app/controllers/admin/admin_invitations_controller.rb, app/policies/admin_invitation_policy.rb, app/policies/invitation_policy.rb, app/views/admin/admin_invitations/index.html.erb, features/admins/admin_invitations.feature, spec/controllers/admin/admin_invitations_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7038
Add an AdminInvitationPolicy and restrict access to `grant_invites_to_users` to superadmins.
Bilka
=> AO3-7038 Restrict ability to grant invitations to all current users

app/controllers/external_works_controller.rb, spec/controllers/external_works_controller_spec.rb
https://otwarchive.atlassian.net/browse/AO3-7023
This PR fixes the 500 error when ExternalWorksController#fetch gets an invalid URL for `external_work_url`. 
=> AO3-7023 Fix ExternalWorkscontroller#fetch when the URL is invalid

app/views/tag_wranglings/index.html.erb, app/views/tags/wrangle.html.erb, config/locales/views/en.yml, features/tags_and_wrangling/tag_wrangling.feature
https://otwarchive.atlassian.net/browse/AO3-6968
This PR adds tag comment links to the fandom and mass wrangling bins for easier access to tag comment pages (and counts) when wrangling.
marcus8448 (he/him)
=> AO3-6968 Add tag comment links to the wrangling bins

README.md
On README.md, change the outdated link to ao3's page on tw.org to the updated one. You can also consider changing "history and future" part, if you think that doesn't represent what that page is about anymore.
Currently, the README links to a 404. This new link will show the correct page.
ömer faruk he/him
=> update the link to ao3's history on README.md

public/stylesheets/site/2.0/13-group-blurb.css
https://otwarchive.atlassian.net/browse/AO3-7075
This PR adds padding around the grey blurb on the history page.
Before change:
After change:
=> AO3-7075 Add padding around the grey blurb on the history page
